### ISSUE TITLE
FragPipe 19.1 on Ubuntu 22.04 - Error: The BROWSE action is not supported on the current platform!

### ISSUE THREAD

**Issue by jacobfh1** [Nesvilab/FragPipe#1014]
**I have a problem with FragPipe version 19.1 on Ubuntu 22.04.**

While the app can be launched successfully, hyperlinks to documentation of integrated software tools are not working. I have tried to resolve this issue by building from scratch as per GitHub documentation, without any solution. Interestingly, no issues are encountered when using Windows 10.

When I try to open the hyperlinks inside of FragPipe I receive the log file pasted below.

Is this a compatibility issue between FragPipe and Ubuntu or something else? Can a fix be implemented to resolve this problem?

**Log file:**
ERROR: Something unexpected happened!
java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:380)
	at java.desktop/java.awt.Desktop.browse(Desktop.java:524)
	at com.github.chhh.utils.SwingUtils.openBrowserOrThrow(SwingUtils.java:708)
	at com.github.chhh.utils.swing.HtmlStyledJEditorPane.lambda$new$0(HtmlStyledJEditorPane.java:55)
	at java.desktop/javax.swing.JEditorPane.fireHyperlinkUpdate(JEditorPane.java:345)
	at java.desktop/javax.swing.text.html.HTMLEditorKit$LinkController.activateLink(HTMLEditorKit.java:899)
	at java.desktop/javax.swing.text.html.HTMLEditorKit$LinkController.mouseClicked(HTMLEditorKit.java:695)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6638)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4556)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by fcyu** [comment]
> While the app can be launched successfully, hyperlinks to documentation of integrated software tools are not working.

If I understand it correctly, FragPipe can run without any issue. When you clicked the links to open the webpage of the document, there were errors. Is that right? 

It seems that your system does not have browser configured correctly: `The BROWSE action is not supported on the current platform!`

Best,

Fengchao

**Comment by jacobfh1** [comment]
> It seems that your system does not have browser configured correctly

Thanks for your quick response!

I attempted to set both Firefox and Chrome as my default browsers, and while they function well outside of FragPipe, I encounter an error when attempting to access online documentation through the hyperlinks inside the program. Do I need to configure the browser cache files or any other settings within FragPipe, or is there an alternate location where I should adjust my browser settings?

Best,
Jacob

**Comment by fcyu** [comment]
Hi Jacob,

I have no idea. But since it doesn't affect running FragPipe, I think it is minor.

Best,

Fengchao
