### ISSUE TITLE
Java error_02

### ISSUE THREAD

**Issue by pankajdwid** [Nesvilab/FragPipe#1056]
Trying to search DDA files from thermo using LFQ MBR method, previously i was getting different error (see issue # 53) and google the solution and found that unchecking the normalize in ionquant might help. When I tried that I got the error described below:

Count java.lang.NullPointerException: mzBIN header not found!
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.readMZBINStructure(MZBINFile.java:479)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.readMZBIN(MZBINFile.java:413)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.<init>(MZBINFile.java:67)
	at p.a(Unknown Source)
	at p.a(Unknown Source)
	at o.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 26 remaining tasks

**Comment by fcyu** [comment]
Same issue as https://github.com/Nesvilab/FragPipe/issues/1054. Please rerun, and send us the log if the error presist.

Best,

Fengchao
