### ISSUE TITLE
Java error_03

### ISSUE THREAD

**Issue by pankajdwid** [Nesvilab/FragPipe#1057]
This is just follow up on the 2 previous java related errors, after i got mzBin header error, i downloaded the FASTA file from FragPipe and researched the data, this time it gave new error:

Count java.lang.NegativeArraySizeException: -1699445604
	at java.base/java.lang.StringCoding.decodeUTF8_0(Unknown Source)
	at java.base/java.lang.StringCoding.decodeUTF8(Unknown Source)
	at java.base/java.lang.StringCoding.decode(Unknown Source)
	at java.base/java.lang.String.<init>(Unknown Source)
	at java.base/java.lang.String.<init>(Unknown Source)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.__unpackHeader(MZBINFile.java:392)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.__unpackBINHeader(MZBINFile.java:584)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.readMZBINStructure(MZBINFile.java:494)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.readMZBIN(MZBINFile.java:413)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.<init>(MZBINFile.java:67)
	at p.a(Unknown Source)
	at p.a(Unknown Source)
	at o.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 26 remaining tasks

**Comment by fcyu** [comment]
Still seems to be the same reason in https://github.com/Nesvilab/FragPipe/issues/1054

Best,

Fengchao
