### ISSUE TITLE
FragPipe headless error on HPC system 

### ISSUE THREAD

**Issue by Jmonod** [Nesvilab/FragPipe#1092]
Hi Fengchao, 

I'm having the same following error as reported by Belaid while running FragPipe in headless mode (version 19.1) on a HPC system with a DDA variable modifications worfklow. Since no log file is getting created, I'm joining my workflow. Fyi, I'm able to run other workflows flawlessly even if easypqp is not installed. 

Any insight? 

[fragpipe.workflow.txt](https://github.com/Nesvilab/FragPipe/files/11357605/fragpipe.workflow.txt)

[SEVERE] Could not dispatch event: class com.dmtavt.fragpipe.messages.MessageRun to subscribing class class com.dmtavt.fragpipe.tabs.TabRun
java.lang.NumberFormatException: empty String
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
        at java.base/jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.base/java.lang.Float.parseFloat(Float.java:476)
        at com.dmtavt.fragpipe.tabs.TabMsfragger.lambda$static$21(TabMsfragger.java:259)
        at com.dmtavt.fragpipe.tabs.TabMsfragger.paramsFromMap(TabMsfragger.java:1601)
        at com.dmtavt.fragpipe.tabs.TabMsfragger.formCollect(TabMsfragger.java:1504)
        at com.dmtavt.fragpipe.tabs.TabMsfragger.getParams(TabMsfragger.java:1545)
        at com.dmtavt.fragpipe.FragpipeRun.configureTaskGraph(FragpipeRun.java:1025)
        at com.dmtavt.fragpipe.FragpipeRun.run(FragpipeRun.java:286)
        at com.dmtavt.fragpipe.tabs.TabRun.on(TabRun.java:174)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
        at org.greenrobot.eventbus.EventBus.invokeSubscribe
r(EventBus.java:511)
        at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
2023-04-28 17:57:52,522 ERROR - Error delivering events through the bus
java.lang.NumberFormatException: empty String
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
        at java.base/jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.base/java.lang.Float.parseFloat(Float.java:476)
        at com.dmtavt.fragpipe.tabs.TabMsfragger.lambda$static$21(TabMsfragger.java:259)
        at com.dmtavt.fragpipe.tabs.TabMsfragger.paramsFromMap(TabMsfragger.java:1601)
        at com.dmtavt.fragpipe.tabs.TabMsfragger.formCollect(TabMsfragger.java:1504)
        at com.dmtavt.fragpipe.tabs.TabMsfragger.getParams(TabMsfragger.java:1545)
        at com.dmtavt.fragpipe.FragpipeRun.configureTaskGraph(FragpipeRun.java:1025)
        at com.dmtavt.fragpipe.FragpipeRun.run(FragpipeRun.java:286)
        at com.dmtavt.fragpipe.tabs.TabRun.on(TabRun.java:174)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:511)
        at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
2023-04-28 17:57:52,525 ERROR - java.lang.NumberFormatException: empty String
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
        at java.base/jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.base/java.lang.Float.parseFloat(Float.java:476)
        at com.dmtavt.fragpipe.tabs.TabMsfragger.lambda$static$21(TabMsfragger.java:259)
        at com.dmtavt.fragpipe.tabs.TabMsfragger.paramsFromMap(TabMsfragger.java:1601)
        at com.dmtavt.fragpipe.tabs.TabMsfragger.formCollect(TabMsfragger.java:1504)
        at com.dmtavt.fragpipe.tabs.TabMsfragger.getParams(TabMsfragger.java:1545)
        at com.dmtavt.fragpipe.FragpipeRun.configureTaskGraph(FragpipeRun.java:1025)
        at com.dmtavt.fragpipe.FragpipeRun.run(FragpipeRun.java:286)
        at com.dmtavt.fragpipe.tabs.TabRun.on(TabRun.java:174)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:511)
        at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

2023-04-28 17:59:28,352 WARN  - Something happened while checking for IonQuant updates
2023-04-28 17:59:28,352 WARN  - Something happened while checking for MSFragger updates

####################################################################

 Hi Fengchao,
  One of our users is doing a run based on DIA_SpecLib_Quant.workflow but we are consistently getting the following error:

[SEVERE] Could not dispatch event: class com.dmtavt.fragpipe.messages.MessageRun to subscribing class class com.dmtavt.fra
gpipe.tabs.TabRun
java.util.NoSuchElementException: Sticky note not on the bus: com.dmtavt.fragpipe.messages.NoteConfigSpeclibgen
        at com.dmtavt.fragpipe.Fragpipe.getStickyStrict(Fragpipe.java:930)
        at com.dmtavt.fragpipe.FragpipeRun.lambda$configureTaskGraph$55(FragpipeRun.java:1228)
        at com.dmtavt.fragpipe.FragpipeRun.configureTaskGraph(FragpipeRun.java:1354)
        at com.dmtavt.fragpipe.FragpipeRun.run(FragpipeRun.java:228)
        at com.dmtavt.fragpipe.tabs.TabRun.on(TabRun.java:164)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:511)
        at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
16:29:33 ERROR - Error delivering events through the bus
java.util.NoSuchElementException: Sticky note not on the bus: com.dmtavt.fragpipe.messages.NoteConfigSpeclibgen
        at com.dmtavt.fragpipe.Fragpipe.getStickyStrict(Fragpipe.java:930)
        at com.dmtavt.fragpipe.FragpipeRun.lambda$configureTaskGraph$55(FragpipeRun.java:1228)
        at com.dmtavt.fragpipe.FragpipeRun.configureTaskGraph(FragpipeRun.java:1354)
        at com.dmtavt.fragpipe.FragpipeRun.run(FragpipeRun.java:228)
        at com.dmtavt.fragpipe.tabs.TabRun.on(TabRun.java:164)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
....
Are we missing something at our end?
Cheers,
-Belaid.

_Originally posted by @bmoa in https://github.com/Nesvilab/FragPipe/issues/560#issuecomment-1067440369_

**Comment by fcyu** [comment]
Hi Belaid,

For the first error, it is because `msfragger.mass_offsets=` in your workflow file. It should be something like `msfragger.mass_offsets=0` if you are not performing mass offset search. I will add some checks to make it more robust.

For the second error, I guess EasyPQP was not configured correctly. 

Best,

Fengchao

**Comment by Jmonod** [comment]
Thanks Fengchao, I confirm the cause of the error, it's now running smoothly. 

Thank you for this great tool ! 

Joe

**Comment by fcyu** [comment]
Hi Joe,

You are welcome!

I will close this issue now but feel free to contact us if you have any other questions in the future.

Best,

Fengchao
