### ISSUE TITLE
"fatal error: all goroutines are asleep - deadlock!" at DB-processing step

### ISSUE THREAD

**Issue by MaxWeydmann** [Nesvilab/FragPipe#111]
# Describe the problem

* **I'm submitting a:**
  - [X] problem running the software
  - [ ] bug report
  - [ ] feature request
  - [ ] question

* **My MSFragger use case:**
  - [X] _Closed_ search (standard small precursor mass tolerance)
  - [ ] _Open_ search (large precursor mass tolerance)

 ** At the Database-processing step, a fatal error occure (fatal error: all goroutines are asleep - deadlock!) **

## System info

- OS and version: ** Win10/AMD64, MSFragger v20190222, Philosopher v20190322, FragPipe v9.3-RC3, Python v3.6.5 **
- Java version: ** 1.8.0_201, JavaHotspot 64-Bit Server VM **

----

### Genral proteomics experiment description
** Tryptic Digest of bacterial cell lysate, DDA acquisition on QE **

...

### Input data files
** Thermo raw file converted to mzML with MSConvert. mzML file size ~ 350MB **

### Sequence database

** combined FASTA-database of about 11k bacterial species. Decoy-Tag rev_ created with openMS. FASTA-size with decoys ~ 5.5 GB **  

----

## Attach fragger.params file

default closed search parameters were used.
```
** database_name = C:\Max\MSFragger_Test_BSL2DB\uniref-90_BSL-2_nr_DECOY.fasta
num_threads = 20			# 0=poll CPU to set num threads; else specify num threads directly (max 64)

precursor_mass_lower = -50
precursor_mass_upper = 50
precursor_mass_units = 1			# 0=Daltons, 1=ppm
precursor_true_tolerance = 20
precursor_true_units = 1			# 0=Daltons, 1=ppm
fragment_mass_tolerance = 20
fragment_mass_units = 1			# 0=Daltons, 1=ppm
isotope_error = 0/1/2			# 0=off, -1/0/1/2/3 (standard C13 error)
mass_offsets = 0			# allow for additional precursor mass window shifts. Multiplexed with isotope_error. mass_offsets = 0/79.966 can be used as a restricted ‘open’ search that looks for unmodified and phosphorylated peptides (on any residue)
precursor_mass_mode = selected
shifted_ions = 0
shifted_ions_exclude_ranges = (-1.5,3.5)
fragment_ion_series = b,y
search_enzyme_name = Trypsin
search_enzyme_cutafter = KR
search_enzyme_butnotafter = P
num_enzyme_termini = 2			# 2 for enzymatic, 1 for semi-enzymatic, 0 for nonspecific digestion
allowed_missed_cleavage = 1			# maximum value is 5
clip_nTerm_M = 1
#maximum of 7 mods - amino acid codes, * for any amino acid, [ and ] specifies protein termini, n and c specifies peptide termini
variable_mod_01 = 15.99490 M
variable_mod_02 = 42.01060 [
# variable_mod_03 = 79.96633 STY
# variable_mod_04 = -17.02650 nQnC
# variable_mod_05 = -18.01060 nE
allow_multiple_variable_mods_on_residue = 1			# static mods are not considered
max_variable_mods_per_mod = 3			# maximum of 5
max_variable_mods_combinations = 5000			# maximum of 65534, limits number of modified peptides generated from sequence
output_file_extension = pepXML
output_format = pepXML
output_report_topN = 1
output_max_expect = 50
report_alternative_proteins = 0			# 0=no, 1=yes
precursor_charge = 1 4			# precursor charge range to analyze; does not override any existing charge; 0 as 1st entry ignores parameter
override_charge = 0			# 0=no, 1=yes to override existing precursor charge states with precursor_charge parameter
digest_min_length = 7
digest_max_length = 50
digest_mass_range = 500.0 5000.0			# MH+ peptide mass range to analyze
max_fragment_charge = 2			# set maximum fragment charge state to analyze (allowed max 5)
#open search parameters
track_zero_topN = 0			# in addition to topN results, keep track of top results in zero bin
zero_bin_accept_expect = 0.00			# boost top zero bin entry to top if it has expect under 0.01 - set to 0 to disable
zero_bin_mult_expect = 1.00			# disabled if above passes - multiply expect of zero bin for ordering purposes (does not affect reported expect)
add_topN_complementary = 0
# spectral processing
minimum_peaks = 15			# required minimum number of peaks in spectrum to search (default 10)
use_topN_peaks = 150
min_fragments_modelling = 3
min_matched_fragments = 4
minimum_ratio = 0.01			# filter peaks below this fraction of strongest peak
clear_mz_range = 0.0 0.0			# for iTRAQ/TMT type data; will clear out all peaks in the specified m/z range
# additional modifications
add_Cterm_peptide = 0.000000
add_Nterm_peptide = 0.000000
add_Cterm_protein = 0.000000
add_Nterm_protein = 0.000000
add_G_glycine = 0.000000
add_A_alanine = 0.000000
add_S_serine = 0.000000
add_P_proline = 0.000000
add_V_valine = 0.000000
add_T_threonine = 0.000000
add_C_cysteine = 57.021464
add_L_leucine = 0.000000
add_I_isoleucine = 0.000000
add_N_asparagine = 0.000000
add_D_aspartic_acid = 0.000000
add_Q_glutamine = 0.000000
add_K_lysine = 0.000000
add_E_glutamic_acid = 0.000000
add_M_methionine = 0.000000
add_H_histidine = 0.000000
add_F_phenylalanine = 0.000000
add_R_arginine = 0.000000
add_Y_tyrosine = 0.000000
add_W_tryptophan = 0.000000
add_B_user_amino_acid = 0.000000
add_J_user_amino_acid = 0.000000
add_O_user_amino_acid = 0.000000
add_U_user_amino_acid = 0.000000
add_X_user_amino_acid = 0.000000
add_Z_user_amino_acid = 0.000000

 **
```

## Run log output

```
** System info:
System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_201, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation

Version info:
FragPipe version 9.3-RC3
MSFragger version 20190222
Philosopher version 20190322 (build 201903221307)


LCMS files:
  Experiment/Group: 
  - C:\Max\MSFragger_Test_BSL2DB\388_2018_ZBS6_Abaumannii_DDA_iRT_2h_1_neu.mzML

9 commands to execute:
Workspace [Work dir: C:\Max\MSFragger_Test_BSL2DB]
C:\Users\ZBS6-Proteomik\Desktop\FragPipe\philosopher_windows_amd64 (1).exe workspace --clean
Workspace [Work dir: C:\Max\MSFragger_Test_BSL2DB]
C:\Users\ZBS6-Proteomik\Desktop\FragPipe\philosopher_windows_amd64 (1).exe workspace --init
MsFragger [Work dir: C:\Max\MSFragger_Test_BSL2DB]
java -jar -Dfile.encoding=UTF-8 -Xmx60G C:\Users\ZBS6-Proteomik\Desktop\FragPipe\MSFragger-20190222.jar C:\Max\MSFragger_Test_BSL2DB\fragger.params C:\Max\MSFragger_Test_BSL2DB\388_2018_ZBS6_Abaumannii_DDA_iRT_2h_1_neu.mzML
ReportDbAnnotate [Work dir: C:\Max\MSFragger_Test_BSL2DB]
C:\Users\ZBS6-Proteomik\Desktop\FragPipe\philosopher_windows_amd64 (1).exe database --annotate C:\Max\MSFragger_Test_BSL2DB\uniref-90_BSL-2_nr_DECOY.fasta --prefix rev_
PeptideProphet [Work dir: C:\Max\MSFragger_Test_BSL2DB]
C:\Users\ZBS6-Proteomik\Desktop\FragPipe\philosopher_windows_amd64 (1).exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database C:\Max\MSFragger_Test_BSL2DB\uniref-90_BSL-2_nr_DECOY.fasta 388_2018_ZBS6_Abaumannii_DDA_iRT_2h_1_neu.pepXML
ProteinProphet [Work dir: C:\Max\MSFragger_Test_BSL2DB]
C:\Users\ZBS6-Proteomik\Desktop\FragPipe\philosopher_windows_amd64 (1).exe proteinprophet --maxppmdiff 2000000 C:\Max\MSFragger_Test_BSL2DB\interact-388_2018_ZBS6_Abaumannii_DDA_iRT_2h_1_neu.pep.xml
ReportFilter [Work dir: C:\Max\MSFragger_Test_BSL2DB]
C:\Users\ZBS6-Proteomik\Desktop\FragPipe\philosopher_windows_amd64 (1).exe filter --sequential --razor --mapmods --prot 0.01 --tag rev_ --pepxml C:\Max\MSFragger_Test_BSL2DB --protxml C:\Max\MSFragger_Test_BSL2DB\interact.prot.xml
ReportReport [Work dir: C:\Max\MSFragger_Test_BSL2DB]
C:\Users\ZBS6-Proteomik\Desktop\FragPipe\philosopher_windows_amd64 (1).exe report
Workspace [Work dir: C:\Max\MSFragger_Test_BSL2DB]
C:\Users\ZBS6-Proteomik\Desktop\FragPipe\philosopher_windows_amd64 (1).exe workspace --clean
~~~~~~~~~~~~~~~~~~~~~~


Workspace [Work dir: C:\Max\MSFragger_Test_BSL2DB]
C:\Users\ZBS6-Proteomik\Desktop\FragPipe\philosopher_windows_amd64 (1).exe workspace --clean
INFO[12:13:51] Executing Workspace 20190322                 
INFO[12:13:55] Removing workspace                           
INFO[12:13:55] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: C:\Max\MSFragger_Test_BSL2DB]
C:\Users\ZBS6-Proteomik\Desktop\FragPipe\philosopher_windows_amd64 (1).exe workspace --init
INFO[12:13:56] Executing Workspace 20190322                 
INFO[12:13:57] Creating workspace                           
INFO[12:13:57] Done                                         
Process 'Workspace' finished, exit code: 0

MsFragger [Work dir: C:\Max\MSFragger_Test_BSL2DB]
java -jar -Dfile.encoding=UTF-8 -Xmx60G C:\Users\ZBS6-Proteomik\Desktop\FragPipe\MSFragger-20190222.jar C:\Max\MSFragger_Test_BSL2DB\fragger.params C:\Max\MSFragger_Test_BSL2DB\388_2018_ZBS6_Abaumannii_DDA_iRT_2h_1_neu.mzML
MSFragger version MSFragger-20190222
MSFTBX version 1.8.6
(c) University of Michigan

System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_201, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation
JVM started with 54613MB memory

Unknown parmameters:
	fragment_ion_series = b,y
Sequence database filtered and tagged in 1109ms
Digestion completed in 13153ms
Merged digestion results in 891ms
Sorting digested sequences...
	of length 7: 18820912
	of length 8: 17385284
	of length 9: 15784757
	of length 10: 14755251
	of length 11: 13895665
	of length 12: 12810054
	of length 13: 11779915
	of length 14: 11058959
	of length 15: 10166624
	of length 16: 9387630
	of length 17: 8762368
	of length 18: 8102871
	of length 19: 7504114
	of length 20: 7036441
	of length 21: 6540460
	of length 22: 6114242
	of length 23: 5663988
	of length 24: 5219472
	of length 25: 4857384
	of length 26: 4513643
	of length 27: 4163363
	of length 28: 3820323
	of length 29: 3525623
	of length 30: 3283167
	of length 31: 2987644
	of length 32: 2715627
	of length 33: 2478877
	of length 34: 2279001
	of length 35: 2097357
	of length 36: 1911001
	of length 37: 1744105
	of length 38: 1599110
	of length 39: 1469372
	of length 40: 1347962
	of length 41: 1233963
	of length 42: 1130213
	of length 43: 986388
	of length 44: 833041
	of length 45: 672318
	of length 46: 502431
	of length 47: 346705
	of length 48: 220495
	of length 49: 129110
	of length 50: 70405
	DONE
Removing duplicates and compacting...
Reduced to 200170024  peptides in 122897ms
Generating modified peptides...DONE in 19933ms
Generated 334858882 modified peptides
Merging peptide pools from threads... DONE in 5968ms
Sorting modified peptides by mass...DONE in 32703ms
Peptide index written in 11087ms
Selected fragment tolerance 0.10 Da and maximum fragment slice size of 39805.88MB
26210206092 fragments to be searched in 6 slices (195.28GB total)
Operating on slice 1 of 6: 48084ms
	388_2018_ZBS6_Abaumannii_DDA_iRT_2h_1_neu.mzML 5409ms
	388_2018_ZBS6_Abaumannii_DDA_iRT_2h_1_neu.mzML 5409ms [progress: 21271/56231 (37.83%) - 4228.83 spectra/s]
	388_2018_ZBS6_Abaumannii_DDA_iRT_2h_1_neu.mzML 5409ms [progress: 56119/56231 (99.80%) - 6928.03 spectra/s]
	388_2018_ZBS6_Abaumannii_DDA_iRT_2h_1_neu.mzML 5409ms [progress: 56231/56231 (100.00%) - 511.42 spectra/s] - completed 10388ms
Operating on slice 2 of 6: 11513ms
	388_2018_ZBS6_Abaumannii_DDA_iRT_2h_1_neu.mzML 1328ms
	388_2018_ZBS6_Abaumannii_DDA_iRT_2h_1_neu.mzML 1328ms [progress: 49832/56231 (88.62%) - 9906.96 spectra/s]
	388_2018_ZBS6_Abaumannii_DDA_iRT_2h_1_neu.mzML 1328ms [progress: 56231/56231 (100.00%) - 5319.20 spectra/s] - completed 6295ms
Operating on slice 3 of 6: 10982ms
	388_2018_ZBS6_Abaumannii_DDA_iRT_2h_1_neu.mzML 1063ms
	388_2018_ZBS6_Abaumannii_DDA_iRT_2h_1_neu.mzML 1063ms [progress: 56231/56231 (100.00%) - 17643.87 spectra/s] - completed 3233ms
Operating on slice 4 of 6: 10808ms
	388_2018_ZBS6_Abaumannii_DDA_iRT_2h_1_neu.mzML 1047ms
	388_2018_ZBS6_Abaumannii_DDA_iRT_2h_1_neu.mzML 1047ms [progress: 56231/56231 (100.00%) - 22793.27 spectra/s] - completed 2522ms
Operating on slice 5 of 6: 21495ms
	388_2018_ZBS6_Abaumannii_DDA_iRT_2h_1_neu.mzML 1035ms
	388_2018_ZBS6_Abaumannii_DDA_iRT_2h_1_neu.mzML 1035ms [progress: 56231/56231 (100.00%) - 27631.94 spectra/s] - completed 2088ms
Operating on slice 6 of 6: 10338ms
	388_2018_ZBS6_Abaumannii_DDA_iRT_2h_1_neu.mzML 1039ms
	388_2018_ZBS6_Abaumannii_DDA_iRT_2h_1_neu.mzML 1039ms [progress: 56231/56231 (100.00%) - 31608.21 spectra/s] - completed 1845ms
Process 'MsFragger' finished, exit code: 0

ReportDbAnnotate [Work dir: C:\Max\MSFragger_Test_BSL2DB]
C:\Users\ZBS6-Proteomik\Desktop\FragPipe\philosopher_windows_amd64 (1).exe database --annotate C:\Max\MSFragger_Test_BSL2DB\uniref-90_BSL-2_nr_DECOY.fasta --prefix rev_
INFO[12:21:50] Executing Database 20190322                  
INFO[12:21:50] Processing database                          
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_SemacquireMutex(0xc0001581d4, 0xc0d8048600)
	/usr/local/go/src/runtime/sema.go:71 +0x44
sync.(*Mutex).Lock(0xc0001581d0)
	/usr/local/go/src/sync/mutex.go:134 +0x106
internal/poll.(*FD).Write(0xc000158000, 0xc35dc00000, 0x104dced78, 0x17730e6d3, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_windows.go:673 +0x139
os.(*File).write(...)
	/usr/local/go/src/os/file_windows.go:224
os.(*File).Write(0xc000006080, 0xc35dc00000, 0x104dced78, 0x17730e6d3, 0xc000006080, 0x0, 0x0)
	/usr/local/go/src/os/file.go:145 +0x77
io/ioutil.WriteFile(0xc000422180, 0xc, 0xc35dc00000, 0x104dced78, 0x17730e6d3, 0xc0000001a4, 0xc, 0xc00012f000)
	/usr/local/go/src/io/ioutil/ioutil.go:84 +0x9b
github.com/prvst/philosopher/lib/dat.(*Base).Serialize(0xc000181880, 0xc00001c2c0)
	/home/prvst/go/src/github.com/prvst/philosopher/lib/dat/dat.go:350 +0x238
github.com/prvst/philosopher/lib/dat.Run(0xc00001a720, 0x24, 0xc00001e7e0, 0x1c, 0xc0000245a0, 0x49, 0xc00001a750, 0x2b, 0xc00001a780, 0x22, ...)
	/home/prvst/go/src/github.com/prvst/philosopher/lib/dat/dat.go:55 +0x949
github.com/prvst/philosopher/cmd.glob..func4(0x8422500, 0xc000181740, 0x0, 0x4)
	/home/prvst/go/src/github.com/prvst/philosopher/cmd/database.go:21 +0x16d
github.com/spf13/cobra.(*Command).execute(0x8422500, 0xc000181700, 0x4, 0x4, 0x8422500, 0xc000181700)
	/home/prvst/go/src/github.com/spf13/cobra/command.go:766 +0x2b5
github.com/spf13/cobra.(*Command).ExecuteC(0x8423f20, 0x4057f6, 0xc0000b2058, 0x0)
	/home/prvst/go/src/github.com/spf13/cobra/command.go:852 +0x2c7
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/src/github.com/spf13/cobra/command.go:800
github.com/prvst/philosopher/cmd.Execute()
	/home/prvst/go/src/github.com/prvst/philosopher/cmd/root.go:32 +0x35
main.main()
	/home/prvst/go/src/github.com/prvst/philosopher/main.go:19 +0x75
Process 'ReportDbAnnotate' finished, exit code: 2

Process returned non-zero exit code, stopping
PeptideProphet [Work dir: C:\Max\MSFragger_Test_BSL2DB]
C:\Users\ZBS6-Proteomik\Desktop\FragPipe\philosopher_windows_amd64 (1).exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database C:\Max\MSFragger_Test_BSL2DB\uniref-90_BSL-2_nr_DECOY.fasta 388_2018_ZBS6_Abaumannii_DDA_iRT_2h_1_neu.pepXML

~~~~~~~~~~~~~~~~~~~~
Stopping 6/10 processes (4 already finished)
Processing interrupted, stopping PeptideProphet

 **
```
Thank You for your help and support.
Best Regards,
Max

**Comment by prvst** [comment]
@MaxWeydmann 

Could you elaborate a little bit on your database ? Also , please paste the FASTA header of one protein here as well.

The error is probably originating from the size of your database. Normally we don't use protein databases that big neither with that impressive number of species. Even if the program is able to process the file, the fact that you have 11 million species, most likely phylogenetically similar to each other, will create an extremely complex network of shared peptides.

**Comment by MaxWeydmann** [comment]
There are "just" 11 thousand species inside, but youre allright, its definitely a very large db.
Counting with dbtoolkit, the FASTA file contains of 6215006 entries (sum of proteins+decoys).

I also used the same FASTA ( without decoys) for DB searches with MaxQuant and ProteomeDiscoverer using the same DDA data and it works without any problem (but of course huge operating times of the searches).

I also tried to perform the FragPipe searches on a computer with more RAM (160GB), but there was the same fatal error.

The first 20 entries of the FASTA are following:
```
>UniRef90_K5V4C3 Uncharacterized protein (Fragment) n=1 Tax=Vibrio sp. HENC-02 TaxID=992011 RepID=K5V4C3_9VIBR
QAFSEWFIGFL

>rev_UniRef90_K5V4C3 Uncharacterized protein (Fragment) n=1 Tax=Vibrio sp. HENC-02 TaxID=992011 RepID=K5V4C3_9VIBR
QFGIFWESFAL

>UniRef90_A0A1D3N004 Uncharacterized protein n=1 Tax=Bacillus cereus TaxID=1396 RepID=A0A1D3N004_BACCE
MHVKGSAREKR

>rev_UniRef90_A0A1D3N004 Uncharacterized protein n=1 Tax=Bacillus cereus TaxID=1396 RepID=A0A1D3N004_BACCE
MVHKGASREKR

>UniRef90_A0A1C3TGS8 Uncharacterized protein n=1 Tax=Bacillus weihenstephanensis TaxID=86662 RepID=A0A1C3TGS8_9BACI
MALYKMEEDDM

>rev_UniRef90_A0A1C3TGS8 Uncharacterized protein n=1 Tax=Bacillus weihenstephanensis TaxID=86662
 RepID=A0A1C3TGS8_9BACI
MYLAKMDDEEM

>UniRef90_A0A1C4EH54 Uncharacterized protein n=1 Tax=Bacillus weihenstephanensis TaxID=86662 RepID=A0A1C4EH54_9BACI
MMKFGETNYTF

>rev_UniRef90_A0A1C4EH54 Uncharacterized protein n=1 Tax=Bacillus weihenstephanensis TaxID=86662
 RepID=A0A1C4EH54_9BACI
MMKFTYNTEGF

>UniRef90_A0A1C3T4N0 Uncharacterized protein n=1 Tax=Bacillus weihenstephanensis TaxID=86662 RepID=A0A1C3T4N0_9BACI
MHLKGSASEKR

>rev_UniRef90_A0A1C3T4N0 Uncharacterized protein n=1 Tax=Bacillus weihenstephanensis TaxID=86662
 RepID=A0A1C3T4N0_9BACI
MLHKGESASKR

>UniRef90_K5VZT1 Uncharacterized protein (Fragment) n=1 Tax=Vibrio sp. HENC-02 TaxID=992011 RepID=K5VZT1_9VIBR
DRFNSSRYAQW

>rev_UniRef90_K5VZT1 Uncharacterized protein (Fragment) n=1 Tax=Vibrio sp. HENC-02 TaxID=992011 RepID=K5VZT1_9VIBR
DRFSSNRYQAW

>UniRef90_K5UW23 Uncharacterized protein (Fragment) n=1 Tax=Vibrio sp. HENC-02 TaxID=992011 RepID=K5UW23_9VIBR
VRYFSVLVTST

>rev_UniRef90_K5UW23 Uncharacterized protein (Fragment) n=1 Tax=Vibrio sp. HENC-02 TaxID=992011 RepID=K5UW23_9VIBR
VRYSTVLVSFT

>UniRef90_K5V4Q4 Uncharacterized protein (Fragment) n=1 Tax=Vibrio sp. HENC-02 TaxID=992011 RepID=K5V4Q4_9VIBR
QKKLTTSLKQK

>rev_UniRef90_K5V4Q4 Uncharacterized protein (Fragment) n=1 Tax=Vibrio sp. HENC-02 TaxID=992011 RepID=K5V4Q4_9VIBR
QKKLLSTTKQK

>UniRef90_K5VG65 Putative membrane protein (Fragment) n=1 Tax=Vibrio sp. HENC-02 TaxID=992011 RepID=K5VG65_9VIBR
LLMKTTLLIRK

>rev_UniRef90_K5VG65 Putative membrane protein (Fragment) n=1 Tax=Vibrio sp. HENC-02 TaxID=992011
 RepID=K5VG65_9VIBR
LMLKTILLTRK

>UniRef90_K5V8G7 DEAD/DEAH box helicase family protein (Fragment) n=1 Tax=Vibrio sp. HENC-02 TaxID=992011
 RepID=K5V8G7_9VIBR
SSLRLAMILSV

>rev_UniRef90_K5V8G7 DEAD/DEAH box helicase family protein (Fragment) n=1 Tax=Vibrio sp. HENC-02 TaxID=992011
 RepID=K5V8G7_9VIBR
SLSRLSLIMAV
```

**Comment by MaxWeydmann** [comment]
There are "just" 11 thousand species inside, but youre allright, its definitely a very large db.
Counting with dbtoolkit, the FASTA file contains of 6215006 entries (sum of proteins+decoys).

I also used the same FASTA ( without decoys) for DB searches with MaxQuant and ProteomeDiscoverer using the same DDA data and it works without any problem (but of course huge operating times of the searches).

I also tried to perform the FragPipe searches on a computer with more RAM (160GB), but there was the same fatal error.

The first 20 entries of the FASTA are following:
```
>UniRef90_K5V4C3 Uncharacterized protein (Fragment) n=1 Tax=Vibrio sp. HENC-02 TaxID=992011 RepID=K5V4C3_9VIBR
QAFSEWFIGFL

>rev_UniRef90_K5V4C3 Uncharacterized protein (Fragment) n=1 Tax=Vibrio sp. HENC-02 TaxID=992011 RepID=K5V4C3_9VIBR
QFGIFWESFAL

>UniRef90_A0A1D3N004 Uncharacterized protein n=1 Tax=Bacillus cereus TaxID=1396 RepID=A0A1D3N004_BACCE
MHVKGSAREKR

>rev_UniRef90_A0A1D3N004 Uncharacterized protein n=1 Tax=Bacillus cereus TaxID=1396 RepID=A0A1D3N004_BACCE
MVHKGASREKR

>UniRef90_A0A1C3TGS8 Uncharacterized protein n=1 Tax=Bacillus weihenstephanensis TaxID=86662 RepID=A0A1C3TGS8_9BACI
MALYKMEEDDM

>rev_UniRef90_A0A1C3TGS8 Uncharacterized protein n=1 Tax=Bacillus weihenstephanensis TaxID=86662
 RepID=A0A1C3TGS8_9BACI
MYLAKMDDEEM

>UniRef90_A0A1C4EH54 Uncharacterized protein n=1 Tax=Bacillus weihenstephanensis TaxID=86662 RepID=A0A1C4EH54_9BACI
MMKFGETNYTF

>rev_UniRef90_A0A1C4EH54 Uncharacterized protein n=1 Tax=Bacillus weihenstephanensis TaxID=86662
 RepID=A0A1C4EH54_9BACI
MMKFTYNTEGF

>UniRef90_A0A1C3T4N0 Uncharacterized protein n=1 Tax=Bacillus weihenstephanensis TaxID=86662 RepID=A0A1C3T4N0_9BACI
MHLKGSASEKR

>rev_UniRef90_A0A1C3T4N0 Uncharacterized protein n=1 Tax=Bacillus weihenstephanensis TaxID=86662
 RepID=A0A1C3T4N0_9BACI
MLHKGESASKR

>UniRef90_K5VZT1 Uncharacterized protein (Fragment) n=1 Tax=Vibrio sp. HENC-02 TaxID=992011 RepID=K5VZT1_9VIBR
DRFNSSRYAQW

>rev_UniRef90_K5VZT1 Uncharacterized protein (Fragment) n=1 Tax=Vibrio sp. HENC-02 TaxID=992011 RepID=K5VZT1_9VIBR
DRFSSNRYQAW

>UniRef90_K5UW23 Uncharacterized protein (Fragment) n=1 Tax=Vibrio sp. HENC-02 TaxID=992011 RepID=K5UW23_9VIBR
VRYFSVLVTST

>rev_UniRef90_K5UW23 Uncharacterized protein (Fragment) n=1 Tax=Vibrio sp. HENC-02 TaxID=992011 RepID=K5UW23_9VIBR
VRYSTVLVSFT

>UniRef90_K5V4Q4 Uncharacterized protein (Fragment) n=1 Tax=Vibrio sp. HENC-02 TaxID=992011 RepID=K5V4Q4_9VIBR
QKKLTTSLKQK

>rev_UniRef90_K5V4Q4 Uncharacterized protein (Fragment) n=1 Tax=Vibrio sp. HENC-02 TaxID=992011 RepID=K5V4Q4_9VIBR
QKKLLSTTKQK

>UniRef90_K5VG65 Putative membrane protein (Fragment) n=1 Tax=Vibrio sp. HENC-02 TaxID=992011 RepID=K5VG65_9VIBR
LLMKTTLLIRK

>rev_UniRef90_K5VG65 Putative membrane protein (Fragment) n=1 Tax=Vibrio sp. HENC-02 TaxID=992011
 RepID=K5VG65_9VIBR
LMLKTILLTRK

>UniRef90_K5V8G7 DEAD/DEAH box helicase family protein (Fragment) n=1 Tax=Vibrio sp. HENC-02 TaxID=992011
 RepID=K5V8G7_9VIBR
SSLRLAMILSV

>rev_UniRef90_K5V8G7 DEAD/DEAH box helicase family protein (Fragment) n=1 Tax=Vibrio sp. HENC-02 TaxID=992011
 RepID=K5V8G7_9VIBR
SLSRLSLIMAV
```

**Comment by anesvi** [comment]
Assuming Philosopher can deal with the database, you will need to use database splitting option in MSFragger/FragPipe to avoid the 2 billion peptide limit

**Comment by prvst** [comment]
can you send me your database ?

**Comment by MaxWeydmann** [comment]
You can download it here:
https://1drv.ms/u/s!AsvMhfCfg8TNgwvL7vrWYT3DClys

**Comment by prvst** [comment]
@MaxWeydmann 

I need you to do the following for me :

1. Go to the FragPipe folder and copy philosopher binary to the folder containing your data.
2. Hold Shift + right click the folder, on the pop up menu select "open command window here"
3. type te following two commands:
 `.\philosopher_windows_amd64 workspace --init`
`.\philosopher_windows_amd64 database --annotate uniref-90_BSL-2_nr_DECOY.fasta`

Wait until its done and tell me what you see on the terminal screen.

**Comment by MaxWeydmann** [comment]
there is the same error:

```
INFO[19:28:26] Executing Database 20190322
INFO[19:28:26] Processing database
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_SemacquireMutex(0xc0001581d4, 0xc138d40600)
        /usr/local/go/src/runtime/sema.go:71 +0x44
sync.(*Mutex).Lock(0xc0001581d0)
        /usr/local/go/src/sync/mutex.go:134 +0x106
internal/poll.(*FD).Write(0xc000158000, 0xc34ec00000, 0x104dced78, 0x1703c72c0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_windows.go:673 +0x139
os.(*File).write(...)
        /usr/local/go/src/os/file_windows.go:224
os.(*File).Write(0xc000006080, 0xc34ec00000, 0x104dced78, 0x1703c72c0, 0xc000006080, 0x0, 0x0)
        /usr/local/go/src/os/file.go:145 +0x77
io/ioutil.WriteFile(0xc00042c250, 0xc, 0xc34ec00000, 0x104dced78, 0x1703c72c0, 0xc0000001a4, 0xc, 0xc00012f000)
        /usr/local/go/src/io/ioutil/ioutil.go:84 +0x9b
github.com/prvst/philosopher/lib/dat.(*Base).Serialize(0xc000183800, 0xc00001e2e0)
        /home/prvst/go/src/github.com/prvst/philosopher/lib/dat/dat.go:350 +0x238
github.com/prvst/philosopher/lib/dat.Run(0xc00001a6f0, 0x24, 0xc00001a720, 0x28, 0xc0000245a0, 0x49, 0xc00001c500, 0x37, 0xc00001a750, 0x2e, ...)
        /home/prvst/go/src/github.com/prvst/philosopher/lib/dat/dat.go:55 +0x949
github.com/prvst/philosopher/cmd.glob..func4(0x8422500, 0xc0000055a0, 0x0, 0x2)
        /home/prvst/go/src/github.com/prvst/philosopher/cmd/database.go:21 +0x16d
github.com/spf13/cobra.(*Command).execute(0x8422500, 0xc000005580, 0x2, 0x2, 0x8422500, 0xc000005580)
        /home/prvst/go/src/github.com/spf13/cobra/command.go:766 +0x2b5
github.com/spf13/cobra.(*Command).ExecuteC(0x8423f20, 0x4057f6, 0xc0000b2058, 0x0)
        /home/prvst/go/src/github.com/spf13/cobra/command.go:852 +0x2c7
github.com/spf13/cobra.(*Command).Execute(...)
        /home/prvst/go/src/github.com/spf13/cobra/command.go:800
github.com/prvst/philosopher/cmd.Execute()
        /home/prvst/go/src/github.com/prvst/philosopher/cmd/root.go:32 +0x35
main.main()
        /home/prvst/go/src/github.com/prvst/philosopher/main.go:19 +0x75
```
Where do I find the database splitting option?

**Comment by prvst** [comment]
@MaxWeydmann 

This seems to be a problem in Philosopher, and unfortunately the split option will not help. A fix is on its way now, I'll post here when its available.

**Comment by prvst** [comment]
@MaxWeydmann 
The problem was fixed on the last version.
