### ISSUE TITLE
PhilosopherFilter has problem with parsing a file

### ISSUE THREAD

**Issue by vanostad** [Nesvilab/FragPipe#1128]
- Describe the issue or question:
Hello
I'm running an open search on three samples without PTMprophet. The search stops with the Philosopher message "Cannot read file. Error parsing the file". Can you let me know what went wrong?
Thanks already!

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2023-06-02_15-16-26.zip](https://github.com/Nesvilab/FragPipe/files/11635930/log_2023-06-02_15-16-26.zip)

**Comment by dpolasky** [comment]
There appears to be a temporary PeptideProphet file in the directory: 
`INFO[15:08:29] Parsing C:\Tijdelijk\Fragpipe_output\01-07-2023-2\Cry1_Dark\interact.pep.xml.tmp.a20216`
You can delete that temp file and try rerunning from the filter command.

I'm not sure if it's related, but for an open search you should not specify mass offsets for MSFragger, and include at some some area below 0 in the precursor mass tolerance (e.g., -0.1 to +350 Da) to allow unmodified peptides with a small mass error to be found. 

Best,
Dan

**Comment by vanostad** [comment]
Hi Dan
Great, it works! I also converted the files to mzML files which shortened the processing. 
But now I'm running into another problem: for using Fragpipe-Analyst I can only find the file "combined_protein.tsv". Where can I find the "experiment_annotation.tsv" file?

[log_2023-06-02_18-28-39.txt](https://github.com/Nesvilab/FragPipe/files/11637217/log_2023-06-02_18-28-39.txt)

**Comment by fcyu** [comment]
Hi @vanostad ,

You need to enable IonQuant (for LFQ), TMT-Integrator (for TMT), or DIA-NN (for DIA) to have the `experiment_annotation.tsv` file.

Best,

Fengchao

**Comment by vanostad** [comment]
Hi Fengchao
Ok, I see. But enabling IonQuant (on the Quant MS1 tab) blocks the proces immediately, giving the following message:

19:02:54 ERROR: Error delivering events through the bus
java.lang.NumberFormatException: empty String
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(Unknown Source)
	at java.base/jdk.internal.math.FloatingDecimal.parseFloat(Unknown Source)
	at java.base/java.lang.Float.parseFloat(Unknown Source)
	at com.dmtavt.fragpipe.tabs.TabMsfragger.getMassOffsetSet(TabMsfragger.java:1606)
	at com.dmtavt.fragpipe.FragpipeRun.configureTaskGraph(FragpipeRun.java:1494)
	at com.dmtavt.fragpipe.FragpipeRun.run(FragpipeRun.java:294)
	at com.dmtavt.fragpipe.tabs.TabRun.on(TabRun.java:178)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:511)
	at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by vanostad** [comment]
This is all of log file I got from the latest run (with IonQuant activated)...
[log_2023-06-02_19-13-33.txt](https://github.com/Nesvilab/FragPipe/files/11637491/log_2023-06-02_19-13-33.txt)

This is the log file from the run before that was succesfull but did not give me the experiment_annotation.tsv file:
[log_2023-06-02_18-28-39.txt](https://github.com/Nesvilab/FragPipe/files/11637507/log_2023-06-02_18-28-39.txt)

**Comment by fcyu** [comment]
Can you put 0 to your mass-offset setting in MSFragger tab?

**Comment by vanostad** [comment]
Done, and yes, he's running... (now with IonQuant on)!
Thanks a lot!
