### ISSUE TITLE
Error while checking MSFragger jar contents

### ISSUE THREAD

**Issue by animesh** [Nesvilab/FragPipe#1161]
Trying to run latest fragpipe in linux and getting following error

```
/cluster/projects/nn9036k/FPv20/bin/fragpipe --headless --threads 40 --ram 40 --workflow $HOME/open.wf.workflow --manifest $HOME/fp.manifest.fp-manifest --workdir .
2023-06-28 14:25:51,286 WARN  - Error while checking MSFragger jar contents
java.io.IOException: Bad address
        at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at java.base/sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:48)
        at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:245)
        at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:223)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:945)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:940)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1117)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:136)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:139)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:524)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:396)
        at com.dmtavt.fragpipe.tabs.TabConfig.validateMsfraggerJarContents(TabConfig.java:645)
        at com.dmtavt.fragpipe.tabs.TabConfig.on(TabConfig.java:593)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
        at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:454)
        at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:421)
        at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:394)
        at org.greenrobot.eventbus.EventBus.post(EventBus.java:275)
        at com.dmtavt.fragpipe.api.Bus.post(Bus.java:76)
        at com.dmtavt.fragpipe.Fragpipe.headless(Fragpipe.java:470)
        at com.dmtavt.fragpipe.Fragpipe.main0(Fragpipe.java:437)
        at com.dmtavt.fragpipe.FragPipeMain.main(FragPipeMain.java:59)
2023-06-28 14:25:54,105 ERROR - Not a MSFragger jar.
```

Installation of Java and the MSFragger jar file seems to be fine

```
java -jar /cluster/projects/nn9036k/FPv20/tools/MSFragger-3.8/MSFragger-3.8.jar
MSFragger version MSFragger-3.8
Batmass-IO version 1.28.12
timsdata library version timsdata-2-21-0-4
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
timdTOF .d reading tool. Copyright (c) 2022 by Bruker Daltonics GmbH & Co. KG. All rights reserved.
System OS: Linux, Architecture: amd64
Java Info: 17.0.4, OpenJDK 64-Bit Server VM, Eclipse Adoptium
Usage:
        To perform a search either use a parameter file:
                1) java -jar MSFragger.jar <parameter file> <list of mzML/mzXML/MGF/RAW/.d files>
        Or specify options on the command line:
                2) java -jar MSFragger.jar <options> <list of mzML/mzXML/MGF/RAW/.d files>
To generate default parameter files use --config closed/open/nonspecific/glyco. E.g. "java -jar MSFragger.jar --config closed"
To list all the available options, run with --help or -h flag.

```

Linux
```

uname -a
Linux login-1 5.14.0-162.23.1.el9_1.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Apr 11 19:09:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by fcyu** [comment]
Could you please double check if the `fragpipe-config.bin-msfragger` has the correct path to MSFragger jar file?

Best,

Fengchao

**Comment by animesh** [comment]
At least in the UI cache IT Looks like it has correct path, is this variable also somewhere else?

```
(base) [ash022@login-1.SAGA ~]$ java -jar /cluster/projects/nn9036k/fragpipe/tools/MSFragger-3.8/MSFragger-3.8.jar
MSFragger version MSFragger-3.8
Batmass-IO version 1.28.12
timsdata library version timsdata-2-21-0-4
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
timdTOF .d reading tool. Copyright (c) 2022 by Bruker Daltonics GmbH & Co. KG. All rights reserved.
System OS: Linux, Architecture: amd64
Java Info: 17.0.4, OpenJDK 64-Bit Server VM, Eclipse Adoptium
Usage:
        To perform a search either use a parameter file:
                1) java -jar MSFragger.jar <parameter file> <list of mzML/mzXML/MGF/RAW/.d files>
        Or specify options on the command line:
                2) java -jar MSFragger.jar <options> <list of mzML/mzXML/MGF/RAW/.d files>
To generate default parameter files use --config closed/open/nonspecific/glyco. E.g. "java -jar MSFragger.jar --config closed"
To list all the available options, run with --help or -h flag.

```

**Comment by fcyu** [comment]
Could you check the path in the workflow file?

Thanks,

Fengchao

**Comment by animesh** [comment]
Don't see a path variable in 
[open.wf.workflow.txt](https://github.com/Nesvilab/FragPipe/files/11906306/open.wf.workflow.txt) ?

**Comment by fcyu** [comment]
That is the cause of the problem. You need to have 
```shell
fragpipe-config.bin-ionquant=
fragpipe-config.bin-msfragger=
fragpipe-config.bin-philosopher=
fragpipe-config.bin-python=
```
in your workflow file, or `--config-msfragger`, `--config-ionquant`, `--config-philosopher`, and `--config-python` in your command line.

If you are not very familiar with how FragPipe works, I suggest you set the parameters in GUI and save the custom workflow. Then, use that workflow in the headless mode. This is also suggested in https://fragpipe.nesvilab.org/docs/tutorial_headless.html

Best,

Fengchao

**Comment by animesh** [comment]
Thanks for RTFM, the workflow file is created using the GUI, probably that is why it is in the GUI cache directory? Somehow it is failing to add those variable, so i explicity added it now but rrror seems to persists even after adding the path?

```
(base) [ash022@login-1.SAGA ~]$ head open.wf.workflow
# Workflow: open.wf


# Please edit the following path to point to the correct location.
# In Windows, please replace single '\' with '\\'
database.db-path=/cluster/projects/nn9036k/FastaDB/2022-04-21-decoys-isoforms-contam-UP000005640.fas
fragpipe-config.bin-ionquant=/cluster/projects/nn9036k/fragpipe/tools/IonQuant-1.9.8.jar
fragpipe-config.bin-msfragger=/cluster/projects/nn9036k/fragpipe/tools/MSFragger-3.8/MSFragger-3.8.jar
fragpipe-config.bin-philosopher=/cluster/projects/nn9036k/fragpipe/tools/philosopher_v5.0.0_linux_amd64/philosopher
fragpipe-config.bin-python=python
(base) [ash022@login-1.SAGA ~]$ /cluster/projects/nn9036k/fragpipe/bin/fragpipe --headless --threads 40 --ram 40 --workflow $HOME/open.wf.workflow --manifest $HOME/fp.manifest.fp-manifest --workdir .
2023-06-29 15:59:33,002 WARN  - Error while checking MSFragger jar contents
java.io.IOException: Bad address
        at java.base/sun.nio.ch.FileDispatcherImpl.pread0(Native Method)
        at java.base/sun.nio.ch.FileDispatcherImpl.pread(FileDispatcherImpl.java:54)
        at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:328)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:296)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:273)
        at java.base/sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:839)
        at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:824)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1241)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1236)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1553)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:179)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:528)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:400)
        at com.dmtavt.fragpipe.tabs.TabConfig.validateMsfraggerJarContents(TabConfig.java:645)
        at com.dmtavt.fragpipe.tabs.TabConfig.on(TabConfig.java:593)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
        at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:454)
        at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:421)
        at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:394)
        at org.greenrobot.eventbus.EventBus.post(EventBus.java:275)
        at com.dmtavt.fragpipe.api.Bus.post(Bus.java:76)
        at com.dmtavt.fragpipe.Fragpipe.headless(Fragpipe.java:470)
        at com.dmtavt.fragpipe.Fragpipe.main0(Fragpipe.java:437)
        at com.dmtavt.fragpipe.FragPipeMain.main(FragPipeMain.java:59)
2023-06-29 15:59:35,257 ERROR - Not a MSFragger jar.
```

**Comment by fcyu** [comment]
Hmm, could you use the `--config-msfragger` flag on the command line to see if it works?

Thanks,

Fengchao

**Comment by animesh** [comment]
Error still persists, probably i am not invoking it properly?
```

(base) [ash022@login-1.SAGA ~]$ /cluster/projects/nn9036k/fragpipe/bin/fragpipe  --config-msfragger /cluster/projects/nn9036k/fragpipe/tools/MSFragger-3.8/MSFragger-3.8.jar --headless --threads 40 --ram 40 --workflow $HOME/open.wf.workflow --manifest $HOME/fp.manifest.fp-manifest --workdir .
2023-06-29 16:15:28,430 WARN  - Error while checking MSFragger jar contents
java.io.IOException: Bad address
        at java.base/sun.nio.ch.FileDispatcherImpl.pread0(Native Method)
        at java.base/sun.nio.ch.FileDispatcherImpl.pread(FileDispatcherImpl.java:54)
        at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:328)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:296)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:273)
        at java.base/sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:839)
        at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:824)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1241)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1236)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1553)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:179)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:528)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:400)
        at com.dmtavt.fragpipe.tabs.TabConfig.validateMsfraggerJarContents(TabConfig.java:645)
        at com.dmtavt.fragpipe.tabs.TabConfig.on(TabConfig.java:593)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
        at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:454)
        at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:421)
        at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:394)
        at org.greenrobot.eventbus.EventBus.post(EventBus.java:275)
        at com.dmtavt.fragpipe.api.Bus.post(Bus.java:76)
        at com.dmtavt.fragpipe.Fragpipe.headless(Fragpipe.java:470)
        at com.dmtavt.fragpipe.Fragpipe.main0(Fragpipe.java:437)
        at com.dmtavt.fragpipe.FragPipeMain.main(FragPipeMain.java:59)
2023-06-29 16:15:32,120 ERROR - Not a MSFragger jar.

```

**Comment by fcyu** [comment]
I have no idea. Maybe due to some Linux permission configurations. You might need to troubleshoot locally with your IT support.

Best,

Fengchao

**Comment by fcyu** [comment]
Although it is unlikely the cause, but could you put `--headless` to the first position? If it still can't solve the problem, I have no idea. Maybe you should troubleshoot locally with your IT support.

Best,

Fengchao

**Comment by animesh** [comment]
Thanks for trying nonetheless but error seems to still persist, will check with local IT 👍🏽
