### ISSUE TITLE
ERROR: Error delivering events through the bus

### ISSUE THREAD

**Issue by ClaSofMag** [Nesvilab/FragPipe#1162]
Hello,

I not an imediate error while trying to start the run on the GUI.

Please find the log Report attached.

Thank you for your help.

[log_2023-06-28_21-50-21.txt](https://github.com/Nesvilab/FragPipe/files/11899899/log_2023-06-28_21-50-21.txt)

**Comment by fcyu** [comment]
The FragPipe folder was corrupted. Could you re-download the zip file, **unzip** it to a folder, and try again?

Thanks,

Fengchao

**Comment by ClaSofMag** [comment]
Hello,

It didn't work, so I was trying now to run it on a remote core from my University, but not it gives this error:

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/dmtavt/fragpipe/FragPipeMain has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:621)

But java is up to date:
[claudia@ceta eofiles]$ java -version
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (build 25.362-b09, mixed mode)

Thank you for your help,

**Comment by fcyu** [comment]
@ClaSofMag , a little background in case you don't understand. 

Java 8 was released in 2014 and its premier support ended in March 2022: https://www.oracle.com/java/technologies/java-se-support-roadmap.html

FragPipe requires java 9+ since version 18.0 released on May 27, 2022: https://github.com/Nesvilab/FragPipe/releases/tag/18.0

Best,

Fengchao
