### ISSUE TITLE
 java.net.SocketTimeoutException: timeout 

### ISSUE THREAD

**Issue by pankajdwid** [Nesvilab/FragPipe#1175]
java.net.SocketTimeoutException: timeout
	at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:147)
	at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:158)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:337)
	at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
	at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.kt:331)
	at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.kt:368)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
	at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
	at okio.ForwardingSource.read(ForwardingSource.kt:27)
	at com.dmtavt.fragpipe.tools.ionquant.IonQuantVersionFetcherServer$1.read(IonQuantVersionFetcherServer.java:185)
	at com.dmtavt.fragpipe.tools.ionquant.IonQuantVersionFetcherServer.autoUpdate(IonQuantVersionFetcherServer.java:194)
	at com.dmtavt.fragpipe.tabs.TabConfig.lambda$actionIonQuantUpdate$12(TabConfig.java:498)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(Unknown Source)
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at okio.InputStreamSource.read(JvmOkio.kt:94)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
	... 10 more

**Comment by fcyu** [comment]
Something was run when FragPipe was downloading IonQuant. Please troubleshoot your Internet connection.

Best,

Fengchao
