### ISSUE TITLE
Add decoys problem

### ISSUE THREAD

**Issue by cesarrivera** [Nesvilab/FragPipe#1203]
Hello community. When trying to add decoys to a database of bacterial amino acid sequences, MSfragger shows the following error:

java.lang.IllegalStateException: Something happened during database update
	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$updateDb$7(DownloadDbHelper.java:376)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Process returned non zero value
	at com.dmtavt.fragpipe.api.DownloadDbHelper.runProcesses(DownloadDbHelper.java:296)
	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$updateDb$7(DownloadDbHelper.java:372)
	... 1 more

![image](https://github.com/Nesvilab/FragPipe/assets/2237782/5e7a9147-7ad3-469e-a016-9909bf2bf70f)

I have verified the database, and the decoys or contaminants are not added. How can I resolve this error? I am using MSFragger-3.8.jar, IonQuant-1.9.8.jar, and philosopher_v5.0.0.

**Comment by fcyu** [comment]
To get more information about the error, could you copy paste the messages in the console of the `run` tab and paste them here? 

Best

**Comment by cesarrivera** [comment]
Hello, I corrected the error. When I merged several fasta files with windows functions, the file was left with problems. I cleaned up the headers and sequences with R studio scripts. Thank you!
