### ISSUE TITLE
Upon putting in an expected modification there is an error

### ISSUE THREAD

**Issue by kapoochi** [Nesvilab/FragPipe#1213]
Checking database...
java.lang.ArrayIndexOutOfBoundsException: Index 276 out of bounds for length 256
	at u.a(Unknown Source)
	at u.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping
[log_2023-08-10_16-33-45.txt](https://github.com/Nesvilab/FragPipe/files/12314608/log_2023-08-10_16-33-45.txt)

**Comment by fcyu** [comment]
Your variable modification setting, `178.04774,galactosyl,1`, does not follow the format requirement. It should be one single character for the amino acid. Also, `galactosyl` does not seems to be an amino acid.

Best,

Fengchao
