### ISSUE TITLE
peptideprophet - combine results filure

### ISSUE THREAD

**Issue by tretyacv** [Nesvilab/FragPipe#1218]
Hi I am trying to run a pipeline and I identified a step where it crashes. When i run  

```
./philosopher peptideprophet --nonparam --expectscore --decoyprobs --masswidth 1000.0 --clevel -2 --decoy rev_ --database 2021-03-16-reviewed-contam-UP000002311.fas --combine 
``` 
(I took fasta file from one of your papers to avoid any fasta related mistakes) I get this:

I
```
INFO[15:21:04] Executing PeptideProphet  v5.0.0             
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/Nesvilab/philosopher/lib/ext/peptideprophet.interactParser({{0xc0000346c0, 0x38}, {0xc000034700, 0x37}, {0xc000034740, 0x3e}, {0xc000034780, 0x3c}, {0xc0000347c0, 0x3b}, ...}, ...)
	D:/Projects/philosopher/philosopher/lib/ext/peptideprophet/peptideprophet.go:179 +0xbbc
github.com/Nesvilab/philosopher/lib/ext/peptideprophet.PeptideProphet.Execute({{0xc0000346c0, 0x38}, {0xc000034700, 0x37}, {0xc000034740, 0x3e}, {0xc000034780, 0x3c}, {0xc0000347c0, 0x3b}, ...}, ...)
	D:/Projects/philosopher/philosopher/lib/ext/peptideprophet/peptideprophet.go:86 +0x205
github.com/Nesvilab/philosopher/lib/ext/peptideprophet.Run({{0xc00002c510, 0x24}, {0xc0000363c0, 0x43}, {0xc00002c540, 0x29}, {0xc00004a2a0, 0x52}, {0xc000036410, 0x49}, ...}, ...)
	D:/Projects/philosopher/philosopher/lib/ext/peptideprophet/peptideprophet.go:67 +0x373
github.com/Nesvilab/philosopher/cmd.glob..func12(0x2657fa0?, {0xc000000300, 0x0, 0xc})
	D:/Projects/philosopher/philosopher/cmd/peproph.go:26 +0xc8
github.com/spf13/cobra.(*Command).execute(0x2657fa0, {0xc000000240, 0xc, 0xc})
	D:/Projects/philosopher/philosopher/vendor/github.com/spf13/cobra/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x2658e00)
	D:/Projects/philosopher/philosopher/vendor/github.com/spf13/cobra/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	D:/Projects/philosopher/philosopher/vendor/github.com/spf13/cobra/command.go:968
github.com/Nesvilab/philosopher/cmd.Execute()
	D:/Projects/philosopher/philosopher/cmd/root.go:35 +0x25
main.main()
	D:/Projects/philosopher/philosopher/main.go:23 +0x85
``` 
Can you advise on the issue please?

**Comment by fcyu** [comment]
Could you share the whole log file?

Thanks,

Fengchao

**Comment by tretyacv** [comment]
Ah, yes, I'm sorry, I forgot to mention this. I am using older version of fragpipe/msfragger for a compatibility reasons. I wanted to supply them with the philosopher 4.1.0 but I had some trouble with building it. I followed instructions from here: https://github.com/Nesvilab/philosopher/wiki/How-to-Build and downloaded source from the [github](https://github.com/Nesvilab/philosopher/releases?page=2)

```
gox -os="linux" -ldflags "-w -s -X main.version=4.1.0"

``` 
this gets me
```
Number of parallel builds: 15

-->    linux/mipsle: philosopher
-->       linux/386: philosopher
-->   linux/ppc64le: philosopher
-->    linux/mips64: philosopher
-->     linux/s390x: philosopher
-->       linux/arm: philosopher
-->     linux/arm64: philosopher
-->  linux/mips64le: philosopher
-->     linux/ppc64: philosopher
-->     linux/amd64: philosopher
-->      linux/mips: philosopher

11 errors occurred:
--> linux/amd64 error: exit status 1
Stderr: # philosopher/lib/ext/rawfilereader/deb64
lib/ext/rawfilereader/deb64/deb64.go:15:13: undefined: Asset
# philosopher/lib/ext/rawfilereader/reh64
lib/ext/rawfilereader/reh64/reh64.go:15:13: undefined: Asset
# philosopher/lib/ext/rawfilereader/win
lib/ext/rawfilereader/win/win.go:15:13: undefined: Asset
lib/ext/rawfilereader/win/win.go:29:13: undefined: Asset
lib/ext/rawfilereader/win/win.go:43:13: undefined: Asset

--> linux/ppc64 error: exit status 1
Stderr: # philosopher/lib/ext/rawfilereader/deb64
lib/ext/rawfilereader/deb64/deb64.go:15:13: undefined: Asset
# philosopher/lib/ext/rawfilereader/reh64
lib/ext/rawfilereader/reh64/reh64.go:15:13: undefined: Asset
# philosopher/lib/ext/rawfilereader/win
lib/ext/rawfilereader/win/win.go:15:13: undefined: Asset
lib/ext/rawfilereader/win/win.go:29:13: undefined: Asset
lib/ext/rawfilereader/win/win.go:43:13: undefined: Asset

--> linux/mipsle error: exit status 1
Stderr: # philosopher/lib/ext/rawfilereader/deb64
lib/ext/rawfilereader/deb64/deb64.go:15:13: undefined: Asset
# philosopher/lib/ext/rawfilereader/win
lib/ext/rawfilereader/win/win.go:15:13: undefined: Asset
lib/ext/rawfilereader/win/win.go:29:13: undefined: Asset
lib/ext/rawfilereader/win/win.go:43:13: undefined: Asset
# philosopher/lib/ext/rawfilereader/reh64
lib/ext/rawfilereader/reh64/reh64.go:15:13: undefined: Asset

--> linux/arm error: exit status 1
Stderr: # philosopher/lib/ext/rawfilereader/deb64
lib/ext/rawfilereader/deb64/deb64.go:15:13: undefined: Asset
# philosopher/lib/ext/rawfilereader/reh64
lib/ext/rawfilereader/reh64/reh64.go:15:13: undefined: Asset
# philosopher/lib/ext/rawfilereader/win
lib/ext/rawfilereader/win/win.go:15:13: undefined: Asset
lib/ext/rawfilereader/win/win.go:29:13: undefined: Asset
lib/ext/rawfilereader/win/win.go:43:13: undefined: Asset

--> linux/mips error: exit status 1
Stderr: # philosopher/lib/ext/rawfilereader/deb64
lib/ext/rawfilereader/deb64/deb64.go:15:13: undefined: Asset
# philosopher/lib/ext/rawfilereader/reh64
lib/ext/rawfilereader/reh64/reh64.go:15:13: undefined: Asset
# philosopher/lib/ext/rawfilereader/win
lib/ext/rawfilereader/win/win.go:15:13: undefined: Asset
lib/ext/rawfilereader/win/win.go:29:13: undefined: Asset
lib/ext/rawfilereader/win/win.go:43:13: undefined: Asset

--> linux/386 error: exit status 1
Stderr: # philosopher/lib/ext/rawfilereader/deb64
lib/ext/rawfilereader/deb64/deb64.go:15:13: undefined: Asset
# philosopher/lib/ext/rawfilereader/reh64
lib/ext/rawfilereader/reh64/reh64.go:15:13: undefined: Asset
# philosopher/lib/ext/rawfilereader/win
lib/ext/rawfilereader/win/win.go:15:13: undefined: Asset
lib/ext/rawfilereader/win/win.go:29:13: undefined: Asset
lib/ext/rawfilereader/win/win.go:43:13: undefined: Asset

--> linux/s390x error: exit status 1
Stderr: # philosopher/lib/ext/rawfilereader/deb64
lib/ext/rawfilereader/deb64/deb64.go:15:13: undefined: Asset
# philosopher/lib/ext/rawfilereader/reh64
lib/ext/rawfilereader/reh64/reh64.go:15:13: undefined: Asset
# philosopher/lib/ext/rawfilereader/win
lib/ext/rawfilereader/win/win.go:15:13: undefined: Asset
lib/ext/rawfilereader/win/win.go:29:13: undefined: Asset
lib/ext/rawfilereader/win/win.go:43:13: undefined: Asset

--> linux/mips64le error: exit status 1
Stderr: # philosopher/lib/ext/rawfilereader/deb64
lib/ext/rawfilereader/deb64/deb64.go:15:13: undefined: Asset
# philosopher/lib/ext/rawfilereader/reh64
lib/ext/rawfilereader/reh64/reh64.go:15:13: undefined: Asset
# philosopher/lib/ext/rawfilereader/win
lib/ext/rawfilereader/win/win.go:15:13: undefined: Asset
lib/ext/rawfilereader/win/win.go:29:13: undefined: Asset
lib/ext/rawfilereader/win/win.go:43:13: undefined: Asset

--> linux/ppc64le error: exit status 1
Stderr: # philosopher/lib/ext/rawfilereader/deb64
lib/ext/rawfilereader/deb64/deb64.go:15:13: undefined: Asset
# philosopher/lib/ext/rawfilereader/reh64
lib/ext/rawfilereader/reh64/reh64.go:15:13: undefined: Asset
# philosopher/lib/ext/rawfilereader/win
lib/ext/rawfilereader/win/win.go:15:13: undefined: Asset
lib/ext/rawfilereader/win/win.go:29:13: undefined: Asset
lib/ext/rawfilereader/win/win.go:43:13: undefined: Asset

--> linux/mips64 error: exit status 1
Stderr: # philosopher/lib/ext/rawfilereader/deb64
lib/ext/rawfilereader/deb64/deb64.go:15:13: undefined: Asset
# philosopher/lib/ext/rawfilereader/reh64
lib/ext/rawfilereader/reh64/reh64.go:15:13: undefined: Asset
# philosopher/lib/ext/rawfilereader/win
lib/ext/rawfilereader/win/win.go:15:13: undefined: Asset
lib/ext/rawfilereader/win/win.go:29:13: undefined: Asset
lib/ext/rawfilereader/win/win.go:43:13: undefined: Asset

--> linux/arm64 error: exit status 1
Stderr: # philosopher/lib/ext/rawfilereader/deb64
lib/ext/rawfilereader/deb64/deb64.go:15:13: undefined: Asset
# philosopher/lib/ext/rawfilereader/reh64
lib/ext/rawfilereader/reh64/reh64.go:15:13: undefined: Asset
# philosopher/lib/ext/rawfilereader/win
lib/ext/rawfilereader/win/win.go:15:13: undefined: Asset
lib/ext/rawfilereader/win/win.go:29:13: undefined: Asset
lib/ext/rawfilereader/win/win.go:43:13: undefined: Asset

```

**Comment by anesvi** [comment]
As a general comment, unfortunately, we cannot go back to older versions of Philosopher. We can only recommend upgrading to the latest version of all tools. We fixed ton of issues like this, and that's why release new versions.... We cannot go back two years ago and start fixing the same issues...
Alexey

**Comment by fcyu** [comment]
Could you use the latest versions of MSFragger and Philosopher? You can also use FragPipe that has command line interface and GUI.

Also, your MSFragger parameters are not open search. I list some serious mistakes in the following.

precursor_mass_lower = -5.0
precursor_mass_upper = 5.0
precursor_mass_units = 1
isotope_error = 0/1
localize_delta_mass = false

Please please use FragPipe and the build-in Open workflow if you are not very familiar with our tools.

Best,

Fengchao
