### ISSUE TITLE
Java error

### ISSUE THREAD

**Issue by alexproteomics** [Nesvilab/FragPipe#123]
# Describe the problem

* **I'm submitting a:**
  - [x] problem running the software
  - [ ] bug report
  - [ ] feature request
  - [ ] question

* **My MSFragger use case:**
  - [ ] _Closed_ search (standard small precursor mass tolerance)
  - [x] _Open_ search (large precursor mass tolerance)

FragPipe stops after a while. It seems a java memory error: java.lang.OutOfMemoryError

## System info

System OS: Windows Server 2012 R2, Architecture: AMD64
Java Info: 1.8.0_201, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation

----

## Describe your experiment
Trying to identify potential targets of proteases using TAILS approach. That is, TMT was used to label proteins following protease treatment. Then, proteins were digested with trypsin. 
I want to perform a semispecific Open search in order to find out unexpected modifications. Note that while most Lys should be labeled, only n-termini cut with the protease of interest should be TMT-labeled. 

### General proteomics experiment description
TMT labeled at protein level so TMT should be a variable modification, Human, secretome, trypsin digest but with expected non-tryptic termini

...

### Input data files
2 mzml files 700Mb each

### Sequence database

swissprot human database with rev_ entries (26Mb total), after indexing = 1.6Gb

----

## Attach fragger.params file

[fragger.params.txt](https://github.com/Nesvilab/FragPipe/files/3370684/fragger.params.txt)

## Run log output

```
System info:
System OS: Windows Server 2012 R2, Architecture: AMD64
Java Info: 1.8.0_201, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation

Version info:
FragPipe version 9.4
MSFragger version 20171106
Philosopher version Unknown


LCMS files:
  Experiment/Group: HEK
  - S:\data\Smith\P000942\S13892.mzML
  Experiment/Group: YUSIK
  - S:\data\Smith\P000942\S13890.mzML

7 commands to execute:
MsFragger [Work dir: S:\data\Smith\P000942\MSFragger\results]
java -jar -Dfile.encoding=UTF-8 S:\apps\MSFragger-20171106\MSFragger-20171106.jar S:\data\Smith\P000942\MSFragger\results\fragger.params S:\data\Smith\P000942\S13892.mzML S:\data\Smith\P000942\S13890.mzML
MsFragger
java -cp S:\apps\FragPipe.exe umich.msfragger.util.FileMove S:\data\Smith\P000942\S13892.pepXML S:\data\Smith\P000942\MSFragger\results\HEK\S13892.pepXML
MsFragger
java -cp S:\apps\FragPipe.exe umich.msfragger.util.FileMove --no-err S:\data\Smith\P000942\S13892.tsv S:\data\Smith\P000942\MSFragger\results\HEK\S13892.tsv
MsFragger
java -cp S:\apps\FragPipe.exe umich.msfragger.util.FileMove S:\data\Smith\P000942\S13890.pepXML S:\data\Smith\P000942\MSFragger\results\YUSIK\S13890.pepXML
MsFragger
java -cp S:\apps\FragPipe.exe umich.msfragger.util.FileMove --no-err S:\data\Smith\P000942\S13890.tsv S:\data\Smith\P000942\MSFragger\results\YUSIK\S13890.tsv
Crystal-C [Work dir: S:\data\Smith\P000942\MSFragger\results\HEK]
java -cp "C:\Users\AROSAC~1\AppData\Local\Temp\3\fragpipe\common-deps-1.0.3.jar;C:\Users\AROSAC~1\AppData\Local\Temp\3\fragpipe\original-CrystalC-1.0.5.jar" Main S:\data\Smith\P000942\MSFragger\results\HEK\crystalc-0-S13892.pepXML.params S:\data\Smith\P000942\MSFragger\results\HEK\S13892.pepXML
Crystal-C [Work dir: S:\data\Smith\P000942\MSFragger\results\YUSIK]
java -cp "C:\Users\AROSAC~1\AppData\Local\Temp\3\fragpipe\common-deps-1.0.3.jar;C:\Users\AROSAC~1\AppData\Local\Temp\3\fragpipe\original-CrystalC-1.0.5.jar" Main S:\data\Smith\P000942\MSFragger\results\YUSIK\crystalc-1-S13890.pepXML.params S:\data\Smith\P000942\MSFragger\results\YUSIK\S13890.pepXML
~~~~~~~~~~~~~~~~~~~~~~


MsFragger [Work dir: S:\data\Smith\P000942\MSFragger\results]
java -jar -Dfile.encoding=UTF-8 S:\apps\MSFragger-20171106\MSFragger-20171106.jar S:\data\Smith\P000942\MSFragger\results\fragger.params S:\data\Smith\P000942\S13892.mzML S:\data\Smith\P000942\S13890.mzML
MSFragger version MSFragger-20171106
(c) University of Michigan

Unknown parmameters:
	calibrate_mass = 2
	decoy_prefix = rev_
	delta_mass_exclude_ranges = (-1.5,3.5)
	fragment_ion_series = b,y
	localize_delta_mass = 1
	mass_offsets = 0
	precursor_mass_mode = selected
	report_alternative_proteins = 0
Sequence database filtered and tagged in 128ms
Digestion completed in 1596ms
Merged digestion results in 1347ms
Sorting digested sequences...
	of length 7: 2440908
	of length 8: 2423626
	of length 9: 2398644
	of length 10: 2375961
	of length 11: 2351217
	of length 12: 2323434
	of length 13: 2295319
	of length 14: 2265391
	of length 15: 2236102
	of length 16: 2206021
	of length 17: 2173639
	of length 18: 2139887
	of length 19: 2105318
	of length 20: 2072413
	of length 21: 2037342
	of length 22: 2002082
	of length 23: 1967610
	of length 24: 1932195
	of length 25: 1897004
	of length 26: 1862039
	of length 27: 1825248
	of length 28: 1783670
	of length 29: 1749350
	of length 30: 1714418
	of length 31: 1677858
	of length 32: 1641807
	of length 33: 1605835
	of length 34: 1570172
	of length 35: 1536192
	of length 36: 1501165
	of length 37: 1466886
	of length 38: 1433006
	of length 39: 1400210
	of length 40: 1363430
	of length 41: 1314778
	of length 42: 1224071
	of length 43: 1062354
	of length 44: 837544
	of length 45: 594982
	of length 46: 386741
	of length 47: 234254
	of length 48: 134536
	of length 49: 75792
	of length 50: 43257
	DONE
Removing duplicates and compacting...
Reduced to 67837844  peptides in 46209ms
Generating modified peptides...Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at y.a(Unknown Source)
	at w.a(Unknown Source)
	at e.a(Unknown Source)
	at MSFragger.main(Unknown Source)
	... 5 more
Caused by: java.lang.OutOfMemoryError: Java heap space

~~~~~~~~~~~~~~~~~~~~
Stopping 8/8 processes (0 already finished)
Processing interrupted, stopping MsFragger

```

**Comment by fcyu** [comment]
Hi,

Thanks for your interest in MSFragger. First of all, you are using a very old version of MSFragger. You may download the latest one from [http://msfragger.arsci.com/upgrader/](http://msfragger.arsci.com/upgrader/). Second, you need to fill in a memory value according to your computer in the FragPipe:
![image](https://user-images.githubusercontent.com/6926299/60851406-0d92df00-a1c1-11e9-9d73-639a5794a1ba.png)

Best,

Fengchao

**Comment by alexproteomics** [comment]
Thanks for your help Fengchao! Actually, I had the new version of MSFragger, I either forgot to update the FragPipe config or sent you the old file. Anyway, I will try it again and set the RAM, I thought that leaving it at zero would do an auto-detect.
thanks again
Alex

**Comment by fcyu** [comment]
Welcome.
