### ISSUE TITLE
Unknown MSFragger error

### ISSUE THREAD

**Issue by Dan-Zed** [Nesvilab/FragPipe#125]
# Describe the problem

* **I'm submitting a:**
  - [x] problem running the software
  - [ ] bug report
  - [ ] feature request
  - [ ] question

* **My MSFragger use case:**
  - [ ] _Closed_ search (standard small precursor mass tolerance)
  - [x] _Open_ search (large precursor mass tolerance)

 ** Unknown error, same in either GUI or command line. **

## System info

You can find that printed on the _Config_ tab.
- OS and version: ** Win10 **
- Java version: ** 1.8 (latest update) **

----

### Genral proteomics experiment description
Simple 1 protein system, tryptic digest

...

### Input data files
One file, tested both thermo raw and mzxml

### Sequence database

1 protein with several decoys. 

----

## Attach fragger.params file

```
num_threads = 8
database_name = C:\Users\MS Studio\Documents\FASTAs\pTf-ApTbpB_trunc_MSF.fasta
decoy_prefix = rev_
precursor_mass_lower = -20.0
precursor_mass_upper = 20.0
precursor_mass_units = 1
precursor_true_tolerance = 20.0
precursor_true_units = 1
fragment_mass_tolerance = 20.0
fragment_mass_units = 1
calibrate_mass = 2
evaluate_mass_calibration = false
isotope_error = 0/1
mass_offsets = 0
precursor_mass_mode = SELECTED
localize_delta_mass = false
delta_mass_exclude_ranges = (-1.5,3.5)
fragment_ion_series = b,y
search_enzyme_name = Trypsin
search_enzyme_cutafter = KR
search_enzyme_butnotafter = P
num_enzyme_termini = 2
allowed_missed_cleavage = 1
clip_nTerm_M = true
allow_multiple_variable_mods_on_residue = false
max_variable_mods_per_mod = 3
max_variable_mods_combinations = 5000
output_file_extension = pepXML
output_format = pepXML
output_report_topN = 1
output_max_expect = 50.0
report_alternative_proteins = false
override_charge = false
precursor_charge_low = 1
precursor_charge_high = 4
digest_min_length = 7
digest_max_length = 50
digest_mass_range_low = 500.0
digest_mass_range_high = 5000.0
max_fragment_charge = 2
track_zero_topN = 0
zero_bin_accept_expect = 0.0
zero_bin_mult_expect = 1.0
add_topN_complementary = 0
minimum_peaks = 15
use_topN_peaks = 100
minIonsScoring = 3
min_matched_fragments = 5
minimum_ratio = 0.01
clear_mz_range_low = 0.0
clear_mz_range_high = 0.0
excluded_scan_list_file = 
variable_mod_01 = 15.99490 M
variable_mod_02 = 42.01060 [^                 

# Fixed modifications
add_Cterm_peptide = 0.000000
add_Nterm_peptide = 0.000000
add_Cterm_protein = 0.000000
add_Nterm_protein = 0.000000
add_G_glycine = 0.000000
add_A_alanine = 0.000000
add_S_serine = 0.000000
add_P_proline = 0.000000
add_V_valine = 0.000000
add_T_threonine = 0.000000
add_C_cysteine = 57.021464
add_L_leucine = 0.000000
add_I_isoleucine = 0.000000
add_N_asparagine = 0.000000
add_D_aspartic_acid = 0.000000
add_Q_glutamine = 0.000000
add_K_lysine = 0.000000
add_E_glutamic_acid = 0.000000
add_M_methionine = 0.000000
add_H_histidine = 0.000000
add_F_phenylalanine = 0.000000
add_R_arginine = 0.000000
add_Y_tyrosine = 0.000000
add_W_tryptophan = 0.000000
add_B_user_amino_acid = 0.000000
add_J_user_amino_acid = 0.000000
add_O_user_amino_acid = 0.000000
add_U_user_amino_acid = 0.000000
add_X_user_amino_acid = 0.000000
add_Z_user_amino_acid = 0.000000
```

## Run log output

```
PS C:\Users\MS Studio\Documents\MSFragger-20190628> java -Xmx16G -jar .\MSFragger-20190628.jar .\open_fragger_cust.param
s .\LC.mzXML
MSFragger version MSFragger-20190628
MSFTBX version 1.9.10
(c) University of Michigan
RawFileReader reading tool. Copyright ? 2016 by Thermo Fisher Scientific, Inc. All rights reserved.

System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_201, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation
JVM started with 14564 MB memory

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.NumberFormatException: For input string: "false"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at edu.umich.andykong.msfragger.E.a(Unknown Source)
        at edu.umich.andykong.msfragger.E.a(Unknown Source)
        at edu.umich.andykong.msfragger.E.<init>(Unknown Source)
        at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source)
        at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source)
        at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
        ... 6 more
```

**Comment by fcyu** [comment]
Looks like you give “false” to one parameter that is supposed to have a
integer number. Could you please double check your parameters?

Thanks,

Fengchao

**Comment by Dan-Zed** [comment]
Thanks Fengchao, indeed I had true/false instead of 1/0. My mistake - I copied and pasted from the GUI.
