### ISSUE TITLE
EasyPQP convert error

### ISSUE THREAD

**Issue by Amon789** [Nesvilab/FragPipe#1252]
I get this Error message when analyzing DIA mzML in both modes either 
1) [DIA_SpecLib_Quant,   2) DIA_DIA-Umpire_SpecLib_Quant

Here is the beginning of the error message. Attached is the log

EasyPQP convert error BEGIN
2023-09-18 17:20:48 - Info: Converting ['C:\\Users\\ahmedmon\\Desktop\\My_WorkSpace\\Proteomics\\20230911\\OutPut\\fragepipe\\DIA_SpecLib_workflow\\interact-20230911_10_S3_2_DIA_rank4.pep.xml'].
2023-09-18 17:20:48 - Info: Parsing run 20230911_10_S3_2_DIA.
Warning: OPENMS_DATA_PATH environment variable already exists. pyOpenMS will use it (C:\Users\ahmedmon\AppData\Local\Programs\Python\Python39\lib\site-packages\pyopenms\share/OpenMS) to locate data in the OpenMS share folder (e.g., the unimod database), instead of the default (C:\Users\ahmedmon\AppData\Local\Programs\Python\Python39\lib\site-packages\pyopenms\share/OpenMS).
2023-09-18 17:20:49 - Info: Parsing pepXML: C:\Users\ahmedmon\Desktop\My_WorkSpace\Proteomics\20230911_Rahul\OutPut\fragepipe\DIA_SpecLib_workflow\interact-20230911_10_S3_2_DIA_rank4.pep.xml
2023-09-18 17:20:49 - Info: Processing spectra from file C:\Users\ahmedmon\Desktop\My_WorkSpace\Proteomics\20230911_Rahul\mzml\DIA\20230911_10_S3_2_DIA.mzML.
2023-09-18 17:21:03 - Info: Loaded 49649 spectra
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\ahmedmon\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\Users\ahmedmon\AppData\Local\Programs\Python\Python39\lib\site-packages\easypqp\convert.py", line 688, in parse_pepxmls
    psms['group_id'] = psms['run_id'] + "_" + psms['scan_id'].astype(str) + rank_str
  File "C:\Users\ahmedmon\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\ahmedmon\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexes\range.py", line 349, in get_loc
    raise KeyError(key)
KeyError: 'run_id'
"""

[log_2023-09-18_17-47-04.txt](https://github.com/Nesvilab/FragPipe/files/12649342/log_2023-09-18_17-47-04.txt)

**Comment by danielgeiszler** [comment]
This is because you have quite a files with no PSMs. Can you please check your settings to make sure they match your experiment?

**Comment by Amon789** [comment]
This DIA data contains few proteins in two samples but about hundreds in others. The DDA data of the same set works well. I try to analyze these DIA with the default DIA workflow in fragepipe, Is that ok? Or I need to change some parameters in the workflow?

**Comment by fcyu** [comment]
Same issue as https://github.com/Nesvilab/FragPipe/issues/1223 and https://github.com/Nesvilab/FragPipe/issues/1217#issuecomment-1683042664. The current workaround is in https://github.com/Nesvilab/FragPipe/issues/1217#issuecomment-1684897694. 

The new EasyPQP will be released after George accepts my pull request: https://github.com/grosenberger/easypqp/pull/105

Best,

Fengchao
