### ISSUE TITLE
NoSuchFileException error possibly due to some random IO issue... Fragpipe in headless mode

### ISSUE THREAD

**Issue by marioernestovaldes** [Nesvilab/FragPipe#1289]
- Describe the issue or question:

I am running Fragpipe in headless mode on a cluster. I have 200 mzML files and I am running 200 jobs, and all of them use the same fragpipe executable. Oddly, most of them finish successfully, while a few end up with an error like this:

```
2023-10-13 18:31:04,851 ERROR - Something unexpected happened!
java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /home/mario.valdeztresanco/.config/FragPipe/fragpipe/workflows/glyco-O-Pair.workflow
	at java.base/java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:87)
	at java.base/java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:103)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.dmtavt.fragpipe.tabs.TabWorkflow.findPropsFiles(TabWorkflow.java:549)
	at com.dmtavt.fragpipe.tabs.TabWorkflow.loadWorkflowFiles(TabWorkflow.java:569)
	at com.dmtavt.fragpipe.tabs.TabWorkflow.createPanelWorkflows(TabWorkflow.java:626)
	at com.dmtavt.fragpipe.tabs.TabWorkflow.init(TabWorkflow.java:469)
	at com.dmtavt.fragpipe.tabs.TabWorkflow.<init>(TabWorkflow.java:278)
	at com.dmtavt.fragpipe.Fragpipe.createTabs(Fragpipe.java:618)
	at com.dmtavt.fragpipe.Fragpipe.initUi(Fragpipe.java:691)
	at com.dmtavt.fragpipe.Fragpipe.<init>(Fragpipe.java:216)
	at com.dmtavt.fragpipe.Fragpipe.lambda$displayMainWindow$3(Fragpipe.java:495)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.nio.file.NoSuchFileException: /home/mario.valdeztresanco/.config/FragPipe/fragpipe/workflows/glyco-O-Pair.workflow
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1764)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:373)
	at java.base/java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:83)
	... 31 common frames omitted

``` 

I suspect this is probably due to the fact that I am using the same executable for all of them and at some point there is some overwriting in the .config folder?

Can you comment on this and give some advice?

Thanks in advance for your time and consideration...

Mario

**Comment by fcyu** [comment]
It seems that FragPipe couldn't read the built-in workflow file. Could you reproduce it for that specific run? If not, I am not sure how to figure out the cause and fix it.

Best,

Fengchao

**Comment by marioernestovaldes** [comment]
Why should fragpipe read the built-in workflow file in some generic folder (I assume this generic folder would be .config in the home directory), if I am providing the specific location of the workflow file everytime? It's interesting, if I go and run the same job that failed previously, without changing anything, it works fine... so, I would say the error probably comes from using the same fragpipe executable accross many runs, rather that some error in the input files....

Have you guys  try to run diferent runs of fragpipe on a cluster, or have some information about its performance in such environments?

**Comment by fcyu** [comment]
> Why should fragpipe read the built-in workflow file in some generic folder (I assume this generic folder would be .config in the home directory), if I am providing the specific location of the workflow file everytime? 

The error was thrown when starting FragPipe. It loads the built-in workflows before running anything.

>  It's interesting, if I go and run the same job that failed previously, without changing anything, it works fine... so, I would say the error probably comes from using the same fragpipe executable accross many runs, rather that some error in the input files....

I don't think it is because using FragPipe for many runs/jobs. If this is the case and deterministic, you would see the errors from the second run/job. Your error is more like some random IO issue in your computer.

Best,

Fengchao

**Comment by marioernestovaldes** [comment]
Instead of relying on fragpipe to execute all the commands for me, I have adopted a different approach. Basically, I will run all the commands fragpipe runs, that way I will overcome the IO issue. So far, everything works fine, except this command:

```
# Percolator: Convert to pepxml [Work dir: /home/mario/Downloads/FragPipe-20.0/test]
java -cp /home/mario/Downloads/FragPipe-20.0/fragpipe/lib/* com.dmtavt.fragpipe.tools.percolator.PercolatorOutputToPepXML FAES001_G2_220422_A.pin FAES001_G2_220422_A FAES001_G2_220422_A_percolator_target_psms.tsv FAES001_G2_220422_A_percolator_decoy_psms.tsv interact-FAES001_G2_220422_A DDA 0.5 /home/mario/Downloads/FragPipe-20.0/test/FAES001_G2_220422_A.mzML
``` 

that ends in error:

```
Error: Could not find or load main class com.dmtavt.fragpipe.tools.percolator.PercolatorOutputToPepXML
Caused by: java.lang.ClassNotFoundException: com.dmtavt.fragpipe.tools.percolator.PercolatorOutputToPepXML
```

could you please comment if is possible to run this command without fragpipe's aid?

thanks in advance...

**Comment by fcyu** [comment]
The main class is part of FragPipe, so I am not sure if it is straightforward to extract and run it without FragPipe.

On the other hand, your script won't be flexible according to different settings. That's why we developed the headless mode in FragPipe. 

Best,

Fengchao

**Comment by marioernestovaldes** [comment]
I found a solution to the problem in case anyone is interested in running fragpipe on a cluster and has similar issues. The thing is that when all the jobs are sent at the same time, then all the runs likely start at the same time and throw the error because of the IO issue. The solution is pretty simple, just wait a certain time before submitting the next job. This is doable for example using `time.sleep(30)` in Python between jobs submissions. Now, I haven't done any benchmarking to find the minimum time necessary to avoid the IO issue. I assume that will depend on the OS and the time it takes the jobs on average to start after they have been submitted to the queue.

**Comment by anesvi** [comment]
Thank you for your feedback! Alexey

**Comment by guoci** [comment]
@marioernestovaldes You can set the `XDG_CONFIG_HOME` environment variable to a unique directory for each run of FragPipe, the default is `~/.config`. This should avoid the overwriting issue you have.

**Comment by marioernestovaldes** [comment]
@guoci Indeed! That does the work... Thank you so much for your advice...

Great work guys. Keep it up!
