### ISSUE TITLE
Empty PSM list crashes EasyPQP: `ValueError: No objects to concatenate`

### ISSUE THREAD

**Issue by hupak2022** [Nesvilab/FragPipe#1293]
Hello,

I got this error. I checked the folder and I have most of expected output files except library.tsv and DIA-NN folder is empty.
I don't know why I do have such an error. Is it possible to have an explanations? 
Thanks in advance for your help

Best

Hui Song

Error log message:

EasyPQP convert error BEGIN
2023-10-17 20:05:29 - Info: Converting ['D:\\HuPa\\Stella_Carro\\results\\interact-20230829_DIA_COL049-00002-HLAIIp_R03_Q1.pep.xml'].
2023-10-17 20:05:29 - Info: Parsing run 20230829_DIA_COL049-00002-HLAIIp_R03_Q1.
2023-10-17 20:05:29 - Info: Parsing pepXML: D:\HuPa\Stella_Carro\results\interact-20230829_DIA_COL049-00002-HLAIIp_R03_Q1.pep.xml
2023-10-17 20:05:29 - Info: 0 PSMs parsed.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\easypqp.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1690, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\easypqp\main.py", line 90, in convert
    psms, peaks = conversion(pepxmlfile_list, spectralfile, unimodfile, exclude_range, max_delta_unimod, max_delta_ppm, enable_unannotated, enable_massdiff, fragment_types, fragment_charges, enable_specific_losses, enable_unspecific_losses, max_psm_pep, precision_digits)
  File "C:\ProgramData\Anaconda3\lib\site-packages\easypqp\convert.py", line 735, in conversion
    psms, theoretical = parse_pepxmls(pepxmlfile_list, um, base_name, exclude_range, enable_unannotated, enable_massdiff, fragment_charges, fragment_types, enable_specific_losses, enable_unspecific_losses, precision_digits)
  File "C:\ProgramData\Anaconda3\lib\site-packages\easypqp\convert.py", line 695, in parse_pepxmls
    psms = pd.concat(psmslist)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\reshape\concat.py", line 294, in concat
    op = _Concatenator(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\reshape\concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
exit status: 1
EasyPQP convert error END
EasyPQP convert error BEGIN
2023-10-17 20:05:38 - Info: Converting ['D:\\HuPa\\Stella_Carro\\results\\interact-20230829_DIA_COL049-00005-HLAIIp_R02_Q1.pep.xml'].
2023-10-17 20:05:38 - Info: Parsing run 20230829_DIA_COL049-00005-HLAIIp_R02_Q1.
2023-10-17 20:05:38 - Info: Parsing pepXML: D:\HuPa\Stella_Carro\results\interact-20230829_DIA_COL049-00005-HLAIIp_R02_Q1.pep.xml
2023-10-17 20:05:38 - Info: 0 PSMs parsed.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\easypqp.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1690, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\easypqp\main.py", line 90, in convert
    psms, peaks = conversion(pepxmlfile_list, spectralfile, unimodfile, exclude_range, max_delta_unimod, max_delta_ppm, enable_unannotated, enable_massdiff, fragment_types, fragment_charges, enable_specific_losses, enable_unspecific_losses, max_psm_pep, precision_digits)
  File "C:\ProgramData\Anaconda3\lib\site-packages\easypqp\convert.py", line 735, in conversion
    psms, theoretical = parse_pepxmls(pepxmlfile_list, um, base_name, exclude_range, enable_unannotated, enable_massdiff, fragment_charges, fragment_types, enable_specific_losses, enable_unspecific_losses, precision_digits)
  File "C:\ProgramData\Anaconda3\lib\site-packages\easypqp\convert.py", line 695, in parse_pepxmls
    psms = pd.concat(psmslist)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\reshape\concat.py", line 294, in concat
    op = _Concatenator(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\reshape\concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
Traceback (most recent call last):
  File "C:\DATA\FragPipe-jre-20.0\fragpipe\tools\speclib\gen_con_spec_lib.py", line 980, in <module>
    main_easypqp()
  File "C:\DATA\FragPipe-jre-20.0\fragpipe\tools\speclib\gen_con_spec_lib.py", line 797, in main_easypqp
    assert all(p.returncode == 0 for p in procs)
AssertionError
exit status: 1
EasyPQP convert error END
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 4 remaining tasks

**Comment by danielgeiszler** [comment]
Please post the whole log, otherwise we can't see which EasyPQP version you're using.

This is the same issue as https://github.com/Nesvilab/FragPipe/issues/1283

Run these commands to fix it:

```
pip uninstall easypqp -y
pip install git+https://github.com/Nesvilab/easypqp.git@master
```

**Comment by hupak2022** [comment]
thank you I will test it.

**Comment by veslugleynat** [comment]
Hi,
Sorry I am very new to all this and I got the same error. Where do I need to run those commands you suggested, please? In python, command prompt or FragPipe console? Thank you.

**Comment by fcyu** [comment]
In command prompt.

Best,

Fengchao

**Comment by veslugleynat** [comment]
Thank you!
