### ISSUE TITLE
Error in PTM-Shepherd for glycopeptide analysis

### ISSUE THREAD

**Issue by yishai99** [Nesvilab/FragPipe#1332]
I am processing one raw file of glycopeptides, OT data, in EThcD mode. I ticked the 'Assign glycans with FDR'. I'm also using a custom glyco database. 
Attached is the log.
The error:
Created similarity/RT reports

Beginning diagnostic ion extraction
	FS1_MS_14373_79_05082021 - 7146 (733 ms, 545 ms)
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at edu.umich.andykong.ptmshepherd.glyco.StaticGlycoUtilities.parseGlycanString(StaticGlycoUtilities.java:528)
	at edu.umich.andykong.ptmshepherd.glyco.StaticGlycoUtilities.parseDefaultGlycan(StaticGlycoUtilities.java:225)
	at edu.umich.andykong.ptmshepherd.glyco.StaticGlycoUtilities.parseGlycanDatabase(StaticGlycoUtilities.java:133)
	at edu.umich.andykong.ptmshepherd.PTMShepherd.main(PTMShepherd.java:708)
Done with diagnostic ion extraction

Thanks,

Yishai

**Comment by dpolasky** [comment]
Hi Yishai,

It's because a glycan in the database has a monosaccharide that isn't supported (or possibly some other formatting error). The list of supported glycans and adducts can be found here: https://github.com/Nesvilab/PTM-Shepherd/blob/main/src/edu/umich/andykong/ptmshepherd/glyco/GlycanResidue.java. I can also take a look at your custom glycan database if you're not sure where the error is coming from. 

I'm planning to add support for custom/any monosaccharides and modified glycans (very) soon, so stay tuned! 

Best,
Dan
