### ISSUE TITLE
in silico digestion parameters

### ISSUE THREAD

**Issue by masarumiyagi** [Nesvilab/FragPipe#134]
* **I'm submitting a:**
  - [x ] problem running the software
  - [ ] bug report
  - [ ] feature request
  - [ ] question

* **My MSFragger use case:**
  - [ ] _Closed_ search (standard small precursor mass tolerance)
  - [x ] _Open_ search (large precursor mass tolerance)

 ** _put your general problem description here_ **
The default setting with trypsin works just fine with the same MZML file. I'm trying to digest with other enzymes, this particular case, the enzyme was Lyc-C. I changed the enzyme name to "Lys-C", Cut after to "K", and left blank the But not before parameter. The remaining parameters were the same as those with default trypsin parameters. However, the run stops before completion. I want to find out how to set the enzyme parameters. Thanks for your help.

## System info

You can find that printed on the _Config_ tab.
- OS and version: ** _Windows 10 **
- Java version: ** _Java 8**

----

### Genral proteomics experiment description
enzymatic digestion of a relative pure protein

...

### Input data files
one 2 Gb MZML file

### Sequence database
custom database containing a single protein sequence

----

## Run log output
System info:
System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_212, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation

Version info:
FragPipe version 9.4
MSFragger version 20190628
Philosopher version v1.2.3 (build 1562095019)

LCMS files:
  Experiment/Group: 
  - C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test\Lum_19may2301.mzML

9 commands to execute:
Workspace [Work dir: C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test]
C:\Users\mxm35\Documents\MSFragger\philosopher_v1.2.3_windows_amd64\philosopher.exe workspace --clean
Workspace [Work dir: C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test]
C:\Users\mxm35\Documents\MSFragger\philosopher_v1.2.3_windows_amd64\philosopher.exe workspace --init
MsFragger [Work dir: C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test]
java -jar -Dfile.encoding=UTF-8 -Xmx8G C:\Users\mxm35\Documents\MSFragger\MSFragger-20190628\MSFragger-20190628.jar C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test\fragger.params C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test\Lum_19may2301.mzML
ReportDbAnnotate [Work dir: C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test]
C:\Users\mxm35\Documents\MSFragger\philosopher_v1.2.3_windows_amd64\philosopher.exe database --annotate C:\Users\mxm35\Desktop\Protein sequence database\target.decoy.Erk_John Wang special.fasta --prefix REV_
PeptideProphet [Work dir: C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test]
C:\Users\mxm35\Documents\MSFragger\philosopher_v1.2.3_windows_amd64\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy REV_ --database C:\Users\mxm35\Desktop\Protein sequence database\target.decoy.Erk_John Wang special.fasta Lum_19may2301.pepXML
ProteinProphet [Work dir: C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test]
C:\Users\mxm35\Documents\MSFragger\philosopher_v1.2.3_windows_amd64\philosopher.exe proteinprophet --maxppmdiff 2000000 C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test\interact-Lum_19may2301.pep.xml
ReportFilter [Work dir: C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test]
C:\Users\mxm35\Documents\MSFragger\philosopher_v1.2.3_windows_amd64\philosopher.exe filter --sequential --razor --mapmods --prot 0.01 --tag REV_ --pepxml C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test --protxml C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test\interact.prot.xml
ReportReport [Work dir: C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test]
C:\Users\mxm35\Documents\MSFragger\philosopher_v1.2.3_windows_amd64\philosopher.exe report
Workspace [Work dir: C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test]
C:\Users\mxm35\Documents\MSFragger\philosopher_v1.2.3_windows_amd64\philosopher.exe workspace --clean
~~~~~~~~~~~~~~~~~~~~~~


Workspace [Work dir: C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test]
C:\Users\mxm35\Documents\MSFragger\philosopher_v1.2.3_windows_amd64\philosopher.exe workspace --clean
INFO[16:14:12] Executing Workspace v1.2.3                   
WARN[16:14:12] There is a new version of Philosopher available for download: https://github.com/prvst/philosopher/releases 
INFO[16:14:12] Removing workspace                           
INFO[16:14:12] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test]
C:\Users\mxm35\Documents\MSFragger\philosopher_v1.2.3_windows_amd64\philosopher.exe workspace --init
INFO[16:14:13] Executing Workspace v1.2.3                   
WARN[16:14:13] There is a new version of Philosopher available for download: https://github.com/prvst/philosopher/releases 
INFO[16:14:13] Creating workspace                           
INFO[16:14:13] Done                                         
Process 'Workspace' finished, exit code: 0

MsFragger [Work dir: C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test]
java -jar -Dfile.encoding=UTF-8 -Xmx8G C:\Users\mxm35\Documents\MSFragger\MSFragger-20190628\MSFragger-20190628.jar C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test\fragger.params C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test\Lum_19may2301.mzML
MSFragger version MSFragger-20190628
MSFTBX version 1.9.10
(c) University of Michigan
RawFileReader reading tool. Copyright © 2016 by Thermo Fisher Scientific, Inc. All rights reserved.

System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_212, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation
JVM started with 7282 MB memory

***********************************FIRST SEARCH************************************
Parameters:
num_threads = 4
database_name = C:\Users\mxm35\Desktop\Protein sequence database\target.decoy.Erk_John Wang special.fasta
decoy_prefix = REV_
precursor_mass_lower = -20.0
precursor_mass_upper = 20.0
precursor_mass_units = 1
precursor_true_tolerance = 20.0
precursor_true_units = 1
fragment_mass_tolerance = 20.0
fragment_mass_units = 1
calibrate_mass = 2
evaluate_mass_calibration = false
isotope_error = 0/1
mass_offsets = 0
precursor_mass_mode = SELECTED
localize_delta_mass = false
delta_mass_exclude_ranges = (-1.5,3.5)
fragment_ion_series = b,y
search_enzyme_name = Lys-C
search_enzyme_cutafter = K
search_enzyme_butnotafter = 
num_enzyme_termini = 2
allowed_missed_cleavage = 1
clip_nTerm_M = true
allow_multiple_variable_mods_on_residue = false
max_variable_mods_per_mod = 3
max_variable_mods_combinations = 5000
output_file_extension = pepXML
output_format = pepXML
output_report_topN = 1
output_max_expect = 50.0
report_alternative_proteins = false
override_charge = false
precursor_charge_low = 1
precursor_charge_high = 4
digest_min_length = 7
digest_max_length = 50
digest_mass_range_low = 500.0
digest_mass_range_high = 5000.0
max_fragment_charge = 2
track_zero_topN = 0
zero_bin_accept_expect = 0.0
zero_bin_mult_expect = 1.0
add_topN_complementary = 0
minimum_peaks = 15
use_topN_peaks = 100
minIonsScoring = 3
min_matched_fragments = 5
minimum_ratio = 0.01
clear_mz_range_low = 0.0
clear_mz_range_high = 0.0
excluded_scan_list_file = 
variable_mod_01 = 15.99490 M
variable_mod_02 = 42.01060 [^
Number of unique peptides
	of length 7: 4
	of length 8: 6
	of length 9: 2
	of length 11: 4
	of length 12: 2
	of length 13: 10
	of length 14: 2
	of length 15: 2
	of length 17: 2
	of length 18: 1
	of length 19: 5
	of length 21: 2
	of length 22: 1
	of length 23: 1
	of length 24: 4
	of length 26: 2
	of length 28: 4
	of length 33: 4
	of length 34: 3
	of length 37: 2
	of length 38: 1
	of length 39: 6
	of length 40: 2
	of length 43: 2
In total 74 peptides.
Generated 154 modified peptides.
Selected fragment tolerance 0.10 Da and maximum fragment slice size of 4.89 GB.
8064 fragments to be searched in 1 slices (0.00 GB total)
Operating on slice 1 of 1: 
	001. Lum_19may2301.mzML 10.8 s
	001. Lum_19may2301.mzML 10.8 s [progress: 57006/82931 (68.74%) - 11290.55 spectra/s]
	001. Lum_19may2301.mzML 10.8 s [progress: 82931/82931 (100.00%) - 11580.92 spectra/s] - completed 7.2 s
***************************FIRST SEARCH DONE IN 0.313 MIN**************************

*********************************MASS CALIBRATION**********************************
-----|---------------|---------------|---------------|---------------
     |  MS1   (Old)  |  MS1   (New)  |  MS2   (Old)  |  MS2   (New)  
-----|---------------|---------------|---------------|---------------
 Run |  Median  MAD  |  Median  MAD  |  Median  MAD  |  Median  MAD  
 001 | Not enough data to perform mass calibration. Using the uncalibrated data.
-----|---------------|---------------|---------------|---------------
Finding the optimal parameters:
-------|-------|-------|-------|-------|-------|-------
  MS2  |    7  |   10  |   15  |   20  |   25  |   30  
-------|-------|-------|-------|-------|-------|-------
 Count |      0|      0|      0|      0|      0|      0
-------|-------|-------|-------|-------|-------|-------
-------|-------|-------|-------|-------|-------
 Peaks |  50_1 |  75_1 | 100_1 | 125_1 | 150_1 
-------|-------|-------|-------|-------|-------
 Count |      0|      0|      0|      0|      0
-------|-------|-------|-------|-------|-------
New fragment_mass_tolerance = 20 PPM
New use_topN_peaks = 100
New minimum_ratio = 0.010000
**************************MASS CALIBRATION DONE IN 2.630 MIN***********************

************************************MAIN SEARCH************************************
Parameters:
num_threads = 4
database_name = C:\Users\mxm35\Desktop\Protein sequence database\target.decoy.Erk_John Wang special.fasta
decoy_prefix = REV_
precursor_mass_lower = -150.0
precursor_mass_upper = 500.0
precursor_mass_units = 0
precursor_true_tolerance = 20.0
precursor_true_units = 1
fragment_mass_tolerance = 20.0
fragment_mass_units = 1
calibrate_mass = 2
evaluate_mass_calibration = false
isotope_error = 0
mass_offsets = 0
precursor_mass_mode = SELECTED
localize_delta_mass = true
delta_mass_exclude_ranges = (-1.5,3.5)
fragment_ion_series = b,y
search_enzyme_name = Lys-C
search_enzyme_cutafter = K
search_enzyme_butnotafter = 
num_enzyme_termini = 2
allowed_missed_cleavage = 1
clip_nTerm_M = true
allow_multiple_variable_mods_on_residue = true
max_variable_mods_per_mod = 3
max_variable_mods_combinations = 5000
output_file_extension = pepXML
output_format = pepXML
output_report_topN = 1
output_max_expect = 50.0
report_alternative_proteins = false
override_charge = false
precursor_charge_low = 1
precursor_charge_high = 4
digest_min_length = 7
digest_max_length = 50
digest_mass_range_low = 500.0
digest_mass_range_high = 5000.0
max_fragment_charge = 2
track_zero_topN = 0
zero_bin_accept_expect = 0.0
zero_bin_mult_expect = 1.0
add_topN_complementary = 0
minimum_peaks = 15
use_topN_peaks = 100
minIonsScoring = 3
min_matched_fragments = 5
minimum_ratio = 0.01
clear_mz_range_low = 0.0
clear_mz_range_high = 0.0
excluded_scan_list_file = 
variable_mod_01 = 15.99490 M
variable_mod_02 = 42.01060 [^
Number of unique peptides
	of length 7: 4
	of length 8: 6
	of length 9: 2
	of length 11: 4
	of length 12: 2
	of length 13: 10
	of length 14: 2
	of length 15: 2
	of length 17: 2
	of length 18: 1
	of length 19: 5
	of length 21: 2
	of length 22: 1
	of length 23: 1
	of length 24: 4
	of length 26: 2
	of length 28: 4
	of length 33: 4
	of length 34: 3
	of length 37: 2
	of length 38: 1
	of length 39: 6
	of length 40: 2
	of length 43: 2
In total 74 peptides.
Generated 162 modified peptides.
Selected fragment tolerance 0.02 Da and maximum fragment slice size of 4.89 GB.
17248 fragments to be searched in 1 slices (0.00 GB total)
Operating on slice 1 of 1: 
	001. Lum_19may2301.mzML 9.7 s
	001. Lum_19may2301.mzML 9.7 s [progress: 24328/82931 (29.34%) - 4863.65 spectra/s]
	001. Lum_19may2301.mzML 9.7 s [progress: 43586/82931 (52.56%) - 4314.59 spectra/s]
	001. Lum_19may2301.mzML 9.7 s [progress: 70035/82931 (84.45%) - 4634.40 spectra/s]
	001. Lum_19may2301.mzML 9.7 s [progress: 82931/82931 (100.00%) - 4804.81 spectra/s] - completed 17.3 s
***************************MAIN SEARCH DONE IN 0.468 MIN***************************

*******************************TOTAL TIME 3.411 MIN********************************
Process 'MsFragger' finished, exit code: 0

ReportDbAnnotate [Work dir: C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test]
C:\Users\mxm35\Documents\MSFragger\philosopher_v1.2.3_windows_amd64\philosopher.exe database --annotate C:\Users\mxm35\Desktop\Protein sequence database\target.decoy.Erk_John Wang special.fasta --prefix REV_
INFO[16:17:41] Executing Database v1.2.3                    
INFO[16:17:41] Processing database                          
INFO[16:17:41] Done                                         
Process 'ReportDbAnnotate' finished, exit code: 0

PeptideProphet [Work dir: C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test]
C:\Users\mxm35\Documents\MSFragger\philosopher_v1.2.3_windows_amd64\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy REV_ --database C:\Users\mxm35\Desktop\Protein sequence database\target.decoy.Erk_John Wang special.fasta Lum_19may2301.pepXML
INFO[16:17:41] Executing PeptideProphet v1.2.3              
 file 1: C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test\Lum_19may2301.pepXML
INFO: Results written to file: C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test\interact-Lum_19may2301.pep.xml
 processed altogether 34 results
  - Building Commentz-Walter keyword tree...
  - C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test\interact-Lum_19may2301.pep.xml

  - Searching the tree...
  - Linking duplicate entries...
  - Printing results...

 PeptideProphet  (TPP v5.2.1-dev Flammagenitus, Build 201906281613-exported (Windows_NT-x86_64)) AKeller@ISB
 read in 0 1+, 0 2+, 26 3+, 7 4+, 1 5+, 0 6+, and 0 7+ spectra.
Found 13 Decoys, and 21 Non-Decoys
WARNING: Mixture model quality test failed for charge (1+).
WARNING: Mixture model quality test failed for charge (2+).
WARNING: Mixture model quality test failed for charge (3+).
WARNING: Mixture model quality test failed for charge (5+).
WARNING: Mixture model quality test failed for charge (6+).
WARNING: Mixture model quality test failed for charge (7+).
using Accurate Mass Bins
using PPM mass difference
Using Decoy Label "REV_".
Decoy Probabilities will be reported.
Using non-parametric distributions
 (X! Tandem) (using Tandem's expectation score for modeling)
adding ACCMASS mixture distribution
using search_offsets in ACCMASS mixture distr: 0
init with X! Tandem lysc 
MS Instrument info: Manufacturer: UNKNOWN, Model: UNKNOWN, Ionization: UNKNOWN, Analyzer: UNKNOWN, Detector: UNKNOWN

INFO: Processing standard MixtureModel ... 
Initialising statistical models ...
Iterations: .........10.........20
model complete after 21 iterations
INFO[16:17:53] Done                                         
Process 'PeptideProphet' finished, exit code: 0

ProteinProphet [Work dir: C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test]
C:\Users\mxm35\Documents\MSFragger\philosopher_v1.2.3_windows_amd64\philosopher.exe proteinprophet --maxppmdiff 2000000 C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test\interact-Lum_19may2301.pep.xml
INFO[16:17:54] Executing ProteinProphet v1.2.3              
ProteinProphet (C++) by Insilicos LLC and LabKey Software, after the original Perl by A. Keller (TPP v5.2.1-dev Flammagenitus, Build 201906281613-exported (Windows_NT-x86_64))
 (no FPKM) (using degen pep info)
Reading in C:/Users/mxm35/Desktop/D2 and D2CA_uninterpreted data/D2 test/interact-Lum_19may2301.pep.xml...
did not find any PeptideProphet results in input data!  Did you forget to run PeptideProphet?
...read in 0 1+, 0 2+, 0 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

WARNING: no data - output file will be empty
INFO[16:17:55] Done                                         
Process 'ProteinProphet' finished, exit code: 0

ReportFilter [Work dir: C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test]
C:\Users\mxm35\Documents\MSFragger\philosopher_v1.2.3_windows_amd64\philosopher.exe filter --sequential --razor --mapmods --prot 0.01 --tag REV_ --pepxml C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test --protxml C:\Users\mxm35\Desktop\D2 and D2CA_uninterpreted data\D2 test\interact.prot.xml
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x5048c0]

goroutine 1 [running]:
github.com/prvst/philosopher/lib/err.(*Error).Error(0x0, 0x24, 0xc000084340)
	/home/prvst/go/src/github.com/prvst/philosopher/lib/err/err.go:134 +0x30
github.com/prvst/philosopher/cmd.glob..func5(0x8702240, 0xc0000c8630, 0x0, 0xb)
	/home/prvst/go/src/github.com/prvst/philosopher/cmd/filter.go:53 +0xb87
github.com/spf13/cobra.(*Command).execute(0x8702240, 0xc0000c8580, 0xb, 0xb, 0x8702240, 0xc0000c8580)
	/home/prvst/go/src/github.com/spf13/cobra/command.go:766 +0x2b5
github.com/spf13/cobra.(*Command).ExecuteC(0x8703c60, 0x405826, 0xc00005a058, 0x0)
	/home/prvst/go/src/github.com/spf13/cobra/command.go:850 +0x303
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/src/github.com/spf13/cobra/command.go:800
github.com/prvst/philosopher/cmd.Execute()
	/home/prvst/go/src/github.com/prvst/philosopher/cmd/root.go:32 +0x35
main.main()
	/home/prvst/go/src/github.com/prvst/philosopher/main.go:24 +0x75
INFO[16:17:55] Executing Filter v1.2.3                      
INFO[16:17:55] Processing peptide identification files      
Process 'ReportFilter' finished, exit code: 2

Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Stopping 4/10 processes (6 already finished)

**Comment by fcyu** [comment]
You can use the name `lysc`. But looks like there is no hit from your database. Changing enzyme name won't change that. You may provide a "real" database rather than the one having only one protein.

Best,

Fengchao
