### ISSUE TITLE
Exception in thread "main" java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by May2020** [Nesvilab/FragPipe#136]
Searches did not go through and stopped from the beginning. Error message was displayed below. Could you please kindly help me to take a look at it?
thanks a lot lot lot!

* **I'm submitting a:**
  - [X ] problem running the software
  - [ ] bug report
  - [ ] feature request
  - [ ] question

* **My MSFragger use case:**
  - [ X] _Closed_ search (standard small precursor mass tolerance)
  - [ ] _Open_ search (large precursor mass tolerance)

 ** _put your general problem description here_ **

## System info

You can find that printed on the _Config_ tab.
- OS and version: ** _your response here_ **
- Java version: ** _your response here_ **

----

## Describe your experiment
Hela Test Run
### Genral proteomics experiment description
Hela standards search against human datbabase

...

### Input data files
Hela
2 samples

### Sequence database
Human
----

## Attach fragger.params file

** _You can find it in the output directory you specified for analysis._ **

[log-fragpipe-run-at_2019-09-10_14-56-47.log](https://github.com/Nesvilab/FragPipe/files/3602122/log-fragpipe-run-at_2019-09-10_14-56-47.log)

## Run log output
Selected fragment tolerance 0.10 Da and maximum fragment slice size of 19.07 GB.
162413612 fragments to be searched in 1 slices (2.42 GB total)
Operating on slice 1 of 1: 
	001. Hela200ngC1.mzXML Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: umich.ms.fileio.exceptions.FileParsingException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No enum constant umich.ms.datatypes.scan.props.ScanType.CID
	at umich.ms.fileio.filetypes.xmlbased.AbstractXMLBasedDataSource.parse(AbstractXMLBasedDataSource.java:198)
	at umich.ms.datatypes.scancollection.impl.ScanCollectionDefault.loadData(ScanCollectionDefault.java:804)
	at umich.ms.datatypes.scancollection.impl.ScanCollectionDefault.loadData(ScanCollectionDefault.java:788)
	at edu.umich.andykong.msfragger.b.a(Unknown Source)
	at edu.umich.andykong.msfragger.b.a(Unknown Source)
	at edu.umich.andykong.msfragger.t.a(Unknown Source)
	at edu.umich.andykong.msfragger.r.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
	... 6 more
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No enum constant umich.ms.datatypes.scan.props.ScanType.CID
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at umich.ms.fileio.filetypes.xmlbased.AbstractXMLBasedDataSource.parse(AbstractXMLBasedDataSource.java:191)
	... 14 more
Caused by: java.lang.IllegalArgumentException: No enum constant umich.ms.datatypes.scan.props.ScanType.CID
	at java.lang.Enum.valueOf(Unknown Source)
	at umich.ms.util.StringUtils.getEnumFromString(StringUtils.java:110)
	at umich.ms.datatypes.scan.props.ScanType.fromString(ScanType.java:54)
	at umich.ms.fileio.filetypes.mzxml.MZXMLMultiSpectraParser.tagScanStart(MZXMLMultiSpectraParser.java:389)
	at umich.ms.fileio.filetypes.mzxml.MZXMLMultiSpectraParser.call(MZXMLMultiSpectraParser.java:177)
	at umich.ms.fileio.filetypes.mzxml.MZXMLMultiSpectraParser.call(MZXMLMultiSpectraParser.java:65)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Process 'MsFragger' finished, exit code: 1

Process returned non-zero exit code, stopping
MsFragger
java -cp E:\software\FragPipe\FragPipe-10.1.jar umich.msfragger.util.FileMove Y:\RawData\Hela\Column60\Hela200ngC1.pepXML E:\FragPipeResult\HELAtest\t3\Hela200ngC1.pepXML

~~~~~~~~~~~~~~~~~~~~
Stopping 8/11 processes (3 already finished)
Processing interrupted, stopping MsFragger

**Comment by guoci** [comment]
Please consider sending the input files (mzXMLs, fasta, parameter) to us.

**Comment by fcyu** [comment]
Close this issue due to no feedback.
