### ISSUE TITLE
A search can not finish in Fragpipe 21.1, also can not finish in FragPipe 20

### ISSUE THREAD

**Issue by WeiqiangChen** [Nesvilab/FragPipe#1385]
- Describe the issue or question:
I want to search for a project with FragPipe21.1.
It showed the following error. 

`PhilosopherFilter [Work dir: D:\20231221_ID_23258_new\data\processed\A]
D:\software\FragPipe-jre-21.1\fragpipe\tools\philosopher_v5.1.0_windows_amd64\philosopher.exe filter --sequential --prot 0.01 --tag rev_ --pepxml D:\20231221_ID_23258_new\data\processed\A --protxml D:\20231221_ID_23258_new\data\processed\combined.prot.xml --razor
INFO[08:59:36] Executing Filter  v5.1.0                     
INFO[08:59:36] Processing peptide identification files      
INFO[08:59:36] Parsing D:\20231221_ID_23258_new\data\processed\A\interact-20231215_E1_NEO3_Stelzer_jlphealth_MPLGmbH_Company_MPLID23258_A_7c5p.pep.xml 
ERRO[08:59:40] Cannot read file. Error parsing the file     
Process 'PhilosopherFilter' finished, exit code: 1
Process returned non-zero exit code, stopping
Cancelling 11 remaining tasks`

I copied my folder to another computer and did Fragpipe20 search there. It gets another error. 
`Internal state when error was thrown: recordCount=11453, recordData=[tr|A0A8F3I251|A0A8F3I251_9HIV1]
	at com.univocity.parsers.common.AbstractWriter.throwExceptionAndClose(AbstractWriter.java:1046)
	at com.univocity.parsers.common.AbstractWriter.addValue(AbstractWriter.java:1185)
	at Features.percolatorFormatter.editPin(percolatorFormatter.java:480)
	at Features.MainClass.main(MainClass.java:588)
Process 'MSBooster' finished, exit code: 1
Process returned non-zero exit code, stopping
Cancelling 26 remaining tasks`

What should I do to let the search go through? Thanks!

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2023-12-22_08-59-40_FragPipe21.1_error.txt.zip](https://github.com/Nesvilab/FragPipe/files/13749837/log_2023-12-22_08-59-40_FragPipe21.1_error.txt.zip)
[log_2023-12-22_09-08-31_FragPipe20_error.zip](https://github.com/Nesvilab/FragPipe/files/13749838/log_2023-12-22_09-08-31_FragPipe20_error.zip)

**Comment by WeiqiangChen** [comment]
I tried to remove Run MSBooster in FragPipe 20. And get the following error.


INFO[09:23:07] Executing Filter  v5.0.0                     
INFO[09:23:07] Processing peptide identification files      
INFO[09:23:07] Parsing X:\WeiQiang\20231221_ID_23258_new\data\processed\A\interact-20231215_E1_NEO3_Stelzer_jlphealth_MPLGmbH_Company_MPLID23258_A_7c5p.pep.xml 
ERRO[09:23:13] Cannot read file. Error parsing the file     
Process 'PhilosopherFilter' finished, exit code: 1
Process returned non-zero exit code, stopping
~~~~~~~~~~~~~~~~~~~~
Cancelling 11 remaining tasks

**Comment by fcyu** [comment]
Everything looks good until Philosopher. Let me transfer it to https://github.com/Nesvilab/philosopher
