### ISSUE TITLE
Task stopped in the middle

### ISSUE THREAD

**Issue by YechenHu** [Nesvilab/FragPipe#1394]
- Describe the issue or question:
Hi, I updated the software to the latest version and performed the configuration. However, when I attempted to perform another search using data that was previously searched with version 19, the process stopped midway. I am unsure of the reason, as I repeated the process twice with the same result. Please help me resolve this issue.
Thanks a lot!
[log_2023-12-15_10-58-48.txt](https://github.com/Nesvilab/FragPipe/files/13824419/log_2023-12-15_10-58-48.txt)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
The error seems related to the glycan assignment. @dpolasky , can you take a look when you have time?

```shell
Combining and cleaning reports
Writing combined table for dataset dataset01
Beginning glycan assignment
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at edu.umich.andykong.ptmshepherd.glyco.StaticGlycoUtilities.parseGlycanStringOld(StaticGlycoUtilities.java:509)
	at edu.umich.andykong.ptmshepherd.glyco.StaticGlycoUtilities.parseDefaultGlycan(StaticGlycoUtilities.java:233)
	at edu.umich.andykong.ptmshepherd.glyco.StaticGlycoUtilities.parseGlycanDatabase(StaticGlycoUtilities.java:133)
	at edu.umich.andykong.ptmshepherd.PTMShepherd.main(PTMShepherd.java:708)
Process 'PTMShepherd' finished, exit code: 1
```

Thanks,

Fengchao

**Comment by dpolasky** [comment]
This issue is resolved in FragPipe version 21 - please download the latest version of FragPipe here: https://github.com/Nesvilab/FragPipe/releases

Best,
Dan
