### ISSUE TITLE
Unrecognized error during reading timsTOF file

### ISSUE THREAD

**Issue by plyush1993** [Nesvilab/FragPipe#1429]
Hello there, 
I use a predefined workflow (LFQ workflow, for a DDA experiment. IM-MS data) and I'm pretty sure all parameters and the files conversion are correct (.d format). Moreover, other files from this instrument passed without errors. 

- The relevant snippet from the log file is:
Operating on slice 1 of 1: 
	Fragment index slice generated in 1.51 s
	001. Serum_Aptamer_15m_1.d There are multiple scan modes: 0,8. Will only use the scans with mode 8 (PASEF).
​
	001. Serum_Aptamer_15m_1.d loading 45% 
Could not load file Y:\Members\Ivan\TIMS-TOF_data\2024_01_28_HSA_10k_d_15_30_45_60min\Serum_Aptamer_15m_1.d. The file may be corrupted.
java.util.concurrent.ExecutionException: umich.ms.fileio.exceptions.FileParsingException: org.sqlite.SQLiteException: [SQLITE_BUSY] The database file is locked (database is locked)
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at edu.umich.andykong.msfragger.MSRun.readAsTimsTof(MSRun.java:524)
	at edu.umich.andykong.msfragger.MSRun.loadScans(MSRun.java:115)
	at edu.umich.andykong.msfragger.MSFraggerCore.<init>(MSFraggerCore.java:93)
	at edu.umich.andykong.msfragger.MSFragger.main1(MSFragger.java:821)
	at edu.umich.andykong.msfragger.MSFragger.main0(MSFragger.java:207)
	at edu.umich.andykong.msfragger.MSFragger.main(MSFragger.java:75)
Caused by: umich.ms.fileio.exceptions.FileParsingException: org.sqlite.SQLiteException: [SQLITE_BUSY] The database file is locked (database is locked)
	at umich.ms.fileio.filetypes.bruker.BrukerTdfFileBase.readMs1AsPasef(BrukerTdfFileBase.java:116)
	at edu.umich.andykong.msfragger.MSRun.lambda$readAsTimsTof$6(MSRun.java:353)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.sqlite.SQLiteException: [SQLITE_BUSY] The database file is locked (database is locked)
	at org.sqlite.core.DB.newSQLException(DB.java:1179)
	at org.sqlite.core.DB.newSQLException(DB.java:1190)
	at org.sqlite.core.DB.execute(DB.java:985)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.lambda$executeQuery$1(JDBC3PreparedStatement.java:89)
	at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:459)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:84)
	at umich.ms.fileio.filetypes.bruker.BrukerTdfSql.sqlReadPrecursorById(BrukerTdfSql.java:302)
	at umich.ms.fileio.filetypes.bruker.BrukerTdfFileBase.readMs1AsPasef(BrukerTdfFileBase.java:102)
	... 5 more

**Comment by fcyu** [comment]
Your .d folder has been corrupted. And also, something seems not right: "There are multiple scan modes: 0,8. Will only use the scans with mode 8 (PASEF)."

Best,

Fengchao

**Comment by plyush1993** [comment]
> Your .d folder has been corrupted. And also, something seems not right: "There are multiple scan modes: 0,8. Will only use the scans with mode 8 (PASEF)."
> 
> Best,
> 
> Fengchao

Thank you for your quick reply.
multiple scan modes is not a problem, for other files the same modes run without error.
I also can't identify any corruption in files. Maybe you could provide other suggestions/potential solutions?

With best regards,
Ivan

**Comment by fcyu** [comment]
It seems to be related to the tdf file. Could you make sure that there is no other program reading or writing the .d, and try again?

Best,

Fengchao

**Comment by plyush1993** [comment]
I noticed that each time it gaves error on different stage of loading the first processed file, like: 39 %, next 67 %, etc.
I mean it is not completely reproducible. Maybe this will help somehow too

**Comment by fcyu** [comment]
Yeah, something was wrong with your operating system or file system. Please troubleshoot locally. I don't think we can help much here.

Best,

Fengchao

**Comment by plyush1993** [comment]
Ok thanks
