### ISSUE TITLE
DIASpecLibQuant: Issue with iRT

### ISSUE THREAD

**Issue by user9301** [Nesvilab/FragPipe#1430]
- Describe the issue or question:
Hello,
I am trying to run DIA-PASEF files along with fractionated DDA files (samples from mouse cell line) using DIASpecLibQuant workflow with Biognosys iRT peptides however, my run keeps getting terminated with the following error:
Traceback (most recent call last):
  File "E:\software\FragPipe-jre-20\fragpipe\tools\speclib\gen_con_spec_lib.py", line 980, in <module>
    main_easypqp()
  File "E:\software\FragPipe-jre-20\fragpipe\tools\speclib\gen_con_spec_lib.py", line 764, in main_easypqp
    irt_df.to_csv(irt_file, index=False, sep='\t', lineterminator='\n')
TypeError: to_csv() got an unexpected keyword argument 'lineterminator'
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping

I have tried running the workflow on FragPipe versions 20, 21, and 21.1 and all of them give the same error. I have attached the complete log file for one of the runs for your reference.

Thank you for your help.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-01-31_01-47-24.txt](https://github.com/Nesvilab/FragPipe/files/14138684/log_2024-01-31_01-47-24.txt)

**Comment by user9301** [comment]
Hello,

Thank you for the help. We updated the Python pandas but now it is showing a new error. It seems while updating the one python package (pandas),  it also updated the NumPy and now there seems to be an issue with the new NumPy version? 

The exact error was:


Traceback (most recent call last):
  File "E:\software\Python3_9_6\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\software\Python3_9_6\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\software\Python3_9_6\Scripts\easypqp.exe\__main__.py", line 4, in <module>
  File "E:\software\Python3_9_6\lib\site-packages\easypqp\main.py", line 9, in <module>
    from .convert import conversion, basename_spectralfile
  File "E:\software\Python3_9_6\lib\site-packages\easypqp\convert.py", line 580, in <module>
    import numba
  File "E:\software\Python3_9_6\lib\site-packages\numba\__init__.py", line 55, in <module>
    _ensure_critical_deps()
  File "E:\software\Python3_9_6\lib\site-packages\numba\__init__.py", line 42, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.24 or less")
ImportError: Numba needs NumPy 1.24 or less
Traceback (most recent call last):
  File "E:\software\FragPipe-jre-21.1\fragpipe\tools\speclib\gen_con_spec_lib.py", line 724, in <module>
    main_easypqp()
  File "E:\software\FragPipe-jre-21.1\fragpipe\tools\speclib\gen_con_spec_lib.py", line 566, in main_easypqp
    subprocess.run([os.fspath(easypqp), '--version'], check=True)
  File "E:\software\Python3_9_6\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['E:\\software\\Python3_9_6\\Scripts\\easypqp.exe', '--version']' returned non-zero exit status 1.
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping


Thank you for your help.

**Comment by guoci** [comment]
Can you run the command below and try again?
`pip install numpy==1.24`

**Comment by user9301** [comment]
Hello,
We installed NumPy 1.24 and ran the workflow again. But this time also we got an error. 

E:\software\Python3_9_6\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "E:\software\Python3_9_6\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\software\Python3_9_6\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\software\Python3_9_6\Scripts\easypqp.exe\__main__.py", line 4, in <module>
  File "E:\software\Python3_9_6\lib\site-packages\easypqp\main.py", line 10, in <module>
    from .library import generate
  File "E:\software\Python3_9_6\lib\site-packages\easypqp\library.py", line 24, in <module>
    import statsmodels.api as sm
  File "E:\software\Python3_9_6\lib\site-packages\statsmodels\api.py", line 9, in <module>
    from . import regression
  File "E:\software\Python3_9_6\lib\site-packages\statsmodels\regression\__init__.py", line 1, in <module>
    from .linear_model import yule_walker
  File "E:\software\Python3_9_6\lib\site-packages\statsmodels\regression\linear_model.py", line 46, in <module>
    import statsmodels.base.model as base
  File "E:\software\Python3_9_6\lib\site-packages\statsmodels\base\model.py", line 16, in <module>
    from statsmodels.tools.numdiff import approx_fprime
  File "E:\software\Python3_9_6\lib\site-packages\statsmodels\tools\numdiff.py", line 51, in <module>
    EPS = np.MachAr().eps
  File "E:\software\Python3_9_6\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'MachAr'
Traceback (most recent call last):
  File "E:\software\FragPipe-jre-21.1\fragpipe\tools\speclib\gen_con_spec_lib.py", line 724, in <module>
    main_easypqp()
  File "E:\software\FragPipe-jre-21.1\fragpipe\tools\speclib\gen_con_spec_lib.py", line 566, in main_easypqp
    subprocess.run([os.fspath(easypqp), '--version'], check=True)
  File "E:\software\Python3_9_6\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['E:\\software\\Python3_9_6\\Scripts\\easypqp.exe', '--version']' returned non-zero exit status 1.
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping

Thank you for your help.

**Comment by guoci** [comment]
Can you also do:
`pip install -U statsmodels`?

**Comment by user9301** [comment]
Thank you. It worked.
