### ISSUE TITLE
easypqp.exe returned non-zero exit status 1

### ISSUE THREAD

**Issue by clin888** [Nesvilab/FragPipe#1431]
Traceback (most recent call last):
  File "C:\Fragpipe\FragPipe-jre-21.1\fragpipe\tools\speclib\gen_con_spec_lib.py", line 724, in <module>
    main_easypqp()
  File "C:\Fragpipe\FragPipe-jre-21.1\fragpipe\tools\speclib\gen_con_spec_lib.py", line 566, in main_easypqp
    subprocess.run([os.fspath(easypqp), '--version'], check=True)
  File "C:\ProgramData\anaconda3\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\redpc\\AppData\\Roaming\\Python\\Python311\\Scripts\\easypqp.exe', '--version']' returned non-zero exit status 1.
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping
[log_2024-02-02_09-33-54.txt](https://github.com/Nesvilab/FragPipe/files/14143364/log_2024-02-02_09-33-54.txt)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by guoci** [comment]
Your Python is installed at `C:\ProgramData\anaconda3\`, but the libraries are installed at `C:\Users\redpc\AppData\Roaming\Python\Python311\Scripts\`. Can you install all libraries in `C:\ProgramData\anaconda3\`?

**Comment by clin888** [comment]
Thank you, I still have the same issue

Traceback (most recent call last):
  File "C:\ProgramData\Python_3.9\Scripts\easypqp-script.py", line 33, in <module>
    sys.exit(load_entry_point('easypqp==0.1.42', 'console_scripts', 'easypqp')())
  File "C:\ProgramData\Python_3.9\Scripts\easypqp-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\ProgramData\Python_3.9\lib\importlib\metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "C:\ProgramData\Python_3.9\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\ProgramData\Python_3.9\lib\site-packages\easypqp\main.py", line 9, in <module>
    from .convert import conversion, basename_spectralfile
  File "C:\ProgramData\Python_3.9\lib\site-packages\easypqp\convert.py", line 18, in <module>
    import pyopenms as po
  File "C:\ProgramData\Python_3.9\lib\site-packages\pyopenms\__init__.py", line 107, in <module>
    raise e
  File "C:\ProgramData\Python_3.9\lib\site-packages\pyopenms\__init__.py", line 65, in <module>
    from ._all_modules import *  # pylint: disable=wildcard-import; lgtm(py/polluting-import)
  File "C:\ProgramData\Python_3.9\lib\site-packages\pyopenms\_all_modules.py", line 1, in <module>
    from ._pyopenms_1 import *  # pylint: disable=wildcard-import; lgtm(py/polluting-import)
ImportError: DLL load failed while importing _pyopenms_1: A dynamic link library (DLL) initialization routine failed.

======================================================================
Error when loading pyOpenMS libraries!
Libraries could not be found / could not be loaded.

To debug this error, please run ldd (on linux), otool -L (on macOS) or dependency walker (on windows) on 

C:\ProgramData\Python_3.9\lib\site-packages\pyopenms\pyopenms*.so

======================================================================
Traceback (most recent call last):
  File "C:\Fragpipe\FragPipe-jre-21.1\fragpipe\tools\speclib\gen_con_spec_lib.py", line 724, in <module>
    main_easypqp()
  File "C:\Fragpipe\FragPipe-jre-21.1\fragpipe\tools\speclib\gen_con_spec_lib.py", line 566, in main_easypqp
    subprocess.run([os.fspath(easypqp), '--version'], check=True)
  File "C:\ProgramData\Python_3.9\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\ProgramData\\Python_3.9\\Scripts\\easypqp.exe', '--version']' returned non-zero exit status 1.
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping

[log_2024-02-04_16-55-51.txt](https://github.com/Nesvilab/FragPipe/files/14159234/log_2024-02-04_16-55-51.txt)

**Comment by guoci** [comment]
@clin888 This error is from `OpenMS`, please post at https://github.com/OpenMS/OpenMS/issues

**Comment by guoci** [comment]
Continued at https://github.com/OpenMS/OpenMS/issues/7333.

**Comment by fcyu** [comment]
Similar to https://github.com/Nesvilab/FragPipe/issues/1836 and https://github.com/Nesvilab/FragPipe/issues/1543.

It may be due to the reason explained in https://github.com/Nesvilab/FragPipe/issues/1543#issuecomment-2435555771

Best,

Fengchao
