### ISSUE TITLE
Search peptidomics diaPASEF data with fasta generated library

### ISSUE THREAD

**Issue by heylookabed** [Nesvilab/FragPipe#1442]
- Describe the issue or question:

I am currently using the DIA_SpecLib_Quant workflow with diaPASEF data.
Since my sample is comprised of endogenous peptides, I have set enzyems to null in MSFragger.
My goal is to create a spectral library from the fasta file and use this in-silico spectral library to quantify my results in DIA-NN.
However, FragPipe will not let me proceed without specifying a spectral library even though the interface says it is optional.
Is what I am trying to do even possible in FragPipe?

[https://github.com/Nesvilab/FragPipe/issues/1022]
In a previous post, chris-discopharma said inputting "" for the optional spectral library can bypass the issue but I got an error.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

java.nio.file.InvalidPathException: Illegal char <"> at index 0: ""
	at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.base/java.nio.file.Path.of(Unknown Source)
	at java.base/java.nio.file.Paths.get(Unknown Source)
	at com.dmtavt.fragpipe.cmd.CmdDiann.configure(CmdDiann.java:247)
	at com.dmtavt.fragpipe.FragpipeRun.lambda$configureTaskGraph$68(FragpipeRun.java:1851)
	at com.dmtavt.fragpipe.FragpipeRun.configureTaskGraph(FragpipeRun.java:1974)
	at com.dmtavt.fragpipe.FragpipeRun.run(FragpipeRun.java:313)
	at com.dmtavt.fragpipe.tabs.TabRun.on(TabRun.java:179)
	at jdk.internal.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:511)
	at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by fcyu** [comment]
The current version does not support searching diaPASEF directly. You will need ddaPASEF to build the library.

Best,

Fengchao
