### ISSUE TITLE
non-zero exit code for IonQuant 

### ISSUE THREAD

**Issue by SamueldelaCamaraFuentes** [Nesvilab/FragPipe#1444]
Hi everyone!

I'm currently using FragPipe with those specific versions:

Version info:

    FragPipe version 20.0
    MSFragger version 3.8
    IonQuant-1.9.8
    Philosopher v5.0.0

I am using a default workflow on 141 timsTOF Pro data (ddaPASEF files Bruker .d) files. The analysis is run with MSFragger with its parameters set as default (the expection is with a Split database value = 19), with a Validation tab with PSM Validation (Percolator is run) and ProteinProphet as Protein Inference module. Finally the Quant (MS1) tab is run with default parameters. 

After all of the above modules are run the following error message is displayed: 

~~~~~~~~~~~~~~~~~~~~

2024-02-11 16:47:30 [INFO] - Training LDA models for all matched features.
2024-02-11 16:47:37 [INFO] - #{+1} = 278272, #{-1} = 233470, #{+2} = 14302, #{-2} = 7255
2024-02-11 16:47:37 [INFO] - Standardized coefficients:
2024-02-11 16:47:37 [INFO] - log10(intensity): 0.8963579122713958
2024-02-11 16:47:37 [INFO] - log10(KL): -0.2644878415339306
2024-02-11 16:47:37 [INFO] - abs(ppm): -0.14662237939155665
2024-02-11 16:47:37 [INFO] - IM diff: -0.32349236204758514
2024-02-11 16:47:37 [INFO] - RT diff: -0.0210533690325264
2024-02-11 16:47:38 [INFO] - Fitting a mixture model...
java.lang.IllegalStateException
	at umontreal.ssj.probdist.EmpiricalDist.cdf(EmpiricalDist.java:132)
	at a.a(Unknown Source)
	at t.<init>(Unknown Source)
	at ionquant.IonQuant.main(Unknown Source)
2024-02-11 16:47:38 [ERROR] - null
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping

Cancelling 1 remaining tasks
~~~~~~~~~~~~~~~~~~~~
It is neccessary to clear out that this analyses took 3 weeks long until the error has been displayed that´s why the software is not updated to the latest versions; Fragpipe v21 and MSFragger v4.0.

Thank you so much in advance,

Samuel

- log file uploaded
[log_2024-02-11_16-47-41.txt](https://github.com/Nesvilab/FragPipe/files/14236329/log_2024-02-11_16-47-41.txt)

**Comment by fcyu** [comment]
HI Samuel,

Thanks for reaching out. This bug might have been fixed in the latest version. Could you download the latest FragPipe, MSFragger, Philosopher, and IonQuant. And try again?

Thanks,

Fengchao

**Comment by SamueldelaCamaraFuentes** [comment]
With the latest FragPipe version, the problem is solved. Thank you so much for your help.

Kind regards,
Samuel
