### ISSUE TITLE
csv.Error: field larger than field limit (131072)

### ISSUE THREAD

**Issue by hcmslab** [Nesvilab/FragPipe#1452]
Hello, I was generating spectral library using Fragpipe with a large database (split of 10), but get the following errors. 
Run with two samples only works well, but not for using all samples I have (32 samples). 
can you please advise on this issue? Thanks. 
Xu

Traceback (most recent call last):
  File "C:\Users\ULTRA\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "E:\FragPipe-jre-21.1\fragpipe\tools\msfragger_pep_split.py", line 406, in write_pin
    pins = [read_pin(tempdir_part / (infile.stem + '.pin')) for tempdir_part in tempdir_parts]
  File "E:\FragPipe-jre-21.1\fragpipe\tools\msfragger_pep_split.py", line 406, in <listcomp>
    pins = [read_pin(tempdir_part / (infile.stem + '.pin')) for tempdir_part in tempdir_parts]
  File "E:\FragPipe-jre-21.1\fragpipe\tools\msfragger_pep_split.py", line 457, in read_pin
    for row in reader:
_csv.Error: field larger than field limit (131072)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "E:\FragPipe-jre-21.1\fragpipe\tools\msfragger_pep_split.py", line 630, in <module>
    main()
  File "E:\FragPipe-jre-21.1\fragpipe\tools\msfragger_pep_split.py", line 622, in main
    combine_results()
  File "E:\FragPipe-jre-21.1\fragpipe\tools\msfragger_pep_split.py", line 476, in combine_results
    e.result()
  File "C:\Users\ULTRA\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\ULTRA\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
_csv.Error: field larger than field limit (131072)
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

[log_2024-02-17_02-17-20.txt](https://github.com/Nesvilab/FragPipe/files/14320732/log_2024-02-17_02-17-20.txt)

**Comment by guoci** [comment]
Please send any pin files you have generated.

**Comment by hcmslab** [comment]
[20240211_CHFL-DDA_Pool2-F4_Slot2-21_1_2539.zip](https://github.com/Nesvilab/FragPipe/files/14525878/20240211_CHFL-DDA_Pool2-F4_Slot2-21_1_2539.zip)
Hi Ci, here is a pin file. Thank you.

**Comment by guoci** [comment]
@hcmslab Is there any other pin files? That pin file wasn't the cause of the error.

**Comment by guoci** [comment]
@hcmslab It seems that none of the pin files was the cause of the error.
Can you try rerunning?

**Comment by hcmslab** [comment]
Hi Ci, it seems to be the issue of a single file (20240211_CHFL-DDA_Pool2-F2_Slot2-19_1_2537.d). I did several runs with or without this file and this file only as well. All runs with this file can't finish, while the others were successful. There was no PIN file generated for this raw file. 
Interestingly, this file is not a problem if I ran the search with a smaller database (sutset of the big database). PIN file can be generated for smaller database search. This file can open well and the spectrum also looks fine. 

I have attached logs for two searches with or without this file, as well as a search using smaller database which succeeded. 

[log_2024-03-07_20-48-22.txt](https://github.com/Nesvilab/FragPipe/files/14544119/log_2024-03-07_20-48-22.txt)
[log_2024-03-07_22-24-51.txt](https://github.com/Nesvilab/FragPipe/files/14544115/log_2024-03-07_22-24-51.txt)
[log_2024-03-08_12-25-12.txt](https://github.com/Nesvilab/FragPipe/files/14544110/log_2024-03-08_12-25-12.txt)

**Comment by guoci** [comment]
If no pin was generated, then the error should be:
`FileNotFoundError: [Errno 2] No such file or directory: '...`
and not the csv error.
I think some pin files were generated for `20240211_CHFL-DDA_Pool2-F2_Slot2-19_1_2537.d`. Since you have 10 DB splits, you should have 10 pin files for it,
Can you show me a full listing for the tempdir directory?

**Comment by hcmslab** [comment]
Oh, found the PIN files in tempdir. I was looking for PIN files in raw data folder (other files did generate one there). 
I have attached two PIN files for F1 (the one more likely has issues as only searches with this file have issue). 
[20240211_CHFL-DDA_Pool2-F1_Slot2-18_1_2536[search0].zip](https://github.com/Nesvilab/FragPipe/files/14548822/20240211_CHFL-DDA_Pool2-F1_Slot2-18_1_2536.search0.zip)
[20240211_CHFL-DDA_Pool2-F1_Slot2-18_1_2536[search9].zip](https://github.com/Nesvilab/FragPipe/files/14548826/20240211_CHFL-DDA_Pool2-F1_Slot2-18_1_2536.search9.zip)

**Comment by guoci** [comment]
@hcmslab the 2 files are fine too.
Can you send also 8 other pin files of `20240211_CHFL-DDA_Pool2-F1_Slot2-18_1_2536`?

**Comment by hcmslab** [comment]
For sure. Here are the other 8 PIN  files. Thank you very much! 
[20240211_CHFL-DDA_Pool2-F1_Slot2-18_1_2536[search1].zip](https://github.com/Nesvilab/FragPipe/files/14551517/20240211_CHFL-DDA_Pool2-F1_Slot2-18_1_2536.search1.zip)
[20240211_CHFL-DDA_Pool2-F1_Slot2-18_1_2536[search2].zip](https://github.com/Nesvilab/FragPipe/files/14551518/20240211_CHFL-DDA_Pool2-F1_Slot2-18_1_2536.search2.zip)
[20240211_CHFL-DDA_Pool2-F1_Slot2-18_1_2536[search3].zip](https://github.com/Nesvilab/FragPipe/files/14551519/20240211_CHFL-DDA_Pool2-F1_Slot2-18_1_2536.search3.zip)
[20240211_CHFL-DDA_Pool2-F1_Slot2-18_1_2536[search4].zip](https://github.com/Nesvilab/FragPipe/files/14551520/20240211_CHFL-DDA_Pool2-F1_Slot2-18_1_2536.search4.zip)
[20240211_CHFL-DDA_Pool2-F1_Slot2-18_1_2536[search5].zip](https://github.com/Nesvilab/FragPipe/files/14551521/20240211_CHFL-DDA_Pool2-F1_Slot2-18_1_2536.search5.zip)
[20240211_CHFL-DDA_Pool2-F1_Slot2-18_1_2536[search6].zip](https://github.com/Nesvilab/FragPipe/files/14551522/20240211_CHFL-DDA_Pool2-F1_Slot2-18_1_2536.search6.zip)
[20240211_CHFL-DDA_Pool2-F1_Slot2-18_1_2536[search7].zip](https://github.com/Nesvilab/FragPipe/files/14551523/20240211_CHFL-DDA_Pool2-F1_Slot2-18_1_2536.search7.zip)
[20240211_CHFL-DDA_Pool2-F1_Slot2-18_1_2536[search8].zip](https://github.com/Nesvilab/FragPipe/files/14551524/20240211_CHFL-DDA_Pool2-F1_Slot2-18_1_2536.search8.zip)

**Comment by guoci** [comment]
For splits 5 and 6, there is spectrum `20240211_CHFL-DDA_Pool2-F1_Slot2-18_1_2536.29319.29319.2_1`
with very long `Proteins`.
![image](https://github.com/Nesvilab/FragPipe/assets/1260178/f36d3e97-24c5-4696-992b-f6a9c5c2e14a)
That is the cause, I will work on a fix.

**Comment by hcmslab** [comment]
Thank you very much Ci! Interesting, most are reversed sequences for this.

**Comment by hcmslab** [comment]
Hi Ci, thank you, however I got an error with this edit. 
Here is the log for a test run using one sample. 
[log_2024-03-11_21-32-07.txt](https://github.com/Nesvilab/FragPipe/files/14566096/log_2024-03-11_21-32-07.txt)


Traceback (most recent call last):
  File "C:\Users\ULTRA\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "E:\FragPipe-jre-21.1\fragpipe\tools\msfragger_pep_split.py", line 406, in write_pin
    pins = [read_pin(tempdir_part / (infile.stem + '.pin')) for tempdir_part in tempdir_parts]
  File "E:\FragPipe-jre-21.1\fragpipe\tools\msfragger_pep_split.py", line 406, in <listcomp>
    pins = [read_pin(tempdir_part / (infile.stem + '.pin')) for tempdir_part in tempdir_parts]
  File "E:\FragPipe-jre-21.1\fragpipe\tools\msfragger_pep_split.py", line 452, in read_pin
    csv.field_size_limit(sys.maxsize)
OverflowError: Python int too large to convert to C long
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\FragPipe-jre-21.1\fragpipe\tools\msfragger_pep_split.py", line 631, in <module>
    main()
  File "E:\FragPipe-jre-21.1\fragpipe\tools\msfragger_pep_split.py", line 623, in main
    combine_results()
  File "E:\FragPipe-jre-21.1\fragpipe\tools\msfragger_pep_split.py", line 477, in combine_results
    e.result()
  File "C:\Users\ULTRA\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\ULTRA\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
OverflowError: Python int too large to convert to C long
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 14 remaining tasks

**Comment by guoci** [comment]
@hcmslab can you change that line to
`csv.field_size_limit(2 ** 31 - 1)`
On Windows, long is 32bit, but is 64bit on Linux, so I didn't get that error.

**Comment by hcmslab** [comment]
Hi Ci, that works very well now. Thank yo so much!
