### ISSUE TITLE
Issue with SILAC analysis on DDA PASEF data

### ISSUE THREAD

**Issue by hcahaya** [Nesvilab/FragPipe#1465]
I encountered the following error: 
2024-02-26 20:29:58 [INFO] - Updating Philosopher's tables...
2024-02-26 20:29:58 [INFO] - Performing label quant...
2024-02-26 20:29:58 [INFO] - Re-quantifying 
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 14
	at r.a(Unknown Source)
	at r.<init>(Unknown Source)
	at ionquant.IonQuant.main(Unknown Source)
2024-02-26 20:30:05 [INFO] - Combining experiments and estimating protein intensity...
2024-02-26 20:30:05 [ERROR] - Index -1 out of bounds for length 14
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping

Here's the log file
[log_2024-02-26_20-34-55.txt](https://github.com/Nesvilab/FragPipe/files/14414397/log_2024-02-26_20-34-55.txt)

**Comment by fcyu** [comment]
It is a known issue: https://github.com/Nesvilab/FragPipe/issues/1387 

Could you send an email to yufe AY umich.edu to get a fixed version?

Thanks,

Fengchao

**Comment by hcahaya** [comment]
Great. Thank you!

**Comment by hcahaya** [comment]
Hi Fengchao, I sent an email at yufe at umich.edu yesterday. I still have not heard anything.

**Comment by fcyu** [comment]
I received your email 1 hour ago, and just replied it.

Best,

Fengchao
