### ISSUE TITLE
Dimethyl 3plex error in combining experiments and estimating protein intensity

### ISSUE THREAD

**Issue by FriedLabJHU** [Nesvilab/FragPipe#1476]
- Describe the issue or question:
Using the SILAC3 workflow for dimethyl 3plex labeled samples, I keep getting the following error:  
  
```
2024-03-04 16:38:28 [INFO] - Combining experiments and estimating protein intensity...
java.lang.ArrayIndexOutOfBoundsException: Index -476 out of bounds for length 40007
	at r.a(Unknown Source)
	at r.<init>(Unknown Source)
	at ionquant.IonQuant.main(Unknown Source)
2024-03-04 16:38:29 [ERROR] - Index -476 out of bounds for length 40007
Process 'IonQuant' finished, exit code: 1
```
[log_2024-03-04_16-38-29.txt](https://github.com/Nesvilab/FragPipe/files/14487540/log_2024-03-04_16-38-29.txt)

**Comment by fcyu** [comment]
Known bug: https://github.com/Nesvilab/FragPipe/issues/1387 

Could you send an email to yufe AT umich.edu to get the fixed version?

Thanks,

Fengchao
