### ISSUE TITLE
MalformedInputException

### ISSUE THREAD

**Issue by NatanSkibinski** [Nesvilab/FragPipe#1494]
- Describe the issue or question:
Fragpipe doesn't even open. I tried to reinstall Java, download fragpipe again, restart the PC, delete the tmp files, and so on. Unfortunately the issue still appears, when I am trying to start the programm. 

java.lang.IllegalStateException: Exception handler must throw a RuntimeException
	at org.jooq.lambda.Unchecked.lambda$consumer$17(Unchecked.java:699)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.dmtavt.fragpipe.tabs.TabWorkflow.findPropsFiles(TabWorkflow.java:540)
	at com.dmtavt.fragpipe.tabs.TabWorkflow.loadWorkflowFiles(TabWorkflow.java:560)
	at com.dmtavt.fragpipe.tabs.TabWorkflow.createPanelWorkflows(TabWorkflow.java:617)
	at com.dmtavt.fragpipe.tabs.TabWorkflow.init(TabWorkflow.java:480)
	at com.dmtavt.fragpipe.tabs.TabWorkflow.<init>(TabWorkflow.java:289)
	at com.dmtavt.fragpipe.Fragpipe.createTabs(Fragpipe.java:629)
	at com.dmtavt.fragpipe.Fragpipe.initUi(Fragpipe.java:702)
	at com.dmtavt.fragpipe.Fragpipe.<init>(Fragpipe.java:218)
	at com.dmtavt.fragpipe.Fragpipe.lambda$displayMainWindow$3(Fragpipe.java:506)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
	at java.base/java.nio.charset.CoderResult.throwException(Unknown Source)
	at java.base/sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at java.base/sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.base/java.io.InputStreamReader.read(Unknown Source)
	at java.base/java.io.BufferedReader.read1(Unknown Source)
	at java.base/java.io.BufferedReader.read(Unknown Source)
	at java.base/java.io.Reader.read(Unknown Source)
	at java.base/java.util.Properties$LineReader.readLine(Unknown Source)
	at java.base/java.util.Properties.load0(Unknown Source)
	at java.base/java.util.Properties.load(Unknown Source)
	at com.dmtavt.fragpipe.api.PropsFile.load(PropsFile.java:61)
	at com.dmtavt.fragpipe.tabs.TabWorkflow.lambda$findPropsFiles$9(TabWorkflow.java:542)
	at org.jooq.lambda.Unchecked.lambda$consumer$17(Unchecked.java:694)
	... 34 more

**Comment by fcyu** [comment]
Could you remove the files in the following locations and try again? The parent paths may be different in your Linux system.
```shell
<your fragpipe directory>/fragpipe/cache/
~/.config/FragPipe/
```

Thanks,

Fengchao
