### ISSUE TITLE
Library not generated, not enough peptides could be found for alignment.

### ISSUE THREAD

**Issue by lbwfff** [Nesvilab/FragPipe#1496]
- Describe the issue or question:

Hi fragpipe developer, I am using DIA_SpecLib_Quant flow to analyse the data and have encountered some issues, here is my workflow file along with the run logs.

[workflow.txt](https://github.com/Nesvilab/FragPipe/files/14662704/workflow.txt)
[slurm-5627242.txt](https://github.com/Nesvilab/FragPipe/files/14662705/slurm-5627242.txt)

This seems to be due to a problem with one of the files Generate theoretical spectra.

```
2024-03-19 17:30:52 - Info: Converting ['/scratch/lb4489/project/van_cell/cort_inter/fragpipe/interact-211019_MvO_2069_SN158_VIP-P2_2_rank1.pep.xml', '/scratch/lb4489/project/van_cell/cort_inter/fragpipe/interact-211019_MvO_2069_SN158_VIP-P2_2_rank2.pep.xml', '/scratch/lb4489/project/van_cell/cort_inter/fragpipe/interact-211019_MvO_2069_SN158_VIP-P2_2_rank3.pep.xml', '/scratch/lb4489/project/van_cell/cort_inter/fragpipe/interact-211019_MvO_2069_SN158_VIP-P2_2_rank4.pep.xml', '/scratch/lb4489/project/van_cell/cort_inter/fragpipe/interact-211019_MvO_2069_SN158_VIP-P2_2_rank5.pep.xml'].
2024-03-19 17:30:52 - Info: Parsing run 211019_MvO_2069_SN158_VIP-P2_2.
2024-03-19 17:30:52 - Info: Parsing pepXML: /scratch/lb4489/project/van_cell/cort_inter/fragpipe/interact-211019_MvO_2069_SN158_VIP-P2_2_rank1.pep.xml
2024-03-19 17:30:54 - Info: 10241 PSMs parsed.
2024-03-19 17:30:54 - Info: Parsing pepXML: /scratch/lb4489/project/van_cell/cort_inter/fragpipe/interact-211019_MvO_2069_SN158_VIP-P2_2_rank2.pep.xml
2024-03-19 17:30:54 - Info: 2039 PSMs parsed.
2024-03-19 17:30:54 - Info: Parsing pepXML: /scratch/lb4489/project/van_cell/cort_inter/fragpipe/interact-211019_MvO_2069_SN158_VIP-P2_2_rank3.pep.xml
2024-03-19 17:30:54 - Info: 436 PSMs parsed.
2024-03-19 17:30:54 - Info: Parsing pepXML: /scratch/lb4489/project/van_cell/cort_inter/fragpipe/interact-211019_MvO_2069_SN158_VIP-P2_2_rank4.pep.xml
2024-03-19 17:30:54 - Info: 107 PSMs parsed.
2024-03-19 17:30:54 - Info: Parsing pepXML: /scratch/lb4489/project/van_cell/cort_inter/fragpipe/interact-211019_MvO_2069_SN158_VIP-P2_2_rank5.pep.xml
2024-03-19 17:30:54 - Info: 21 PSMs parsed.
2024-03-19 17:30:54 - Info: Generate theoretical spectra.
2024-03-19 17:30:57 - Info: Processing spectra from file /scratch/lb4489/project/van_cell/cort_inter/dia/VIP_158/211019_MvO_2069_SN158_VIP-P2_2.mzML.
/__w/OpenMS/OpenMS/OpenMS/src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp(104): While loading '/scratch/lb4489/project/van_cell/cort_inter/dia/VIP_158/211019_MvO_2069_SN158_VIP-P2_2.mzML': input ended before all started tags were ended; last tag started is 'chromatogramList'( in line 5377423 column 1)
Traceback (most recent call last):
  File "/home/lb4489/.conda/envs/py3.9/bin/easypqp", line 8, in <module>
    sys.exit(cli())
  File "/home/lb4489/.conda/envs/py3.9/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/lb4489/.conda/envs/py3.9/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/lb4489/.conda/envs/py3.9/lib/python3.9/site-packages/click/core.py", line 1719, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/lb4489/.conda/envs/py3.9/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lb4489/.conda/envs/py3.9/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/lb4489/.conda/envs/py3.9/lib/python3.9/site-packages/easypqp/main.py", line 90, in convert
    psms, peaks = conversion(pepxmlfile_list, spectralfile, unimodfile, exclude_range, max_delta_unimod, max_delta_ppm, enable_unannotated, enable_massdiff, fragment_types, fragment_charges, enable_specific_losses, enable_unspecific_losses, max_psm_pep, precision_digits)
  File "/home/lb4489/.conda/envs/py3.9/lib/python3.9/site-packages/easypqp/convert.py", line 744, in conversion
    input_map = get_map_mzml_or_mzxml(spectralfile, 'mzml')
  File "/home/lb4489/.conda/envs/py3.9/lib/python3.9/site-packages/easypqp/convert.py", line 726, in get_map_mzml_or_mzxml
    fh.transform(path, consumer)
  File "pyopenms/_pyopenms_2.pyx", line 10320, in pyopenms._pyopenms_2.MzMLFile.transform
  File "pyopenms/_pyopenms_2.pyx", line 10406, in pyopenms._pyopenms_2.MzMLFile._transform_1
RuntimeError: - due to that error of type Parse Error in: /__w/OpenMS/OpenMS/OpenMS/src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp@105-void OpenMS::Internal::XMLHandler::fatalError(OpenMS::Internal::XMLHandler::ActionMode, const OpenMS::String&, OpenMS::UInt, OpenMS::UInt) const
```

I am using the latest version of easypqp (0.1.42), why is this happening and what should I do to fix it.

Thanks,
LeeLee

**Comment by guoci** [comment]
@lbwfff please post the file `/scratch/lb4489/project/van_cell/cort_inter/dia/VIP_158/211019_MvO_2069_SN158_VIP-P2_2.mzML`

**Comment by lbwfff** [comment]
Hi guoci, you can find the file at this link

https://www.dropbox.com/scl/fi/dtr4mwj1vhegm76ckv9tt/211019_MvO_2069_SN158_VIP-P2_2.mzML?rlkey=n2tn94q2kjhgjmx4glwce5xh0&dl=0

**Comment by guoci** [comment]
That file is invaild. It ends with
```
...
            </binaryDataArray>
          </binaryDataArrayList>
        </chromatogram>
```
That is the cause of the error.

**Comment by lbwfff** [comment]
Thanks for the reply, I see, let me re-download the data and analyse it again.

**Comment by lbwfff** [comment]
Yes, the analysis went smoothly after re-downloading the data.
