### ISSUE TITLE
corrupted files cause MSFragger to terminate

### ISSUE THREAD

**Issue by liangxiao023** [Nesvilab/FragPipe#1502]
- Describe the issue or question:
Hi, I am trying to process 251 files at once using fragpipe and have allocated 895GB of running memory to it. But there is a runtime error in the MSFragger section, is it due to some datasets not being formatted correctly? The log file is below.

Mar 25, 2024 2:10:27 PM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Previous channel ManagedChannelImpl{logId=641, target=localhost:43813} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:102)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:60)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:51)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:655)
	at io.grpc.ForwardingChannelBuilder2.build(ForwardingChannelBuilder2.java:261)
	at umich.ms.fileio.filetypes.thermo.ThermoRawFile.init(ThermoRawFile.java:218)
	at umich.ms.fileio.filetypes.thermo.ThermoRawFile.<init>(ThermoRawFile.java:164)
	at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

There are corrupted files. Please remove those files and re-start the task.
Traceback (most recent call last):
  File "/home/liangx/software/fragpipe/tools/msfragger_pep_split.py", line 630, in <module>
    main()
  File "/home/liangx/software/fragpipe/tools/msfragger_pep_split.py", line 614, in main
    calibrate_mzBIN, params_txt_new = calibrate(fasta_path_sample, calibrate_mass)
  File "/home/liangx/software/fragpipe/tools/msfragger_pep_split.py", line 494, in calibrate
    raise AssertionError(p)
AssertionError: <Popen: returncode: 1 args: ['java', '-jar', '-Dfile.encoding=UTF-8', '-Xmx8...>
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

[log_2024-03-25_14-12-22.txt](https://github.com/Nesvilab/FragPipe/files/14739853/log_2024-03-25_14-12-22.txt)

**Comment by fcyu** [comment]
The following file was corrupted `/home/liangx/data/PXD04894/20141213_QEp7_MiBa_SA_HLA-I-p_MM16_1_B_1.raw`. Could you remove it and try again.?

```shell
[pool-1-thread-4] ERROR umich.ms.fileio.filetypes.thermo.ThermoRawFile - PRC method Open() returned ErrorStatus. Messages: Could not open the specified file.
Failed in checking /home/liangx/data/PXD04894/20141213_QEp7_MiBa_SA_HLA-I-p_MM16_1_B_1.raw. Will ignore it.
Server could not open location
/home/liangx/data/PXD04894/20141213_QEp7_MiBa_SA_HLA-I-p_MM16_1_B_1.raw: Scans = 0; Isolation sizes = []
Mar 25, 2024 2:10:27 PM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Previous channel ManagedChannelImpl{logId=641, target=localhost:43813} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:102)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:60)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:51)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:655)
	at io.grpc.ForwardingChannelBuilder2.build(ForwardingChannelBuilder2.java:261)
	at umich.ms.fileio.filetypes.thermo.ThermoRawFile.init(ThermoRawFile.java:218)
	at umich.ms.fileio.filetypes.thermo.ThermoRawFile.<init>(ThermoRawFile.java:164)
	at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Thanks,

Fengchao

**Comment by fcyu** [comment]
> why does the combined_modified_peptide file contain peptides that do not contain modifications and are larger than the combined_peptide file?

Because it contains both modified and unmodified peptides.

> I want to know how many peptides were measured in total and how many modified peptides are in them, which file should I look at?

combined_modified_peptide.tsv

> why some peptides are still listed even though their intensity is 0. Doesn't an intensity of 0 mean that the peptide does not exist?

They were identified but failed passing the quantification quality filtering.

Best,

Fengchao

**Comment by liangxiao023** [comment]
> > why does the combined_modified_peptide file contain peptides that do not contain modifications and are larger than the combined_peptide file?
> 
> Because it contains both modified and unmodified peptides.
> 
> > I want to know how many peptides were measured in total and how many modified peptides are in them, which file should I look at?
> 
> combined_modified_peptide.tsv
> 
> > why some peptides are still listed even though their intensity is 0. Doesn't an intensity of 0 mean that the peptide does not exist?
> 
> They were identified but failed passing the quantification quality filtering.
> 
> Best,
> 
> Fengchao

Thank you so much for your answers, they have been a great help to me.
