### ISSUE TITLE
PTM not working

### ISSUE THREAD

**Issue by TimKarr** [Nesvilab/FragPipe#1511]
This happens repeatedly, with the same error message. 

Exception in thread "main" java.io.FileNotFoundException: C:\DmelBrains_March24\DmelBrainsPTM\Dmel1ABrain1\psm.tsv (The system cannot find the file specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(Unknown Source)
	at java.base/java.io.FileInputStream.<init>(Unknown Source)
	at edu.umich.andykong.ptmshepherd.PSMFile.getCRC32(PSMFile.java:71)
	at edu.umich.andykong.ptmshepherd.PTMShepherd.getMzDataMapping(PTMShepherd.java:936)
	at edu.umich.andykong.ptmshepherd.PTMShepherd.main(PTMShepherd.java:347)

PTM-Shepherd version 2.0.6
(c) 2022 University of Michigan

Using Java 11.0.9.1 on 32768MB memory

Finding spectral data
Process 'PTMShepherd' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 1 remaining tasks
- Describe the issue or question:



- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by danielgeiszler** [comment]
Please upload your log file.

**Comment by danielgeiszler** [comment]
However, the reason is because the psm file it's trying to access (C:\DmelBrains_March24\DmelBrainsPTM\Dmel1ABrain1\psm.tsv) is not there.

**Comment by TimKarr** [comment]
[log_2024-03-30_19-22-03.txt](https://github.com/Nesvilab/FragPipe/files/14818422/log_2024-03-30_19-22-03.txt)

**Comment by danielgeiszler** [comment]
You have the Validation tab disabled, which creates the input for PTM-Shepherd. Please use one of the prespecified workflows shipped with FragPipe.

We have tutorials for new users available here: https://fragpipe.nesvilab.org/docs/tutorial_fragpipe.html
