### ISSUE TITLE
Process 'Percolator' finished, exit code: 134

### ISSUE THREAD

**Issue by lbwfff** [Nesvilab/FragPipe#1519]
- Describe the issue or question:

I am using DIA_DIA-Umpire_SpecLib_Quant process to analyze the data, and I have only DIA and no DDA type in my data, and the following error message is reported

```
Found 0 test set PSMs with q<0.01.
No targets found with q<0.01
Resetting score vector, using default vector. Use --override flag to prevent this.
Split 1:	Selected feature 7 as initial direction. Could separate 95 training set positives with q<0.01 in that direction.
Split 2:	Selected feature 4 as initial direction. Could separate 65 training set positives with q<0.01 in that direction.
Split 3:	Selected feature 6 as initial direction. Could separate 74 training set positives with q<0.01 in that direction.
Selected best-scoring PSM per file+scan+expMass (target-decoy competition): 696 target PSMs and 368 decoy PSMs.
Calculating q values.
Final list yields 112 target PSMs with q<0.01.
Calculating posterior error probabilities (PEPs).
percolator: /storage/yufe/tools/percolator-rel-3-06-04/src/BaseSpline.cpp:234: void BaseSpline::initiateQR(): Assertion `dx[ix] > 0' failed.
Process 'Percolator' finished, exit code: 134
Process returned non-zero exit code, stopping
```

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

Here is the full log
[Uploading slurm-6804377.out.txt…]()

**Comment by lbwfff** [comment]
Not sure if this helps, but I also encountered an error when using peptideprophet

```
Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.ClassLoader ch.qos.logback.core.util.Loader.systemClassloaderIfNull(java.lang.ClassLoader)'
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:73)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:66)
	at ch.qos.logback.classic.spi.LogbackServiceProvider.initializeLoggerContext(LogbackServiceProvider.java:52)
	at ch.qos.logback.classic.spi.LogbackServiceProvider.initialize(LogbackServiceProvider.java:41)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:152)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:139)
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:422)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:408)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at com.dmtavt.fragpipe.util.RewritePepxml.<clinit>(RewritePepxml.java:40)
Process 'Rewrite pepxml' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 10 remaining tasks
```

[slurm-6828298.zip](https://github.com/Nesvilab/FragPipe/files/14965286/slurm-6828298.zip)

**Comment by fcyu** [comment]
Regarding the PeptideProphet error, the FragPipe executable files have been corrupted. Please download a new one and start from scratch.

Best,

Fengchao

**Comment by BaylorSci** [comment]
I am also having the same issues running the DIA_DIA-Umpire_SpecLib_Quant workflow. (I have also tried this without the workflow loaded but individually selected the tabs with the same parameters). This is a recent issue, where the same samples (small subset) I have successfully ran previously are suddenly terminating at the percolator step: 

```
Found 0 test set PSMs with q<0.01.
No targets found with q<0.01
Resetting score vector, using default vector. Use --override flag to prevent this.
Split 1:	Selected feature 21 as initial direction. Could separate 21 training set positives with q<0.01 in that direction.
Split 2:	Selected feature 1 as initial direction. Could separate 26 training set positives with q<0.01 in that direction.
Split 3:	Selected feature 21 as initial direction. Could separate 22 training set positives with q<0.01 in that direction.
Selected best-scoring PSM per file+scan+expMass (target-decoy competition): 38 target PSMs and 1 decoy PSMs.
Calculating q values.
Final list yields 0 target PSMs with q<0.01.
Calculating posterior error probabilities (PEPs).
ERROR: Fewer than 4 bins available for PEP estimation, cannot perform quadratic spline.
No-terminate flag set: ignoring error and adding additional bins to get 4 bins.
percolator: /storage/yufe/tools/percolator-rel-3-06-04/src/BaseSpline.cpp:234: void BaseSpline::initiateQR(): Assertion `dx[ix] > 0' failed.
Process 'Percolator' finished, exit code: 134
Process returned non-zero exit code, stopping
```
Any help with this would be very appreciated, although I note that the crosslinked post to percolator has not gotten any replies since this issue was first raised. Could the program have somehow become
