### ISSUE TITLE
KeyError with split dataset

### ISSUE THREAD

**Issue by kfattila** [Nesvilab/FragPipe#1547]
Hi there,

First of all, thank you very much for developing the FragPipe eco system for mass spec data analysis, it is a very convenient tool. :)

I am trying to run MS-Fragger (v4.0) via FragPie (v21.1) to search DDA data against a non-tryptic peptide database split in half ("Split database=2"). The search in two steps finishes, but there seems to be a bug in the python script when it merges the search results. 
Could you please let me know a workaround this issue?

The error message:
```
*******************************TOTAL TIME 33.812 MIN********************************
DONE: DB split 2 of 2
['java', '-jar', '-Dfile.encoding=UTF-8', '-Xmx94G', WindowsPath('D:/fragpipe/tools/MSFragger-4.0/MSFragger-4.0.jar'), '--generate_expect_functions', '20180630_SKMEL5_P1uM_L7__scores_histogram.tsv', '20180630_SKMEL5_Palbo_1uM__scores_histogram.tsv', '20180630_SKMEL5_Palbo_1uM_AUC_scores_histogram.tsv', '20180630_SKMEL5_Palbo_all_L7_scores_histogram.tsv', '20181022_IPC_Palbo-2_scores_histogram.tsv', '20181113_SKMEL5_Ifng_15_1-1_scores_histogram.tsv', '20181115_IPC_ifng_15_scores_histogram.tsv', '20181201_SK2_ifng_scores_histogram.tsv', '20190227_231_15_L7_scores_histogram.tsv', '20190227_SK28_IFNg_15_all_scores_histogram.tsv', '20190304_231_all_scores_histogram.tsv', '20190307_SK2_Palbo_15_all_scores_histogram.tsv', '20190908_231_2_nolabel_all5_Perc_scores_histogram.tsv', '20190908_231_all_AUC_nolabel_REAL_scores_histogram.tsv', '20191023_IPC_1uM_P_20_all_scores_histogram.tsv', '20191026_SK28_1P_15_all_scores_histogram.tsv', '20191119_231_L7_scores_histogram.tsv', '20191213_231_1_3_L7_253_scores_histogram.tsv', 'SK28_Palbo_scores_histogram.tsv', 'SK2_Palbo_scores_histogram.tsv', 'SKMEL5_palbo_scores_histogram.tsv']
MSFragger version MSFragger-4.0
Batmass-IO version 1.30.0
timsdata library version timsdata-2-21-0-4
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
timdTOF .d reading tool. Copyright (c) 2022 by Bruker Daltonics GmbH & Co. KG. All rights reserved.
System OS: Windows 10, Architecture: AMD64
Java Info: 22.0.1, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\kfattila\anaconda3\lib\concurrent\futures\process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "D:\fragpipe-21.2\tools\msfragger_pep_split.py", line 419, in write_pin
    sorted_spectrums = sorted([(spec_to_index_map[k],
  File "D:\fragpipe-21.2\tools\msfragger_pep_split.py", line 419, in <listcomp>
    sorted_spectrums = sorted([(spec_to_index_map[k],
KeyError: '20180630_SKMEL5_P1uM_L7_.2.2'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\fragpipe-21.2\tools\msfragger_pep_split.py", line 630, in <module>
    main()
  File "D:\fragpipe-21.2\tools\msfragger_pep_split.py", line 622, in main
    combine_results()
  File "D:\fragpipe-21.2\tools\msfragger_pep_split.py", line 476, in combine_results
    e.result()
  File "C:\Users\kfattila\anaconda3\lib\concurrent\futures\_base.py", line 438, in result
    return self.__get_result()
  File "C:\Users\kfattila\anaconda3\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
KeyError: '20180630_SKMEL5_P1uM_L7_.2.2'
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 43 remaining tasks
```

**Comment by fcyu** [comment]
Can you share the whole log file?

Thanks,

Fengchao

**Comment by kfattila** [comment]
Hi Fengchao,

Attached is my log file along with the msfragger parameter file. I used the public PXD017407 data set 
[log_2024-04-17_19-02-38.txt](https://github.com/Nesvilab/FragPipe/files/15040942/log_2024-04-17_19-02-38.txt)

[fragger.zip](https://github.com/Nesvilab/FragPipe/files/15040960/fragger.zip)

Thanks!

**Comment by fcyu** [comment]
@guoci The error was from the split database. Could you take a look?

Thanks,

Fengchao
