### ISSUE TITLE
PTMShepherd_Exception in thread "main" java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Luc2702** [Nesvilab/FragPipe#1560]
Hello,

I have been trying to use the offsets search with ptm-sheperd to identify specific modifications in peptides. I am using mzML converted raw files (using MSConvert). 
For some of the files the following error happens.
Has anyone an idea how to fix this issue ? Thanks a lot for your help! 
I also attached the full log report 
[log_2024-04-26_20-31-51.txt](https://github.com/Nesvilab/FragPipe/files/15134206/log_2024-04-26_20-31-51.txt)

Running peak picking
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 72 out of bounds for length 72
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at edu.umich.andykong.ptmshepherd.peakpicker.PeakPicker.pickPeaks(PeakPicker.java:205)
	at edu.umich.andykong.ptmshepherd.PTMShepherd.main(PTMShepherd.java:490)
Process 'PTMShepherd' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 12 remaining tasks

**Comment by dpolasky** [comment]
Hi,
This is a known bug that will be fixed in the next release. You can usually get around it by loading the default "open search" settings on the PTM-Shepherd tab and rerunning from that point. (You don't need to keep the open search defaults, the parameters can be changed back - the important part is just to click the load button for open search defaults on the PTM-Shepherd tab).

Best,
Dan
