### ISSUE TITLE
Process 'Percolator: Convert to pepxml' finished, exit code: 1

### ISSUE THREAD

**Issue by Miracheng** [Nesvilab/FragPipe#1574]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-05-11_23-41-07.txt](https://github.com/Nesvilab/FragPipe/files/15285982/log_2024-05-11_23-41-07.txt)

**- Describe the issue or question:**

Hi, I am using my own database, and add decoys through fragpipe, and the following error message is reported.

~~~~~~~~~~~~~~~~~~~~
Exception in thread "main" java.lang.NumberFormatException: For input string: "-nan(ind)"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(Unknown Source)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(Unknown Source)
	at java.base/java.lang.Double.parseDouble(Unknown Source)
	at com.dmtavt.fragpipe.tools.percolator.PercolatorOutputToPepXML.percolatorToPepXML(PercolatorOutputToPepXML.java:366)
	at com.dmtavt.fragpipe.tools.percolator.PercolatorOutputToPepXML.main(PercolatorOutputToPepXML.java:59)
Process 'Percolator: Convert to pepxml' finished, exit code: 1
Process returned non-zero exit code, stopping

Cancelling 12 remaining tasks

**Comment by danielgeiszler** [comment]
Please check your data, settings, and database. You're getting no IDs.

**Comment by Miracheng** [comment]
Thanks for your reply. I used the solution of #1211  and it worked, but there are some new issues in the easyPQP section. 
And it seems different from the question I raised last time #1407 , because I tried to update easyPQP and restart the computer, and even converted the raw file to mzml format, but the problem still exists. Can you give me some advice?

[log_2024-05-13_13-34-26.txt](https://github.com/Nesvilab/FragPipe/files/15291296/log_2024-05-13_13-34-26.txt)

~~~~~~~~~~~~~~~~~~~~
File "E:\fragpipe\python\lib\site-packages\easypqp\main.py", line 200, in library
    generate(infiles, outfile, psmtsv, peptidetsv, perform_rt_calibration, rt_referencefile, rt_reference_run_path, rt_filter, perform_im_calibration, im_referencefile, im_reference_run_path, im_filter, psm_fdr_threshold, peptide_fdr_threshold, protein_fdr_threshold, rt_lowess_fraction, rt_psm_fdr_threshold, im_lowess_fraction, im_psm_fdr_threshold, pi0_lambda, peptide_plot_path, protein_plot_path, min_peptides, proteotypic, consensus, nofdr)
  File "E:\fragpipe\python\lib\site-packages\easypqp\library.py", line 441, in generate
    pepida = pepida.loc[np.isfinite(pepida['irt'])]
  File "E:\fragpipe\python\lib\site-packages\pandas\core\frame.py", line 3893, in __getitem__
    indexer = self.columns.get_loc(key)
  File "E:\fragpipe\python\lib\site-packages\pandas\core\indexes\range.py", line 418, in get_loc
    raise KeyError(key)
KeyError: 'irt'
Library not generated, not enough peptides could be found for alignment.
Library not generated, not enough peptides could be found for alignment.
Please try using other options for alignment (e.g. ciRT if used other options)
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping

**Comment by fcyu** [comment]
There are almost no IDs from you data. Please double check your sample and settings.

```shell
INFO[13:16:08] 1+ Charge profile                             decoy=0 target=0
INFO[13:16:08] 2+ Charge profile                             decoy=0 target=1
INFO[13:16:08] 3+ Charge profile                             decoy=0 target=0
INFO[13:16:08] 4+ Charge profile                             decoy=0 target=0
INFO[13:16:08] 5+ Charge profile                             decoy=0 target=0
INFO[13:16:08] 6+ Charge profile                             decoy=0 target=0
INFO[13:16:08] Database search results                       ions=1 peptides=1 psms=1
INFO[13:16:08] Converged to 0.00 % FDR with 1 PSMs           decoy=0 threshold=0.773086 total=1
INFO[13:16:08] Converged to 0.00 % FDR with 1 Peptides       decoy=0 threshold=0.773086 total=1
INFO[13:16:08] Converged to 0.00 % FDR with 1 Ions           decoy=0 threshold=0.773086 total=1
INFO[13:16:08] Protein inference results                     decoy=0 target=1
INFO[13:16:08] Converged to 0.00 % FDR with 1 Proteins       decoy=0 threshold=0.7723 total=1
INFO[13:16:08] 2D FDR estimation: Protein mirror image       decoy=1 target=1
INFO[13:16:08] Second filtering results                      ions=1 peptides=1 psms=1
INFO[13:16:08] Converged to 0.00 % FDR with 1 PSMs           decoy=0 threshold=0.773086 total=1
INFO[13:16:08] Converged to 0.00 % FDR with 1 Peptides       decoy=0 threshold=0.773086 total=1
INFO[13:16:08] Converged to 0.00 % FDR with 1 Ions           decoy=0 threshold=0.773086 total=1
INFO[13:16:08] Post processing identifications    
```

Best,

Fengchao
