### ISSUE TITLE
how to configure DIA-NN on Linux

### ISSUE THREAD

**Issue by huizhu2020** [Nesvilab/FragPipe#1584]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**
After configuring DIA-NN to fragpipe/tools/diann/1.8.2_beta_8/linux/diann-1.8.1.8, I get an error. What is the correct file for DIA-NN in Linux? Thanks
com.dmtavt.fragpipe.exceptions.ValidationException: Version string not found for DIA-NN from "../fragpipe/tools/diann/1.8.2_beta_8/linux/diann-1.8.1.8"
        at com.dmtavt.fragpipe.tools.diann.Diann.validate(Diann.java:127)
        at com.dmtavt.fragpipe.tabs.TabConfig.on(TabConfig.java:569)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
        at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:454)
        at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:421)
        at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:394)
        at org.greenrobot.eventbus.EventBus.post(EventBus.java:275)
        at com.dmtavt.fragpipe.api.Bus.post(Bus.java:76)
        at com.dmtavt.fragpipe.Fragpipe.loadUi(Fragpipe.java:802)
        at com.dmtavt.fragpipe.Fragpipe.on(Fragpipe.java:789)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
        at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:454)
        at org.greenrobot.eventbus.EventBus.checkPostStickyEventToSubscription(EventBus.java:213)
        at org.greenrobot.eventbus.EventBus.subscribe(EventBus.java:199)
        at org.greenrobot.eventbus.EventBus.register(EventBus.java:153)
        at com.dmtavt.fragpipe.api.Bus.register(Bus.java:50)
        at com.dmtavt.fragpipe.Fragpipe.initMore(Fragpipe.java:729)
        at com.dmtavt.fragpipe.Fragpipe.<init>(Fragpipe.java:219)
        at com.dmtavt.fragpipe.Fragpipe.lambda$displayMainWindow$3(Fragpipe.java:506)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by fcyu** [comment]
Similar to https://github.com/Nesvilab/FragPipe/issues/1518 and https://github.com/Nesvilab/FragPipe/issues/1066

Please check if your Linux has the correct GLIBC library. 

Best,

Fengchao

**Comment by huizhu2020** [comment]
> Similar to #1518 and #1066
> 
> Please check if your Linux has the correct GLIBC library.
> 
> Best,
> 
> Fengchao

Thank you for your help

**Comment by witszymanski** [comment]
Hi! 

I didn't want to start a new issue, as it's somehow related. 

I wanted to ask, how to configure a newer version of DIA-NN in the linux installation of FragPipe. In case of 1.8.2_beta_8 it's the file 

<img width="146" height="25" alt="Image" src="https://github.com/user-attachments/assets/46aaa363-6969-41af-9b01-6fe9565b81e0" />

There is no such file in newer installations of DIA-NN. Here an example of 2.2.0

<img width="526" height="407" alt="Image" src="https://github.com/user-attachments/assets/4cdbd799-a164-4b54-9f05-c7f559cba28f" />

The file `diann-linux` is not being accepted here. 

I'd be grateful for any help. 
Greets
Witek

**Comment by fcyu** [comment]
Hi Witek,

It seems that Vadim changed the file name so that FragPipe can't recognize it. Could you rename `diann-linux` to `diann-2.2.0` and try again?

Thanks,

Fengchao

**Comment by fcyu** [comment]
Yes, you can use the DIA_SpecLib_Quant_diaPASEF workflow.

Best,

Fengchao

**Comment by witszymanski** [comment]
I'm blind... 
☉_☉

It runs now, of course. 

Thanks!

**Comment by witszymanski** [comment]
> I think it was accepted now, at least the path was changed:
> <img alt="Image" width="934" height="152" src="https://private-user-images.githubusercontent.com/15866068/497822336-70e216ce-62f0-4ef4-a2d1-4854c8356469.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTk4MjIwMDksIm5iZiI6MTc1OTgyMTcwOSwicGF0aCI6Ii8xNTg2NjA2OC80OTc4MjIzMzYtNzBlMjE2Y2UtNjJmMC00ZWY0LWEyZDEtNDg1NGM4MzU2NDY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDA3VDA3MjE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MWUzOWQ5NTAwMDkxNTQ5MDM4YWE0MGY1MzhkMjJmOTZhYzY5NjVlN2UwOGQzMDQwYmZkYmE4MGQyZWQ4NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.maDNGzgTEreIvq3uqPOWBkBS9lIlj5ceDs8k5cHGf2A">
> 

I get the error though: 

```

Failed in checking /home/vitia/MS_data/FragPipe-23.1-linux/fragpipe-23.1/tools/diann/diann-2.2.0/diann-2.2.0
java.io.IOException: Cannot run program "/home/vitia/MS_data/FragPipe-23.1-linux/fragpipe-23.1/tools/diann/diann-2.2.0/diann-2.2.0": error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at org.nesvilab.fragpipe.tools.diann.Diann.checkExitCode(Diann.java:194)
	at org.nesvilab.fragpipe.tools.diann.Diann.getLDPRELOAD(Diann.java:165)
	at org.nesvilab.fragpipe.tools.diann.Diann.<clinit>(Diann.java:87)
	at org.nesvilab.fragpipe.tabs.TabConfig.on(TabConfig.java:578)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
	at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:454)
	at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:421)
	at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:394)
	at org.greenrobot.eventbus.EventBus.post(EventBus.java:275)
	at org.nesvilab.fragpipe.api.Bus.post(Bus.java:76)
	at org.nesvilab.fragpipe.Fragpipe.loadUi(Fragpipe.java:848)
	at org.nesvilab.fragpipe.Fragpipe.on(Fragpipe.java:835)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
	at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:454)
	at org.greenrobot.eventbus.EventBus.checkPostStickyEventToSubscription(EventBus.java:213)
	at org.greenrobot.eventbus.EventBus.subscribe(EventBus.java:199)
	at org.greenrobot.eventbus.EventBus.register(EventBus.java:153)
	at org.nesvilab.fragpipe.api.Bus.register(Bus.java:50)
	at org.nesvilab.fragpipe.Fragpipe.initMore(Fragpipe.java:757)
	at org.nesvilab.fragpipe.Fragpipe.<init>(Fragpipe.java:227)
	at org.nesvilab.fragpipe.Fragpipe.lambda$displayMainWindow$3(Fragpipe.java:527)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 43 more
org.nesvilab.fragpipe.exceptions.ValidationException: Does not appear to be an executable file: "/home/vitia/MS_data/FragPipe-23.1-linux/fragpipe-23.1/tools/diann/diann-2.2.0/diann-2.2.0"
	at org.nesvilab.fragpipe.tools.diann.Diann.validate(Diann.java:105)
	at org.nesvilab.fragpipe.tabs.TabConfig.on(TabConfig.java:578)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
	at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:454)
	at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:421)
	at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:394)
	at org.greenrobot.eventbus.EventBus.post(EventBus.java:275)
	at org.nesvilab.fragpipe.api.Bus.post(Bus.java:76)
	at org.nesvilab.fragpipe.Fragpipe.loadUi(Fragpipe.java:848)
	at org.nesvilab.fragpipe.Fragpipe.on(Fragpipe.java:835)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
	at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:454)
	at org.greenrobot.eventbus.EventBus.checkPostStickyEventToSubscription(EventBus.java:213)
	at org.greenrobot.eventbus.EventBus.subscribe(EventBus.java:199)
	at org.greenrobot.eventbus.EventBus.register(EventBus.java:153)
	at org.nesvilab.fragpipe.api.Bus.register(Bus.java:50)
	at org.nesvilab.fragpipe.Fragpipe.initMore(Fragpipe.java:757)
	at org.nesvilab.fragpipe.Fragpipe.<init>(Fragpipe.java:227)
	at org.nesvilab.fragpipe.Fragpipe.lambda$displayMainWindow$3(Fragpipe.java:527)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by witszymanski** [comment]
Ha! I made it. One has to make it "executive as program". 

<img width="435" height="619" alt="Image" src="https://github.com/user-attachments/assets/e32188dd-7a26-47ca-9d36-37618362f4d8" />

<img width="988" height="167" alt="Image" src="https://github.com/user-attachments/assets/0a831e69-8f3d-4052-b0c6-633a78a427be" />
