### ISSUE TITLE
Using DDA data from Waters

### ISSUE THREAD

**Issue by orbitra** [Nesvilab/FragPipe#1597]
Hello,
Is there a way to process DDA data acquired from a Waters SynaptXS?
I do not use any ion mobility during the acquisition.
I tried to convert the raw file in mzML with Waters´s data connect that basically recalibrates the mass with the lock mass, removes the lock mass scans, centroid and compress using mzlib.
I also tried with MSconvert, with the recommended conversion parameters but both approaches give me the same error with centroid check.

Process 'CheckCentroid' finished, exit code: 1
Process returned non-zero exit code, stopping.

CheckCentroid
C:\Users\\Documents\software-tools\glycoproteomics\fragpipe\FragPipe-jre-21.1\fragpipe\jre\bin\java.exe -Xmx2G -cp C:\Users\\Documents\software-tools\glycoproteomics\fragpipe\FragPipe-jre-21.1\fragpipe\lib\fragpipe-21.1.jar;C:\Users\\Documents\software-tools\glycoproteomics\fragpipe\FragPipe-jre-21.1\fragpipe\tools\batmass-io-1.30.0.jar com.dmtavt.fragpipe.util.CheckCentroid E:\AL-20240425-C18-fetuin-GluCtryp-std.mzML 3
java.lang.IndexOutOfBoundsException
	at java.base/java.io.RandomAccessFile.readBytes(Native Method)
	at java.base/java.io.RandomAccessFile.read(Unknown Source)
	at java.base/java.io.RandomAccessFile.readFully(Unknown Source)
	at umich.ms.fileio.filetypes.xmlbased.AbstractXMLBasedDataSource.readContinuousBatchOfSpectra(AbstractXMLBasedDataSource.java:343)
	at umich.ms.fileio.filetypes.xmlbased.AbstractXMLBasedDataSource.parse(AbstractXMLBasedDataSource.java:184)
	at umich.ms.datatypes.scancollection.impl.ScanCollectionDefault.loadData(ScanCollectionDefault.java:807)
	at umich.ms.datatypes.scancollection.impl.ScanCollectionDefault.loadData(ScanCollectionDefault.java:791)
	at com.dmtavt.fragpipe.util.CheckCentroid.isCentroid(CheckCentroid.java:76)
	at com.dmtavt.fragpipe.util.CheckCentroid.main(CheckCentroid.java:39)
Process 'CheckCentroid' finished, exit code: 1
Process returned non-zero exit code, stopping

**Comment by fcyu** [comment]
Unfortunately, our tools don't support Waters data due to its unique scan header format. We have contacted the Waters' engineers but it seems that there are no updates since then.

Best,

Fengchao
