### ISSUE TITLE
ArrayIndexOutOfBoundsException during peak picking in Open Search

### ISSUE THREAD

**Issue by armadillocommander** [Nesvilab/FragPipe#161]
The error happened during open search, while the peak picking step:
```
Running peak picking

Picked top 500 peaks

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at java.util.Arrays$ArrayList.get(Unknown Source)
	at edu.umich.andykong.ptmshepherd.peakpicker.PeakAnnotator.init(PeakAnnotator.java:192)
	at edu.umich.andykong.ptmshepherd.PTMShepherd.main(PTMShepherd.java:328)
created summary table

Process 'PTMShepherd' finished, exit code: 1

Process returned non-zero exit code, stopping
```
[log_2019-12-12_15-28-01.txt](https://github.com/Nesvilab/FragPipe/files/3958211/log_2019-12-12_15-28-01.txt)

**Comment by chhh** [comment]
@danielgeiszler 
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at java.util.Arrays$ArrayList.get(Unknown Source)
	at edu.umich.andykong.ptmshepherd.peakpicker.PeakAnnotator.init(PeakAnnotator.java:192)
```

**Comment by danielgeiszler** [comment]
Hi armadillocommander,

It looks like an issue with parameter parsing. This was corrected and will be fixed next release, but in the meantime you should be able to change the PTM-Shepherd variable mods parameter to "None:0" to fix the issue.

Let me know if this doesn't work so we can dig deeper.

**Comment by chhh** [comment]
I guess this can be closed as fixed in dev version, will appear in the next release?

**Comment by danielgeiszler** [comment]
Yes, I need to merge dev and master.
