### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Index 1200 out of bounds for length 1200

### ISSUE THREAD

**Issue by trungttt** [Nesvilab/FragPipe#1631]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-06-10_22-50-50.txt](https://github.com/user-attachments/files/15838087/log_2024-06-10_22-50-50.txt)
[log_2024-06-14_14-20-49.txt](https://github.com/user-attachments/files/15838088/log_2024-06-14_14-20-49.txt)
[log_2024-06-14_14-27-39.txt](https://github.com/user-attachments/files/15838089/log_2024-06-14_14-27-39.txt)
[log_2024-06-14_14-30-28.txt](https://github.com/user-attachments/files/15838090/log_2024-06-14_14-30-28.txt)
**- Describe the issue or question:**
Hi,
I tried to use the "DIA_Speclib_quant_diaPASEF" workflow but keeps getting this error message. Could you please help me take a look.? Thanks so much for your help.
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 1200 out of bounds for length 1200
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at o.b(Unknown Source)
	at diatracer.diaTracerMainClass.a(Unknown Source)
	at diatracer.diaTracerMainClass.a(Unknown Source)
	at diatracer.diaTracerMainClass.<init>(Unknown Source)
	at diatracer.diaTracerMainClass.main(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1200 out of bounds for length 1200
	at o.a(Unknown Source)
	at o.b(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Process 'diaTracer' finished, exit code: 1
Process returned non-zero exit code, stopping

Best,
Trung

**Comment by fcyu** [comment]
Same as https://github.com/Nesvilab/FragPipe/issues/1623

Best,

Fengchao
