### ISSUE TITLE
Process 'MSBooster' finished, exit code: 1, java.lang.NullPointerException

### ISSUE THREAD

**Issue by ciancone94** [Nesvilab/FragPipe#1645]
**- Upload your log file**
[log_2024-06-24_15-10-10.txt](https://github.com/user-attachments/files/15960618/log_2024-06-24_15-10-10.txt)

**- Describe the issue or question:**
Hello,

I seem to be running into an issue when searching some HeLa files where MSBooster will error out. When MSBooster is unchecked, the search runs without error. The issue occurs right after DIA-NN supposedly finishes, so I'm not sure the source of the error. Here is the relevant text snippet:

DIA-NN will use deep learning to predict spectra/RTs/IMs even for peptides carrying modifications which are not recognised by the deep learning predictor. In this scenario, if also generating a spectral library from the DIA data or using the MBR mode, it might or might not be better (depends on the data) to also use the --out-measured-rt option - it's recommended to test it with and without this option
Deep learning predictor will predict 100 fragments

0 files will be processed
[0:00] Loading spectral library Z:\Users\SSBS\MS_Data\QC\HeLa\E240424_HeLa_MSBooster_UpdatedEasyPQP\2\spectraRT.tsv
[0:00] Finding proteotypic peptides (assuming that the list of UniProt ids provided for each peptide is complete)
[0:00] Spectral library loaded: 0 protein isoforms, 0 protein groups and 122923 precursors in 120857 elution groups.
[0:01] Encoding peptides for spectra and RTs prediction
[0:01] Predicting spectra and IMs
[1:04] Predicting RTs
[1:27] Decoding predicted spectra and IMs
[1:29] Decoding RTs
[1:29] Saving the list of predictions to Z:\Users\SSBS\MS_Data\QC\HeLa\E240424_HeLa_MSBooster_UpdatedEasyPQP\2\spectraRT.predicted.bin
Finished
java.lang.NullPointerException: Cannot invoke "java.lang.Float.floatValue()" because the return value of "java.util.HashMap.get(Object)" is null
	at Features.MassCalculator.calcMass(MassCalculator.java:165)
	at Features.MassCalculator.<init>(MassCalculator.java:118)
	at Features.DiannSpeclibReader.<init>(DiannSpeclibReader.java:81)
	at Features.SpectralPredictionMapper.createSpectralPredictionMapper(SpectralPredictionMapper.java:47)
	at Features.PercolatorFormatter.editPin(PercolatorFormatter.java:90)
	at Features.MainClass.main(MainClass.java:647)
Done generating DIA-NN predictions
Model running took 95086 milliseconds
Generating edited pin with following features: [unweightedSpectralEntropy, deltaRTLOESS]
Loading predicted spectra
Process 'MSBooster' finished, exit code: 1
Process returned non-zero exit code, stopping

Cancelling 26 remaining tasks

Any advice would be appreciated. Thank you,

Anthony

P.S. Here is the same search with MSBooster unchecked: 
[log_2024-06-24_14-21-10.txt](https://github.com/user-attachments/files/15960642/log_2024-06-24_14-21-10.txt)

**Comment by fcyu** [comment]
Could you upgrade FragPipe to version 22.0 and try again?

Thanks,

Fengchao

**Comment by ciancone94** [comment]
That solved the issue, thanks!

Anthony
