### ISSUE TITLE
Cannot run program "" in  process WorkspaceCleanInit when running Fragpipe V22 on linux 

### ISSUE THREAD

**Issue by wuwo007** [Nesvilab/FragPipe#1658]
Hi, authors:

 Thank you for your effort in developing such a user-friendly software. Everything runs smoothly when I use Fragpipe V22 on Windows. However, I encountered an error while trying to run Fragpipe version V22 on Linux through the command line. 

The main error message is as follows:
CheckCentroid
java -Xmx845G -cp /mnt/dia_denovo/code/fragpipe_v22/lib/fragpipe-22.0.jar:/mnt/dia_denovo/code/fragpipe_v22/tools/batmass-io-1.33.4.jar com.dmtavt.fragpipe.util.CheckCentroid /mnt/data/msdata_zeng/timsDDA-zeng/ad8_dia/raws/timsTOF_GXJ_H15150_15min_20230731_AD-Plasma_P1-43_A10_Slot1-19_1_3319.d 128
Done in 0.0 s.
Process 'CheckCentroid' finished, exit code: 0
WorkspaceCleanInit [Work dir: /mnt/data/msdata_zeng/timsDDA-zeng/ad8_dia/raws/fragpipe_results]
 workspace --clean --nocheck
2024-07-02 16:13:38,156 ERROR - Error while starting process: WorkspaceCleanInit, stopping
java.io.IOException: Cannot run program "" (in directory "/mnt/data/msdata_zeng/timsDDA-zeng/ad8_dia/raws/fragpipe_results"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.dmtavt.fragpipe.process.ProcessResult.start(ProcessResult.java:55)
	at com.dmtavt.fragpipe.cmd.ProcessBuilderInfo.lambda$toRunnable$0(ProcessBuilderInfo.java:66)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 7 common frames omitted

I suspect that it's because Fragpipe couldn't locate the installation address of Philosopher accurately. Could you please guide me on how to specify the installation address of Philosopher when running Fragpipe in a Linux environment?

My running log is here:

[test_fragpipe.log](https://github.com/user-attachments/files/16064673/test_fragpipe.log)

Thanks

**Comment by fcyu** [comment]
The path `/mnt/dia_denovo/code/fragpipe_v22/lib/fragpipe-22.0.jar` indicates that you moved the FragPipe files after unzip them, because the original directory structure should be something like `<parent dir>/fragpipe/lib/fragpipe-22.0.jar`.

Can you double check 
1. The FragPipe folder is intact.
2. `/mnt/dia_denovo/code/fragpipe_v22/tools/Philosopher/philosopher-v5.1.1` has the executable permission.

Best,

Fengchao

**Comment by wuwo007** [comment]
My problem was solved. It is caused by the permission of /mnt/dia_denovo/code/fragpipe_v22/tools/Philosopher/philosopher-v5.1.1.

Thanks for your help!

Best Regards
