### ISSUE TITLE
'DIA-NN: Propagate information' issue

### ISSUE THREAD

**Issue by Ulianafederico** [Nesvilab/FragPipe#1661]
Hi,
running DIA-NN with the Fragpipe environment I have the following error:
Exception in thread "main" java.lang.NoSuchMethodError: 'com.dmtavt.fragpipe.util.UnimodOboReader$Precursor com.dmtavt.fragpipe.util.UnimodOboReader.convertPrecursor(java.lang.String, java.lang.String, int)'
	at com.dmtavt.fragpipe.tools.diann.Propagation.propagate(Propagation.java:144)
	at com.dmtavt.fragpipe.tools.diann.Propagation.main(Propagation.java:69)

Please see attached the logfile
DIA-NN can still create an output file but I am not sure what is going on. How can I fix this issue?
Thank you for the help!
Federico
[log_2024-07-03_16-08-03.txt](https://github.com/user-attachments/files/16086287/log_2024-07-03_16-08-03.txt)

**Comment by fcyu** [comment]
Similar to https://github.com/Nesvilab/FragPipe/issues/1629#issuecomment-2166504696, you messed up the FragPipe files: 

C:\Software\fragpipe\jre\bin\java.exe -cp C:\Software\fragpipe\tools\batmass-io-1.33.4.jar;C:\Software\fragpipe\lib\fragpipe-**21.1**.jar;C:\Software\fragpipe\lib\fragpipe-**22.0**.jar;C:\Software\fragpipe\lib\fragpipe-**22.0**.jar com.dmtavt.fragpipe.tools.diann.Propagation F:\Federico\EXT_01

Could you re-download FragPipe and unzip it to a new folder, and try again?

Thanks,

Fengchao
