### ISSUE TITLE
Problem running DIA-NN

### ISSUE THREAD

**Issue by Dobrokhotov1989** [Nesvilab/FragPipe#1696]
Hello,

I've tried to run the DIA_SpecLib_Quant workflow and got into an error.
(I've converted RAW file to mzML with a PeakPicker filter as recommended in the tutorial).

Any idea what could be wrong?
Many thanks in advance.

```
Process 'DIA-NN' finished, exit code: 0
DIA-NN [Work dir: C:\Users\workstation_user\Desktop\Oleg\IA206_outputs\DIA\SpLibQuan_test]
C:\Users\workstation_user\Desktop\Oleg\FragPipe-jre-21.1\fragpipe\tools\diann\1.8.2_beta_8\win\dia-nn-plotter.exe diann-output\report.stats.tsv diann-output\report.tsv diann-output\report.pdf
[14500] Failed to execute script dia-nn-plotter
Traceback (most recent call last):
  File "dia-nn-plotter.py", line 347, in <module>
  File "dia-nn-plotter.py", line 179, in report
  File "site-packages\pandas\core\indexes\base.py", line 1520, in droplevel
ValueError: Cannot remove 1 levels from an index with 1 levels: at least one level must be left.
Generating report. Stats, main report, output file: diann-output\report.stats.tsv, diann-output\report.tsv, diann-output\report.pdf
Process 'DIA-NN' finished, exit code: -1
Process returned non-zero exit code, stopping
```

[log_2024-07-27_16-47-54.txt](https://github.com/user-attachments/files/16405133/log_2024-07-27_16-47-54.txt)

**Comment by fcyu** [comment]
There are no quantifiable IDs from your data

```shell
[0:13] Number of protein isoforms identified at 1% FDR: 0 (precursor-level), 0 (protein-level) (inference performed using proteotypic peptides only)
```

Best,

Fengchao
