### ISSUE TITLE
MAc OS X

### ISSUE THREAD

**Issue by stephvanstich** [Nesvilab/FragPipe#171]
Good day, I have run into issue trying to run this program on a mac althought I have seen that it is feasible. my issue is with philosopher. I have been able to make the fasta on a PC we have around but the memory is kindof low so can not use it for the full program. on my mac, I am not sure which of the philosopher exe file I need, it always comes back as an error when I run the pipeline MS fragger. 
philosopher “ can not run the binary file”
Any fix for that?
my mac is really the only one that has memory enough to run this program!

**Comment by anesvi** [comment]
Sorry, bad news. The key components of Philosopher (PeptideProphet etc.) do not run on Mac.

You would have to find a Windows or Linux machine
Speaking of memory, what do you have and what kind of searches are you trying to do? For regular searches, memory requirements are quite low.

Alexey

**Comment by stephvanstich** [comment]
Thanks, i have successfully(almost) run the software on a windows until this pop up. Any idea why and how to fix it?!

Stephanie Olivier-Van Stichelen
Assistant professor
Dpt of Biochemistry, Medical College of Wisconsin

________________________________

**Comment by fcyu** [comment]
That's mainly because PeptideProphet and ProteinProphet used by Philosopher do not compatible with OS X.

**Comment by stephvanstich** [comment]
sorry forgot to attached the issue. here it is:

Exception in thread "main" java.lang.reflect.InvocationTargetException
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at com.simontuffs.onejar.Boot.run(Boot.java:340)
 at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.util.concurrent.ExecutionException:
java.lang.OutOfMemoryError: Java heap space
 at java.util.concurrent.FutureTask.report(Unknown Source)
 at java.util.concurrent.FutureTask.get(Unknown Source)
 at edu.umich.andykong.msfragger.D.a(Unknown Source)
 at edu.umich.andykong.msfragger.F.a(Unknown Source)
 at edu.umich.andykong.msfragger.j.a(Unknown Source)
 at edu.umich.andykong.msfragger.x.<init>(Unknown Source)
 at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
 at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
 ... 6 more
Caused by: java.lang.OutOfMemoryError: Java heap space
 at edu.umich.andykong.msfragger.I.a(Unknown Source)
 at edu.umich.andykong.msfragger.E.call(Unknown Source)
 at java.util.concurrent.FutureTask.run(Unknown Source)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 at java.lang.Thread.run(Unknown Source)
Process 'MsFragger' finished, exit code: 1
Process returned non-zero exit code, stopping
MsFragger
java -cp C:\skyline_fragpipe\FragPipe.exe umich.msfragger.util.FileMove
C:\skyline_fragpipe\2048-Olivier-Van_Stichelen\2048_Porter_191218_Ts016_90min-SynPep-2pmol-z2_01.pepXML
C:\skyline_fragpipe\outputCTD1\2048_Porter_191218_Ts016_90min-SynPep-2pmol-z2_01.pepXML

**Comment by stephvanstich** [comment]
I am on windows now!

**Comment by fcyu** [comment]
Sorry, I thought your question is "Any idea why (Philosopher doesn't support OS X) and how to fix it?!"

For your error, that's because of not enough memory. Can you share your whole log and fragger.params with us?

Thanks,

Fengchao

**Comment by stephvanstich** [comment]
Yes I have find a computer that has enough. here is the parameter for that
run.
