### ISSUE TITLE
Changing temp directory when running FragPipe using Docker

### ISSUE THREAD

**Issue by rjcorb** [Nesvilab/FragPipe#1716]
**- Describe the feature:**

I am receiving the following error when I run Fragpipe within the docker container:

```
1866400382 fragments to be searched in 1 slices (27.81 GB total)
Operating on slice 1 of 1: 
	Fragment index slice generated in 12.32 s
	001. NCI-11plex-1-F1-f10268.mzML has fragtmp, skip
	002. NCI-11plex-1-F10-f10281.mzML has fragtmp, skip
	003. NCI-11plex-1-F11-f10282.mzML has fragtmp, skip
	004. NCI-11plex-1-F12-f10283.mzML has fragtmp, skip
	005. NCI-11plex-1-F2-f10270.mzML has fragtmp, skip
	006. NCI-11plex-1-F3-f10274.mzML has fragtmp, skip
	007. NCI-11plex-1-F4-f10275.mzML has fragtmp, skip
	008. NCI-11plex-1-F5-f10276.mzML 2.3 s
		[progress: 20430/20430 (100%) - 6000 spectra/s] 3.4sjava.nio.file.FileSystemException: /home/rstudio/msfragger/data/projects/harenzaj/proteomics/01CBTTC_PBT_Proteome_HMS_20180626/NCI-11plex-1-F5-f10276.1001519111.0.fragtmp: Invalid argument
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
	at edu.umich.andykong.msfragger.p.a(Unknown Source)
	at edu.umich.andykong.msfragger.p.a(Unknown Source)
	at edu.umich.andykong.msfragger.o.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.c(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping
```

I believe this is due to the mzML files being stored in a mounted sbgenomics project directory, and there being some permission issues after creating the `fragtmp` files. When I copy the mzML files to a local directory and run, I do not receive this error and FragPipe runs successfully. 

I think this issue can be resolved by changing the directory where these tmp files are generated. Is there a way to do this within the docker container? I have found some [previously-submitted issues](https://github.com/Nesvilab/FragPipe/issues/755) related to this question, but I don't think the solutions apply when running in docker. I also noticed that a `temp_location` parameter [was supposedly added to MSFragger in 2018 ](https://github.com/Nesvilab/FragPipe/issues/61), but this doesn't seem to be an acceptable parameter when I add it to my workflow file.

**Comment by fcyu** [comment]
Same issue as https://github.com/Nesvilab/FragPipe/issues/1321

**Comment by rjcorb** [comment]
was a solution ever provided for that issue?

**Comment by fcyu** [comment]
No, that is why that issue is still open.

Best,

Fengchao
