### ISSUE TITLE
out of memory error when running IonQuant

### ISSUE THREAD

**Issue by tobiasko** [Nesvilab/FragPipe#174]
Hi FragPipe team,

```
2020-03-05 15:04:04 [INFO] - Quantifying...
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at ionquant.IonQuant.<init>(Unknown Source)
	at ionquant.IonQuant.main(Unknown Source)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at e.a(Unknown Source)
	at ionquant.IonQuant.a(Unknown Source)
	at ionquant.IonQuant$$Lambda$20/1661081225.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-03-05 15:05:27 [ERROR] - java.lang.OutOfMemoryError: GC overhead limit exceeded
Process 'IonQuant' finished, exit code: 1

Process returned non-zero exit code, stopping
```
How much memory is recommended for IonQuant? Does it scale with the size & number of the tdf_bin? Are memory settings on the FragPipe MSFragger tab also used for IonQuant.

[log-fragpipe-run-at_2020-03-05_15-05-31.log](https://github.com/Nesvilab/FragPipe/files/4294017/log-fragpipe-run-at_2020-03-05_15-05-31.log)

Thx,
Tobi

**Comment by fcyu** [comment]
Hi Tobi,

Thanks for your interest in IonQuant. For a 2h timsTOF run, we recommend at least 20 GB, while you provided 15GB. And yes, the memory settings on the FragPipe is used for IonQuant. 

Best,

Fengchao

**Comment by tobiasko** [comment]
I just realized one of my questions is answered by this:

```
IonQuant [Work dir: D:\Data2San\p3061\Proteomics\TIMSTOF_1\tobiasko_20200229\MSFragger\20200205]
java -Xmx15G -Dbruker.lib.path="D:\Software\MSFragger-2.2\MSFragger-2.2\ext\bruker" -cp "C:\Users\Admin\AppData\Local\Temp\fragpipe\batmass-io-1.17.2.jar;C:\Users\Admin\AppData\Local\Temp\fragpipe\ionquant-1.0.0.jar" ionquant.IonQuant --threads 7 --mztol 10 --imtol 0.05 --rttol 0.4 --minfreq 0.50 --plot 0 --psm D:\Data2San\p3061\Proteomics\TIMSTOF_1\tobiasko_20200229\MSFragger\20200205\400ngLoad_1\psm.tsv --psm D:\Data2San\p3061\Proteomics\TIMSTOF_1\tobiasko_20200229\MSFragger\20200205\300ngLoad_1\psm.tsv --psm D:\Data2San\p3061\Proteomics\TIMSTOF_1\tobiasko_20200229\MSFragger\20200205\200ngLoad_1\psm.tsv --multidir D:\Data2San\p3061\Proteomics\TIMSTOF_1\tobiasko_20200229\MSFragger\20200205 D:\Data2San\p3061\Proteomics\TIMSTOF_1\tobiasko_20200229\3-4-2020_18-31-38_200ngHeLa_incl_iRTs_475_1_Slot1-2.d 200ngLoad_1\3-4-2020_18-31-38_200ngHeLa_incl_iRTs_475_1_Slot1-2.pepXML D:\Data2San\p3061\Proteomics\TIMSTOF_1\tobiasko_20200229\3-4-2020_23-35-32_400ngHeLa_incl_iRTs_477_1_Slot1-2.d 400ngLoad_1\3-4-2020_23-35-32_400ngHeLa_incl_iRTs_477_1_Slot1-2.pepXML D:\Data2San\p3061\Proteomics\TIMSTOF_1\tobiasko_20200229\3-4-2020_21-01-39_300ngHeLa_incl_iRTs_476_1_Slot1-2.d 300ngLoad_1\3-4-2020_21-01-39_300ngHeLa_incl_iRTs_476_1_Slot1-2.pepXML
IonQuant version IonQuant-1.0.0
Batmass-IO version 1.17.2
timsdata library version timsdata-2-4-4
(c) University of Michigan
System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_222, OpenJDK 64-Bit Server VM, 
JVM started with 13 GB memory
```

**Comment by tobiasko** [comment]
So 15 Gig is hard coded in FragPipe?

**Comment by fcyu** [comment]
No, if you set 0 here
![image](https://user-images.githubusercontent.com/6926299/76003503-21205200-5ed6-11ea-8cd4-0518432540da.png)

FragPipe would automatically pick a value based on the free memory on you PC.

**Comment by tobiasko** [comment]
ok. thx!

**Comment by fcyu** [comment]
No problem.
