### ISSUE TITLE
I m facing the issue for java.lang.NegativeArraySizeException: -2147483647 	at e.<init>(Unknown Source) 	at edu.umich.andykong.msfragger.MSFragger.c(Unknown Source) 	at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source) 	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source) Process 'MSFragger' finished, exit code: 1 Process returned non-zero exit code, stopping  as i m conducting close search on 50 files

### ISSUE THREAD

**Issue by mansi123-rana** [Nesvilab/FragPipe#1754]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**

**Comment by mansi123-rana** [comment]
[log_2024-08-27_14-47-30.txt](https://github.com/user-attachments/files/16759858/log_2024-08-27_14-47-30.txt)

**Comment by fcyu** [comment]
Could you share `20150911_QE7_UPLC11_DBJ_SA_HELA_3MG_50FRAC_TiO2_12_unassigned.mzML` and `2024-08-27-decoys-contam-UP000005640_9606.fasta.fas` with us?

Thanks,

Fengchao

**Comment by fcyu** [comment]
No response.

**Comment by dtabb73** [comment]
Hello, I have encountered the same NegativeArraySizeException during the MSFragger mass calibration and parameter optimization set.  This is a TMT6 search, so there's a number of PTMs all going at once.
[log_2024-10-31_11-07-28.txt](https://github.com/user-attachments/files/17586290/log_2024-10-31_11-07-28.txt)
[fragger.params.txt](https://github.com/user-attachments/files/17586291/fragger.params.txt)

I can deactivate mass calibration and parameter optimization, and then the search would finish just fine; I would rather include recalibration for this study, though.

Thanks!
Dave

**Comment by fcyu** [comment]
Hi Dave, 

Could you share your fasta file `2024-10-07-decoys-contam-UP000000625-UP000001940-UP000436333-ASM297520v1.fasta`?

Thanks,

Fengchao

**Comment by dtabb73** [comment]
Yes, of course!
[2024-10-07-decoys-contam-UP000000625-UP000001940-UP000436333-ASM297520v1.zip](https://github.com/user-attachments/files/17588189/2024-10-07-decoys-contam-UP000000625-UP000001940-UP000436333-ASM297520v1.zip)
Thanks,
Dave

**Comment by fcyu** [comment]
Hi Dave,

I couldn't reproduce the error: [msfragger.log](https://github.com/user-attachments/files/17607287/msfragger.log)

I think the error was due to the random IO error. Could you rerun it to see if the error persist?

Thanks,

Fengchao

**Comment by dtabb73** [comment]
Hi, Fengchao.  The problem was perfectly consistent for me; it would _always_ occur.  Based on your success, though, I checked the MD5 sums of the RAWs.  The signature for Celegans_Exp2_07_i2.raw did not match when I redownloaded the RAWs!  I was surprised that it only appeared at the search optimization stage, but that was the cause.  Thank you for proving that these files could be searched correctly.

**Comment by fcyu** [comment]
Hi Dave,

Thank you for the troubleshooting. Glad that you found the reason for the error.

It was from the mass calibration stage where reads more info, such as MS1 scans, than the database search. 

Do you still have the corrupted file? If so, could you share it with me? I can take a look to figure out the exact reason of the error, and (maybe) make MSFragger more robust.

Best,

Fengchao

**Comment by dtabb73** [comment]
I believe this file is one of a few that gives rise to the recalibration problem.
[corrupted-raw-fromPXD008105.zip](https://github.com/user-attachments/files/17619987/corrupted-raw-fromPXD008105.zip)
Weirdly, it's the same number of bytes as the one on the FTP server, but it has a different md5 sum.

Thanks!
Dave

**Comment by fcyu** [comment]
That zip file is empty. I think GitHub won't let you upload a big file. Here is the link to upload the file if you need: https://www.dropbox.com/request/YM63mN1NjAtylgQBIMeO

Best,

Fengchao

**Comment by fcyu** [comment]
Hi Dave,

Thanks for sharing the file. 

I diff two raw files and there is one block of difference

![image](https://github.com/user-attachments/assets/fdf1874c-8920-4238-8fce-22c1fa8d92af)

It seems that the scan 58283 was affected and resulted in unreasonably large values, such as 4.7427375E30, of the fragment MZ and intensity. I have added a filter in MSFragger to remove all peaks with the intensity larger than 1E20. Thus, the next version should be more robust.

Best,

Fengchao

**Comment by dtabb73** [comment]
Thank you for investigating that!
I had hoped to produce an output from these three TMT6 experiments that was compatible with FragPipe Analyst, but I don't think I'm setting the annotations quite right.

Is it immediately obvious to you what I am doing wrong in these annotation files?
[20241007-TMT-Associations_Exp1-annotation.txt](https://github.com/user-attachments/files/17628393/20241007-TMT-Associations_Exp1-annotation.txt)
[20241007-TMT-Associations_Exp2-annotation.txt](https://github.com/user-attachments/files/17628394/20241007-TMT-Associations_Exp2-annotation.txt)
[20241007-TMT-Associations_Exp3-annotation.txt](https://github.com/user-attachments/files/17628395/20241007-TMT-Associations_Exp3-annotation.txt)

Thanks,
Dave

**Comment by fcyu** [comment]
I didn't spot any issues. What error messages did FragPipe-Analyst say?

If it is about FragPipe-Analyst, maybe create a ticket at https://github.com/Nesvilab/FragPipe-Analyst

Best,

Fengchao
