### ISSUE TITLE
Process 'Crystal-C' finished, exit code: 1

### ISSUE THREAD

**Issue by BenSamy2020** [Nesvilab/FragPipe#1773]
Greetings @fcyu,

I am perfroming open search for 294 .raw file using FragPipeGUI. I hit the error of: 

**Unhandled Exception: System.Exception: No open raw file.
   at ThermoFisher.CommonCore.RawFileReader.RawFileAccessBase.ValidateOpenFile()
   at ThermoFisher.CommonCore.RawFileReader.RawFileAccessBase.GetInstrumentCountOfType(Device type)
   at DmtAvt.BatmassIo.Thermo.ISourceFactoryImplThermo.SelectDataSource(SelectSourceRequest request)
   at DmtAvt.BatmassIo.Thermo.BatmassIoThermoServer.ParseIndex(String[] args)
   at DmtAvt.BatmassIo.Thermo.BatmassIoThermoServer.Main(String[] args)
Exception in thread "main" umich.ms.fileio.exceptions.FileParsingException: Could not get ThermoIndex
	at umich.ms.fileio.filetypes.thermo.ThermoRawFile.parseIndex(ThermoRawFile.java:261)
	at umich.ms.fileio.filetypes.thermo.ThermoRawFile.fetchIndex(ThermoRawFile.java:212)
	at umich.ms.fileio.filetypes.thermo.ThermoRawFile.parse(ThermoRawFile.java:642)
	at umich.ms.datatypes.scancollection.impl.ScanCollectionDefault.loadData(ScanCollectionDefault.java:807)
	at umich.ms.datatypes.scancollection.impl.ScanCollectionDefault.loadData(ScanCollectionDefault.java:791)
	at crystalc.p_ReadData.LoadRawFile(p_ReadData.java:196)
	at crystalc.Run.ProcessPepXML(Run.java:84)
	at crystalc.Run.main(Run.java:66)
Process 'Crystal-C' finished, exit code: 1
Process returned non-zero exit code, stopping**

I have attatched my fragpipe workflow file and log file here for your reference. Please do advise me on how to troubleshoot this error?

Regards,
Ben

[log_2024-09-07_09-15-29.txt](https://github.com/user-attachments/files/16914928/log_2024-09-07_09-15-29.txt)
[fragpipe.txt](https://github.com/user-attachments/files/16914943/fragpipe.txt)
[filelist_proteinprophet.txt](https://github.com/user-attachments/files/16914956/filelist_proteinprophet.txt)

**Comment by fcyu** [comment]
You accidently set that file to `DIA` data type, which you shouldn't.

Best,

Fengchao

**Comment by BenSamy2020** [comment]
Greetings @fcyu,

My bad, thank you!
