### ISSUE TITLE
Process 'DIA-NN: Propagate information' finished, exit code: 1

### ISSUE THREAD

**Issue by S-Watanabe0123** [Nesvilab/FragPipe#1815]
Hi,
I have the same error with this #1684. It seems like it was fixed. Please let me know what I should do to avoid this error.
```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.dmtavt.fragpipe.tools.diann.LocalizedPeptide.getBestLocalization(LocalizedPeptide.java:89)
	at com.dmtavt.fragpipe.tools.diann.Propagation.editReport(Propagation.java:290)
	at com.dmtavt.fragpipe.tools.diann.Propagation.propagate(Propagation.java:190)
	at com.dmtavt.fragpipe.tools.diann.Propagation.main(Propagation.java:69)
Process 'DIA-NN: Propagate information' finished, exit code: 1
Process returned non-zero exit code, stopping
```

[log_2024-10-04_07-20-30.txt](https://github.com/user-attachments/files/17258948/log_2024-10-04_07-20-30.txt)

Best,
Shinya

**Comment by fcyu** [comment]
Hi Shinya,

It was actually due to a different reason. Could you share your .d folders with us?

Thanks,

Fengchao

**Comment by Shinya-Watanabe** [comment]
How do you want me to share .d file? I have 6 files, and each of them is about 5GB size.

**Comment by fcyu** [comment]
Yes, please. Here is the link to upload the .d: https://www.dropbox.com/request/TG1snTlVtJNHY1vuzReD

Thanks,

Fengchao

**Comment by Shinya-Watanabe** [comment]
Hi Fengchao,

I just finished uploading all the .d files. 

Thanks,
Shinya

**Comment by fcyu** [comment]
Hi Shinya,

Thank you for sharing the files. 

I think PTMProphet, which is used to perform PTM localization, has issues with C terminal modifications. For example, the localization probability of one peptide is like `GFGFVTYATVE(0.0682)E(0.0748)VD(0.2317)AAMNTTPHKc`. The summation of the probability does not equal to 1, which should.

There are also many weird errors printed by PTMProphet due to the C terminal modifications. Such as

```shell
[ERROR:] Cannot initialize for sequence: nEMNEAPSESGSWSSPEMc[61], unknown mods may exist in spectrum 20240927_SW-KF_S1_sup_Slot2-37_1_8056_diatracer.174820.174820.3
[ERROR:] Cannot initialize for sequence: nIENLLQSLEMc[105], unknown mods may exist in spectrum 20240927_SW-KF_S1_sup_Slot2-37_1_8056_diatracer.183725.183725.2
...
```

After removing the C terminal modifications, it went well [log_2024-10-05_13-21-57.txt](https://github.com/user-attachments/files/17266941/log_2024-10-05_13-21-57.txt)

You could also disable the PTMProphet id you don't need the PTM localization prob.

Best,

Fengchao

**Comment by Shinya-Watanabe** [comment]
Thank you, Fengchao, for figuring this out. 

Protein C-term modification is a positive control to check if we can detect the known modification site. I don't think PTM localization probabilities, but Do I still get PTM localization when PTMProphet is disabled?

Best,
Shinya

**Comment by fcyu** [comment]
If PTMProphet is disabled, you will still have the PTMs localized in the peptides, but there will be no probability to measure the confidence.

Best,

Fengchao

**Comment by Shinya-Watanabe** [comment]
Thanks. It seems like that is the only way to go for now. Is this a bug that PTMProphet would fix at some point?

Best,
Shinya

**Comment by fcyu** [comment]
We need to contact the PTMProphet developer to figure it out.

Best,

Fengchao

**Comment by Shinya-Watanabe** [comment]
Would you be able to report this issue to them? or Could you direct me how to contact them?

Best,
Shinya

**Comment by fcyu** [comment]
I will keep you updated.

Best,

Fengchao

**Comment by Shinya-Watanabe** [comment]
Thank you! I am looking forward to it!

Best,
Shinya

**Comment by fcyu** [comment]
Fixed in https://github.com/Nesvilab/FragPipe/releases/tag/23.0

Best,

Fengchao
