### ISSUE TITLE
DIA_SpecLib_Quant_diaPASEF workflow

### ISSUE THREAD

**Issue by wenbostar** [Nesvilab/FragPipe#1837]
I got the following error when I ran the DIA_SpecLib_Quant_diaPASEF workflow using the dia file N20211212chenc_WOSP00101_DIA_60min_K562_rep1_1_Slot2-37_1_9898.d.zip from PXD041421

```
add_Z_user_amino_acid = 0.0
Selected fragment index width 0.10 Da.
314766972 fragments to be searched in 1 slices (4.69 GB total)
Operating on slice 1 of 1: 
	Fragment index slice generated in 2.54 s
	001. N20211212chenc_WOSP00101_DIA_60min_K562_rep1_1_Slot2-37_1_9898_diatracer.mzML 99.7 s | deisotoping 10.4 s
		[progress: 274921/1760884 (16%) - 27258 spectra/s]​
		[progress: 687981/1760884 (39%) - 34084 spectra/s]​
		[progress: 1107901/1760884 (63%) - 36497 spectra/s]​
		[progress: 1586634/1760884 (90%) - 39249 spectra/s]​
		[progress: 1760884/1760884 (100%) - 39099 spectra/s] 45.0s | postprocessing 5.3 s
***************************FIRST SEARCH DONE IN 2.827 MIN**************************

*********************MASS CALIBRATION AND PARAMETER OPTIMIZATION*******************
-----|---------------|---------------|---------------|---------------
     |  MS1   (Old)  |  MS1   (New)  |  MS2   (Old)  |  MS2   (New)  
-----|---------------|---------------|---------------|---------------
 Run |  Median  MAD  |  Median  MAD  |  Median  MAD  |  Median  MAD  
 001 |  -5.50   6.23 |   0.03   3.88 |  -6.81   5.82 |  -1.01   5.19  
-----|---------------|---------------|---------------|---------------
Finding the optimal parameters:
-------|-------|-------|-------|-------|-------|-------|-------|-------
  MS2  |    5  |    7  |   10  |   15  |   20  |   25  |   30  |   50  
-------|-------|-------|-------|-------|-------|-------|-------|-------
 Count | skip  | skip  | skip  | 124700
Could not load file ...N20211212chenc_WOSP00101_DIA_60min_K562_rep1_1_Slot2-37_1_9898_diatracer.mzBIN_calibrated. The file may be corrupted.
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.__unpackHeader(MZBINFile.java:412)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.__unpackBINHeader(MZBINFile.java:602)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.readMZBINStructure(MZBINFile.java:511)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.readMZBIN(MZBINFile.java:430)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.<init>(MZBINFile.java:79)
	at edu.umich.andykong.msfragger.p.b(Unknown Source)
	at edu.umich.andykong.msfragger.p.a(Unknown Source)
	at edu.umich.andykong.msfragger.o.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.c(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 19 remaining tasks
```

**Comment by fcyu** [comment]
Could you share N20211212chenc_WOSP00101_DIA_60min_K562_rep1_1_Slot2-37_1_9898_diatracer.mzML and the fasta file with me?

Thanks,

Fengchao

**Comment by fcyu** [comment]
Thank you for sharing the data. The error seems to be similar to https://github.com/Nesvilab/FragPipe/issues/840. It should be due to the errors in the file system or IO. I couldn't reproduce it from my end (ignore the other errors at the end of the log. It was due to no DIA files): [log_2024-10-23_23-45-33.txt](https://github.com/user-attachments/files/17500758/log_2024-10-23_23-45-33.txt)

Best,

Fengchao
