### ISSUE TITLE
license issues with conda env when offline

### ISSUE THREAD

**Issue by eaundhe** [Nesvilab/FragPipe#1867]
Hi,

I'm sorry if I missed info on how to get around this issue, but I can't seem to figure out how to use fragpipe in a conda env offline. I have installed fragpipe as a conda env on our cluster and can run fragpipe on our login node with license keys:
fragpipe --headless --msfragger_key <msfragger key> --ionquant_key <ionquant key> 

The problem is that the computational nodes are offline and using the same keys now fails :

> Failed to verify license: Connection timed out
> java.net.ConnectException: Connection timed out
> 	at java.base/sun.nio.ch.Net.connect0(Native Method)
> 	at java.base/sun.nio.ch.Net.connect(Net.java:589)
> 	at java.base/sun.nio.ch.Net.connect(Net.java:578)
> 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)
> 	at java.base/java.net.Socket.connect(Socket.java:752)
> 	at java.base/java.net.Socket.connect(Socket.java:687)
> 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
> 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
> 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
> 	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280)
> 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386)
> 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1310)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1243)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1129)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1058)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1460)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1423)
> 	at c.a(Unknown Source)
> 	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
> Failed to verify license key. Please check your internet connection or report this problem to the developer.
> Error: Invalid MSFragger license key
> 
> Please accept the academic license.
> 
> FragPipe uses tools that are available freely for academic research and educational purposes only.
> 
> Please provide license keys for MSFragger and IonQuant with the --msfragger_key and --ionquant_key flags. By passing these, you verify that you have read the ACADEMIC licenses for the MSFragger and IonQuant tools. You may obtain these keys by agreeing to the terms at http://msfragger-upgrader.nesvilab.org/upgrader/ and https://msfragger.arsci.com/ionquant/.

Again, sorry if there is an easy fix that I've missed. But thank you very much for your help and for making such a great tool.

**Comment by fcyu** [comment]
The conda package requires internet to validate the license. For your case, I suggest you download the standalone version from https://msfragger-upgrader.nesvilab.org/upgrader/ (MSFragger) and https://msfragger-upgrader.nesvilab.org/ionquant/ (IonQuant).

Best,

Fengchao

**Comment by eaundhe** [comment]
Hi Fengchao,

Thanks for the quick reply. 

I've tried running fragpipe and using a downloaded standalone version of MSFragger but keep getting the error that MSFragger is not a MSFragger jar file. I don't get any other error details but MSFragger is in the tools folder and seems to work on its own.

> fragpipe --headless --config-tools-folder software/fragpipe/tools/ --config-diann $EBROOTDIAMINNN/diann-1.8.1 --config-python  $EBROOTPYTHON//bin/python  --workflow workflow_test.workflow --manifest test.fp-manifest --workdir test
> 
> 2024-11-12 07:02:33,139 ERROR - Not a MSFragger jar.
 

> ls -hl software/fragpipe/tools/MSFragger-4.1/
> total 54M
> -rw-rw-r-- 1   10K closed_fragger.params
> drwxrwsr-x 4     2 ext
> -rwxrwxr-x 1   54M MSFragger-4.1.jar
> -rw-rw-r-- 1   67K MSFragger-LICENSE-3RD-PARTY.txt
> -rw-rw-r-- 1   68K MSFragger-LICENSE.pdf
> -rw-rw-r-- 1   13K Nglyco-HCD_fragger.params
> -rw-rw-r-- 1   10K nonspecific_fragger.params
> -rw-rw-r-- 1   10K open_fragger.params
> -rw-rw-r-- 1  106K RawFileRdr_License_Agreement_RevA.pdf
> -rw-rw-r-- 1   342 redist.txt
> -rw-rw-r-- 1   41K THIRD-PARTY-LICENSE-README.txt> 


> java -jar software/fragpipe/tools/MSFragger-4.1/MSFragger-4.1.jar
> MSFragger version MSFragger-4.1
> Batmass-IO version 1.33.4
> timsdata library version timsdata-2-21-0-4
> (c) University of Michigan
> RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
> timdTOF .d reading tool. Copyright (c) 2022 by Bruker Daltonics GmbH & Co. KG. All rights reserved.
> System OS: Linux, Architecture: amd64
> Java Info: 17.0.4, OpenJDK 64-Bit Server VM, Eclipse Adoptium
> Usage:
> 	To perform a search either use a parameter file:
> 		1) java -jar MSFragger.jar <parameter file> <list of mzML/mzXML/MGF/RAW/.d files>
> 	Or specify options on the command line:
> 		2) java -jar MSFragger.jar <options> <list of mzML/mzXML/MGF/RAW/.d files>
> To generate default parameter files use --config closed/open/nonspecific/glyco. E.g. "java -jar MSFragger.jar --config closed"
> To list all the available options, run with --help or -h flag.

**Comment by eaundhe** [comment]
Just wanted to add I get the same error when installing/updating using the GUI. It's just MSFragger — Ionquant seems to work fine.

**Comment by eaundhe** [comment]
Thanks for the quick reply, once again! 

I've tried that a few times, but tried it again this time also unzipping locally and uploading the uncompressed folder. I also tried using the GUI to download directly. I get no errors until "Not a MSFragger jar". Also, it works fine on its own.

Is there a path somewhere I can check (I couldn't find out where...)? Or force it to use the MSFragger jar file even if it doesn't say it is the correct file somehow?

Sorry, I seem to be the only one with this error. But thanks for your help!

**Comment by eaundhe** [comment]
Sorry for the delay. I removed and reinstalled fragpipe. Here's a screenshot just after downloading/installing using the GUI.

![Screenshot 2024-11-19 at 07 53 52](https://github.com/user-attachments/assets/0e8d3745-4dec-4b92-987d-97057c20b244)

**Comment by fcyu** [comment]
Something is still wrong with the MSFragger

![image](https://github.com/user-attachments/assets/0f1981d0-90ea-4dbf-a496-d5386b92e802)


Best,

Fengchao

**Comment by eaundhe** [comment]
Yes. Same error regardless. This time I downloaded and installed through the fragpipe GUI. Maybe we'll just have to work around it by running MSFragger on its own. 

Cheers,
Eivind

**Comment by fcyu** [comment]
Hi Eivind,

I have no clue about this one now. I will make FragPipe more robust when checking the MSFragger version in the next release.

Let me know if you would like to try the pre-released version.

Best,

Fengchao

**Comment by eaundhe** [comment]
Hi Fengchao,

That would be great, thank you! Sorry for giving you grief with this.  

Cheers,
Eivind

**Comment by fcyu** [comment]
Hi Eivind,

Could you try this version: https://www.dropbox.com/t/okndWrC7b7laEYyn. If there still an issue, it will print a stack trace message in both GUI or headless mode. If so, please send the message to me.

Thanks,

Fengchao

**Comment by eaundhe** [comment]
Hi Fengchao, 

Thanks! Still the same issue. If it's of use I'm using Java 17.0.4. The error messages are below. 

Thanks for all your help!

Cheers,
Eivind

INSTALLING VIA GUI
java.io.IOException: Bad address
	at java.base/sun.nio.ch.FileDispatcherImpl.pread0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.pread(FileDispatcherImpl.java:54)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:328)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:296)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:273)
	at java.base/sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:839)
	at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:824)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1241)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1236)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1553)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:179)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:528)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:400)
	at com.dmtavt.fragpipe.tabs.TabConfig.validateJarContents(TabConfig.java:704)
	at com.dmtavt.fragpipe.tabs.TabConfig.on(TabConfig.java:607)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
	at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:454)
	at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:421)
	at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:394)
	at org.greenrobot.eventbus.EventBus.post(EventBus.java:275)
	at com.dmtavt.fragpipe.api.Bus.post(Bus.java:76)
	at com.dmtavt.fragpipe.tabs.TabConfig.lambda$actionToolsDownload$10(TabConfig.java:500)
	at java.base/java.lang.Thread.run(Thread.java:833)


INSTALLED SEPARATELY AND UPDATED TOOLS FOLDER
java.io.IOException: Bad address
	at java.base/sun.nio.ch.FileDispatcherImpl.pread0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.pread(FileDispatcherImpl.java:54)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:328)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:296)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:273)
	at java.base/sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:839)
	at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:824)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1241)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1236)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1553)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:179)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:528)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:400)
	at com.dmtavt.fragpipe.tabs.TabConfig.validateJarContents(TabConfig.java:704)
	at com.dmtavt.fragpipe.tabs.TabConfig.on(TabConfig.java:607)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
	at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:454)
	at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:421)
	at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:394)
	at org.greenrobot.eventbus.EventBus.post(EventBus.java:275)
	at com.dmtavt.fragpipe.api.Bus.post(Bus.java:76)
	at com.dmtavt.fragpipe.tabs.TabConfig.lambda$createPanelTools$4(TabConfig.java:300)
	at java.desktop/javax.swing.JTextField.fireActionPerformed(JTextField.java:525)
	at java.desktop/javax.swing.JTextField.postActionEvent(JTextField.java:740)
	at java.desktop/javax.swing.JTextField$NotifyAction.actionPerformed(JTextField.java:856)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
	at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2947)
	at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:2995)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2909)
	at java.desktop/java.awt.Component.processEvent(Component.java:6403)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1952)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:883)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1150)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1020)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:848)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4882)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by eaundhe** [comment]
That's weird. But at least we're the only ones having this issue, which is good I guess. 

I'll let you know if I find a fix. Thanks for all your help and support! Very much appreciated even if it remains a bit of a mystery.

Cheers,
Eivind
