### ISSUE TITLE
MSFragger error:  too many peptides were generated, Could not continue. The limit is approximately 2 billion peptides.

### ISSUE THREAD

**Issue by SamueldelaCamaraFuentes** [Nesvilab/FragPipe#1874]
Dear FragPipe team,

With my version:

- FragPipe v22.0
- MSFragger 4.1
- Python 3.9.13

I am trying to perform a DDA search with a database whose size is  9.9 GB (34 millions of sequences, decoys included at 50%) and I encounter the following error:

~~~~~~~~~~~~~~~~~~~~
Too many peptides were generated 2951142583! Could not continue. The limit is approximately 2 billion peptides. 
If running using FragPipe: in MSFragger tab, use “Split database” option (requires python; see Configuration page of FragPipe). Set “Split database” parameter to 2. If the program continues to crash, gradually increase the “Split database” value (e.g. to 4, then to 8, etc.) until the program runs successfully.
Alternatively, or in combination with the “Split database” option, consider the following options: reduce the number of variable modifications specified; reduce the range of allowed peptide length (from 7-50 to e.g. 7-35).
Traceback (most recent call last):
  File "C:\FragPipe-jre-22.0\fragpipe\tools\msfragger_pep_split.py", line 631, in <module>
    main()
  File "C:\FragPipe-jre-22.0\fragpipe\tools\msfragger_pep_split.py", line 617, in main
    run_msfragger(calibrate_mzBIN if calibrate_mass in [1, 2] else infiles_name)
  File "C:\FragPipe-jre-22.0\fragpipe\tools\msfragger_pep_split.py", line 133, in run_msfragger
    subprocess.run(list(map(os.fspath, cmd)), cwd=cwd, check=True)
  File "C:\Users\userpd\anaconda3\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\FragPipe-jre-22.0\\fragpipe\\jre\\bin\\java.exe', '-jar', '-Dfile.encoding=UTF-8', '-Xmx200G', 'C:\\FragPipe-jre-22.0\\fragpipe\\tools\\MSFragger-4.1\\MSFragger-4.1.jar', 'fragger.params', 'G:\\24_138_Manuel_Ferrer\\prueba_db_manuel\\24-138_100.d', '--partial', '0']' returned non-zero exit status 1.
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

Cancelling 13 remaining tasks

~~~~~~~~~~~~~~~~~~~~

What should I do? I have already tried to increase the "split database" parameter, reduced the number of variable modifications and the range of alowed peptide length and the same caption is always displayed.

Here I attach my log:

[log_2024-11-14_14-39-59.txt](https://github.com/user-attachments/files/17750432/log_2024-11-14_14-39-59.txt)

Thank you so much for your help,

Samuel

**Comment by fcyu** [comment]
Increase the number of database splitting until there are enough memory to finish the search.

Best,

Fengchao
