### ISSUE TITLE
Error on EasyPQP

### ISSUE THREAD

**Issue by LKittinun** [Nesvilab/FragPipe#1876]
**- Upload your log file**
[log.txt](https://github.com/user-attachments/files/17770847/log.txt)

**- Describe the issue or question:**
I tried to analyze the DIA file with speclib quant workflow and got an error on the validation part.
![image](https://github.com/user-attachments/assets/c0d479ab-796c-4325-a08b-f218830cb54c)
 At first, I thought it might be a file problem, but these files can be run successfully on native DIA-NN, so I don't know what the cause is. Please help me with the issue.

Regards,
Pete

**Comment by fcyu** [comment]
Another Python-related error:

```
2024-11-15 13:53:11 - Info: 56422 redundant PSMs identified after filtering with D:\Fragpipe\FragPipe-22.0\result\cell_lines\psm.tsv and D:\Fragpipe\FragPipe-22.0\result\cell_lines\peptide.tsv
2024-11-15 13:53:13 -                          base_name  modified_peptide
0  PMF_BR1_stagetip_20241114005419             30372
1                   PMF_BR1_ziptip             26050
2024-11-15 13:53:13 - Info: easypqp_rt_alignment_PMF_BR1_stagetip_20241114005419; Peptide overlap between run and reference: 30372.
XXX lineno: 44, opcode: 0
XXX lineno: 234, opcode: 0
XXX lineno: 161, opcode: 0
Exception in thread ExecutorManagerThread:
Traceback (most recent call last):
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\psutil\_pswindows.py", line 727, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\psutil\_pswindows.py", line 915, in kill
    return cext.proc_kill(self.pid)
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\externals\loky\process_executor.py", line 599, in run
    self.terminate_broken(bpe)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\externals\loky\process_executor.py", line 803, in terminate_broken
    self.kill_workers(reason="broken executor")
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\externals\loky\process_executor.py", line 836, in kill_workers
    kill_process_tree(p)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\externals\loky\backend\utils.py", line 19, in kill_process_tree
    _kill_process_tree_with_psutil(process)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\externals\loky\backend\utils.py", line 43, in _kill_process_tree_with_psutil
    descendant.kill()
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\psutil\__init__.py", line 1313, in kill
    self._proc.kill()
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\psutil\_pswindows.py", line 729, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=11388)
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\externals\loky\process_executor.py", line 426, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\multiprocessing\queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\easypqp\library.py", line 5, in <module>
    import matplotlib
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\__init__.py", line 184, in <module>
    from packaging.version import parse as parse_version
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\packaging\version.py", line 159, in <module>
    class Version(_BaseVersion):
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\packaging\version.py", line 183, in Version
    _regex = re.compile(r"^\s*" + VERSION_PATTERN + r"\s*$", re.VERBOSE | re.IGNORECASE)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\re.py", line 252, in compile
    return _compile(pattern, flags)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\sre_parse.py", line 841, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\sre_parse.py", line 841, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\sre_parse.py", line 512, in _parse
    sourceget()
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\sre_parse.py", line 257, in get
    self.__next()
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\sre_parse.py", line 234, in __next
    def __next(self):
SystemError: unknown opcode
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\Scripts\easypqp.exe\__main__.py", line 7, in <module>
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1719, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\easypqp\main.py", line 205, in library
    generate(infiles, outfile, psmtsv, peptidetsv, perform_rt_calibration, rt_referencefile, rt_reference_run_path, rt_filter, perform_im_calibration, im_referencefile, im_reference_run_path, im_filter, psm_fdr_threshold, peptide_fdr_threshold, protein_fdr_threshold, rt_lowess_fraction, rt_psm_fdr_threshold, im_lowess_fraction, im_psm_fdr_threshold, pi0_lambda, peptide_plot_path, protein_plot_path, min_peptides, proteotypic, consensus, nofdr)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\easypqp\library.py", line 392, in generate
    aligned_runs = aligned_runs.groupby('base_name', as_index=False, group_keys=False).apply(lambda x: lowess(x, rt_reference_run, 'retention_time', 'irt', rt_lowess_frac, rt_psm_fdr_threshold, min_peptides, "easypqp_rt_alignment_" + x.name, main_path))
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\groupby\groupby.py", line 1770, in apply
    result = self._python_apply_general(f, self._selected_obj)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\groupby\groupby.py", line 1819, in _python_apply_general
    values, mutated = self.grouper.apply_groupwise(f, data, self.axis)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\groupby\ops.py", line 911, in apply_groupwise
    res = f(group)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\easypqp\library.py", line 392, in <lambda>
    aligned_runs = aligned_runs.groupby('base_name', as_index=False, group_keys=False).apply(lambda x: lowess(x, rt_reference_run, 'retention_time', 'irt', rt_lowess_frac, rt_psm_fdr_threshold, min_peptides, "easypqp_rt_alignment_" + x.name, main_path))
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\easypqp\library.py", line 252, in lowess
    run[ycol] = lowess_iso_predictor(filename, dfm[xcol].to_numpy(), dfm[ycol].to_numpy(), run[xcol].to_numpy()) \
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\easypqp\library.py", line 227, in lowess_iso_predictor
    gsc.fit(x.reshape(-1, 1), y)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_search.py", line 898, in fit
    self._run_search(evaluate_candidates)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_search.py", line 1422, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_search.py", line 845, in evaluate_candidates
    out = parallel(
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\parallel.py", line 65, in __call__
    return super().__call__(iterable_with_config)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\parallel.py", line 1952, in __call__
    return output if self.return_generator else list(output)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\parallel.py", line 1595, in _get_outputs
    yield from self._retrieve()
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\parallel.py", line 1699, in _retrieve
    self._raise_error_fast()
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\parallel.py", line 1734, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\parallel.py", line 736, in get_result
    return self._return_or_raise()
  File "C:\Users\OE480PPC\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\parallel.py", line 754, in _return_or_raise
    raise self._result
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
```

Hopefully, Guo Ci @guoci can take a look.

Thanks,

Fengchao

**Comment by LKittinun** [comment]
Thank you for your help. Tried python 3.11 (both miniconda and normal installation) but still found errors.
[log_2024-11-16_14-01-24.txt](https://github.com/user-attachments/files/17783828/log_2024-11-16_14-01-24.txt)
![image](https://github.com/user-attachments/assets/c6589f03-1402-43c5-8e76-e07b34a956ba)

**Comment by guoci** [comment]
@LKittinun Can you try this on another computer? I have never seen this error before.

**Comment by LKittinun** [comment]
It seems like problems persist because I continue running from the last steps. After I re-analyzed at the beginning the issue was resolved. So, It should be the Python version issue. Thank you very much.

Regards,
Pete
