### ISSUE TITLE
MS-Fragger DIA - DIAN-NN Quant failure to write MSstats output file

### ISSUE THREAD

**Issue by rnirujogi** [Nesvilab/FragPipe#1935]
Dear Fengchao,

I hope all is well. Could you direct me to fixing the issue with failure to write MSStats output file for DIA-PTM data set. The error log is pasted here. Let me know if you require more information and greatly appreciated your support.

Process 'DIA-NN' finished, exit code: 0
DIA-NN [Work dir: C:\Raja\MSF_PTM-Project\DN_LT-Phospho\Report_01]
C:\Raja\Software\FragPipe-jre-22.0\fragpipe\tools\diann\1.8.2_beta_8\win\dia-nn-plotter.exe diann-output\report.stats.tsv diann-output\report.tsv diann-output\report.pdf
Generating report. Stats, main report, output file: diann-output\report.stats.tsv, diann-output\report.tsv, diann-output\report.pdf
Process 'DIA-NN' finished, exit code: 0
DIA-NN: Propagate information [Work dir: C:\Raja\MSF_PTM-Project\DN_LT-Phospho\Report_01\diann-output]
C:\Raja\Software\FragPipe-jre-22.0\fragpipe\jre\bin\java.exe -cp C:\Raja\Software\FragPipe-jre-22.0\fragpipe\tools\batmass-io-1.33.4.jar;C:\Raja\Software\FragPipe-jre-22.0\fragpipe\lib\fragpipe-22.0.jar;C:\Raja\Software\FragPipe-jre-22.0\fragpipe\lib\fragpipe-22.0.jar com.dmtavt.fragpipe.tools.diann.Propagation C:\Raja\MSF_PTM-Project\DN_LT-Phospho\Report_01
java.io.IOException: The process cannot access the file because another process has locked a portion of the file
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.write(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.write(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.write(Unknown Source)
	at java.base/sun.nio.ch.FileChannelImpl.write(Unknown Source)
	at java.base/java.nio.channels.Channels.writeFullyImpl(Unknown Source)
	at java.base/java.nio.channels.Channels.writeFully(Unknown Source)
	at java.base/java.nio.channels.Channels$1.write(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.write(Unknown Source)
	at java.base/java.io.OutputStreamWriter.write(Unknown Source)
	at java.base/java.io.BufferedWriter.flushBuffer(Unknown Source)
	at java.base/java.io.BufferedWriter.write(Unknown Source)
	at java.base/java.io.Writer.write(Unknown Source)
	at com.dmtavt.fragpipe.tools.diann.Propagation.editReport(Propagation.java:260)
	at com.dmtavt.fragpipe.tools.diann.Propagation.propagate(Propagation.java:190)
	at com.dmtavt.fragpipe.tools.diann.Propagation.main(Propagation.java:69)
Process 'DIA-NN: Propagate information' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 2 remaining tasks

Thanks and regards,
Raja

**Comment by fcyu** [comment]
> java.io.IOException: The process cannot access the file because another process has locked a portion of the file

Please check your file system and antivirus software to make sure that the file is not locked by other programs.

Best,

Fengchao
