### ISSUE TITLE
Not possible to arrive at the end of DIA_SpecLib_Quant workflow. Cancelling 2 remaining tasks 

### ISSUE THREAD

**Issue by POde97** [Nesvilab/FragPipe#1959]
Hi Fragpipe team. 

I'm running DIA_SpecLib_Quant from command line and I get the following error at the end of the run that stop the job with still 2 task to finish. Can you help me in understanding what is going wrong with that? 

Many thanks 

Below the output 

[51:17] File #12/12
[51:17] Loading run /mnt/shared/data/paolo/MSdata/MSpilot2/mzMLdatapilot2/20241125_Astral_AUR325075C18TS_DIA_30SPD_Project_980_FeNTA_s01.mzML
[56:14] 9661 library precursors are potentially detectable
[56:14] Processing...
[56:15] RT window set to 0.799719
[56:15] Recommended MS1 mass accuracy setting: 5.35911 ppm
[56:16] Removing low confidence identifications
[56:16] Removing interfering precursors
[56:16] Training neural networks: 9499 targets, 7508 decoys
[56:17] Number of IDs at 0.01 FDR: 8211
[56:17] Calculating protein q-values
[56:17] Number of protein isoforms identified at 1% FDR: 1344 (precursor-level), 1325 (protein-level) (inference performed using proteotypic peptides only)
[56:17] Quantification

[56:18] Cross-run analysis
[56:18] Reading quantification information: 12 files
[56:18] Quantifying peptides
[56:20] Quantifying proteins
[56:20] Calculating q-values for protein and gene groups
[56:20] Calculating global q-values for protein and gene groups
[56:20] Writing report
[56:25] Report saved to diann-output/report.tsv.
[56:25] Saving precursor levels matrix
[56:25] Precursor levels matrix (1% precursor and protein group FDR) saved to diann-output/report.pr_matrix.tsv.
[56:25] Saving protein group levels matrix
[56:25] Protein group levels matrix (1% precursor FDR and protein group FDR) saved to diann-output/report.pg_matrix.tsv.
[56:25] Saving gene group levels matrix
[56:26] Gene groups levels matrix (1% precursor FDR and protein group FDR) saved to diann-output/report.gg_matrix.tsv.
[56:26] Saving unique genes levels matrix
[56:26] Unique genes levels matrix (1% precursor FDR and protein group FDR) saved to diann-output/report.unique_genes_matrix.tsv.
[56:26] Stats report saved to diann-output/report.stats.tsv
[56:26] Log saved to diann-output/report.log.txt
Finished

Process 'DIA-NN' finished, exit code: 0
DIA-NN: Propagate information [Work dir: /home/p.odello/MSDataAnalysis/DIAquant/diann-output]
java -cp /fragpipe_bin/fragPipe-22.0/fragpipe/tools/batmass-io-1.33.4.jar:/fragpipe_bin/fragPipe-22.0/fragpipe/lib/fragpipe-22.0.jar:/fragpipe_bin/fragPipe-22.0/fragpipe/lib/fragpipe-22.0.jar com.dmtavt.fragpipe.tools.diann.Propagation /home/p.odello/MSDataAnalysis/DIAquant
2024-12-29 22:39:43,070 ERROR - Error initializing fragpipe locations
java.nio.file.FileSystemException: /fragpipe_bin/fragPipe-22.0/fragpipe/lib/../cache: Read-only file system
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397)
        at java.base/java.nio.file.Files.createDirectory(Files.java:700)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
        at java.base/java.nio.file.Files.createDirectories(Files.java:793)
        at com.github.chhh.utils.PathUtils.createDirs(PathUtils.java:76)
        at com.dmtavt.fragpipe.FragpipeLocations$Holder.<clinit>(FragpipeLocations.java:121)
        at com.dmtavt.fragpipe.FragpipeLocations.get(FragpipeLocations.java:183)
        at com.dmtavt.fragpipe.FragpipeLocations.tryLocateTools(FragpipeLocations.java:299)
        at com.dmtavt.fragpipe.FragpipeLocations.checkToolsMissing(FragpipeLocations.java:327)
        at com.dmtavt.fragpipe.cmd.ToolingUtils.getUnimodOboPath(ToolingUtils.java:66)
        at com.dmtavt.fragpipe.tools.diann.Propagation.<init>(Propagation.java:79)
        at com.dmtavt.fragpipe.tools.diann.Propagation.main(Propagation.java:68)
java.lang.ArrayIndexOutOfBoundsException: Index 35 out of bounds for length 34
        at com.dmtavt.fragpipe.tools.diann.Propagation.propagate(Propagation.java:169)
        at com.dmtavt.fragpipe.tools.diann.Propagation.main(Propagation.java:69)
Process 'DIA-NN: Propagate information' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 2 remaining tasks

**Comment by fcyu** [comment]
It is similar to https://github.com/Nesvilab/FragPipe/issues/1885 and it is a know bug. It won't affect the result much and will be fixed in the next release.

Best,

Fengchao
