### ISSUE TITLE
MSFragger - ValueError: too many values to unpack 

### ISSUE THREAD

**Issue by Evan-Raymond** [Nesvilab/FragPipe#1960]
Hi there, 

 I've been getting the following error code from MSFragger while (I assume) its writing pepxml to disk, but I don't know enough about what the software is doing at this point to debug the error.  Do you have any ideas? 

Cheers,
 Evan

Writing: CP_184	spectrum: 98304
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\Core i7 PC\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "D:\fragpipe\tools\msfragger_pep_split.py", line 370, in write_pepxml
    pep_to_prot = get_pep_to_prot_mapping(infile)
  File "D:\fragpipe\tools\msfragger_pep_split.py", line 341, in get_pep_to_prot_mapping
    pep, prot = make_dict_entry(sh)
  File "D:\fragpipe\tools\msfragger_pep_split.py", line 336, in make_dict_entry
    key, = sh_peptide.findall(sh)
ValueError: too many values to unpack (expected 1)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\fragpipe\tools\msfragger_pep_split.py", line 631, in <module>
    main()
  File "D:\fragpipe\tools\msfragger_pep_split.py", line 623, in main
    combine_results()
  File "D:\fragpipe\tools\msfragger_pep_split.py", line 477, in combine_results
    e.result()
  File "C:\Users\Core i7 PC\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 439, in result
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

[log_2024-12-30_22-45-25.zip](https://github.com/user-attachments/files/18273842/log_2024-12-30_22-45-25.zip)

**Comment by Evan-Raymond** [comment]
Hi guoci,

Thanks for getting back to me.
The  split_peptide_index_tempdir file is way too big to upload, even when compressed its almost 14GB. Can I send you part of the file?

Cheers,
   Evan

**Comment by guoci** [comment]
yes, can just send the pepxml files

**Comment by Evan-Raymond** [comment]
Hi @guoci 

I've uploaded one of the smaller pepxml files I could find, as most are over 25 MB compressed. Please bear in mind that this is only one of 275 pepxml files split over 5 folders in the split_peptide_index_tempdir and MSFragger seemed fine with most of them, so I don't know if its a specific file thats the problem. 

Cheers,
  Evan

[CP_484.zip](https://github.com/user-attachments/files/18286984/CP_484.zip)

**Comment by Evan-Raymond** [comment]
Hi @guoci 

Any updates on the above issue?

Cheers,
  Evan
