### ISSUE TITLE
LFQ failed when runing FragPipe 13.

### ISSUE THREAD

**Issue by andyzim111** [Nesvilab/FragPipe#201]
I used FragPipe 13 to analyze two mzML files and wanted to try LFQ functions, and the error happened. 
The log file is attached. 
[log_2020-07-02_19-46-48.txt](https://github.com/Nesvilab/FragPipe/files/4864026/log_2020-07-02_19-46-48.txt)

**Comment by fcyu** [comment]
Thanks for your interest in our tools. We have pushed updates to FragPipe 13.0. After you restart FragPipe, you will see a dialog like

![image](https://user-images.githubusercontent.com/6926299/86366865-5309b100-bc49-11ea-843c-efe953d1e2e6.png)

You need to click "OK". Then, FragPipe will download the updates.

Best,

Fengchao

**Comment by andyzim111** [comment]
@fcyu , I have restarted FragPipe 13 several times, and nothing happened. No update dialog appeared.

**Comment by chhh** [comment]
@andyzim111 
1) Please check your FragPipe installation folder (where you unpacked the zip file). Do if you have `udpdates` subfolder there? If yes, then what's in it. 
2) Is the computer where that happens connected to internet?

**Comment by andyzim111** [comment]
1.There is no subfolder named updates in FragPipe installation folder.
2. The computer is connected to the internet.

**Comment by andyzim111** [comment]
@chhh, the message showed in the console.

08:46:32 WARN : Something happened while checking for MSFragger updates
java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:1198)
	at com.dmtavt.fragpipe.tools.fragger.MsfraggerVersionFetcherServer.fetchVersionResponse(MsfraggerVersionFetcherServer.java:103)
	at com.dmtavt.fragpipe.tools.fragger.MsfraggerVersionFetcherServer.fetchVersion(MsfraggerVersionFetcherServer.java:62)
	at com.dmtavt.fragpipe.tools.fragger.Msfragger.lambda$checkUpdates$0(Msfragger.java:68)
	at java.lang.Thread.run(Unknown Source)

**Comment by chhh** [comment]
Ok, so FP can't connect to github. It's either your computer's firewall blocking it or your organization firewall or something like that. No way to tell what's causing the connection to fail, but it's not caused by FP itself.

You can update manually though. Like really really manualy:
- Go to: https://github.com/Nesvilab/FragPipe/tree/updates/MSFragger-GUI/updates
- Download `ionquant-132.zip` there, save it to the root folder of your FP install
- Unpack the zip (using `extract here` option of your archiver, so that it maintains the folder structure)
- You should now have `<FP-install>/tools/ionquant-1.3.2.jar` file
- Just run FP as you would normally. You it should use the updated version.

**Comment by andyzim111** [comment]
@chhh, I have updated FP manually. Now LFQ works. Thanks.

**Comment by fcyu** [comment]
Put it to [wiki](https://github.com/Nesvilab/MSFragger/wiki/Frequently-Asked-Questions).
