### ISSUE TITLE
Bruker native libraries not found

### ISSUE THREAD

**Issue by jkelabora** [Nesvilab/FragPipe#211]
**Describe the bug**

After following the [setup instructions](https://msfragger.nesvilab.org/tutorial_setup_fragpipe.html) on a clean Windows machine i received the following error when processing a single `.d` folder. I've replicated the issue on a separate Windows machine.

----------------------
Folder structure:
![Screen Shot 2020-07-24 at 10 19 34 am](https://user-images.githubusercontent.com/57252/88350766-6ff05a80-cd97-11ea-9eb6-83d04934941b.png)
![Screen Shot 2020-07-24 at 10 19 56 am](https://user-images.githubusercontent.com/57252/88350764-6ebf2d80-cd97-11ea-98bf-f3952b77bd51.png)

Full log:
[log_2020-07-22_05-56-41.txt](https://github.com/Nesvilab/FragPipe/files/4969608/log_2020-07-22_05-56-41.txt)

Stack trace:
```Checking C:\Users\Administrator\Desktop\190719_Hela_Ecoli_1to1_01_Slot1-1_1_1926.d...
[main] WARN umich.ms.fileio.filetypes.bruker.Timsdata - JNA could not load native Bruker library
java.lang.UnsatisfiedLinkError: Unable to load library 'timsdata-2-4-4':
The specified module could not be found.

The specified module could not be found.

The specified module could not be found.

Native library (win32-x86-64/timsdata-2-4-4.dll) not found in resource path (C:\Users\Administrator\Desktop\MSFragger-3.0\MSFragger-3.0.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
	at com.sun.jna.Library$Handler.<init>(Library.java:192)
	at com.sun.jna.Native.load(Native.java:596)
	at com.sun.jna.Native.load(Native.java:570)
	at umich.ms.fileio.filetypes.bruker.Timsdata$Instance.<clinit>(Timsdata.java:170)
	at umich.ms.fileio.filetypes.bruker.Timsdata.getLoadedLibName(Timsdata.java:190)
	at umich.ms.fileio.filetypes.bruker.BrukerTdfFileBase.<init>(BrukerTdfFileBase.java:55)
	at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
	Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 16 more
	Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 16 more
	Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:265)
		... 16 more
	Suppressed: java.io.IOException: Native library (win32-x86-64/timsdata-2-4-4.dll) not found in resource path (C:\Users\Administrator\Desktop\MSFragger-3.0\MSFragger-3.0.jar)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1095)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:276)
		... 16 more
Failed in checking C:\Users\Administrator\Desktop\190719_Hela_Ecoli_1to1_01_Slot1-1_1_1926.d
Bruker native libraries not found
Process 'MsFragger' finished, exit code: 1
Process returned non-zero exit code, stoppingMsFragger
```

**Comment by fcyu** [comment]
Thanks for your interest in out tools. Can you install [Visual C++ Redistributable for Visual Studio 2017](https://aka.ms/vs/16/release/VC_redist.x64.exe) and try again?

Thanks,

Fengchao

**Comment by jkelabora** [comment]
Worked! Thanks for such a quick response - much appreciated🥇
