### ISSUE TITLE
Consistent error on TimsTOF files with split database

### ISSUE THREAD

**Issue by JRKrieger37** [Nesvilab/FragPipe#227]
Hi - 
I've tried running many files and just 1 file and I continuously see the same error. I've tried re-installing python but I get the same error.

concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\kjonathan\Anaconda3\lib\concurrent\futures\process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\fragpipe\tools\msfragger_pep_split.py", line 315, in write_pepxml
    pepxml_header, = set([get_pepxml_header(tempdir_part / (infile.stem + '.' + output_file_extension)) for tempdir_part in tempdir_parts])
  File "C:\fragpipe\tools\msfragger_pep_split.py", line 315, in <listcomp>
    pepxml_header, = set([get_pepxml_header(tempdir_part / (infile.stem + '.' + output_file_extension)) for tempdir_part in tempdir_parts])
  File "C:\fragpipe\tools\msfragger_pep_split.py", line 299, in get_pepxml_header
    ret = re_pepxml_header.match(mm).group()
AttributeError: 'NoneType' object has no attribute 'group'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\fragpipe\tools\msfragger_pep_split.py", line 472, in <module>
    main()
  File "C:\fragpipe\tools\msfragger_pep_split.py", line 467, in main
    combine_results()
  File "C:\fragpipe\tools\msfragger_pep_split.py", line 331, in combine_results
    e.result()
  File "C:\Users\kjonathan\Anaconda3\lib\concurrent\futures\_base.py", line 428, in result
    return self.__get_result()
  File "C:\Users\kjonathan\Anaconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
AttributeError: 'NoneType' object has no attribute 'group'
Process 'MsFragger' finished, exit code: 1
Process returned non-zero exit code, stopping
~~~~~~~~~~~~~~~~~~~~
Cancelling 8 remaining tasks


I've also attached a log file.
Thank you for your help.
Jonathan
[log_2020-08-19_10-38-46.txt](https://github.com/Nesvilab/FragPipe/files/5097225/log_2020-08-19_10-38-46.txt)

----------------------
## If you're submitting a bug report, please attach log file

The log file can be saved from FragPipe:

- by clicking the `Export Log` button on the `Run` tab.
- or just copy text from the output console on `Run` tab to a text file.

**Comment by guoci** [comment]
Please try the following fix, if it doesn't work, send me the pepXML files.
https://drive.google.com/file/d/13za-0YKsAw8Hw4EKzjHB6MY_6wfbYFWH/view?usp=sharing

**Comment by fcyu** [comment]
No response.

**Comment by JRKrieger37** [comment]
Hi - sorry for the delay. The build you shared gave me the same issues unfortunately. This, uninstalled and reinstalled philosopher and associated packages and that seemed to do the trick. Thanks!
