### ISSUE TITLE
Split Database Issues

### ISSUE THREAD

**Issue by daijie106** [Nesvilab/FragPipe#233]
I am trying non-specific  search. I have been suggested to use split database and I tried it. The processing failed and show the message as following:
 Process 'MsFragger' finished, exit code: 1
Process returned non-zero exit code, stoppingTraceback (most recent call last):
  File "G:\Software\MSFragger\Fragpipe13.0\tools\msfragger_pep_split.py", line 47, in <module>
    params_txt = param_path.read_text()
  File "C:\Users\Administrator\anaconda3\lib\pathlib.py", line 1217, in read_text
    return f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x99 in position 782: illegal multibyte sequence
MsFragger
java -cp G:\Software\MSFragger\Fragpipe13.0\lib\fragpipe-13.0.jar com.github.chhh.utils.FileMove F:\D20137\FW-D-10.pepXML F:\D20137\FW-D\FW-D-10\FW-D-10.pepXML
 
Any suggestion for me?

Thanks.

**Comment by daijie106** [comment]
Thank you guoci!

I tried the new version of FragPipe. And new problem jumped as following:
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
System OS: Windows 7, Architecture: AMD64
Java Info: 1.8.0_242, OpenJDK 64-Bit Server VM, 
JVM started with 9 GB memory
Checking database...
Y_type_masses has an empty value.
Traceback (most recent call last):
  File "G:\Software\MSFragger\FragPipe-jre-13.1-build39\fragpipe-13.1\tools\msfragger_pep_split.py", line 470, in <module>
    main()
  File "G:\Software\MSFragger\FragPipe-jre-13.1-build39\fragpipe-13.1\tools\msfragger_pep_split.py", line 457, in main
    calibrate_mzBIN, params_txt_new = calibrate(fasta_path_sample, calibrate_mass)
  File "G:\Software\MSFragger\FragPipe-jre-13.1-build39\fragpipe-13.1\tools\msfragger_pep_split.py", line 349, in calibrate
    raise AssertionError(p)
AssertionError: <subprocess.Popen object at 0x0000000004CDC748>
Process 'MsFragger' finished, exit code: 1
Process returned non-zero exit code, stoppingMsFragger move pepxml**
G:\Software\MSFragger\FragPipe-jre-13.1-build39\fragpipe-13.1\jre\bin\java.exe -cp G:\Software\MSFragger\FragPipe-jre-13.1-build39\fragpipe-13.1\lib\fragpipe-13.1-build39.jar com.github.chhh.utils.FileMove F:\D20137\FW-D-10.pepXML F:\D20137\FW-D\FW-D-10\FW-D-10.pepXML

Looking forward for your reply!

Many thanks,

Jie

**Comment by fcyu** [comment]
@guoci The dev version of FragPipe is not well compatible with released MSFragger. Could you send the updated script to Jie?

@daijie106 After you receiving Guo Ci's script, you need to put it to `tools` folder inside `fragpipe` folder.

Thanks,

Fengchao

**Comment by guoci** [comment]
@daijie106 please download at:
https://raw.githubusercontent.com/Nesvilab/FragPipe/develop/MSFragger-GUI/tools/msfragger_pep_split.py

**Comment by daijie106** [comment]
@fcyu，@guoci，

Thank you both for help. 
I replaced the mafragger_pep_split.py with the new one, and tried the FragPipe again.
The same problem happened as described as following:

Y_type_masses has an empty value.
Traceback (most recent call last):
  File "G:\Software\MSFragger\FragPipe-jre-13.1-build39\fragpipe-13.1\tools\msfragger_pep_split.py", line 470, in <module>
    main()
  File "G:\Software\MSFragger\FragPipe-jre-13.1-build39\fragpipe-13.1\tools\msfragger_pep_split.py", line 457, in main
    calibrate_mzBIN, params_txt_new = calibrate(fasta_path_sample, calibrate_mass)
  File "G:\Software\MSFragger\FragPipe-jre-13.1-build39\fragpipe-13.1\tools\msfragger_pep_split.py", line 349, in calibrate
    raise AssertionError(p)
AssertionError: <subprocess.Popen object at 0x0000000004CD9608>
Process 'MsFragger' finished, exit code: 1
Process returned non-zero exit code, stopping
~~~~~~~~~~~~~~~~~~~~
Cancelling 23 remaining tasks
MsFragger move pepxml
G:\Software\MSFragger\FragPipe-jre-13.1-build39\fragpipe-13.1\jre\bin\java.exe -cp G:\Software\MSFragger\FragPipe-jre-13.1-build39\fragpipe-13.1\lib\fragpipe-13.1-build39.jar com.github.chhh.utils.FileMove F:\D20137\FW-D-10.pepXML F:\D20137\FW-D\FW-D-10\FW-D-10.pepXML
Processing interrupted, stopping MsFragger move pepxml

I need more help from your guys. Thanks,

Jie

**Comment by daijie106** [comment]
When I tried it without split database, and it showed:
Checking database...
Y_type_masses has an empty value.
Process 'MsFragger' finished, exit code: 1
Process returned non-zero exit code, stoppingMsFragger move pepxml
G:\Software\MSFragger\FragPipe-jre-13.1-build39\fragpipe-13.1\jre\bin\java.exe -cp G:\Software\MSFragger\FragPipe-jre-13.1-build39\fragpipe-13.1\lib\fragpipe-13.1-build39.jar com.github.chhh.utils.FileMove F:\D20137\FW-D-10.pepXML F:\D20137\FW-D\FW-D-10\FW-D-10.pepXML

I was using the default non-specific search config on MSfragger tab with split database:1.

I hope this information will give you guys some hints about the puzzle.

Best,

Jie

**Comment by fcyu** [comment]
Hi Jie,

We just released [FragPipe-14.0 ](https://github.com/Nesvilab/FragPipe/releases/latest) which should solve your problem.

Please feel free to let us know if there is any further questions.

Best.

Fengchao

**Comment by punching-samuel** [comment]
Hi~ I tried fragpipe with the existing workflow. I met the same error, could you give me some suggestion? The solution link is broken.


""
Traceback (most recent call last):
  File "D:\yangsen\conda\Lib\concurrent\futures\process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\yangsen\software\FragPipe-jre-22.0\fragpipe\tools\msfragger_pep_split.py", line 408, in write_pin
    spec_to_index_map = dict((k, int(v)) for k, v in itertools.chain.from_iterable([
                                                                                   ^
  File "D:\yangsen\software\FragPipe-jre-22.0\fragpipe\tools\msfragger_pep_split.py", line 411, in <listcomp>
    re.compile('<spectrum_query .*assumed_charge="(\\d+?)" .*spectrum="(.+?)" .*index="(\\d+?)"').findall(e.read_text())]
                                                                                                          ^^^^^^^^^^^^^
  File "D:\yangsen\conda\Lib\pathlib.py", line 1059, in read_text
    return f.read()
           ^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 224: illegal multibyte sequence
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\yangsen\software\FragPipe-jre-22.0\fragpipe\tools\msfragger_pep_split.py", line 631, in <module>
    main()
  File "D:\yangsen\software\FragPipe-jre-22.0\fragpipe\tools\msfragger_pep_split.py", line 623, in main
    combine_results()
  File "D:\yangsen\software\FragPipe-jre-22.0\fragpipe\tools\msfragger_pep_split.py", line 477, in combine_results
    e.result()
  File "D:\yangsen\conda\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "D:\yangsen\conda\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 224: illegal multibyte sequence
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 42 remaining tasks


My config file shows the same version of the tools compared with the tutorial config shows.

<img width="818" alt="Image" src="https://github.com/user-attachments/assets/c3ae243d-c4ce-4c03-9d22-49b8b7ed7e63" />

Thank you!

Best,
sammi

**Comment by punching-samuel** [comment]
Hi~ I tried fragpipe with the existing workflow. I met the same error, could you give me some suggestion? The solution link is broken.

""
Traceback (most recent call last):
File "D:\yangsen\conda\Lib\concurrent\futures\process.py", line 261, in _process_worker
r = call_item.fn(*call_item.args, **call_item.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\yangsen\software\FragPipe-jre-22.0\fragpipe\tools\msfragger_pep_split.py", line 408, in write_pin
spec_to_index_map = dict((k, int(v)) for k, v in itertools.chain.from_iterable([
^
File "D:\yangsen\software\FragPipe-jre-22.0\fragpipe\tools\msfragger_pep_split.py", line 411, in
re.compile('<spectrum_query .*assumed_charge="(\d+?)" .*spectrum="(.+?)" .*index="(\d+?)"').findall(e.read_text())]
^^^^^^^^^^^^^
File "D:\yangsen\conda\Lib\pathlib.py", line 1059, in read_text
return f.read()
^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 224: illegal multibyte sequence
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "D:\yangsen\software\FragPipe-jre-22.0\fragpipe\tools\msfragger_pep_split.py", line 631, in
main()
File "D:\yangsen\software\FragPipe-jre-22.0\fragpipe\tools\msfragger_pep_split.py", line 623, in main
combine_results()
File "D:\yangsen\software\FragPipe-jre-22.0\fragpipe\tools\msfragger_pep_split.py", line 477, in combine_results
e.result()
File "D:\yangsen\conda\Lib\concurrent\futures_base.py", line 449, in result
return self.__get_result()
^^^^^^^^^^^^^^^^^^^
File "D:\yangsen\conda\Lib\concurrent\futures_base.py", line 401, in __get_result
raise self._exception
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 224: illegal multibyte sequence
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

Cancelling 42 remaining tasks




My config file shows the same version of the tools compared with the tutorial config shows.

<img width="818" alt="Image" src="https://github.com/user-attachments/assets/7a90ab19-7a09-48b2-b8fc-d6d665d58d95" />

Thank you!

Best,
sammi
