### ISSUE TITLE
return value of "java.util.HashMap.get(Object)" is null

### ISSUE THREAD

**Issue by animesh** [Nesvilab/FragPipe#261]
I am running the PTM shepherd via Fragpipe without success. Log mentions that Process "'PTMShepherd' finished, exit code: 1"
```
Process returned non-zero exit code, stopping
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "java.util.HashMap.get(Object)" is null
	at edu.umich.andykong.ptmshepherd.peakpicker.ModSummary.toFile(ModSummary.java:104)
	at edu.umich.andykong.ptmshepherd.PTMShepherd.main(PTMShepherd.java:379)
annotated summary table

```
**Version info:**
FragPipe version 14.0
MSFragger version 3.1\MSFragger-3.1.jar)
Philosopher version 3.3.11 (build 1601497354)

----------------------

**Comment by danielgeiszler** [comment]
Hi animesh,

Sorry for the delay, I didn't see this before. This error means it couldn't find an intermediate file, so it may have been moved or locked. Were you able to get this to work after? It should be solvable by rerunning it.
