### ISSUE TITLE
Process 'MsFragger' finished, exit code: 1

### ISSUE THREAD

**Issue by hcadre** [Nesvilab/FragPipe#287]
When analyzing a set of 42 timsTOF files the Main Search unexpectedly stopped subsequently to the identification of 7.945.980 peptides with this error message:

"In total 7945980 peptides.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at edu.umich.andykong.msfragger.M.a(Unknown Source)
	at edu.umich.andykong.msfragger.K.a(Unknown Source)
	at edu.umich.andykong.msfragger.m.a(Unknown Source)
	at edu.umich.andykong.msfragger.B.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
	... 6 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at edu.umich.andykong.msfragger.O.a(Unknown Source)
	at edu.umich.andykong.msfragger.M.a(Unknown Source)
	at edu.umich.andykong.msfragger.M$$Lambda$39/804611486.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Process 'MsFragger' finished, exit code: 1
Process returned non-zero exit code, stoppingMsFragger move pepxml
D:\MSFragger\FragPipe-jre-14.0\fragpipe\jre\bin\java.exe -cp D:\MSFragger\FragPipe-jre-14.0\fragpipe\lib\fragpipe-14.0.jar com.github.chhh.utils.FileMove E:\exp_1077_1078_MSFragger\20201119_exp1077_Markus_1_Slot1-92_1_1448.pepXML E:\exp_1077_1078_MSFragger\MSFragger_results\C1_1\20201119_exp1077_Markus_1_Slot1-92_1_1448.pepXML"

Do I have to adjust or increase the Java heap space? Or is there something related with the particular data file mentioned in the end of the error message that will cause this error? The corresponding .d file does not seem to be corrupted and can be opened normally in the Bruker Data Viewer....

**Comment by fcyu** [comment]
Yes, you need to increase heap space: `Caused by: java.lang.OutOfMemoryError: Java heap space`.

Best,

Fengchao
