### ISSUE TITLE
EasyPQP Error

### ISSUE THREAD

**Issue by sjr24** [Nesvilab/FragPipe#304]
I get the following error when making an EasyPQP library from Bruker ion mobility data.  The error occurs after all the files were parsed.

Thanks,
Shawn

Info: Parsing file C:\Users\srice\Downloads\HeLa_Evosep_Library_RAW\Lib\20200427_Evosep_60SPD_SG06-16_HeLa_Fr9_S1-A9_1_2407.peakpkl.
Traceback (most recent call last):
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\srice\AppData\Local\Continuum\anaconda3\Scripts\easypqp.exe\__main__.py", line 9, in <module>
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\site-packages\click\core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\site-packages\easypqp\main.py", line 95, in library
    generate(infiles, outfile, psmtsv, peptidetsv, rt_referencefile, rt_filter, im_referencefile, im_filter, psm_fdr_threshold, peptide_fdr_threshold, protein_fdr_threshold, rt_lowess_fraction, rt_psm_fdr_threshold, im_lowess_fraction, im_psm_fdr_threshold, pi0_lambda, peptide_plot_path, protein_plot_path, min_peptides, proteotypic, consensus, nofdr)
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\site-packages\easypqp\library.py", line 429, in generate
    pqp_mass = pqp.groupby(['PrecursorMz','ProductMz','Annotation','ProteinId','GeneName','PeptideSequence','ModifiedPeptideSequence','PrecursorCharge'], dropna=False)['LibraryIntensity'].median().reset_index()
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\site-packages\pandas\core\generic.py", line 7894, in groupby
    **kwargs
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\site-packages\pandas\core\groupby\groupby.py", line 2522, in groupby
    return klass(obj, by, **kwds)
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\site-packages\pandas\core\groupby\groupby.py", line 400, in __init__
    validate_kwargs("group", kwargs, {})
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\site-packages\pandas\util\_validators.py", line 165, in validate_kwargs
    _check_for_invalid_keys(fname, kwargs, compat_args)
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\site-packages\pandas\util\_validators.py", line 134, in _check_for_invalid_keys
    "keyword argument '{arg}'".format(fname=fname, arg=bad_arg)
TypeError: group() got an unexpected keyword argument 'dropna'
Library not generated, not enough peptides could be found for alignment.
Please try using other options for alignment (e.g. ciRT if used other options)
Process 'SpecLibGen' finished, exit code: 0

**Comment by guoci** [comment]
@sjr24 Can you run the following command in your Anaconda Prompt?
`conda update --yes pandas`

**Comment by sjr24** [comment]
Guoci,

Thank you for your response.  The machine is currently running another analysis.  When that is done I will try this.  Hopefully sometime this afternoon.  I’ll let you know what happens.

Thanks,
Shawn

**Comment by sjr24** [comment]
Guoci,

The update for pandas ran well but an error occurred at the same place.  See below.

Info: Parsing file C:\Users\srice\Downloads\HeLa_Evosep_Library_RAW\Lib\20200427_Evosep_60SPD_SG06-16_HeLa_Fr9_S1-A9_1_2407.peakpkl.
Traceback (most recent call last):
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\srice\AppData\Local\Continuum\anaconda3\Scripts\easypqp.exe\__main__.py", line 9, in <module>
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\site-packages\click\core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\site-packages\easypqp\main.py", line 95, in library
    generate(infiles, outfile, psmtsv, peptidetsv, rt_referencefile, rt_filter, im_referencefile, im_filter, psm_fdr_threshold, peptide_fdr_threshold, protein_fdr_threshold, rt_lowess_fraction, rt_psm_fdr_threshold, im_lowess_fraction, im_psm_fdr_threshold, pi0_lambda, peptide_plot_path, protein_plot_path, min_peptides, proteotypic, consensus, nofdr)
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\site-packages\easypqp\library.py", line 429, in generate
    pqp_mass = pqp.groupby(['PrecursorMz','ProductMz','Annotation','ProteinId','GeneName','PeptideSequence','ModifiedPeptideSequence','PrecursorCharge'], dropna=False)['LibraryIntensity'].median().reset_index()
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\site-packages\pandas\core\generic.py", line 7894, in groupby
    **kwargs
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\site-packages\pandas\core\groupby\groupby.py", line 2522, in groupby
    return klass(obj, by, **kwds)
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\site-packages\pandas\core\groupby\groupby.py", line 400, in __init__
    validate_kwargs("group", kwargs, {})
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\site-packages\pandas\util\_validators.py", line 165, in validate_kwargs
    _check_for_invalid_keys(fname, kwargs, compat_args)
  File "c:\users\srice\appdata\local\continuum\anaconda3\lib\site-packages\pandas\util\_validators.py", line 134, in _check_for_invalid_keys
    "keyword argument '{arg}'".format(fname=fname, arg=bad_arg)
TypeError: group() got an unexpected keyword argument 'dropna'
Library not generated, not enough peptides could be found for alignment.
Please try using other options for alignment (e.g. ciRT if used other options)
Process 'SpecLibGen' finished, exit code: 0

**Comment by guoci** [comment]
@sjr24 Can you run the following command in your Anaconda Prompt and show me the output?
`python -c "import pandas as pd; print(pd.__version__); print(pd)"`

**Comment by sjr24** [comment]
(base) C:\>python -c "import pandas as pd; print(pd.__version__); print(pd)"
0.25.1
<module 'pandas' from 'C:\\Users\\srice\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\pandas\\__init__.py'>

**Comment by guoci** [comment]
@sjr24 according to the version number, `pandas` wasn't updated
What was the output you got when you do `conda update --yes pandas`?

**Comment by sjr24** [comment]
(base) C:\>conda update --yes pandas
Collecting package metadata (current_repodata.json): done
Solving environment: -

Updating pandas is constricted by

anaconda -> requires pandas==0.25.1=py37ha925a31_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`

done

# All requested packages already installed.

**Comment by guoci** [comment]
@sjr24 can you do
`conda install --yes pandas==1.2.1`
and then check version
`python -c "import pandas as pd; print(pd.__version__); print(pd)"`

**Comment by sjr24** [comment]
I get the following message when I update pandas.  Do I need to update anaconda?


UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - anaconda-project -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - anaconda==2019.10 -> python[version='2.7.16|3.6.9|3.7.4',build='h5500b2f_0|hcb6e200_0|h5263a28_0']
  - backports.functools_lru_cache -> python[version='>=2.7,<2.8.0a0']
  - backports.os -> python[version='>=3.5,<3.6.0a0']
  - bleach -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - conda[version='>=4.9.2'] -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0']
  - cryptography -> python[version='<=3.3']
  - dask-core -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - h5py -> python[version='<3']
  - html5lib -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - imageio -> python[version='>=3.9,<3.10.0a0']
  - isort -> python[version='>=3.9,<3.10.0a0']
  - jinja2 -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - joblib -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - jupyter_console -> python[version='>=3.9,<3.10.0a0']
  - matplotlib -> python[version='>=3.9,<3.10.0a0']
  - mkl_random -> python[version='>=2.7,<2.8.0a0']
  - mock -> python[version='>=3.9,<3.10.0a0']
  - more-itertools -> python[version='>=3.9,<3.10.0a0']
  - networkx -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - nose -> python[version='>=3.9,<3.10.0a0']
  - numba -> python[version='3.4.*|>=3.9,<3.10.0a0']
  - openpyxl -> python[version='>=3.8,<3.9.0a0']
  - packaging -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - pandas==1.2.1 -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0']
  - partd -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - path.py -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - pickleshare -> python[version='>=3.9,<3.10.0a0']
  - prometheus_client -> python[version='>=3.8,<3.9.0a0']
  - pyflakes -> python[version='>=3.9,<3.10.0a0']
  - pygments -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - pyopenssl -> python[version='>=3.9,<3.10.0a0']
  - pyrsistent -> python[version='>=3.5,<3.6.0a0']
  - pytest-doctestplus -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - pytest-openfiles -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - python-dateutil -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - qtawesome -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - seaborn -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - singledispatch -> python[version='>=3.9,<3.10.0a0']
  - sphinx -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - sphinxcontrib-websupport -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - testpath -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - traitlets -> python[version='>=3.9,<3.10.0a0']
  - urllib3 -> python[version='<=3.3|>=3.9,<3.10.0a0']
  - wheel -> python[version='>=3.9,<3.10.0a0']
  - zict -> python[version='>=3.8,<3.9.0a0']

Your python: python=3.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (pandas):

  - pandas==1.2.1

The following specifications were found to be incompatible with each other:

**Comment by guoci** [comment]
@sjr24 I would suggest you do a fresh install of Anaconda

**Comment by sjr24** [comment]
Guoci,
Reinstalling a new version of anaconda worked.  Thanks for the help.

Thanks,
Shawn

________________________________
