### ISSUE TITLE
bruker native libraries not found

### ISSUE THREAD

**Issue by anfoss** [Nesvilab/FragPipe#324]
I have 8 ddaPASEF files but cannot run a search due to the missing Bruker libraries. After looking around I checked the following.

1. I do have the bruker dll in MS-Fragger/ext/Bruker
2. I have updated Visual C++ Redistributable for Visual Studio 2017  to the required version
This is the full error stack

```
MSFragger version MSFragger-3.2
Batmass-IO version 1.22.1
[main] ERROR umich.ms.fileio.filetypes.bruker.Timsdata - JNA could not load native Bruker library
[main] ERROR umich.ms.fileio.filetypes.bruker.Timsdata - The ext folder with timsdata-2-7-0.dll (Win) or libtimsdata-2-7-0.so (Linux) is needed. If you are using an old ext folder, please upgrade.
java.lang.UnsatisfiedLinkError: Unable to load library 'timsdata-2-7-0':
%1 is not a valid Win32 application.

%1 is not a valid Win32 application.

The specified module could not be found.

Native library (win32-x86/timsdata-2-7-0.dll) not found in resource path (C:\Users\owner\Desktop\FragPipe-15.0\fragpipe\tools\MSFragger-3.2\MSFragger-3.2.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
	at com.sun.jna.Library$Handler.<init>(Library.java:192)
	at com.sun.jna.Native.load(Native.java:596)
	at com.sun.jna.Native.load(Native.java:570)
	at umich.ms.fileio.filetypes.bruker.Timsdata$Instance.<clinit>(Timsdata.java:174)
	at umich.ms.fileio.filetypes.bruker.Timsdata.getLoadedLibName(Timsdata.java:197)
	at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
	Suppressed: java.lang.UnsatisfiedLinkError: %1 is not a valid Win32 application.

		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 14 more
	Suppressed: java.lang.UnsatisfiedLinkError: %1 is not a valid Win32 application.

		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 14 more
	Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.

		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:265)
		... 14 more
	Suppressed: java.io.IOException: Native library (win32-x86/timsdata-2-7-0.dll) not found in resource path (C:\Users\owner\Desktop\FragPipe-15.0\fragpipe\tools\MSFragger-3.2\MSFragger-3.2.jar)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1095)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:276)
		... 14 more
timsdata library version 
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_281, Java HotSpot(TM) Client VM, Oracle Corporation
JVM started with 0 GB memory
Checking database...
Failed in checking C:\AF\gluC\GluC_F1_D1_1_4478.d
Bruker native libraries not found
Failed in checking C:\AF\gluC\GluC_F2_D2_1_4479.d
Bruker native libraries not found
Failed in checking C:\AF\gluC\GluC_F3_D3_1_4480.d
Bruker native libraries not found
Failed in checking C:\AF\gluC\GluC_F4_D4_1_4481.d
Bruker native libraries not found
Failed in checking C:\AF\gluC\GluC_F5_D5_1_4482.d
Bruker native libraries not found
Failed in checking C:\AF\gluC\GluC_F6_D6_1_4483.d
Bruker native libraries not found
Failed in checking C:\AF\gluC\GluC_F7_D7_1_4484.d
Bruker native libraries not found
Failed in checking C:\AF\gluC\GluC_F8_D8_1_4485.d
Bruker native libraries not found
Failed in checking spectral files.
Checking spectral files...
C:\AF\gluC\GluC_F1_D1_1_4478.d: Scans = 0
C:\AF\gluC\GluC_F2_D2_1_4479.d: Scans = 0
C:\AF\gluC\GluC_F3_D3_1_4480.d: Scans = 0
C:\AF\gluC\GluC_F4_D4_1_4481.d: Scans = 0
C:\AF\gluC\GluC_F5_D5_1_4482.d: Scans = 0
C:\AF\gluC\GluC_F6_D6_1_4483.d: Scans = 0
C:\AF\gluC\GluC_F7_D7_1_4484.d: Scans = 0
C:\AF\gluC\GluC_F8_D8_1_4485.d: Scans = 0
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping
~~~~~~~~~~~~~~~~~~~~
Cancelling 18 remaining tasks
18:48:08 ERROR: Error writing log to file
java.nio.channels.ClosedByInterruptException: null
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(Unknown Source)
	at sun.nio.ch.FileChannelImpl.write(Unknown Source)
	at java.nio.channels.Channels.writeFullyImpl(Unknown Source)
	at java.nio.channels.Channels.writeFully(Unknown Source)
	at java.nio.channels.Channels.access$000(Unknown Source)
	at java.nio.channels.Channels$1.write(Unknown Source)
	at sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
	at sun.nio.cs.StreamEncoder.implWrite(Unknown Source)
	at sun.nio.cs.StreamEncoder.write(Unknown Source)
	at java.io.OutputStreamWriter.write(Unknown Source)
	at java.io.BufferedWriter.flushBuffer(Unknown Source)
	at java.io.BufferedWriter.write(Unknown Source)
	at java.io.Writer.write(Unknown Source)
	at com.dmtavt.fragpipe.tabs.TabRun.saveLogToFile(TabRun.java:354)
	at com.dmtavt.fragpipe.tabs.TabRun.on(TabRun.java:309)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:510)
	at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:447)
	at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:414)
	at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:387)
	at org.greenrobot.eventbus.EventBus.post(EventBus.java:268)
	at com.dmtavt.fragpipe.api.Bus.post(Bus.java:51)
	at com.dmtavt.fragpipe.cmd.ProcessBuilderInfo.lambda$toRunnable$0(ProcessBuilderInfo.java:96)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	Suppressed: java.nio.channels.ClosedChannelException: null
		at sun.nio.ch.FileChannelImpl.ensureOpen(Unknown Source)
		at sun.nio.ch.FileChannelImpl.write(Unknown Source)
		at java.nio.channels.Channels.writeFullyImpl(Unknown Source)
		at java.nio.channels.Channels.writeFully(Unknown Source)
		at java.nio.channels.Channels.access$000(Unknown Source)
		at java.nio.channels.Channels$1.write(Unknown Source)
		at sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
		at sun.nio.cs.StreamEncoder.implClose(Unknown Source)
		at sun.nio.cs.StreamEncoder.close(Unknown Source)
		at java.io.OutputStreamWriter.close(Unknown Source)
		at java.io.BufferedWriter.close(Unknown Source)
		at com.dmtavt.fragpipe.tabs.TabRun.saveLogToFile(TabRun.java:355)
		... 16 common frames omitted
```

Thanks!

**Comment by fcyu** [comment]
> I have updated Visual studio code to the required version

I am not sure if it is a typo. What the library needs is Visual C++ Redistributable for Visual Studio 2017, not visual studio code which is an editor. You can download it from https://aka.ms/vs/16/release/VC_redist.x64.exe

Best,

Fengchao

**Comment by anfoss** [comment]
Yeah it was a typo. I installed the one recommended here https://github.com/Nesvilab/FragPipe/issues/211. Is that the same?

**Comment by fcyu** [comment]
Yes, that is the correct one. Can you show me the screenshot of the MSFragger folder and ext folder?

Thanks,

Fengchao

**Comment by anfoss** [comment]
Here we are

![Screen Shot 2021-03-11 at 7 14 23 AM](https://user-images.githubusercontent.com/39403761/110809077-7275c680-8239-11eb-8aca-ea6f1baf47c6.png)

**Comment by fcyu** [comment]
Did you have a chance to analyze your ddaPASEF with older version of MSFragger successfully?

**Comment by anfoss** [comment]
Did not try. Can I just dl another msfragger and change the path in fragpipe?

**Comment by fcyu** [comment]
Could you help to check if your operating system it 64-bit and your java is also 64-bit?

Thanks,

Fengchao

**Comment by anfoss** [comment]
Worked, had the wrong JVM version installed (32 instead of 64). Thx closed!
