### ISSUE TITLE
Process 'MSFragger' finished, exit code: 1

### ISSUE THREAD

**Issue by rajeshksoni11** [Nesvilab/FragPipe#325]
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at edu.umich.andykong.msfragger.E.a(Unknown Source)
	at edu.umich.andykong.msfragger.G.a(Unknown Source)
	at edu.umich.andykong.msfragger.m.a(Unknown Source)
	at edu.umich.andykong.msfragger.z.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
	... 6 more
Caused by: java.lang.OutOfMemoryError: Java heap space
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping
~~~~~~~~~~~~~~~~~~~~
Cancelling 23 remaining tasks

**Comment by danielgeiszler** [comment]
Hi Rajesh,

It looks like you ran out of memory. Try increasing how much you allocate and seeing if that helps.
