### ISSUE TITLE
FragPipe GUI errors on Centos 7

### ISSUE THREAD

**Issue by marianalevineu** [Nesvilab/FragPipe#342]
Hi FragPipe team,
We are trying to set up the GUI Linux version on Centos 7, with java version "1.8.0_181", to be able to run with X11 from the shell command line, but get errors with GUI though users indicated the command line options work fine.

Some other details - I'm using the SLURM scheduler and run the command with x11 forwarding enabled:
$ srun -p short -N 1 -n 16 --x11 --pty /bin/bash
Then, load the Java module:
$ module load oracle_java/jdk1.8.0_181
$ java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

When trying to run the linux shell script fragpipe/bin/fragpipe, the windows opens for a second and then closes with the following error, could you let us know what could be the issue?

08:33:18.695 [ForkJoinPool-1-worker-1] INFO  com.dmtavt.fragpipe.FragpipeLoader - Trying to fetch remote properties, 5 seconds timeout
08:33:23.816 [RxComputationScheduler-1] ERROR com.dmtavt.fragpipe.FragpipeLoader - Something happened while trying to get application properties at startup
java.util.concurrent.TimeoutException: null
	at rx.internal.operators.OnSubscribeTimeoutTimedWithFallback$TimeoutMainSubscriber.onTimeout(OnSubscribeTimeoutTimedWithFallback.java:166)
	at rx.internal.operators.OnSubscribeTimeoutTimedWithFallback$TimeoutMainSubscriber$TimeoutTask.call(OnSubscribeTimeoutTimedWithFallback.java:191)
	at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Thanks for your help!

**Comment by guoci** [comment]
@marianalevineu to build from source, see https://github.com/Nesvilab/FragPipe#building-from-scratch
Can you do the following?
When the GUI hangs, go to the terminal and press `Ctrl` + `\`. Show me the output from the terminal.

**Comment by marianalevineu** [comment]
This is the full output I get:

18:34:54.212 [ForkJoinPool-1-worker-1] INFO  com.dmtavt.fragpipe.FragpipeLoader - Trying to fetch remote properties, 5 seconds timeout
18:34:59.300 [RxComputationScheduler-1] ERROR com.dmtavt.fragpipe.FragpipeLoader - Something happened while trying to get application properties at startup
java.util.concurrent.TimeoutException: null
                at rx.internal.operators.OnSubscribeTimeoutTimedWithFallback$TimeoutMainSubscriber.onTimeout(OnSubscribeTimeoutTimedWithFallback.java:166)
                at rx.internal.operators.OnSubscribeTimeoutTimedWithFallback$TimeoutMainSubscriber$TimeoutTask.call(OnSubscribeTimeoutTimedWithFallback.java:191)
                at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189)
                at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)
^\2021-03-30 18:35:32
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.181-b13 mixed mode):

"DestroyJavaVM" #21 prio=5 os_prio=0 tid=0x00002b9d3400b800 nid=0xbed7 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"RxComputationScheduler-1" #20 daemon prio=5 os_prio=0 tid=0x00002b9d98062800 nid=0xbeef waiting on condition [0x00002b9d4fce4000]
   java.lang.Thread.State: WAITING (parking)
                at sun.misc.Unsafe.park(Native Method)
                - parking to wait for  <0x00000003006af868> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
                at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
                at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
                at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
                at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
                at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)

"RxIoScheduler-2" #19 daemon prio=5 os_prio=0 tid=0x00002b9d98060800 nid=0xbeee runnable [0x00002b9d5e741000]
   java.lang.Thread.State: RUNNABLE
                at java.net.PlainSocketImpl.socketConnect(Native Method)
                at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
                - locked <0x00000000812fd188> (a java.net.SocksSocketImpl)
                at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
                at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
                at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
                at java.net.Socket.connect(Socket.java:589)
                at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
                at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
                at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
                at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
                at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
                - locked <0x00000000812fc0c8> (a sun.net.www.protocol.https.HttpsClient)
                at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
                at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
                at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
                at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
                at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
                at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
                at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
                - locked <0x00000000812f94c8> (a sun.net.www.protocol.https.DelegateHttpsURLConnection)
                at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
                - locked <0x00000000812f94c8> (a sun.net.www.protocol.https.DelegateHttpsURLConnection)
                at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
                - locked <0x00000003006f72e8> (a sun.net.www.protocol.https.HttpsURLConnectionImpl)
                at java.net.URL.openStream(URL.java:1045)
                at org.apache.commons.io.IOUtils.toString(IOUtils.java:1198)
                at com.github.chhh.utils.PropertiesUtils.lambda$loadPropertiesRemote$0(PropertiesUtils.java:280)
                at com.github.chhh.utils.PropertiesUtils$$Lambda$33/721493985.call(Unknown Source)
                at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
                at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
                at rx.Observable.unsafeSubscribe(Observable.java:10327)
                at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
                at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
                at rx.internal.operators.OperatorSubscribeOn.call(OperatorSubscribeOn.java:50)
                at rx.internal.operators.OperatorSubscribeOn.call(OperatorSubscribeOn.java:30)
                at rx.Observable.subscribe(Observable.java:10423)
                at rx.Observable.subscribe(Observable.java:10390)
                at rx.Observable.subscribe(Observable.java:10230)
                at com.github.chhh.utils.PropertiesUtils.loadPropertiesRemote(PropertiesUtils.java:288)
                at com.github.chhh.utils.PropertiesUtils.loadPropertiesRemote(PropertiesUtils.java:275)
                at com.github.chhh.utils.PropertiesUtils.fetchPropertiesFromRemote(PropertiesUtils.java:440)
                at com.github.chhh.utils.PropertiesUtils.initProperties(PropertiesUtils.java:199)
                at com.dmtavt.fragpipe.params.ThisAppProps$HolderRemote.<clinit>(ThisAppProps.java:112)
                at com.dmtavt.fragpipe.params.ThisAppProps.getRemoteProperties(ThisAppProps.java:134)
                at com.dmtavt.fragpipe.params.ThisAppProps.getRemotePropertiesWithLocalDefaults(ThisAppProps.java:140)
                at com.dmtavt.fragpipe.FragpipeLoader$$Lambda$30/826841831.call(Unknown Source)
                at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
                at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
                at rx.Observable.subscribe(Observable.java:10423)
                at rx.Observable.subscribe(Observable.java:10390)
                at rx.internal.operators.OnSubscribeTimeoutTimedWithFallback.call(OnSubscribeTimeoutTimedWithFallback.java:64)
                at rx.internal.operators.OnSubscribeTimeoutTimedWithFallback.call(OnSubscribeTimeoutTimedWithFallback.java:36)
                at rx.Observable.unsafeSubscribe(Observable.java:10327)
                at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
                at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
                at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)

"RxIoScheduler-1 (Evictor)" #18 daemon prio=5 os_prio=0 tid=0x00002b9d9803b800 nid=0xbeed waiting on condition [0x00002b9d5e642000]
   java.lang.Thread.State: TIMED_WAITING (parking)
                at sun.misc.Unsafe.park(Native Method)
                - parking to wait for  <0x00000003006b48f0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
                at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
                at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
                at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
                at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
                at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)

"AWT-EventQueue-0" #16 prio=6 os_prio=0 tid=0x00002b9d3458e800 nid=0xbeeb in Object.wait() [0x00002b9d4fbe2000]
   java.lang.Thread.State: RUNNABLE
                at com.dmtavt.fragpipe.params.ThisAppProps.getRemoteProperties(ThisAppProps.java:134)
                at com.dmtavt.fragpipe.params.ThisAppProps.getRemotePropertiesWithLocalDefaults(ThisAppProps.java:140)
                at com.dmtavt.fragpipe.params.ThisAppProps.def(ThisAppProps.java:154)
                at com.dmtavt.fragpipe.tabs.TabConfig.createPanelPython(TabConfig.java:750)
                at com.dmtavt.fragpipe.tabs.TabConfig.init(TabConfig.java:140)
                at com.dmtavt.fragpipe.tabs.TabConfig.<init>(TabConfig.java:127)
                at com.dmtavt.fragpipe.Fragpipe.createTabs(Fragpipe.java:389)
                at com.dmtavt.fragpipe.Fragpipe.initUi(Fragpipe.java:439)
                - locked <0x00000003006177e8> (a com.dmtavt.fragpipe.Fragpipe)
                at com.dmtavt.fragpipe.Fragpipe.<init>(Fragpipe.java:155)
                at com.dmtavt.fragpipe.Fragpipe.lambda$displayMainWindow$3(Fragpipe.java:269)
                at com.dmtavt.fragpipe.Fragpipe$$Lambda$36/550752602.run(Unknown Source)
                at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
                at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
                at java.awt.EventQueue.access$500(EventQueue.java:97)
                at java.awt.EventQueue$3.run(EventQueue.java:709)
                at java.awt.EventQueue$3.run(EventQueue.java:703)
                at java.security.AccessController.doPrivileged(Native Method)
                at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
                at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
                at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
                at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
                at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
                at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
                at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
                at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

"TimerQueue" #15 daemon prio=5 os_prio=0 tid=0x00002b9d3455b000 nid=0xbeea waiting on condition [0x00002b9d4f662000]
   java.lang.Thread.State: WAITING (parking)
                at sun.misc.Unsafe.park(Native Method)
                - parking to wait for  <0x0000000300580c20> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
                at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
                at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
                at java.util.concurrent.DelayQueue.take(DelayQueue.java:211)
                at javax.swing.TimerQueue.run(TimerQueue.java:174)
                at java.lang.Thread.run(Thread.java:748)

"AWT-Shutdown" #14 prio=5 os_prio=0 tid=0x00002b9d34559800 nid=0xbee9 in Object.wait() [0x00002b9d4f561000]
   java.lang.Thread.State: WAITING (on object monitor)
                at java.lang.Object.wait(Native Method)
                - waiting on <0x000000030057efa8> (a java.lang.Object)
                at java.lang.Object.wait(Object.java:502)
                at sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:295)
                - locked <0x000000030057efa8> (a java.lang.Object)
                at java.lang.Thread.run(Thread.java:748)

"AWT-XAWT" #10 daemon prio=6 os_prio=0 tid=0x00002b9d3441c800 nid=0xbee3 runnable [0x00002b9d4e6dc000]
   java.lang.Thread.State: RUNNABLE
                at sun.awt.X11.XToolkit.waitForEvents(Native Method)
                at sun.awt.X11.XToolkit.run(XToolkit.java:568)
                at sun.awt.X11.XToolkit.run(XToolkit.java:532)
                at java.lang.Thread.run(Thread.java:748)

"Java2D Disposer" #8 daemon prio=10 os_prio=0 tid=0x00002b9d343fd800 nid=0xbee2 in Object.wait() [0x00002b9d4e1ca000]
   java.lang.Thread.State: WAITING (on object monitor)
                at java.lang.Object.wait(Native Method)
                - waiting on <0x000000030042b030> (a java.lang.ref.ReferenceQueue$Lock)
                at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
                - locked <0x000000030042b030> (a java.lang.ref.ReferenceQueue$Lock)
                at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
                at sun.java2d.Disposer.run(Disposer.java:148)
                at java.lang.Thread.run(Thread.java:748)

"Service Thread" #7 daemon prio=9 os_prio=0 tid=0x00002b9d340b7000 nid=0xbede runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00002b9d340b4000 nid=0xbedd waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00002b9d340b1800 nid=0xbedc waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00002b9d340b0000 nid=0xbedb waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00002b9d3407c800 nid=0xbeda in Object.wait() [0x00002b9d32b28000]
   java.lang.Thread.State: WAITING (on object monitor)
                at java.lang.Object.wait(Native Method)
                - waiting on <0x0000000300157c48> (a java.lang.ref.ReferenceQueue$Lock)
                at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
                - locked <0x0000000300157c48> (a java.lang.ref.ReferenceQueue$Lock)
                at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
                at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00002b9d3407a000 nid=0xbed9 in Object.wait() [0x00002b9d32a27000]
   java.lang.Thread.State: WAITING (on object monitor)
                at java.lang.Object.wait(Native Method)
                - waiting on <0x00000003001562e0> (a java.lang.ref.Reference$Lock)
                at java.lang.Object.wait(Object.java:502)
                at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
                - locked <0x00000003001562e0> (a java.lang.ref.Reference$Lock)
                at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"VM Thread" os_prio=0 tid=0x00002b9d34070000 nid=0xbed8 runnable

"VM Periodic Task Thread" os_prio=0 tid=0x00002b9d340bc800 nid=0xbedf waiting on condition

JNI global references: 441

Heap
 def new generation   total 615104K, used 54681K [0x0000000080200000, 0x00000000a9d60000, 0x0000000300150000)
  eden space 546816K,  10% used [0x0000000080200000, 0x0000000083766760, 0x00000000a1800000)
  from space 68288K,   0% used [0x00000000a1800000, 0x00000000a1800000, 0x00000000a5ab0000)
  to   space 68288K,   0% used [0x00000000a5ab0000, 0x00000000a5ab0000, 0x00000000a9d60000)
 tenured generation   total 1366720K, used 6474K [0x0000000300150000, 0x0000000353800000, 0x0000000800000000)
   the space 1366720K,   0% used [0x0000000300150000, 0x00000003007a2810, 0x00000003007a2a00, 0x0000000353800000)
 Metaspace       used 23513K, capacity 23944K, committed 24192K, reserved 1071104K
  class space    used 2954K, capacity 3098K, committed 3200K, reserved 1048576K


Mariana Levi, Ph.D.
Associate Computational Scientist
Research Computing, Information Technology Services
Northeastern University
617-470-4022


From: guoci ***@***.***>
Date: Tuesday, March 30, 2021 at 3:55 PM
To: Nesvilab/FragPipe ***@***.***>
Cc: Levi, Mariana ***@***.***>, Mention ***@***.***>
Subject: Re: [Nesvilab/FragPipe] FragPipe GUI errors on Centos 7 (#342)

@marianalevineu<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmarianalevineu&data=04%7C01%7Cm.levi%40northeastern.edu%7C6df9426351994333687508d8f3b5c6a7%7Ca8eec281aaa34daeac9b9a398b9215e7%7C0%7C0%7C637527309338829613%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2Fq7xDl006TWCUvQoMeODoQkUHS5G3osfGPxh46flL%2Fo%3D&reserved=0> to build from source, see https://github.com/Nesvilab/FragPipe#building-from-scratch<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNesvilab%2FFragPipe%23building-from-scratch&data=04%7C01%7Cm.levi%40northeastern.edu%7C6df9426351994333687508d8f3b5c6a7%7Ca8eec281aaa34daeac9b9a398b9215e7%7C0%7C0%7C637527309338839607%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2YmsTepxUwFizuHBNT6qwxBSPPdiVo9XHH71Od7f7tA%3D&reserved=0>
Can you do the following?
When the GUI hangs, go to the terminal and press Ctrl + \. Show me the output from the terminal.

**Comment by marianalevineu** [comment]
The window actually appeared now, so I guess it was just very slow to load.

Mariana Levi, Ph.D.
Associate Computational Scientist
Research Computing, Information Technology Services
Northeastern University
617-470-4022


From: guoci ***@***.***>
Date: Tuesday, March 30, 2021 at 3:55 PM
To: Nesvilab/FragPipe ***@***.***>
Cc: Levi, Mariana ***@***.***>, Mention ***@***.***>
Subject: Re: [Nesvilab/FragPipe] FragPipe GUI errors on Centos 7 (#342)

@marianalevineu<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmarianalevineu&data=04%7C01%7Cm.levi%40northeastern.edu%7C6df9426351994333687508d8f3b5c6a7%7Ca8eec281aaa34daeac9b9a398b9215e7%7C0%7C0%7C637527309338829613%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2Fq7xDl006TWCUvQoMeODoQkUHS5G3osfGPxh46flL%2Fo%3D&reserved=0> to build from source, see https://github.com/Nesvilab/FragPipe#building-from-scratch<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNesvilab%2FFragPipe%23building-from-scratch&data=04%7C01%7Cm.levi%40northeastern.edu%7C6df9426351994333687508d8f3b5c6a7%7Ca8eec281aaa34daeac9b9a398b9215e7%7C0%7C0%7C637527309338839607%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2YmsTepxUwFizuHBNT6qwxBSPPdiVo9XHH71Od7f7tA%3D&reserved=0>
Can you do the following?
When the GUI hangs, go to the terminal and press Ctrl + \. Show me the output from the terminal.

**Comment by guoci** [comment]
@marianalevineu Do you still have other issues? If not, you can close this.

**Comment by marianalevineu** [comment]
Thanks for your help! It seems to work well on my end but I did not hear back from the user after communicating this information. You can close the ticket, thanks again!

Mariana Levi, Ph.D.
Associate Computational Scientist
Research Computing, Information Technology Services
Northeastern University
617-470-4022


From: guoci ***@***.***>
Date: Monday, April 5, 2021 at 3:25 PM
To: Nesvilab/FragPipe ***@***.***>
Cc: Levi, Mariana ***@***.***>, Mention ***@***.***>
Subject: Re: [Nesvilab/FragPipe] FragPipe GUI errors on Centos 7 (#342)

@marianalevineu<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmarianalevineu&data=04%7C01%7Cm.levi%40northeastern.edu%7C8fd3c89175df432d1e0108d8f8688389%7Ca8eec281aaa34daeac9b9a398b9215e7%7C0%7C0%7C637532475059855186%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=j1av7zQ6nu8W6akynTRpDhOwrDvnyD8sj9fxE%2BKbdoA%3D&reserved=0> Do you still have other issues? If not, you can close this.
