### ISSUE TITLE
Process 'MSFragger' finished, exit code: 1

### ISSUE THREAD

**Issue by ppppippo** [Nesvilab/FragPipe#350]
Dear Fragpipe team,

I am new to Fragpipe and got the following error code: 

java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.util.concurrent.ExecutionException: java.lang.NegativeArraySizeException: -483930968
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at edu.umich.andykong.msfragger.I.a(Unknown Source)
	at edu.umich.andykong.msfragger.G.a(Unknown Source)
	at edu.umich.andykong.msfragger.m.a(Unknown Source)
	at edu.umich.andykong.msfragger.z.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
	... 6 more
Caused by: java.lang.NegativeArraySizeException: -483930968
	at edu.umich.andykong.msfragger.I.a(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

I attached the log file from my search. Could you please advise? 

Thank you very much for your support.

[log_2021-04-09_17-26-24.txt](https://github.com/Nesvilab/FragPipe/files/6284657/log_2021-04-09_17-26-24.txt)

**Comment by fcyu** [comment]
Could you send your log again? The link you attached is dead.

Best,

Fengchao

**Comment by ppppippo** [comment]
[log_2021-04-09_17-26-24.txt](https://github.com/Nesvilab/FragPipe/files/6285823/log_2021-04-09_17-26-24.txt)

Please see attached. I got this error when max occurrences of variable modifications were set to 3. I tried to set max occurrences to 2 and it worked fine.

**Comment by fcyu** [comment]
I reproduced your error. It is due to an overflow when there are many modifications on the same amino acid ("C" in your case). As you already figured out, reducing the max occurrences can avoid this error. The fix will be available in the next release.

Best,

Fengchao
