### ISSUE TITLE
Spectral library building with DDA data fails.

### ISSUE THREAD

**Issue by MarcIsak** [Nesvilab/FragPipe#359]
Hi, I used the SpecLib workflow in Fragpipe 15.0 in order to generate some spectral libraries. However, the library building failed in the end resulting in the following code. Any clues what could cause this issue? thanks in advance! 

The console output where the search failed:

SpecLibGen [Work dir: D:\Data_FRAGGER\vmb_exo_2104\speclib_dda]
C:\Users\marc\anaconda3\python.exe -u C:\fragpipe\lib\..\tools\speclib\gen_con_spec_lib.py D:\Databases\2021-04-20-decoys-uniprot-filtered-proteome_UP000005640+AND+reviewed_yes+AND+organism__Hom_can.fasta.fas D:\Data_FRAGGER\vmb_exo_2104\speclib_dda unused D:\Data_FRAGGER\vmb_exo_2104\speclib_dda True unused use_easypqp ciRT 12 "--max_delta_unimod 0.020000 --max_delta_ppm 15.000000" "--rt_lowess_fraction 0.010000" D:\MS_files\vmb_exo_2104\Marc_P2104_89_uncalibrated.mgf D:\MS_files\vmb_exo_2104\Marc_P2104_58_uncalibrated.mgf D:\MS_files\vmb_exo_2104\Marc_P2104_55_uncalibrated.mgf D:\MS_files\vmb_exo_2104\Marc_P2104_10_uncalibrated.mgf D:\MS_files\vmb_exo_2104\Marc_P2104_97_uncalibrated.mgf D:\MS_files\vmb_exo_2104\Marc_P2104_92_uncalibrated.mgf D:\MS_files\vmb_exo_2104\Marc_P2104_59_uncalibrated.mgf D:\MS_files\vmb_exo_2104\Marc_P2104_22_uncalibrated.mgf D:\MS_files\vmb_exo_2104\Marc_P2104_67_uncalibrated.mgf D:\MS_files\vmb_exo_2104\Marc_P2104_80_uncalibrated.mgf D:\MS_files\vmb_exo_2104\Marc_P2104_11_uncalibrated.mgf D:\MS_files\vmb_exo_2104\Marc_P2104_93_uncalibrated.mgf D:\MS_files\vmb_exo_2104\Marc_P2104_54_uncalibrated.mgf D:\MS_files\vmb_exo_2104\Marc_P2104_101_uncalibrated.mgf D:\MS_files\vmb_exo_2104\Marc_P2104_23_uncalibrated.mgf D:\MS_files\vmb_exo_2104\Marc_P2104_84_uncalibrated.mgf D:\MS_files\vmb_exo_2104\Marc_P2104_6_uncalibrated.mgf D:\MS_files\vmb_exo_2104\Marc_P2104_100_uncalibrated.mgf D:\MS_files\vmb_exo_2104\Marc_P2104_81_uncalibrated.mgf D:\MS_files\vmb_exo_2104\Marc_P2104_7_uncalibrated.mgf D:\MS_files\vmb_exo_2104\Marc_P2104_66_uncalibrated.mgf D:\MS_files\vmb_exo_2104\Marc_P2104_85_uncalibrated.mgf D:\MS_files\vmb_exo_2104\Marc_P2104_96_uncalibrated.mgf D:\MS_files\vmb_exo_2104\Marc_P2104_88_uncalibrated.mgf
Traceback (most recent call last):
  File "C:\fragpipe\lib\..\tools\speclib\gen_con_spec_lib.py", line 434, in <module>
    raise RuntimeError(spectra_files)
RuntimeError: []
Using (un)calibrated.mgfs.
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping
~~~~~~~~~~~~~~~~~~~~
Cancelling 1 remaining tasks
14:41:35 ERROR: Error writing log to file
java.nio.channels.ClosedByInterruptException: null
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(Unknown Source)
	at java.base/sun.nio.ch.FileChannelImpl.write(Unknown Source)
	at java.base/java.nio.channels.Channels.writeFullyImpl(Unknown Source)
	at java.base/java.nio.channels.Channels.writeFully(Unknown Source)
	at java.base/java.nio.channels.Channels.access$000(Unknown Source)
	at java.base/java.nio.channels.Channels$1.write(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.write(Unknown Source)
	at java.base/java.io.OutputStreamWriter.write(Unknown Source)
	at java.base/java.io.BufferedWriter.flushBuffer(Unknown Source)
	at java.base/java.io.BufferedWriter.write(Unknown Source)
	at java.base/java.io.Writer.write(Unknown Source)
	at com.dmtavt.fragpipe.tabs.TabRun.saveLogToFile(TabRun.java:354)
	at com.dmtavt.fragpipe.tabs.TabRun.on(TabRun.java:309)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:510)
	at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:447)
	at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:414)
	at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:387)
	at org.greenrobot.eventbus.EventBus.post(EventBus.java:268)
	at com.dmtavt.fragpipe.api.Bus.post(Bus.java:51)
	at com.dmtavt.fragpipe.cmd.ProcessBuilderInfo.lambda$toRunnable$0(ProcessBuilderInfo.java:96)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.nio.channels.ClosedChannelException: null
		at java.base/sun.nio.ch.FileChannelImpl.ensureOpen(Unknown Source)
		at java.base/sun.nio.ch.FileChannelImpl.write(Unknown Source)
		at java.base/java.nio.channels.Channels.writeFullyImpl(Unknown Source)
		at java.base/java.nio.channels.Channels.writeFully(Unknown Source)
		at java.base/java.nio.channels.Channels.access$000(Unknown Source)
		at java.base/java.nio.channels.Channels$1.write(Unknown Source)
		at java.base/sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
		at java.base/sun.nio.cs.StreamEncoder.implClose(Unknown Source)
		at java.base/sun.nio.cs.StreamEncoder.close(Unknown Source)
		at java.base/java.io.OutputStreamWriter.close(Unknown Source)
		at java.base/java.io.BufferedWriter.close(Unknown Source)
		at com.dmtavt.fragpipe.tabs.TabRun.saveLogToFile(TabRun.java:355)
		... 16 common frames omitted

**Comment by guoci** [comment]
@MarcIsak can you show me the list of files in `D:\MS_files\vmb_exo_2104\`?

**Comment by kparapatics** [comment]
Hi! I have the same problem. Is it solved in the meantime and how?
Thx, Katja

**Comment by MarcIsak** [comment]
Hi @guoci, 

sorry for not getting back to you regarding this issue. Actually, ran the spectral library workflow successfully by simply changing the input files to mzML. When I saw your response I had already overwritten the files in D:\MS_files\vmb_exo_2104\. My layman guess is that the issue has something to do with the MGFs that are generated if no mzML are added as input files. I could of course try to rerun the spectral library workflow without mzML files to see if the error persists.

**Comment by gureann** [comment]
This problem was caused by the wrong file names.
In SpecLib workflow, after philosopher finished and cleaned up, gen_con_spec_lib.py was called to do something. And the arguments passed to this python script are like xxx_**uncalibrated**.mgf, while the actually generated files are like _**calibrated**.mgf for each input raw data.
This makes the scripts cannot find the mgf files and raise a RuntimeError.

A casual solution is to modify the python script in fragpipe\tools\speclib\gen_con_spec_lib.py
At line 55, change to this `spectra_files0 = [pathlib.Path(e.replace('uncalibrated', 'calibrated')) for e in sys.argv[12:]]`
I'm not sure if this will affect something, but it works.

Looking forward to get a pretty solution from developpers @guoci

**Comment by fcyu** [comment]
Hi @gureann ,

Are you using the raw format? We don't support it in spectral library building (because MSFragger won't wrote the `_uncalibrated.mgf`). We will support it in the next release.

Best,

Fengchao

**Comment by gureann** [comment]
Hi, @fcyu ,

Yeah, I used thermo .raw files, and MSFragger wrote `calibrated.mgf` but passed `uncalibrated.mgf` as file names to easypqp
With mzml, it works well.

.raw support will make us more convenient to use.
Waiting for the new release. Thanks for your excellent work.

**Comment by fcyu** [comment]
You are welcome.

Fengchao
