### ISSUE TITLE
Index 90 out of bounds for length 90 Error

### ISSUE THREAD

**Issue by ppppippo** [Nesvilab/FragPipe#360]
Dear Fragpipe team,

I got the following error code: 

java.lang.IndexOutOfBoundsException: Index 90 out of bounds for length 90
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at l.<init>(Unknown Source)
	at ionquant.IonQuant.main(Unknown Source)
2021-04-24 18:08:38 [ERROR] - Index 90 out of bounds for length 90
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping
[log_2021-04-24_18-08-38.txt](https://github.com/Nesvilab/FragPipe/files/6370014/log_2021-04-24_18-08-38.txt)

I attached the log file from my search. Could you please advise?

Thank you very much for your support.

**Comment by fcyu** [comment]
This is a known bug. We will release a fix soon. If you want to try the fixed version now, could you download the pre-released one from [https://www.dropbox.com/s/1jv51gn1jn8pg25/FragPipe-15.1-build9.zip?dl=0](https://www.dropbox.com/s/1jv51gn1jn8pg25/FragPipe-15.1-build9.zip?dl=0)  ?

Best,

Fengchao

**Comment by ppppippo** [comment]
Thanks! Is it possible to avoid the error with current version 15.0?

**Comment by fcyu** [comment]
Yes, unchecking `Normalize` in IonQuant tab can avoid this error.

Best,

Fengchao
