### ISSUE TITLE
PhilosopherDbAnnotate Index out of range

### ISSUE THREAD

**Issue by klannieha** [Nesvilab/FragPipe#362]
Dear FragPipe team,

I am running FragPipe version 15.0 on a 64-bit Windows 10 desktop for one DDA file with a uniprot-swissprot target_decoy fasta database. All the searches, peptide prophet and protein prophet steps seem to work fine, but I am getting an error at the PhilosopherDbAnnotate step:

```Process 'ProteinProphet' finished, exit code: 0
INFO[14:47:18] Done                                         
PhilosopherDbAnnotate [Work dir: D:\projects\pca_urine_spectral_lib\data\library\msfragger]
D:\source\fragpipe\tools\philosopher\philosopher.exe database --annotate D:\projects\pca_urine_spectral_lib\data\library\Human_sp_isoform_iRT_SUC2_target_decoy.fasta --prefix DECOY_
INFO[14:47:18] Executing Database  v3.4.13                  
INFO[14:47:18] Processing database                          
panic: runtime error: index out of range [2] with length 0

goroutine 1 [running]:
philosopher/lib/dat.ProcessUniProtKB(0xc006be8991, 0x23, 0xc006a842d0, 0x86, 0xc000018108, 0x6, 0x0, 0x0, 0x0, 0x0, ...)
	/workspace/philosopher/lib/dat/db.go:274 +0xc6f
philosopher/lib/dat.(*Base).ProcessDB(0xc00007c480, 0xc000058060, 0x5c, 0xc000018108, 0x6)
	/workspace/philosopher/lib/dat/dat.go:132 +0x8ab
philosopher/lib/dat.Run(0xc00001cae0, 0x24, 0xc00001e540, 0x39, 0xc000024500, 0x46, 0xc000024550, 0x48, 0xc00001e580, 0x3f, ...)
	/workspace/philosopher/lib/dat/dat.go:64 +0xbf6
philosopher/cmd.glob..func4(0x7ca6420, 0xc0001b1140, 0x0, 0x4)
	/workspace/philosopher/cmd/database.go:23 +0xdc
github.com/spf13/cobra.(*Command).execute(0x7ca6420, 0xc0001b1100, 0x4, 0x4, 0x7ca6420, 0xc0001b1100)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x7ca8640, 0x0, 0x0, 0x0)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x336
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
philosopher/cmd.Execute()
	/workspace/philosopher/cmd/root.go:35 +0x34
main.main()
	/workspace/philosopher/main.go:22 +0x75
Process 'PhilosopherDbAnnotate' finished, exit code: 2
Process returned non-zero exit code, stopping
~~~~~~~~~~~~~~~~~~~~
Cancelling 4 remaining tasks```

I have tried it with mzML or mzXML files, but it returns the same error. Is there a way around this issue? 
Thanks a lot!
Annie

**Comment by prvst** [comment]
Can I see your database file?

**Comment by klannieha** [comment]
```
>sp|P31946|1433B_HUMAN 14-3-3 protein beta/alpha OS=Homo sapiens GN=YWHAB PE=1 SV=3
MTMDKSELVQKAKLAEQAERYDDMAAAMKAVTEQGHELSNEERNLLSVAYKNVVGARRSSWRVISSIEQKTERNEKKQQM
GKEYREKIEAELQDICNDVLELLDKYLIPNATQPESKVFYLKMKGDYFRYLSEVASGDNKQTTVSNSQQAYQEAFEISKK
EMQPTHPIRLGLALNFSVFYYEILNSPEKACSLAKTAFDEAIAELDTLNEESYKDSTLIMQLLRDNLTLWTSENQGDEGD
AGEGEN
>DECOY_sp|P31946|1433B_HUMAN 14-3-3 protein beta/alpha OS=Homo sapiens GN=YWHAB PE=1 SV=3
MDMTKSQVLEKAKLEAQEARYMAAAMDDKAEENSLEHGQETVRNYAVSLLKNAGVVRRSWSRVQEISSIKTERNEKKQGM
QKEYREKIDLLELVDNCIDQLEAEKYSEPQTANPILKVLYFKMKGFYDRYNDGSAVESLKQSIEFAEQYAQQSNSVTTKK
EIPHTPQMRLEPSNLIEYYFVSFNLALGKAALSCKTYSEENLTDLEAIAEDFAKDLLQMILTSRDEGEGADGEDGQNEST
WLTLNN
>sp|P31946-2|1433B_HUMAN Isoform Short of 14-3-3 protein beta/alpha OS=Homo sapiens GN=YWHAB
MDKSELVQKAKLAEQAERYDDMAAAMKAVTEQGHELSNEERNLLSVAYKNVVGARRSSWRVISSIEQKTERNEKKQQMGK
EYREKIEAELQDICNDVLELLDKYLIPNATQPESKVFYLKMKGDYFRYLSEVASGDNKQTTVSNSQQAYQEAFEISKKEM
QPTHPIRLGLALNFSVFYYEILNSPEKACSLAKTAFDEAIAELDTLNEESYKDSTLIMQLLRDNLTLWTSENQGDEGDAG
EGEN
>DECOY_sp|P31946-2|1433B_HUMAN Isoform Short of 14-3-3 protein beta/alpha OS=Homo sapiens GN=YWHAB
MDKSQVLEKAKLEAQEARYMAAAMDDKAEENSLEHGQETVRNYAVSLLKNAGVVRRSWSRVQEISSIKTERNEKKQGMQK
EYREKIDLLELVDNCIDQLEAEKYSEPQTANPILKVLYFKMKGFYDRYNDGSAVESLKQSIEFAEQYAQQSNSVTTKKEI
PHTPQMRLEPSNLIEYYFVSFNLALGKAALSCKTYSEENLTDLEAIAEDFAKDLLQMILTSRDEGEGADGEDGQNESTWL
TLNN
```
This is just the head of the fasta file, it contains a total of 84084 entries with 42042 decoys (50%) detected in Fragpipe when i loaded the database.

**Comment by prvst** [comment]
Can you share the whole file with me?

**Comment by klannieha** [comment]
[Human_sp_isoform_iRT_SUC2_target_decoy.zip](https://github.com/Nesvilab/FragPipe/files/6394369/Human_sp_isoform_iRT_SUC2_target_decoy.zip)

**Comment by prvst** [comment]
You have a couple of malformed protein headers in your file. Please change these:

`>DECOY_sp|Q8IYH5-4|iRT Biognosys GN=`
`>sp|Q8IYH5-4|iRT Biognosys GN=`

to this:

`>DECOY_sp|Q8IYH5-4|iRT Biognosys`
`>sp|Q8IYH5-4|iRT Biognosys`

**Comment by klannieha** [comment]
Great! Thank you so much!!
