### ISSUE TITLE
Philosopher in Fragpipe keeps failing

### ISSUE THREAD

**Issue by AishaMasud** [Nesvilab/FragPipe#373]
Hello, I am unable to use fragpipe because each time I do the configuration, the Philosopher.exe file goes missen. the tools in the fragpipe v15.0 I download each time also come with empty philosopher and msfragger jar folders. The following error pops up when I try to Run
ERROR: Error while starting process: WorkspaceCleanInit, stopping
java.io.IOException: Cannot run program "C:\Users\Aisha\Downloads\fragpipe_2\fragpipe\tools\philosopher\philosopher.exe" (in directory "C:\Users\Aisha\Desktop\My_output"): CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.dmtavt.fragpipe.process.ProcessResult.start(ProcessResult.java:55)
	at com.dmtavt.fragpipe.cmd.ProcessBuilderInfo.lambda$toRunnable$0(ProcessBuilderInfo.java:49)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:492)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:158)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
	... 7 common frames omitted

**Comment by fcyu** [comment]
Can you move the tools to another folder which is not under `C:\Users\Aisha\` and try again? If it still failed, you could download them from https://github.com/Nesvilab/philosopher/releases/latest and https://msfragger.arsci.com/upgrader/ by yourself.

Best,

Fengchao
