### ISSUE TITLE
Not a valid pathDir for Bruker data directory Failed in checking spectral files.

### ISSUE THREAD

**Issue by dkueltz** [Nesvilab/FragPipe#376]
Hi, I am getting an error when trying to analyze bruker.d raw files. They were generated using the Impact II. The .d folder names are recognized correctly and everything seems fine but when hitting the run button, then fragpipe always complains and throws the following error:

Failed in checking E:\LMR0020_OmBcells\DDA\LMR0020_HP-1k_2-F_8_01_3367.d
Not a valid pathDir for Bruker data directory
Failed in checking spectral files.
Checking spectral files...
E:\LMR0020_OmBcells\DDA\LMR0020_HP-1k_2-F_8_01_3367.d: Scans = 0
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping
~~~~~~~~~~~~~~~~~~~~
Cancelling 11 remaining tasks
18:44:55 ERROR: Error writing log to file
java.nio.channels.ClosedByInterruptException: null
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(Unknown Source)
	at sun.nio.ch.FileChannelImpl.write(Unknown Source)
	at java.nio.channels.Channels.writeFullyImpl(Unknown Source)
	at java.nio.channels.Channels.writeFully(Unknown Source)
	at java.nio.channels.Channels.access$000(Unknown Source)
	at java.nio.channels.Channels$1.write(Unknown Source)
	at sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
	at sun.nio.cs.StreamEncoder.implWrite(Unknown Source)
	at sun.nio.cs.StreamEncoder.write(Unknown Source)
	at java.io.OutputStreamWriter.write(Unknown Source)
	at java.io.BufferedWriter.flushBuffer(Unknown Source)
	at java.io.BufferedWriter.close(Unknown Source)
	at com.dmtavt.fragpipe.tabs.TabRun.saveLogToFile(TabRun.java:355)
	at com.dmtavt.fragpipe.tabs.TabRun.on(TabRun.java:309)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:510)
	at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:447)
	at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:414)
	at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:387)
	at org.greenrobot.eventbus.EventBus.post(EventBus.java:268)
	at com.dmtavt.fragpipe.api.Bus.post(Bus.java:51)
	at com.dmtavt.fragpipe.cmd.ProcessBuilderInfo.lambda$toRunnable$0(ProcessBuilderInfo.java:96)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by dkueltz** [comment]
PS: the same file analyzes fine when using PEAKS or Mascot or XTandem (standard DDA data)

**Comment by fcyu** [comment]
We only support the .d from timsTOF Pro. If you want to analyze your .d, need to convert it to mzML with msconvert.

Best,

Fengchao
