### ISSUE TITLE
non-zero exit code error

### ISSUE THREAD

**Issue by dkueltz** [Nesvilab/FragPipe#385]
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping
~~~~~~~~~~~~~~~~~~~~
Cancelling 31 remaining tasks
08:43:59 ERROR: Error writing log to file
java.nio.channels.ClosedByInterruptException: null
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(Unknown Source)
	at sun.nio.ch.FileChannelImpl.write(Unknown Source)
	at java.nio.channels.Channels.writeFullyImpl(Unknown Source)
	at java.nio.channels.Channels.writeFully(Unknown Source)
	at java.nio.channels.Channels.access$000(Unknown Source)
	at java.nio.channels.Channels$1.write(Unknown Source)
	at sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
	at sun.nio.cs.StreamEncoder.implWrite(Unknown Source)
	at sun.nio.cs.StreamEncoder.write(Unknown Source)
	at java.io.OutputStreamWriter.write(Unknown Source)
	at java.io.BufferedWriter.flushBuffer(Unknown Source)
	at java.io.BufferedWriter.write(Unknown Source)
	at java.io.Writer.write(Unknown Source)
	at com.dmtavt.fragpipe.tabs.TabRun.saveLogToFile(TabRun.java:354)
	at com.dmtavt.fragpipe.tabs.TabRun.on(TabRun.java:309)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:510)
	at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:447)
	at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:414)
	at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:387)
	at org.greenrobot.eventbus.EventBus.post(EventBus.java:268)
	at com.dmtavt.fragpipe.api.Bus.post(Bus.java:51)
	at com.dmtavt.fragpipe.cmd.ProcessBuilderInfo.lambda$toRunnable$0(ProcessBuilderInfo.java:96)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	Suppressed: java.nio.channels.ClosedChannelException: null
		at sun.nio.ch.FileChannelImpl.ensureOpen(Unknown Source)
		at sun.nio.ch.FileChannelImpl.write(Unknown Source)
		at java.nio.channels.Channels.writeFullyImpl(Unknown Source)
		at java.nio.channels.Channels.writeFully(Unknown Source)
		at java.nio.channels.Channels.access$000(Unknown Source)
		at java.nio.channels.Channels$1.write(Unknown Source)
		at sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
		at sun.nio.cs.StreamEncoder.implClose(Unknown Source)
		at sun.nio.cs.StreamEncoder.close(Unknown Source)
		at java.io.OutputStreamWriter.close(Unknown Source)
		at java.io.BufferedWriter.close(Unknown Source)
		at com.dmtavt.fragpipe.tabs.TabRun.saveLogToFile(TabRun.java:355)
		... 16 common frames omitted

**Comment by fcyu** [comment]
Can you send us the whole log file?

Best,

Fengchao

**Comment by dkueltz** [comment]
Hi Fengchao,

Where is the whole log file stored? It is not in the output directory. I copied all of the error message that was in the processing window.

Best,
Dietmar

_____________________________
Dietmar Kültz, PhD
Professor of Physiological Genomics
Department of Animal Sciences
University of California Davis
One Shields Ave., Meyer Hall
Davis, CA 95616, US
Phone: 530-752-2991 · Fax: 530-752-0175
The Kültz Lab @ PanoramaWeb<https://panoramaweb.org/Kueltz%20Lab%20-%20UCDavis>
Stress-induced Evolution · Targeted DIA Proteomics


________________________________

**Comment by fcyu** [comment]
Hi Dietmar,

You can export it by clicking "export log":
![image](https://user-images.githubusercontent.com/6926299/120538547-a71a9980-c3b4-11eb-8a65-e7b07e485a09.png)

Best,

Fengchao

**Comment by dkueltz** [comment]
okay, I'll rerun and then do the export log and email you the file.
thanks for looking into this,
dietmar

________________________________

**Comment by dkueltz** [comment]
Hi Fengchao,

The log file is attached FYI. I actually know the reason for the error now - it was insufficient memory, which makes sense since the error does not occur if I reduce the number of variable modifications.

Thanks for your help,
Dietmar

________________________________

**Comment by fcyu** [comment]
Right, the error message says
```
Not enough memory allocated to MSFragger.
If running using FragPipe: in MSFragger tab, increase the amount of memory allocated using RAM (Gb) parameter. If your computer does not have enough memory, use “Split database” option (requires python; see Configuration page of FragPipe). Set “Split database” parameter to 2. If the program continues to crash, gradually increase the “Split database” value (e.g. to 4, then to 8, etc.) until the program runs successfully.
Alternatively, or in combination with the “Split database” option, consider the following options: reduce the number of variable modifications specified; reduce the range of allowed peptide length (from 7-50 to e.g. 7-35).
```

Best,

Fengchao
