### ISSUE TITLE
ionquant command line: ClassNotFoundException: com.google.common.collect.Multimap

### ISSUE THREAD

**Issue by jj-umn** [Nesvilab/FragPipe#401]
- Describe the issue or question:
While trying to run IonQuant via command line as described on: https://github.com/Nesvilab/IonQuant 
Any suggestions on how to remedy that error?

(__openjdk@8.0.112) galaxy@garbo [~/src/fragpipe/tools] % java -jar ionquant-1.5.5.jar --help
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Multimap
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Multimap
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
You are not using the standalone version of IonQuant. Please download one from https://github.com/Nesvilab/IonQuant/releases

Best,

Fengchao
