### ISSUE TITLE
FragPipe 666 error

### ISSUE THREAD

**Issue by Khalikom** [Nesvilab/FragPipe#413]
Hi NesviLab,
I'm trying my first run in FragPipe and I came across the following error ... Could you please tell me an idea how to solve it, and what does the error mean?
I use a Thermo system and I use MSFileReaded. Maybe that could be the reason. If so, can you please advise any other Reader? 

2021-07-27 10:56:29,615 INFO  [root] Processing \\faf.cuni.cz\data\Users\khalikom\_MK098rawData\MK098_MK089_Trastuz_AcMapLysCtr3h_DIA_2.raw....
2021-07-27 10:56:29,623 INFO  [root] Writing DIA setting to file:\\faf.cuni.cz\data\Users\khalikom\_MK098rawData\MK098_MK089_Trastuz_AcMapLysCtr3h_DIA_2_diasetting.ser...
2021-07-27 10:56:29,649 INFO  [root] Writing parameter to file:\\faf.cuni.cz\data\Users\khalikom\_MK098rawData\MK098_MK089_Trastuz_AcMapLysCtr3h_DIA_2_params.ser...
2021-07-27 10:56:29,669 INFO  [root] Module A: Signal extraction
Batmass-IO version 1.23.4
2021-07-27 10:58:00,666 ERROR [root] java.lang.NumberFormatException: For input string: "351,000000"
	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
	at sun.misc.FloatingDecimal.parseFloat(Unknown Source)
	at java.lang.Float.parseFloat(Unknown Source)
	at MSUmpire.SpectrumParser.mzXMLParser.ParseElutionIndex(mzXMLParser.java:887)
	at MSUmpire.SpectrumParser.mzXMLParser.ReadElutionAndScanIndex(mzXMLParser.java:633)
	at MSUmpire.SpectrumParser.mzXMLParser.<init>(mzXMLParser.java:622)
	at MSUmpire.SpectrumParser.SpectrumParserBase.GetInstance(SpectrumParserBase.java:84)
	at MSUmpire.DIA.DIAPack.GetSpectrumParser(DIAPack.java:162)
	at MSUmpire.DIA.DIAPack.BuildDIAWindows(DIAPack.java:184)
	at MSUmpire.DIA.DIAPack.process(DIAPack.java:176)
	at dia_umpire_se.DIA_Umpire_SE.main(DIA_Umpire_SE.java:376)

2021-07-27 10:58:00,666 ERROR [root] Read spectral file:\\faf.cuni.cz\data\Users\khalikom\_MK098rawData\MK098_MK089_Trastuz_AcMapLysCtr3h_DIA_2.raw failed.
Process 'UmpireSe' finished, exit code: 2
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 33 remaining tasks

**Comment by fcyu** [comment]
```
2021-07-27 10:58:00,666 ERROR [root] java.lang.NumberFormatException: For input string: "351,000000"
```
Are you in the country where using `,` as the decimal separator?

Thanks,

Fengchao

**Comment by Khalikom** [comment]
Dear Fengchao,
thanx for idea. I have changed the region and it seems to work!
