### ISSUE TITLE
TMT10-plex error

### ISSUE THREAD

**Issue by rajeshksoni11** [Nesvilab/FragPipe#467]
12:55:32 ERROR: Error delivering events through the bus
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at com.dmtavt.fragpipe.tools.tmtintegrator.TmtiPanel.parseTmtAnnotationFile(TmtiPanel.java:616)
	at com.dmtavt.fragpipe.cmd.CmdTmtIntegrator.configure(CmdTmtIntegrator.java:114)
	at com.dmtavt.fragpipe.FragpipeRun.lambda$configureTaskGraph$43(FragpipeRun.java:1035)
	at com.dmtavt.fragpipe.FragpipeRun.configureTaskGraph(FragpipeRun.java:1247)
	at com.dmtavt.fragpipe.FragpipeRun.run(FragpipeRun.java:199)
	at com.dmtavt.fragpipe.tabs.TabRun.on(TabRun.java:153)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:510)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:504)
	at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

[log_2021-09-22_12-58-10.txt](https://github.com/Nesvilab/FragPipe/files/7212548/log_2021-09-22_12-58-10.txt)

Do you have example  annotation file for tmt-10plex?

Best,
Rajesh

**Comment by fcyu** [comment]
You can create one and edit it in FragPipe:
![image](https://user-images.githubusercontent.com/6926299/134388755-5df105fa-b681-4612-b6d4-2bce541980b4.png)


Best,

Fengchao

**Comment by rajeshksoni11** [comment]
Hi,
When i create or edit, here is the errors:


java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at com.dmtavt.fragpipe.tools.tmtintegrator.TmtiPanel.parseTmtAnnotationFile(TmtiPanel.java:616)
at com.dmtavt.fragpipe.tools.tmtintegrator.TmtiPanel.actionEditCreate(TmtiPanel.java:858)
at com.dmtavt.fragpipe.tools.tmtintegrator.TmtiPanel$2.actionPerformed(TmtiPanel.java:248)
at com.github.chhh.utils.swing.renderers.ButtonColumn.actionPerformed(ButtonColumn.java:195)
at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.desktop/java.awt.Component.processEvent(Unknown Source)
at java.desktop/java.awt.Container.processEvent(Unknown Source)
at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.repostEvent(Unknown Source)
at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.mouseReleased(Unknown Source)
at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.desktop/java.awt.Component.processEvent(Unknown Source)
at java.desktop/java.awt.Container.processEvent(Unknown Source)
at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)





________________________________
From: Fengchao ***@***.***>
Sent: Wednesday, September 22, 2021 1:02 PM
To: Nesvilab/FragPipe ***@***.***>
Cc: Soni, Rajesh K. ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [Nesvilab/FragPipe] TMT10-plex error (#467)


You can create one and edit it in FragPipe:
[image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_6926299_134388755-2D5df105fa-2Db681-2D4612-2Db6d4-2D2bce541980b4.png&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=3kGEWBYAR_TOTPC4fFAqpAKTOUJHGP7jqdAzaZ1xUoQ&m=8AV_G1t1EXstRjv3d9OZRN3uak_045O5H6NcJsATSrg&s=h8UMIEjID4vXSLNeeQEd5MnhIskUpomxFvCQM6dJqpA&e=>

Best,

Fengchao

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Nesvilab_FragPipe_issues_467-23issuecomment-2D925113748&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=3kGEWBYAR_TOTPC4fFAqpAKTOUJHGP7jqdAzaZ1xUoQ&m=8AV_G1t1EXstRjv3d9OZRN3uak_045O5H6NcJsATSrg&s=mGRnDkenZN6r7BRwWWMQxNuK17CbGiZ_5coN1ajUHig&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ATHFHTG7LNPYMR5M7SSTQUDUDIDY7ANCNFSM5ERYY2XA&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=3kGEWBYAR_TOTPC4fFAqpAKTOUJHGP7jqdAzaZ1xUoQ&m=8AV_G1t1EXstRjv3d9OZRN3uak_045O5H6NcJsATSrg&s=m0UGk6hhImnzit8AKXB1hz4Mf5RP0gFJHLwNFITH140&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=3kGEWBYAR_TOTPC4fFAqpAKTOUJHGP7jqdAzaZ1xUoQ&m=8AV_G1t1EXstRjv3d9OZRN3uak_045O5H6NcJsATSrg&s=3pQgmbhTfYt4trTP5Xfs9AcGE8x-AdGqOW_uPdVKoWY&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=3kGEWBYAR_TOTPC4fFAqpAKTOUJHGP7jqdAzaZ1xUoQ&m=8AV_G1t1EXstRjv3d9OZRN3uak_045O5H6NcJsATSrg&s=cI9pDvDQoBnvAWlAfOntizpUqvdTli9moM4jwRKwSMY&e=>.

**Comment by fcyu** [comment]
Can you try it in a new folder without any files?

**Comment by rajeshksoni11** [comment]
HI,
I am not able to browse the folder:

java.nio.file.InvalidPathException: Illegal char <:> at index 0: ::{20D04FE0-3AEA-1069-A2D8-08002B30309D}
at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
at java.base/java.io.File.toPath(Unknown Source)
at com.dmtavt.fragpipe.tools.tmtintegrator.TmtiPanel$3.accept(TmtiPanel.java:777)
at java.desktop/javax.swing.JFileChooser.accept(Unknown Source)
at java.desktop/javax.swing.plaf.basic.BasicDirectoryModel$FilesLoader.run0(Unknown Source)
at java.desktop/javax.swing.plaf.basic.BasicDirectoryModel$FilesLoader.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)






________________________________
From: Fengchao ***@***.***>
Sent: Wednesday, September 22, 2021 1:05 PM
To: Nesvilab/FragPipe ***@***.***>
Cc: Soni, Rajesh K. ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [Nesvilab/FragPipe] TMT10-plex error (#467)


Can you try it in a new folder without any files?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Nesvilab_FragPipe_issues_467-23issuecomment-2D925116401&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=3kGEWBYAR_TOTPC4fFAqpAKTOUJHGP7jqdAzaZ1xUoQ&m=qrP_2apFa-DI16lxZ9Yph0ot5-6_SBlQsXZ0lJRQft8&s=tKz26ksDPsQyO-J9VqLI5pM3GyXByEAhuQAsoxqeXdE&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ATHFHTBPIKNMSGYHJSIEDPLUDIEGVANCNFSM5ERYY2XA&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=3kGEWBYAR_TOTPC4fFAqpAKTOUJHGP7jqdAzaZ1xUoQ&m=qrP_2apFa-DI16lxZ9Yph0ot5-6_SBlQsXZ0lJRQft8&s=yllI50a88pLAN_preBPRCIXE3V5b20bHV3hPvvZgXyw&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=3kGEWBYAR_TOTPC4fFAqpAKTOUJHGP7jqdAzaZ1xUoQ&m=qrP_2apFa-DI16lxZ9Yph0ot5-6_SBlQsXZ0lJRQft8&s=haxkjTXrIk4ofS3S--LUIT_q8R9hZvRXJqczSZ8WbK0&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=3kGEWBYAR_TOTPC4fFAqpAKTOUJHGP7jqdAzaZ1xUoQ&m=qrP_2apFa-DI16lxZ9Yph0ot5-6_SBlQsXZ0lJRQft8&s=R2duHvnmzmUJv8qZmrZ0PpoSaR3fbGq0-U6BUKZU2uY&e=>.

**Comment by fcyu** [comment]
Can you create a new folder, move all your mzML/raw files to there, restart FragPipe, and try again?

**Comment by rajeshksoni11** [comment]
HI,
When i select the annotation file in new folder, i see this error"

please check my ANNOTATION FILE.

java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at com.dmtavt.fragpipe.tools.tmtintegrator.TmtiPanel.parseTmtAnnotationFile(TmtiPanel.java:616)
at com.dmtavt.fragpipe.tools.tmtintegrator.TmtiPanel.actionEditCreate(TmtiPanel.java:858)
at com.dmtavt.fragpipe.tools.tmtintegrator.TmtiPanel$2.actionPerformed(TmtiPanel.java:248)
at com.github.chhh.utils.swing.renderers.ButtonColumn.actionPerformed(ButtonColumn.java:195)
at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.desktop/java.awt.Component.processEvent(Unknown Source)
at java.desktop/java.awt.Container.processEvent(Unknown Source)
at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.repostEvent(Unknown Source)
at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.mouseReleased(Unknown Source)
at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.desktop/java.awt.Component.processEvent(Unknown Source)
at java.desktop/java.awt.Container.processEvent(Unknown Source)
at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)





________________________________
From: Fengchao ***@***.***>
Sent: Wednesday, September 22, 2021 1:10 PM
To: Nesvilab/FragPipe ***@***.***>
Cc: Soni, Rajesh K. ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [Nesvilab/FragPipe] TMT10-plex error (#467)


Can you create a new folder, move all your mzML/raw files to there, restart FragPipe, and try again?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Nesvilab_FragPipe_issues_467-23issuecomment-2D925120088&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=3kGEWBYAR_TOTPC4fFAqpAKTOUJHGP7jqdAzaZ1xUoQ&m=qWqR3kM5Yu220rIue-zqUltk4XdVZDdXNwFtvTA2ZsQ&s=NYbQUx6QqLUT4n6nhOp4RWLtYrwsZpYCAyDX5a9bY4s&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ATHFHTDXWJBKDDYVKHYFBCTUDIEWVANCNFSM5ERYY2XA&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=3kGEWBYAR_TOTPC4fFAqpAKTOUJHGP7jqdAzaZ1xUoQ&m=qWqR3kM5Yu220rIue-zqUltk4XdVZDdXNwFtvTA2ZsQ&s=0J37jZ1a-K4zuFyl9Tc7bnB1h1Y6s8w_Blet_2GmLkg&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=3kGEWBYAR_TOTPC4fFAqpAKTOUJHGP7jqdAzaZ1xUoQ&m=qWqR3kM5Yu220rIue-zqUltk4XdVZDdXNwFtvTA2ZsQ&s=zzmCo4s_GBHFdg-F9Yg9uCqt98mBm3o-NREiJCFXU1A&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=3kGEWBYAR_TOTPC4fFAqpAKTOUJHGP7jqdAzaZ1xUoQ&m=qWqR3kM5Yu220rIue-zqUltk4XdVZDdXNwFtvTA2ZsQ&s=O4vEjCXNeTBqgZ9yq-DS2hQwZXSY9HcqEPDqfYGwGYU&e=>.

channel	Sample
126	Pool
127N	A
127C	A
128N	A
128C	B
129N	B
129C	B
130N	C
130C	C
131	C

**Comment by fcyu** [comment]
Please do NOT select existing annotation file because it seems that your file is corrupted. Please click `edit/create` to get a new one. That is why I told you to "create a new folder, move all your mzML/raw files to there, restart FragPipe, and try again". Only keeping mzml/raw files in your folder.

**Comment by rajeshksoni11** [comment]
Thank you Fengchao. It is working now.




Rajesh Kumar Soni , PhD
Proteomics Core Manager
Lasker Biomedical Research Building
3960 Broadway, 3rd Floor, Room 350D (Entrance on 166th St.)
Columbia University Medical Center
New York, NY 10032
Email:  ***@***.***
Tel: 212-342-4177


________________________________
From: Fengchao ***@***.***>
Sent: Wednesday, September 22, 2021 1:23 PM
To: Nesvilab/FragPipe ***@***.***>
Cc: Soni, Rajesh K. ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [Nesvilab/FragPipe] TMT10-plex error (#467)


Please do NOT select existing annotation file because it seems that your file is corrupted. Please click edit/create to get a new one. That is why I told you to "create a new folder, move all your mzML/raw files to there, restart FragPipe, and try again". Only keeping mzml/raw files in your folder.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Nesvilab_FragPipe_issues_467-23issuecomment-2D925129823&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=3kGEWBYAR_TOTPC4fFAqpAKTOUJHGP7jqdAzaZ1xUoQ&m=nGtE7K_4w2Ww-tn17dn8blwOcuATZfUEyjD8KMngh8s&s=MM5zxsf4tZ-5aWgU0VC3Hc8sVqbw1l0WfR6MTHbQz-I&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ATHFHTFP3KFG7TWO74V4E6TUDIGIVANCNFSM5ERYY2XA&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=3kGEWBYAR_TOTPC4fFAqpAKTOUJHGP7jqdAzaZ1xUoQ&m=nGtE7K_4w2Ww-tn17dn8blwOcuATZfUEyjD8KMngh8s&s=wndkQCzSLLZ3X9Lk9tPmcnAsEM3xniLJ9eUAHG907uo&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=3kGEWBYAR_TOTPC4fFAqpAKTOUJHGP7jqdAzaZ1xUoQ&m=nGtE7K_4w2Ww-tn17dn8blwOcuATZfUEyjD8KMngh8s&s=XYUyb_TKo6UaG3YvtkngLuDNxOFlOPGkmbdW2xwcOVc&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=3kGEWBYAR_TOTPC4fFAqpAKTOUJHGP7jqdAzaZ1xUoQ&m=nGtE7K_4w2Ww-tn17dn8blwOcuATZfUEyjD8KMngh8s&s=RoCgZVpHhyVWM3qhYcVdWWwEnOe83zePPX7uEZtSeCA&e=>.

**Comment by anesvi** [comment]
Rajesh,
Can I ask you to check the encoding in your annotation.tsv text file?
How did you create it?
I actually had this issue myself once, creating annotation.tsv from Excel, and the file was saved with a strange encoding that was breaking FragPIpe
Thanks
Alexey

**Comment by rajeshksoni11** [comment]
Hi Alexey,
Here is the annotation file from excel.
Thank you very much for all your help.
Best,
Rajesh







________________________________
From: Alexey Nesvizhskii ***@***.***>
Sent: Wednesday, September 22, 2021 1:36 PM
To: Nesvilab/FragPipe ***@***.***>
Cc: Soni, Rajesh K. ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [Nesvilab/FragPipe] TMT10-plex error (#467)


Rajesh,
Can I ask you to check the encoding in your annotation.tsv text file?
How did you create it?
I actually had this issue myself once, creating annotation.tsv from Excel, and the file was saved with a strange encoding that was breaking FragPIpe
Thanks
Alexey

**Comment by anesvi** [comment]
I do not see any attachment, please email directly to me or Fengchao

**Comment by rajeshksoni11** [comment]
Rajesh Kumar Soni , PhD
Proteomics Core Manager
Lasker Biomedical Research Building
3960 Broadway, 3rd Floor, Room 350D (Entrance on 166th St.)
Columbia University Medical Center
New York, NY 10032
Email:  ***@***.***
Tel: 212-342-4177


________________________________
From: Alexey Nesvizhskii ***@***.***>
Sent: Wednesday, September 22, 2021 1:48 PM
To: Nesvilab/FragPipe ***@***.***>
Cc: Soni, Rajesh K. ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [Nesvilab/FragPipe] TMT10-plex error (#467)


I do not see any attachment, please email directly to me or Fengchao
