### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by jjGG** [Nesvilab/FragPipe#481]
Dear developers, 

I keep getting java heap space error (Java out of memory) with philosopher with a relatively large database that I am searching (6.4 gig target-decoy DB). I did manage successfully a 10gig DB with a previous version of FragPipe. (FP14)

Is there anything I can do about this apart from going smaller with my DB?

From the log: 
[SEVERE] Could not dispatch event: class com.dmtavt.fragpipe.messages.MessagePrintToConsole to subscribing class class com.dmtavt.fragpipe.tabs.TabRun
java.lang.OutOfMemoryError: Java heap space
        at java.desktop/javax.swing.text.GapContent.allocateArray(GapContent.java:96)
        at java.desktop/javax.swing.text.GapVector.resize(GapVector.java:215)
        at java.desktop/javax.swing.text.GapContent.resize(GapContent.java:110)
        at java.desktop/javax.swing.text.GapVector.shiftEnd(GapVector.java:230)
        at java.desktop/javax.swing.text.GapContent.shiftEnd(GapContent.java:357)
        at java.desktop/javax.swing.text.GapVector.open(GapVector.java:202)
        at java.desktop/javax.swing.text.GapVector.replace(GapVector.java:143)
        at java.desktop/javax.swing.text.GapContent.insertString(GapContent.java:140)
        at java.desktop/javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:732)
        at java.desktop/javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:716)
        at java.desktop/javax.swing.text.AbstractDocument.replace(AbstractDocument.java:675)
        at java.desktop/javax.swing.JTextPane.replaceSelection(JTextPane.java:190)
        at java.desktop/javax.swing.JTextPane.replaceSelection(JTextPane.java:173)
        at com.github.chhh.utils.swing.TextConsole.append(TextConsole.java:178)
        at com.github.chhh.utils.swing.TextConsole.appendANSI(TextConsole.java:197)
        at com.github.chhh.utils.swing.TextConsole.append(TextConsole.java:163)
        at com.dmtavt.fragpipe.tabs.TabRun.on(TabRun.java:114)
        at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:510)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:504)
        at org.greenrobot.eventbus.BackgroundPoster.run(BackgroundPoster.java:64)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
10:11:14.097 [pool-1-thread-14] ERROR com.dmtavt.fragpipe.Fragpipe - Error delivering events through the bus
java.lang.OutOfMemoryError: Java heap space

**Please complete the following information:**

 - Linux
 - FP 16.0
 - MSFragger 3.3
 - philospher 4.0.0

Any ideas?
best regards 
jonas

**Comment by fcyu** [comment]
Can you send us the log file?

Thanks,

Fengchao

**Comment by jjGG** [comment]
Hello developpers,

Sorry for being mute for a while - I was on holiday for two weeks. 

Update meanwhile - I got "multiple" java heap space errors on the FragPipeGUI but the processes in the background continued .. 

Meanwhile the whole job finished and combined-protein.tsv was written as well as the reprint-files but the log-file is missing. ;(

My question here: Can I trust the written results? What do you need from my side to look into it?

Best regards - jonas

**Comment by fcyu** [comment]
Hi Jonas,

Those files look good to me. If the combined_protein.tsv file was also updated after Oct 13 03:10 and looks complete, I guess you can use the result. But I cannot guarantee that everything is good since there are errors and no log file.

Best,

Fengchao
