### ISSUE TITLE
Error Message: ERROR com.dmtavt.batmass.io.thermo.ThermoGrpcServerProcess

### ISSUE THREAD

**Issue by BenSamy2020** [Nesvilab/FragPipe#484]
Greetings @fcyu,

While running fragpipe, I intermittently experience the following error below. Overall, fragpipe displays the error message and still carries on with the search and successfully completes the search. Does the below error message affect the outcome of the search results?

Regards,
Ben   

[pool-11-thread-1] ERROR com.dmtavt.batmass.io.thermo.ThermoGrpcServerProcess - Error while scanning stream
java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep(Native Method)
	at com.dmtavt.batmass.io.thermo.ThermoGrpcServerProcess.scanStreamForPattern(ThermoGrpcServerProcess.java:307)
	at com.dmtavt.batmass.io.thermo.ThermoGrpcServerProcess.lambda$start$7(ThermoGrpcServerProcess.java:248)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
[main] ERROR com.dmtavt.batmass.io.thermo.ThermoGrpcServerProcess - Did not get port information from server output within timeout.
[pool-12-thread-1] ERROR com.dmtavt.batmass.io.thermo.ThermoGrpcServerProcess - Error while scanning stream
java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep(Native Method)
	at com.dmtavt.batmass.io.thermo.ThermoGrpcServerProcess.scanStreamForPattern(ThermoGrpcServerProcess.java:307)
	at com.dmtavt.batmass.io.thermo.ThermoGrpcServerProcess.lambda$start$7(ThermoGrpcServerProcess.java:248)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by fcyu** [comment]
Hi Ben,

It should be fine. You can stop ThermoGrpcServerProcess by killing it in the task manager in Windows, or in `top`/`htop` in Linux.

Best,

Fengchao
