### ISSUE TITLE
Error DIA_SpectLib_Quan workflow 

### ISSUE THREAD

**Issue by Angrist75** [Nesvilab/FragPipe#532]
- Describe the issue or question:
- 
dear developers
I am trying to use analysis acquired in DIA to build SpectraLibrary and do quantification using DIANN. Unfortunately, as you can see from the log file the execution stops. I don't understand the origin of the error. The process done with only DIANN or Spectronaut is successful. Thanks for your help
Andrea

- Upload your log file
[log_2021-11-18_15-46-21.txt](https://github.com/Nesvilab/FragPipe/files/7563660/log_2021-11-18_15-46-21.txt)
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Hi Guo Ci @guoci ,

The error is from spectral library generation. Can you take a look?

```
Info: There are psm.tsv and peptide.tsv. Will ignore --psm_fdr_threshold, --peptide_fdr_threshold, --protein_fdr_threshold, --pi0_lambda, --proteotypic, and --no-proteotypic.
Info: Reading file C:\Proteomica\RAW_DATA_2021\OT_Fusion\Candiano_21\Novembre21\Lipidomica_Precip_Proteico\MF\Liquor_D_1\Candiano_1121_Liquor_D_1_DIA_50_316_rank1.psmpkl.
Info: Reading file C:\Proteomica\RAW_DATA_2021\OT_Fusion\Candiano_21\Novembre21\Lipidomica_Precip_Proteico\MF\Liquor_D_1\Candiano_1121_Liquor_D_1_DIA_50_316_rank2.psmpkl.
Info: Reading file C:\Proteomica\RAW_DATA_2021\OT_Fusion\Candiano_21\Novembre21\Lipidomica_Precip_Proteico\MF\Liquor_D_1\Candiano_1121_Liquor_D_1_DIA_50_316_rank3.psmpkl.
Info: Reading file C:\Proteomica\RAW_DATA_2021\OT_Fusion\Candiano_21\Novembre21\Lipidomica_Precip_Proteico\MF\Liquor_D_1\Candiano_1121_Liquor_D_1_DIA_50_316_rank4.psmpkl.
Info: Reading file C:\Proteomica\RAW_DATA_2021\OT_Fusion\Candiano_21\Novembre21\Lipidomica_Precip_Proteico\MF\Liquor_D_1\Candiano_1121_Liquor_D_1_DIA_50_316_rank5.psmpkl.
Info: 6769 redundant PSMs identified after filtering with C:\Proteomica\RAW_DATA_2021\OT_Fusion\Candiano_21\Novembre21\Lipidomica_Precip_Proteico\MF\Liquor_D_1\psm.tsv and C:\Proteomica\RAW_DATA_2021\OT_Fusion\Candiano_21\Novembre21\Lipidomica_Precip_Proteico\MF\Liquor_D_1\peptide.tsv
                             base_name  modified_peptide
0  Candiano_1121_Liquor_D_1_DIA_50_316              3842
Info: easypqp_rt_alignment_Candiano_1121_Liquor_D_1_DIA_50_316; Peptide overlap between run and reference: 3842.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\programdata\anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 555, in run
    result_item, is_broken, bpe = self.wait_result_broken_or_wakeup()
  File "c:\programdata\anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 609, in wait_result_broken_or_wakeup
    ready = wait(readers + worker_sentinels)
  File "c:\programdata\anaconda3\lib\multiprocessing\connection.py", line 879, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "c:\programdata\anaconda3\lib\multiprocessing\connection.py", line 811, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 65
```

Thanks,

Fengchao

**Comment by guoci** [comment]
Can you set `RT lowess fraction` to a non-zero value e.g. `0.05` and try again?
![image](https://user-images.githubusercontent.com/1260178/129079122-1de894ca-6df3-412c-a22d-8ee7cc2ff99f.png)

**Comment by Angrist75** [comment]
I did as recommended and it worked! I will do more tests on other samples but now I am very optimistic.
thank you very much!
all the best
Andrea
