### ISSUE TITLE
issue with spectral library building

### ISSUE THREAD

**Issue by hupak2022** [Nesvilab/FragPipe#600]
Hello,

I'm a new user.
I'm using FragPipe v1.71,
MSFragger 3.4
Philosopher 4.1.1
Python 3.9.7

Everything works well except when I want to build a spectral library from my DDA data.
Please find below the error I got... Could someone please help me to solve this?
Many thanks

Exception in thread ExecutorManagerThread:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 563, in run
    result_item, is_broken, bpe = self.wait_result_broken_or_wakeup()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 617, in wait_result_broken_or_wakeup
    ready = wait(readers + worker_sentinels)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\connection.py", line 884, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\connection.py", line 816, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 113

**Comment by guoci** [comment]
@hupak2022 try set the `RT Lowess fraction` to a non zero value.
![image](https://user-images.githubusercontent.com/1260178/153486432-19884a97-9940-4fd9-8d08-6ff9e844c4d0.png)

**Comment by hupak2022** [comment]
It works! thanks a lot for your help
