### ISSUE TITLE
Error trying to run FragPipe

### ISSUE THREAD

**Issue by candidaorelmex** [Nesvilab/FragPipe#602]
Hi,

I set up up FragPipe and MSFragger on my Ubuntu OS, the configuration page looks like everything in place (except for a missing matplotlib python module thatId need for EasPQP, however, I dont want to generate any libraries at the moment).

I selected raw files, picked a workflow, and entered a database including decoys. 

When I try to start my search I get the following output:

CheckCentroid
java -Xmx31G -cp /home/localadmin/fragpipe/lib/fragpipe-17.1.jar:/home/localadmin/fragpipe/tools/batmass-io-1.23.6.jar com.dmtavt.fragpipe.util.CheckCentroid /home/localadmin/fragpipe/raw_files/mouse_organs/20211027_INT004-00609-HLAIp_R01.raw 5
Done in 0 ms.
Process 'CheckCentroid' finished, exit code: 0
WorkspaceCleanInit [Work dir: /home/localadmin/fragpipe/search_results/mouse_livers_test]
/home/localadmin/fragpipe/tools/philosopher/philosopher workspace --clean --nocheck
time="11:44:39" level=info msg="Executing Workspace  v4.1.1"
time="11:44:39" level=info msg="Removing workspace"
time="11:44:39" level=info msg=Done
Process 'WorkspaceCleanInit' finished, exit code: 0
WorkspaceCleanInit [Work dir: /home/localadmin/fragpipe/search_results/mouse_livers_test]
/home/localadmin/fragpipe/tools/philosopher/philosopher workspace --init --nocheck
time="11:44:39" level=info msg="Executing Workspace  v4.1.1"
time="11:44:39" level=info msg="Creating workspace"
time="11:44:39" level=info msg=Done
Process 'WorkspaceCleanInit' finished, exit code: 0
MSFragger [Work dir: /home/localadmin/fragpipe/search_results/mouse_livers_test]
java -jar -Dfile.encoding=UTF-8 -Xmx31G /home/localadmin/fragpipe/tools/MSFragger-3.4/MSFragger-3.4.jar /home/localadmin/fragpipe/search_results/mouse_livers_test/fragger.params /home/localadmin/fragpipe/raw_files/mouse_organs/20211027_INT004-00609-HLAIp_R01.raw /home/localadmin/fragpipe/raw_files/mouse_organs/20211027_INT004-00609-HLAIp_R02.raw
MSFragger version MSFragger-3.4
Batmass-IO version 1.23.6
timsdata library version timsdata-2-7-0
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
System OS: Linux, Architecture: amd64
Java Info: 11.0.13, OpenJDK 64-Bit Server VM, Ubuntu
JVM started with 31 GB memory
Checking database...
11:44:40:005 [pool-1-thread-3] ERROR ThermoGrpcServerProcess - Problmes starting process
11:44:40:005 [pool-1-thread-5] ERROR ThermoGrpcServerProcess - Problmes starting process
java.io.IOException: Cannot run program "mono": error=2, Aucun fichier ou dossier de ce type
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.dmtavt.batmass.io.thermo.ThermoGrpcServerProcess.start(ThermoGrpcServerProcess.java:242)
	at umich.ms.fileio.filetypes.thermo.ThermoRawFile.init(ThermoRawFile.java:204)
	at umich.ms.fileio.filetypes.thermo.ThermoRawFile.<init>(ThermoRawFile.java:161)
	at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: error=2, Aucun fichier ou dossier de ce type
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 9 more
java.io.IOException: Cannot run program "mono": error=2, Aucun fichier ou dossier de ce type
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.dmtavt.batmass.io.thermo.ThermoGrpcServerProcess.start(ThermoGrpcServerProcess.java:242)
	at umich.ms.fileio.filetypes.thermo.ThermoRawFile.init(ThermoRawFile.java:204)
	at umich.ms.fileio.filetypes.thermo.ThermoRawFile.<init>(ThermoRawFile.java:161)
	at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: error=2, Aucun fichier ou dossier de ce type
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 9 more
Failed in checking /home/localadmin/fragpipe/raw_files/mouse_organs/20211027_INT004-00609-HLAIp_R02.raw
Failed in checking /home/localadmin/fragpipe/raw_files/mouse_organs/20211027_INT004-00609-HLAIp_R01.raw
null
null
Failed in checking spectral files.
11:44:40:008 [Thread-0] ERROR ThermoRawFile - Something happened while trying to destory child processes in runtime shutdown hook
java.lang.NullPointerException
	at umich.ms.fileio.filetypes.thermo.ThermoRawFile.lambda$static$0(ThermoRawFile.java:99)
	at java.base/java.lang.Thread.run(Thread.java:829)
11:44:40:008 [Thread-0] ERROR ThermoRawFile - Something happened while trying to destory child processes in runtime shutdown hook
java.lang.NullPointerException
	at umich.ms.fileio.filetypes.thermo.ThermoRawFile.lambda$static$0(ThermoRawFile.java:99)
	at java.base/java.lang.Thread.run(Thread.java:829)
Checking spectral files...
/home/localadmin/fragpipe/raw_files/mouse_organs/20211027_INT004-00609-HLAIp_R01.raw: Scans = 0
/home/localadmin/fragpipe/raw_files/mouse_organs/20211027_INT004-00609-HLAIp_R02.raw: Scans = 0
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 19 remaining tasks



How can I resolve this issue? What is the cause?

Thanks a lot for your help! If you need any additional information let me know.


Kind regards,
Ilja

**Comment by guoci** [comment]
We will add a warning on the next release.
https://github.com/Nesvilab/FragPipe/commit/b3341766e8d8dbc996eebea281f8e90aa8059265
