### ISSUE TITLE
Error in DIA workflow with iRT and DIA-NN

### ISSUE THREAD

**Issue by DrDee79** [Nesvilab/FragPipe#615]
I am having some trouble with the newest Fragpipe 17.1 doing the DIA workflow. It looks to the log like it passes correctly to DIA-NN but then says that zero files will be processed. In addition, the workflow stops when it tries to align to the iRT with the 'Pierce iRT' option selected, but as this was the spike that's what I hope to use. Any help most appreciated, 

Dorothy

----------------------
## If you're submitting a bug report, please attach log file

The log file can be saved from FragPipe:

- by clicking the `Export Log` button on the `Run` tab.
- or just copy text from the output console on `Run` tab to a text file.
[log_2022-03-04_16-18-08.txt](https://github.com/Nesvilab/FragPipe/files/8188794/log_2022-03-04_16-18-08.txt)

**Comment by fcyu** [comment]
@guoci , there are errors from EasyPQP. Can you take a look? Also, can you catch the errors and exit EasyPQP with code 1?
```
Traceback (most recent call last):
  File "C:\Users\q-tof\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'irt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\q-tof\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\q-tof\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\q-tof\AppData\Local\Programs\Python\Python39\Scripts\easypqp.exe\__main__.py", line 7, in <module>
  File "C:\Users\q-tof\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\q-tof\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\q-tof\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1699, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\q-tof\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\q-tof\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\q-tof\AppData\Local\Programs\Python\Python39\lib\site-packages\easypqp\main.py", line 111, in library
    generate(infiles, outfile, psmtsv, peptidetsv, rt_referencefile, rt_reference_run_path, rt_filter, im_referencefile, im_reference_run_path, im_filter, psm_fdr_threshold, peptide_fdr_threshold, protein_fdr_threshold, rt_lowess_fraction, rt_psm_fdr_threshold, im_lowess_fraction, im_psm_fdr_threshold, pi0_lambda, peptide_plot_path, protein_plot_path, min_peptides, proteotypic, consensus, nofdr)
  File "C:\Users\q-tof\AppData\Local\Programs\Python\Python39\lib\site-packages\easypqp\library.py", line 395, in generate
    pepida = pepida.loc[np.isfinite(pepida['irt'])]
  File "C:\Users\q-tof\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\frame.py", line 3455, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\q-tof\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'irt'
```

Best,

Fengchao

**Comment by guoci** [comment]
@DrDee79 Can you send me the following files?
`C:\Users\q-tof\Desktop\DIA\2022-02-HeLa\Test3\irt.tsv`
`C:\Users\q-tof\Desktop\DIA\2022-02-HeLa\Test3\psm.tsv` 
`C:\Users\q-tof\Desktop\DIA\2022-02-HeLa\Test3\peptide.tsv`
`C:\Users\q-tof\Desktop\DIA\2022-02-HeLa\Test3\irt.tsv`
`C:\Users\q-tof\Desktop\DIA\2022-02-HeLa\Test3\filelist_easypqp_library.txt`
and the list of files listed in
`C:\Users\q-tof\Desktop\DIA\2022-02-HeLa\Test3\filelist_easypqp_library.txt`

**Comment by guoci** [comment]
@fcyu This has been done, but not in the released version.
> @guoci , there are errors from EasyPQP. Can you take a look? Also, can you catch the errors and exit EasyPQP with code 1?

**Comment by anesvi** [comment]
We can share a pre-release to test

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by guoci** [comment]
@DrDee79 I did not see the peptides at all, you can look at the generated table in TSV format.
[githubticket615.zip](https://github.com/Nesvilab/FragPipe/files/8217812/githubticket615.zip)

**Comment by DrDee79** [comment]
Hi @guoci can you clarify? I'm not sure how to proceed.

**Comment by guoci** [comment]
@DrDee79 I did not see the Pierce iRT peptides, so the error is expected.
