### ISSUE TITLE
MSBooster - Command line error

### ISSUE THREAD

**Issue by f-huber** [Nesvilab/FragPipe#624]
Dear Fragpipe team, 

I downloaded **FragPipe-17.1** and I am trying to run **MSBooster** in command line, as follow:
`java -jar fragpipe/tools/msbooster-1.0.jar --paramsList msbooster_params.txt > msbooster.log`

Right after the mzML file is loaded, I get an error. (Sorry I had to copy-paste the entire log, but there's a bug that prevents me from attaching the file)

I get the same error when running MSBooster with:
**openjdk/1.8.0_222-b10** or **openjdk/11.0.2**

Do you have any idea on what I'm doing wrong?

Thank you very much for your help, 

########################
              LOG:
########################

```
Using 24 threads
Generating input file for DIA-NN
40433 unique peptides from 67606 PSMs
Writing DIA-NN input file
Diann input file generation took 552 milliseconds
Input file at  /data/username/diann_test/rawmzmlconversion/spectraRT.tsv
40433 unique peptides from 67606 PSMs
DiannFull input file generation took 438 milliseconds
Input file at  /data/username/diann_test/rawmzmlconversion/spectraRT_full.tsv
Generating DIA-NN predictions
/usr/diann/1.8/diann --lib /data/username/diann_test/rawmzmlconversion/spectraRT.tsv --predict --threads 24 --strip-unknown-mods
DIA-NN 1.8 (Data-Independent Acquisition by Neural Networks)
Compiled on Jun 28 2021 10:59:57
Current date and time: Thu Mar 17 14:52:43 2022
Logical CPU cores: 36
Predicted spectra will be saved in a binary format
Thread number set to 24
DIA-NN will use deep learning to predict spectra/RTs/IMs even for peptides carrying modifications which are not recognised by the deep learning predictor. In this scenario, if also generating a spectral library from the DIA data or using the MBR mode, it might or might not be better (depends on the data) to also use the --out-measured-rt option - it's recommended to test it with and without this option

0 files will be processed
[0:00] Loading spectral library /data/username/diann_test/rawmzmlconversion/spectraRT.tsv
[0:00] Finding proteotypic peptides (assuming that the list of UniProt ids provided for each peptide is complete)
[0:00] Spectral library loaded: 0 protein isoforms, 0 protein groups and 40433 precursors in 36742 elution groups.
[0:00] Encoding peptides for spectra and RTs prediction
[0:00] Predicting spectra and IMs
[0:02] Predicting RTs
[0:03] Decoding predicted spectra and IMs
[0:03] Decoding RTs
[0:03] Saving the list of predictions to /data/username/diann_test/rawmzmlconversion/spectraRT.predicted.bin
Finished
Done generating DIA-NN predictions
Model running took 3664 milliseconds
Final parameters used for feature annotation:
	fragger = /data/username/diann_test/rawmzmlconversion/xxx_msfragger.params
	pinPepXMLDirectory = /data/username/diann_test/rawmzmlconversion
	mzmlDirectory = /data/username/diann_test/rawmzmlconversion
	outputDirectory = /data/username/diann_test/rawmzmlconversion
	editedPin = edited
	renamePin = 1
	spectraRTPredInput = /data/username/diann_test/rawmzmlconversion/spectraRT.tsv
	detectPredInput = /data/username/diann_test/rawmzmlconversion/detect.tsv
	spectraRTPredFile = /data/username/diann_test/rawmzmlconversion/spectraRT.predicted.bin
	detectPredFile = null
	deletePreds = true
	fasta = /data/username/diann_test/rawmzmlconversion/xxx.decoys.fa
	decoyPrefix = >rev_
	cutAfter = -
	butNotAfter = 
	digestMinLength = 7
	digestMaxLength = 15
	digestMinMass = 200.0
	digestMaxMass = 2500.0
	numThreads = 24
	DiaNN = /usr/diann/1.8/diann
	ppmTolerance = 20.0
	lowResppmTolerance = 300.0
	highResppmTolerance = 20.0
	useSpectra = true
	useTopFragments = true
	topFragments = 12
	removeRankPeaks = true
	useRT = true
	RTregressionSize = 5000
	uniformPriorPercentile = 10.0
	RTescoreCutoff = 3.1622776E-4
	RTbinMultiplier = 1
	RTIQR = 50.0
	noRTscores = false
	bandwidth = 0.05
	robustIters = 2
	useDetect = false
	useIM = null
	IMregressionSize = 5000
	IMescoreCutoff = 3.1622776E-4
	IMbinMultiplier = 100
	features = cosineSimilarity,spectralContrastAngle,euclideanDistance,brayCurtis,pearsonCorr,dotProduct,deltaRTLOESS,deltaRTLOESSnormalized,RTprobabilityUnifPrior
Generating edited pin with following features: [cosineSimilarity, spectralContrastAngle, euclideanDistance, brayCurtis, pearsonCorr, dotProduct, deltaRTLOESS, deltaRTLOESSnormalized, RTprobabilityUnifPrior]
Loading predicted spectra
Loading 20210723_CTE-BIO-19519-HLAIp_R01.mzML
Exception in thread "main" java.lang.NoClassDefFoundError: umich.ms.fileio.filetypes.LCMSDataSource
	at Features.percolatorFormatter.editPin(percolatorFormatter.java:275)
	at Features.MainClass.main(MainClass.java:481)
Caused by: java.lang.ClassNotFoundException: umich.ms.fileio.filetypes.LCMSDataSource
	at java.net.URLClassLoader.findClass(URLClassLoader.java:591)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:944)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:889)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:872)
	... 2 more
```

**Comment by f-huber** [comment]
I figured out that the missing class is available in:
`fragpipe/tools/batmass-io-1.23.6.jar`

I updated my command to run msbooster as follow:
`java -cp "fragpipe/tools/msbooster-1.0.jar:fragpipe/tools/smile-core-2.6.0.jar:fragpipe/tools/smile-math-2.6.0.jar:fragpipe/tools/batmass-io-1.23.6.jar" Features.MainClass --paramsList msbooster_params.txt`

Now the loading of the mzML works, but I get another error, related to X11 forwarding 

```
...
Generating edited pin with following features: [cosineSimilarity, spectralContrastAngle, euclideanDistance, brayCurtis, pearsonCorr, dotProduct, deltaRTLOESS, deltaRTLOESSnormalized, RTprobabilityUnifPrior]
Loading predicted spectra
Loading 20210723_CTE-BIO-19519-HLAIp_R01.mzML
RT regression using 5000 PSMs
MoTTY X11 proxy: Unsupported authorisation protocol
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable.
        at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:102)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:61)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:101)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:83)
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
        at java.desktop/java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
        at org.knowm.xchart.BitmapEncoder.getBufferedImage(BitmapEncoder.java:280)
        at org.knowm.xchart.BitmapEncoder.saveBitmap(BitmapEncoder.java:85)
        at org.knowm.xchart.BitmapEncoder.saveBitmap(BitmapEncoder.java:69)
        at Features.RTCalibrationFigure.<init>(RTCalibrationFigure.java:82)
        at Features.percolatorFormatter.editPin(percolatorFormatter.java:350)
        at Features.MainClass.main(MainClass.java:481)

```
I am trying to run fragpipe scripts without the GUI (using MSFragger + MSBooster + Percolator + ProteinProphet). Therefore, I would like to use MSBooster without a GUI (I'm assuming that the X11 forwarding requires manual intervention of the user).

Do you know if it is possible to disable the X11 forwarding in MSBooster - or am I doing something wrong?

Thank you very much for your help

**Comment by fcyu** [comment]
We have a pre-release of FragPipe with headless mode. If you want to have a try, please check https://github.com/Nesvilab/FragPipe/issues/560#issuecomment-999748399

Best,

Fengchao

**Comment by f-huber** [comment]
Hi Fengchao,

This is awesome, I'll give it a try, thanks a lot!

Best,

Florian

**Comment by f-huber** [comment]
Hi Fengchao, 

I tried the pre-release of FragPipe with headless mode #560 and it works perfectly.

Thanks again
