### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by zhijcao** [Nesvilab/FragPipe#627]
Hi there,
      I run FragPine on  Linux 20.04 (aws) and got the following error:
      *******************************TOTAL TIME 4.785 MIN********************************
Process 'MSFragger' finished, exit code: 0
MSFragger move pepxml02:25:49 ERROR: Error while starting process: Percolator, stopping
java.io.IOException: Cannot run program "/home/ubuntu/fragpipe/tools/percolator" (in directory "/home/ubuntu/fragtest/normal_6"): error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.dmtavt.fragpipe.process.ProcessResult.start(ProcessResult.java:55)
	at com.dmtavt.fragpipe.cmd.ProcessBuilderInfo.lambda$toRunnable$0(ProcessBuilderInfo.java:49)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 6 common frames omitted

how to solve this issue?

Thanks,
Zhijun

**Comment by zhijcao** [comment]
Hi Fendchao and Guoci,
It works now. Thank you for your quick response and help.
Best,
Zhijun
