### ISSUE TITLE
Process 'MSBooster' finished, exit code: 1

### ISSUE THREAD

**Issue by BenSamy2020** [Nesvilab/FragPipe#639]
Greetings,

I am currently trying to perform nonspecific-peptidome search. I am utilizing fragpipe default workflow with the changes to peptide length of 7 - 25. Unfortunately, I am hitting the error of - 

"Generating edited pin with following features: [cosineSimilarity, spectralContrastAngle, euclideanDistance, brayCurtis, pearsonCorr, dotProduct, deltaRTLOESS, deltaRTLOESSnormalized, RTprobabilityUnifPrior]
Loading predicted spectra
Process 'MSBooster' finished, exit code: 1
Process returned non-zero exit code, stopping"

Please do advise me on how to troubleshoot this error and I would like to thank you in advance for your assistances. 

Regards,
Ben

**Comment by yangkl96** [comment]
Hi Ben,

This is an interesting one, looks like MSBooster is trying to read the predictions before they're ready. Could you try unchecking the MSFragger checkbox to just run from MSBooster and see if this happens again? And then you can decrease the Parallelism number in the Workflow tab to 10 and retry again

**Comment by BenSamy2020** [comment]
Hi Kevin,

I am facing the error of - 

"java.io.FileNotFoundException: D:\MSFragger_Temp\BRCA_Panel\MSBooster_Test\fragger.params (The system cannot find the file specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(Unknown Source)
	at java.base/java.io.FileInputStream.<init>(Unknown Source)
	at java.base/java.io.FileInputStream.<init>(Unknown Source)
	at java.base/java.io.FileReader.<init>(Unknown Source)
	at Features.MainClass.main(MainClass.java:175)
Process 'MSBooster' finished, exit code: 1
Process returned non-zero exit code, stopping"

Regards,
Ben

**Comment by yangkl96** [comment]
Could you copy the file at D:\MSFragger_Temp\BRCA_Panel\Peptidomics_Output\fragger.params to your new folder?

**Comment by BenSamy2020** [comment]
[Error_Log_3.txt](https://github.com/Nesvilab/FragPipe/files/8427832/Error_Log_3.txt)

**Comment by BenSamy2020** [comment]
I re-ran the MSBooster in the BRCA_Panel folder. I have hit this error
[Error_Log_4.txt](https://github.com/Nesvilab/FragPipe/files/8428201/Error_Log_4.txt)
.

**Comment by BenSamy2020** [comment]
If you want, I can re-run the analysis using a small number of file using the exact same workflow to see if I can reproduce the error and we can take the troubleshooting forward. Please do let me know.

**Comment by BenSamy2020** [comment]
Greetings,

I just performed a re-run using a small dataset using the exact same workflow. I hit this error -
[Error_Log_5.txt](https://github.com/Nesvilab/FragPipe/files/8428453/Error_Log_5.txt)

Subsequently, within the exact same study folder, I just re-ran MSBooster and hit this error - 
[Error_Log_6.txt](https://github.com/Nesvilab/FragPipe/files/8428462/Error_Log_6.txt)

Please do advise me on how to troubleshoot this.

Regards,
Ben

**Comment by yangkl96** [comment]
They seem to be all the same errors. 

Do you know if there are any non-canonical amino acids in your database? If you are able, you can put your spectraRT.tsv here: https://www.dropbox.com/request/ARY9mevRb6AKQ6Q93uSG

**Comment by BenSamy2020** [comment]
I do not expect for any non-canonical amino acid in my dataset. But I am expecting alot of non-tryptic peptides. Based on the study folder only 1 sample has a spectraRT.tsv file the remaining spectraRT.tsv files were not generated. I have deposited that one file in the above provided link.

**Comment by yangkl96** [comment]
I should've looked closer at your database search parameters! The first version of MSBooster did not support C-term modifications. Try this FragPipe pre-release with new MSBooster here: https://drive.google.com/drive/folders/1g1Z_v_eWKhIuuC2wTqu0WahkIAgEBxzi

**Comment by BenSamy2020** [comment]
Can I increase my parallelism to 20 or 24?

**Comment by yangkl96** [comment]
I deposited the newer MSBooster 1.1.1 in the dropbox folder. You can replace the old msbooster-1.0.jar with the new one.

And yes you can increase parallelism

**Comment by yangkl96** [comment]
Disregard the FragPipe pre-release, some things have changed

**Comment by BenSamy2020** [comment]
Alright, I have just copied the MSBooster version 1.1 into my FragPipe 17.1. Also I deleted the older version of MSBooster 1.0.

Currently running the workflow with the newer version of MSBooster 1.1

**Comment by yangkl96** [comment]
Hi Ben. Did this resolve the problem?

**Comment by BenSamy2020** [comment]
Hi,It's resolved. Thank you.On 18 Apr 2022 9:44 pm, yangkl96 ***@***.***> wrote:
Hi Ben. Did this resolve the problem?

**Comment by amitkarmakar99** [comment]
2024-09-01 14:06:55 [INFO] - MSBooster v1.2.31
2024-09-01 14:06:55 [INFO] - Using 11 threads
Process 'MSBooster' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 36 remaining tasks - how to resolve the issue, no report file is there

**Comment by fcyu** [comment]
@yangkl96 Could you take a look?

Thanks,

Fengchao

**Comment by yangkl96** [comment]
@amitkarmakar99 it is difficult to diagnose this without a log file. Can you try running it again to see if a log file is produced?
