### ISSUE TITLE
Java error in Philosopher database tools

### ISSUE THREAD

**Issue by enonimos** [Nesvilab/FragPipe#657]
**Describe the bug**
I receive an error when performing any of the philosopher database functions from within the GUI, i.e., "Database" tab (download sequences, add decoys, etc) when the path/file is located on a different drive than the C:\ (which is my OS drive).  The error is pasted below. As a workaround, if I move the files to the C:\ they complete successfully.

java.lang.IllegalStateException: Something happened during database update
	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$updateDb$7(DownloadDbHelper.java:358)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Process returned non zero value
	at com.dmtavt.fragpipe.api.DownloadDbHelper.runProcesses(DownloadDbHelper.java:281)
	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$updateDb$7(DownloadDbHelper.java:354)
	... 1 more

----------------------
## If you're submitting a bug report, please attach log file

N/A, no run has been performed.

**Comment by fcyu** [comment]
Can you paste the whole message here? It is in the `run` tab.

Thanks.

Fengchao

**Comment by enonimos** [comment]
Sorry, please see below. I pasted two different results depending on whether I use "download database" or "Add decoys". Both don't complete. Even though output is different, maybe issues similar to post #641?  

If I try to download database here is output:
21:14:33 INFO : Database for download ID: UP000000589
21:14:44 INFO : Executing: D:\Science\Fragpipe17_1\tools\philosopher\philosopher.exe workspace --init --nocheck
21:14:44 INFO : Process output: 
21:14:44 INFO : Monitoring directory for file changes: D:\Data\_FASTA
21:14:44 INFO : Executing: D:\Science\Fragpipe17_1\tools\philosopher\philosopher.exe database --reviewed --contam --contamprefix --id UP000000589
21:15:09 INFO : Process output: 
21:15:09 INFO : No more file events when downloading database

If I try to add Decoys, here is output
21:15:09 INFO : Process output: 
21:15:09 INFO : No more file events when downloading database
21:16:28 INFO : Executing: D:\Science\Fragpipe17_1\tools\philosopher\philosopher.exe workspace --init --nocheck
21:16:29 INFO : Process output: 
21:16:29 INFO : Executing: D:\Science\Fragpipe17_1\tools\philosopher\philosopher.exe database --custom D:\Data\_FASTA\2021_01_UniProtS_Mouse.fasta
21:16:30 INFO : Process output: 
21:16:30 ERROR: Something happened during database update
java.lang.IllegalStateException: Process returned non zero value
	at com.dmtavt.fragpipe.api.DownloadDbHelper.runProcesses(DownloadDbHelper.java:281)
	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$updateDb$7(DownloadDbHelper.java:354)
	at java.base/java.lang.Thread.run(Thread.java:834)
21:16:30 INFO : No more file events when updating database

**Comment by fcyu** [comment]
Can you open `cmd.exe`, and run the following two command
```
D:\Science\Fragpipe17_1\tools\philosopher\philosopher.exe workspace --init --nocheck
D:\Science\Fragpipe17_1\tools\philosopher\philosopher.exe database --custom D:\Data_FASTA\2021_01_UniProtS_Mouse.fasta
```
And send the output?

Thanks,

Fengchao

**Comment by enonimos** [comment]
Command 1 Output:
INFO[21:27:47] Executing Workspace  v4.2.1
INFO[21:27:47] Creating workspace
INFO[21:27:47] Done

For command 2, I may see the problem.  The path is incorrect.  The actual path on my system is D:\Data\_FASTA, not D:\Data_FASTA  I ran two command with incorrect and correct path, which solves the issue.

Command 2 Output (incorrect path)
INFO[21:28:21] Executing Database  v4.2.1
WARN[21:28:21] contaminants are not going to be added to database
INFO[21:28:21] Generating the target-decoy database
ERRO[21:28:21] Cannot read file. cannot open the database file
INFO[21:28:21] Creating file
INFO[21:28:21] Processing decoys
ERRO[21:28:21] Cannot read file. cannot open the database file
INFO[21:28:21] Creating file
INFO[21:28:21] Done

Command 2 Output (corrected path)
INFO[21:30:35] Executing Database  v4.2.1
WARN[21:30:35] contaminants are not going to be added to database
INFO[21:30:35] Generating the target-decoy database
INFO[21:30:36] Creating file
INFO[21:30:38] Processing decoys
INFO[21:30:38] Creating file
INFO[21:30:39] Done

**Comment by fcyu** [comment]
Wait a sec. What is the correct path? I saw two `D:\Data_FASTA`

Best,

Fengchao

**Comment by enonimos** [comment]
The correct path is D:\Data\_FASTA.   But for some reason is changed to D:\Data_FASTA

**Comment by fcyu** [comment]
Hmm... Thank you very much for your help. I will investigate tomorrow.

Best,

Fengchao

**Comment by enonimos** [comment]
No problem, thanks Fengchao.

**Comment by fcyu** [comment]
Hi @enonimos ,

I cannot reproduce the error:
```
10:27:15 INFO : Database for download ID: UP000000589
10:27:18 INFO : Executing: F:\bin\philosopher-v4.2.1-RC4.exe workspace --init --nocheck
10:27:21 INFO : Process output: 
10:27:21 INFO : Monitoring directory for file changes: F:\Data\_FASTA
10:27:21 INFO : Executing: F:\bin\philosopher-v4.2.1-RC4.exe database --reviewed --contam --contamprefix --nodecoys --id UP000000589
10:27:30 INFO : Process output: 
10:27:30 INFO : Executing: F:\bin\philosopher-v4.2.1-RC4.exe workspace --clean --nocheck
10:27:33 INFO : Process output: 
10:27:33 INFO : Detected new or changed file: 2022-04-21-reviewed-contam-UP000000589.fas
10:27:33 INFO : Extension: [fas]
10:27:33 INFO : Is regular file: true; Is not inside .meta folder: true; Extension starts with .fa: true
10:30:14 INFO : Executing: F:\bin\philosopher-v4.2.1-RC4.exe workspace --init --nocheck
10:30:16 INFO : Process output: 
10:30:16 INFO : Executing: F:\bin\philosopher-v4.2.1-RC4.exe database --custom F:\Data\_FASTA\2022-04-21-reviewed-contam-UP000000589.fas
10:30:23 INFO : Process output: 
10:30:23 INFO : Executing: F:\bin\philosopher-v4.2.1-RC4.exe workspace --clean --nocheck
10:30:25 INFO : Process output: 
10:30:25 INFO : Detected new or changed file: .meta
10:30:25 INFO : Detected new or changed file: .meta
10:30:25 INFO : Detected new or changed file: 2022-04-21-decoys-2022-04-21-reviewed-contam-UP000000589.fas.fas
10:30:40 INFO : No more file events when updating database
```

Best,

Fengchao

**Comment by enonimos** [comment]
Thanks Fengchao,  that's very strange.  I will investigate on my end.  Is the Philosopher processing Python code?
Todd

**Comment by fcyu** [comment]
No, Philosopher is in GO, and there is no Python code related to Philosopher.

Best,

Fengchao

**Comment by enonimos** [comment]
Hi Fengchao,
Somehow it magically started to work. In the past months, I have tried to run the command to save the database to my D: drive location and it did not complete (see first screenshot example).  

However, testing it out again today I tried saving to C: and it worked, then I went back to D: again, and surprisingly it worked. I don't know what I changed.  The only difference in log file is the operation that failed had "new or changed file" as "meta", instead of the .fa file.  Anyway, I'm not sure why it is working now. Thank you for the troubleshooting assistance.

D: save location (previous attempts)
![image](https://user-images.githubusercontent.com/42681821/164796790-692c2b6e-0b82-4d06-a09c-de1165fcfceb.png)

D: save location (latest attempt)
![image](https://user-images.githubusercontent.com/42681821/164799188-9d30767d-3452-4efc-8c09-1705d0c5db2b.png)
