### ISSUE TITLE
issue with FragPipe

### ISSUE THREAD

**Issue by hupak2022** [Nesvilab/FragPipe#665]
Dear support,

I was analyzing some data from FAIMS and I got an error during the process of identification with FragPipe. It is not the first time I analyze FAIMs data but it is the first time I got an error. Please see below and let me know what could be the error on my side.
Thanks a lot for your help

Best

Hui Song

PhilosopherFilter [Work dir: D:\HSP\HLA-II\Result\3CV-2nd_CID_2]
C:\DATA\FragPipe-jre-17.1\fragpipe\tools\philosopher\philosopher.exe filter --sequential --prot 1 --tag rev_ --pepxml D:\HSP\HLA-II\Result\3CV-2nd_CID_2 --protxml D:\HSP\HLA-II\Result\combined.prot.xml --razorbin D:\HSP\HLA-II\Result\2CV_CID_1\.meta\razor.bin
INFO[13:08:08] Executing Filter  v4.2.1                     
INFO[13:08:08] Fetching razor assignment from: D:\HSP\HLA-II\Result\2CV_CID_1\.meta\razor.bin: 40711 razor groups imported. 
INFO[13:08:08] Processing peptide identification files      
INFO[13:08:08] Parsing interact-20220405_Eclipse_LC1_HLA-II_3CV-2nd_CID_R02.pep.xml 
INFO[13:08:10] 1+ Charge profile                             decoy=0 target=0
INFO[13:08:10] 2+ Charge profile                             decoy=165 target=1232
INFO[13:08:10] 3+ Charge profile                             decoy=538 target=2184
INFO[13:08:10] 4+ Charge profile                             decoy=692 target=2147
INFO[13:08:10] 5+ Charge profile                             decoy=219 target=739
INFO[13:08:10] 6+ Charge profile                             decoy=0 target=0
INFO[13:08:10] Database search results                       ions=6262 peptides=5337 psms=7916
INFO[13:08:10] Converged to 0.00 % FDR with 0 PSMs           decoy=0 threshold=10 total=0
INFO[13:08:10] Converged to 0.00 % FDR with 0 Peptides       decoy=0 threshold=10 total=0
INFO[13:08:10] Converged to 0.00 % FDR with 0 Ions           decoy=0 threshold=10 total=0
INFO[13:08:16] Protein inference results                     decoy=9318 target=10890
INFO[13:08:16] Converged to 88.37 % FDR with 10028 Proteins  decoy=8862 threshold=0.05 total=18890
panic: reflect: reflect.flag.mustBeAssignable using unaddressable value

goroutine 1 [running]:
reflect.flag.mustBeAssignableSlow(0x16)
	/usr/lib/go-1.13/src/reflect/value.go:247 +0x13f
reflect.flag.mustBeAssignable(...)
	/usr/lib/go-1.13/src/reflect/value.go:234
reflect.Value.Set(0xbab380, 0xc0001722e0, 0x16, 0xbab380, 0x0, 0x16)
	/usr/lib/go-1.13/src/reflect/value.go:1531 +0x42
github.com/vmihailenco/msgpack/v5.ptrValueDecoder.func1(0xc007853b90, 0xbab380, 0xc0001722e0, 0x16, 0xbab380, 0xc0001722e0)
	/home/prvst/go/pkg/mod/github.com/vmihailenco/msgpack/v5@v5.3.5/decode_value.go:130 +0x103
github.com/vmihailenco/msgpack/v5.(*Decoder).DecodeValue(0xc007853b90, 0xbab380, 0xc0001722e0, 0x16, 0xc0001722e0, 0x16)
	/home/prvst/go/pkg/mod/github.com/vmihailenco/msgpack/v5@v5.3.5/decode.go:309 +0x93
github.com/vmihailenco/msgpack/v5.(*Decoder).Decode(0xc007853b90, 0xb0ee60, 0xc00198d610, 0xc0000c3000, 0xc00040e078)
	/home/prvst/go/pkg/mod/github.com/vmihailenco/msgpack/v5@v5.3.5/decode.go:288 +0x1e5
philosopher/lib/sys.Restore(0xbab380, 0xc0001722e0, 0xc0015c7f10, 0xd, 0x0)
	/workspace/philosopher/lib/sys/sys.go:269 +0x235
philosopher/lib/id.(*PepIDList).Restore(0xc0001722e0, 0xc4c78d, 0x3)
	/workspace/philosopher/lib/id/pep.go:952 +0x101
philosopher/lib/fil.Run(0xc00001a930, 0x24, 0xc00001a960, 0x22, 0xc0000224b0, 0x46, 0xc00001e480, 0x31, 0xc00001a990, 0x28, ...)
	/workspace/philosopher/lib/fil/fil.go:111 +0x1de8
philosopher/cmd.glob..func5(0x2314c80, 0xc00018e0b0, 0x0, 0xb)
	/workspace/philosopher/cmd/filter.go:43 +0x45b
github.com/spf13/cobra.(*Command).execute(0x2314c80, 0xc00018e000, 0xb, 0xb, 0x2314c80, 0xc00018e000)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x2316c00, 0x456570, 0xc0000c7f48, 0xc0000c7f40)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x31e
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
philosopher/cmd.Execute()
	/workspace/philosopher/cmd/root.go:35 +0x34
main.main()
	/workspace/philosopher/main.go:25 +0x83
Process 'PhilosopherFilter' finished, exit code: 2
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 70 remaining tasks

**Comment by guoci** [comment]
Yes, the fix is in a recent commit.

**Comment by hupak2022** [comment]
Thank you for your asnwer. 
What am I supposed to do ? wait for the next update of FragPipe?
Many thanks

Hui Song
