### ISSUE TITLE
runtime error: index out of range [2723] with length 2723 from `ProtXMLFilter()` function.

### ISSUE THREAD

**Issue by candidaorelmex** [Nesvilab/FragPipe#666]
Hi,

I recieved the error in the title when processing ~530 raw files all together, files were acquired with an orbitrap HF-X. I processed a subset of those files before, around 190, and there was no issue. Here more from the log:

```
Running FPKM NSS NRS NSE NSI NSM Model EM:
Computing NSS values ... 

Creating 4 threads 
Wait for threads to finish ...
.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................... done
Computing NRS values ... 

Creating 4 threads 
Wait for threads to finish ...
0--------------------------------------------------50------------------------------------------------100%
..................................................................................................... done
Computing NSE values ... 

Creating 4 threads 
Wait for threads to finish ...
0--------------------------------------------------50------------------------------------------------100%
..................................................................................................... done
Computing NSI values ... 

Creating 4 threads 
Wait for threads to finish ...
0--------------------------------------------------50------------------------------------------------100%
..................................................................................................... done
Computing NSM values ... 

Creating 4 threads 
Wait for threads to finish ...
0--------------------------------------------------50------------------------------------------------100%
..................................................................................................... done
FPKM values are unavailable ... 
Iterations: ......done
Process 'iProphet' finished, exit code: 0
PhilosopherAbacus [Work dir: /media/data/fragpipe_search_results/01_hotspots/220428_bigsearch_both-strains_find-bad-files]
/home/localadmin/fragpipe/tools/philosopher/philosopher abacus --razor --reprint --tag rev_ --protein --peptide balbc black6
time="13:48:47" level=info msg=Done
time="13:48:47" level=info msg="Executing Abacus v4.2.1"
time="13:48:47" level=info msg="Processing combined file"
time="13:48:47" level=info msg="Parsing combined.pep.xml"
time="13:57:57" level=info msg="Converged to 1.00 % FDR with 21463 Peptides" decoy=216 threshold=0.999722 total=21679
time="13:57:57" level=info msg="Restoring peptide results"
time="13:58:20" level=info msg="collecting data from individual experiments"
time="13:58:20" level=info msg="summarizing the quantification"
time="13:58:48" level=info msg="Processing combined file"
time="13:59:01" level=error msg="the protein FDR filter didn't reach the desired threshold, try a higher threshold using the --prot parameter"
panic: runtime error: index out of range [7835] with length 7835

goroutine 1 [running]:
philosopher/lib/fil.ProtXMLFilter(0x0, 0x0, 0x7ffd7d4b0498, 0x4, 0xc01b7fcfe0, 0x1a, 0xc01b596000, 0x7fc9, 0x8999, 0x3f847ae147ae147b, ...)
	/workspace/philosopher/lib/fil/fdr.go:550 +0x1b61
philosopher/lib/aba.processProteinCombinedFile(0x7ffd7d4b0498, 0x4, 0x3feccccccccccccd, 0x3fe0000000000000, 0x101000000010101, 0xc0713bc640, 0x50, 0x0, 0x0, 0x0, ...)
	/workspace/philosopher/lib/aba/pro.go:172 +0x667
philosopher/lib/aba.proteinLevelAbacus(0xc0000983f0, 0x24, 0xc000086360, 0x5c, 0xc000098420, 0x29, 0xc000122380, 0x6b, 0xc0001223f0, 0x62, ...)
	/workspace/philosopher/lib/aba/pro.go:44 +0x1ff
philosopher/lib/aba.Run(0xc0000983f0, 0x24, 0xc000086360, 0x5c, 0xc000098420, 0x29, 0xc000122380, 0x6b, 0xc0001223f0, 0x62, ...)
	/workspace/philosopher/lib/aba/aba.go:33 +0xac
philosopher/cmd.glob..func1(0x1f2c260, 0xc0000f0480, 0x2, 0x8)
	/workspace/philosopher/cmd/abacus.go:29 +0xd3
github.com/spf13/cobra.(*Command).execute(0x1f2c260, 0xc0000f0400, 0x8, 0x8, 0x1f2c260, 0xc0000f0400)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x1f2ec60, 0x455140, 0xc000135f48, 0xc000135f40)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
philosopher/cmd.Execute()
	/workspace/philosopher/cmd/root.go:35 +0x2d
main.main()
	/workspace/philosopher/main.go:25 +0x7c
Process 'PhilosopherAbacus' finished, exit code: 2
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 4 remaining tasks
```

Do you know what went wrong? If there were something wrong with the files, shouldnt there have been an error earlier?

Thanks for your help!

**Comment by fcyu** [comment]
Same as the bug reported here (https://github.com/Nesvilab/FragPipe/issues/545#issuecomment-997002678). This bug will be triggered if a certain condition is met (checking my comment in that thread). When there are not many files, the chance of triggering it is low, but when there are many files....

Felipe @prvst , can you fix it? 

Best,

Fengchao

**Comment by candidaorelmex** [comment]
Ok, thanks for the quick reply:) Looking forward to the bug fix!
