### ISSUE TITLE
non-zero exit of ionquant

### ISSUE THREAD

**Issue by wangxi891879411** [Nesvilab/FragPipe#678]
**Describe the bug**
2022-05-13 01:52:50 [INFO] - ...20%...40%...Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.eclipse.collections.impl.map.mutable.primitive.LongIntHashMap.allocateTable(LongIntHashMap.java:1288)
	at org.eclipse.collections.impl.map.mutable.primitive.LongIntHashMap.<init>(LongIntHashMap.java:97)
	at h.<init>(Unknown Source)
	at ionquant.IonQuant.<init>(Unknown Source)
	at ionquant.IonQuant.main(Unknown Source)

----------------------
## If you're submitting a bug report, please attach log file

The log file can be saved from FragPipe:

- by clicking the `Export Log` button on the `Run` tab.
- or just copy text from the output console on `Run
[log_2022-05-13_02-00-54.txt](https://github.com/Nesvilab/FragPipe/files/8688549/log_2022-05-13_02-00-54.txt)
` tab to a text file.

**Comment by fcyu** [comment]
`Exception in thread "main" java.lang.OutOfMemoryError: Java heap space` There is not enough memory in your computer. If you are analyzing ddaPASEF data, you need to have at least 20 GB **free** memory.

Best,

Fengchao

**Comment by wangxi891879411** [comment]
Thanks a lot.


------------------


王曦 (Xi Wang) 

南方科技大学/化学系-博士后

Biological mass spectrometry and proteomics group, Department of Chemistry
High-resolution mass spectrometry platform, Core research facilities

Guangdong provincial key laboratory for cell microenvironment and disease research
Southern University of Science and Technology (SUSTech)
403, 1st research building, 1088 Xueyuan Rd., Nanshan, Shenzhen
E-mail: ***@***.***


Phone: 13717736753






---- Replied Message ----
| From | ***@***.***> |
| Date | 05/13/2022 22:25 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [Nesvilab/FragPipe] non-zero exit of ionquant (Issue #678) |

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space There is not enough memory in your computer. If you are analyzing ddaPASEF data, you need to have at least 20 GB free memory.

Best,

Fengchao
