### ISSUE TITLE
Null pointer with Version 18.0

### ISSUE THREAD

**Issue by DrDee79** [Nesvilab/FragPipe#696]
Upgraded to Version 18.0 and fragpipe starts up with the attached null pointer, as well as not being able to detect the version. 

Thanks!

Dorothy
----------------------
## If you're submitting a bug report, please attach log file

java.lang.NullPointerException
	at org.apache.maven.artifact.versioning.ComparableVersion.parseVersion(ComparableVersion.java:633)
	at org.apache.maven.artifact.versioning.ComparableVersion.<init>(ComparableVersion.java:623)
	at org.apache.maven.artifact.versioning.DefaultArtifactVersion.parseVersion(DefaultArtifactVersion.java:112)
	at org.apache.maven.artifact.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:48)
	at com.dmtavt.fragpipe.tools.fragger.Msfragger$Version.<init>(Msfragger.java:143)
	at com.dmtavt.fragpipe.tools.fragger.Msfragger.testJar(Msfragger.java:133)
	at com.dmtavt.fragpipe.tools.fragger.Msfragger.getVersion(Msfragger.java:53)
	at com.dmtavt.fragpipe.tabs.TabConfig.on(TabConfig.java:591)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
	at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:454)
	at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:421)
	at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:394)
	at org.greenrobot.eventbus.EventBus.post(EventBus.java:275)
	at com.dmtavt.fragpipe.api.Bus.post(Bus.java:76)
	at com.dmtavt.fragpipe.Fragpipe.loadUi(Fragpipe.java:734)
	at com.dmtavt.fragpipe.Fragpipe.on(Fragpipe.java:721)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
	at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:454)
	at org.greenrobot.eventbus.EventBus.checkPostStickyEventToSubscription(EventBus.java:213)
	at org.greenrobot.eventbus.EventBus.subscribe(EventBus.java:199)
	at org.greenrobot.eventbus.EventBus.register(EventBus.java:153)
	at com.dmtavt.fragpipe.api.Bus.register(Bus.java:50)
	at com.dmtavt.fragpipe.Fragpipe.initMore(Fragpipe.java:662)
	at com.dmtavt.fragpipe.Fragpipe.<init>(Fragpipe.java:200)
	at com.dmtavt.fragpipe.Fragpipe.lambda$displayMainWindow$3(Fragpipe.java:455)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by DrDee79** [comment]
I got rid of the null pointer error, but it still won't recognize the version and therefore says it is not configured.  
![image](https://user-images.githubusercontent.com/71278169/171220097-7ab678a8-7e32-44c9-b735-7093e12ca72a.png)
![image](https://user-images.githubusercontent.com/71278169/171220173-2e8ce1e4-0544-42fe-9b28-c254aea2ef9f.png)

**Comment by fcyu** [comment]
In the MSFragger configuration panel, what you need is **MSFragger**.jar, not **fragpipe**.jar. You can click "download/update" on the right to download a new MSFragger.jar.

Best,

Fengchao
