### ISSUE TITLE
LFQ search: "Panic" during/after protein inference

### ISSUE THREAD

**Issue by wyu** [Nesvilab/FragPipe#698]
Hi, can you take a look at the error as described in the log file? The experiment is set up so each raw file is a separate "experiment".
`
[error_log_2022-06-01_06-41-55.txt](https://github.com/Nesvilab/FragPipe/files/8813394/error_log_2022-06-01_06-41-55.txt)

Thanks!

**Comment by fcyu** [comment]
The error was from Philosopher. The specific run has no ID. But I think we have made Philosopher print an warning and continue in this case. Not sure why it crashed this time. 

I can see that you are using an old version. Can you try the latest version (4.2.2)? You can skip all steps and only run "FDR filter and report". If the error persist, Felipe @prvst , can you take a look?

Thanks,

Fengchao
 
```
INFO[03:42:19] Executing Filter  v4.2.1                     
INFO[03:42:24] Fetching razor assignment from: C:\searches\working\Brain\results-isoform-semi-boosted\QEp15-2550_CON\.meta\razor.bin: 587397 razor groups imported. 
INFO[03:42:24] Processing peptide identification files      
INFO[03:42:24] Parsing interact-QEp15-2592_DFC.pep.xml      
INFO[03:42:32] 1+ Charge profile                             decoy=0 target=0
INFO[03:42:32] 2+ Charge profile                             decoy=3061 target=25057
INFO[03:42:32] 3+ Charge profile                             decoy=2575 target=23204
INFO[03:42:32] 4+ Charge profile                             decoy=1042 target=5911
INFO[03:42:32] 5+ Charge profile                             decoy=202 target=697
INFO[03:42:32] 6+ Charge profile                             decoy=20 target=75
INFO[03:42:32] Database search results                       ions=35822 peptides=31260 psms=61844
INFO[03:42:32] Converged to 0.00 % FDR with 0 PSMs           decoy=0 threshold=10 total=0
INFO[03:42:32] Converged to 0.00 % FDR with 0 Peptides       decoy=0 threshold=10 total=0
INFO[03:42:32] Converged to 0.00 % FDR with 0 Ions           decoy=0 threshold=10 total=0
INFO[03:44:06] Protein inference results                     decoy=45343 target=62785
INFO[03:44:11] Converged to 1.05 % FDR with 11036 Proteins   decoy=116 threshold=0.9982 total=11152
panic: reflect: reflect.flag.mustBeAssignable using unaddressable value

goroutine 1 [running]:
reflect.flag.mustBeAssignableSlow(0x16)
	/usr/lib/go-1.13/src/reflect/value.go:247 +0x13f
reflect.flag.mustBeAssignable(...)
	/usr/lib/go-1.13/src/reflect/value.go:234
reflect.Value.Set(0xbab380, 0xc000196420, 0x16, 0xbab380, 0x0, 0x16)
	/usr/lib/go-1.13/src/reflect/value.go:1531 +0x42
github.com/vmihailenco/msgpack/v5.ptrValueDecoder.func1(0xc10ffc5b90, 0xbab380, 0xc000196420, 0x16, 0xbab380, 0xc000196420)
	/home/prvst/go/pkg/mod/github.com/vmihailenco/msgpack/v5@v5.3.5/decode_value.go:130 +0x103
github.com/vmihailenco/msgpack/v5.(*Decoder).DecodeValue(0xc10ffc5b90, 0xbab380, 0xc000196420, 0x16, 0xc000196420, 0x16)
	/home/prvst/go/pkg/mod/github.com/vmihailenco/msgpack/v5@v5.3.5/decode.go:309 +0x93
github.com/vmihailenco/msgpack/v5.(*Decoder).Decode(0xc10ffc5b90, 0xb0ee60, 0xc008a1d790, 0xc101a91000, 0xc000b6c050)
	/home/prvst/go/pkg/mod/github.com/vmihailenco/msgpack/v5@v5.3.5/decode.go:288 +0x1e5
philosopher/lib/sys.Restore(0xbab380, 0xc000196420, 0xc0072a3820, 0xd, 0x0)
	/workspace/philosopher/lib/sys/sys.go:269 +0x235
philosopher/lib/id.(*PepIDList).Restore(0xc000196420, 0xc4c78d, 0x3)
	/workspace/philosopher/lib/id/pep.go:952 +0x101
philosopher/lib/fil.Run(0xc0000c2600, 0x24, 0xc0000ae460, 0x45, 0xc0000ae4b0, 0x48, 0xc00009c480, 0x54, 0xc0000ae500, 0x4b, ...)
	/workspace/philosopher/lib/fil/fil.go:111 +0x1de8
philosopher/cmd.glob..func5(0x2314c80, 0xc00010e630, 0x0, 0xb)
	/workspace/philosopher/cmd/filter.go:43 +0x45b
github.com/spf13/cobra.(*Command).execute(0x2314c80, 0xc00010e580, 0xb, 0xb, 0x2314c80, 0xc00010e580)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x2316c00, 0x456570, 0xc0000d5f48, 0xc0000d5f40)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x31e
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
philosopher/cmd.Execute()
	/workspace/philosopher/cmd/root.go:35 +0x34
main.main()
	/workspace/philosopher/main.go:25 +0x83
```

**Comment by guoci** [comment]
@wyu this bug is fixed in `4.2.2`

**Comment by fcyu** [comment]
Hi Wen,

You also need to upgrade FragPipe, IonQuant, and MSFragger to the latest version since you are using the latest Philosopher.

Best,

Fengchao

**Comment by wyu** [comment]
In situ upgrade of MsFragger is not working for some reason. I'll try to download it separately.
