### ISSUE TITLE
Running FragPipe in headless mode crashes silently

### ISSUE THREAD

**Issue by animesh** [Nesvilab/FragPipe#701]
**Describe the bug**
I am trying to follow https://github.com/Nesvilab/FragPipe/blob/gh-pages/docs/tutorial_headless.md and have created the workflow
[Open - Copy.workflow.txt](https://github.com/Nesvilab/FragPipe/files/8823198/Open.-.Copy.workflow.txt) and manifest 
[open.fp-manifest.txt](https://github.com/Nesvilab/FragPipe/files/8823209/open.fp-manifest.txt) (created a txt copy just to append to github) followed by command `f:\promec\Animesh\FP18\fragpipe\bin\fragpipe.bat --headless --workflow f:\promec\TIMSTOF\LARS\2022\februar\Sigrid\FP18\workflow\Open.workflow --manifest f:\promec\TIMSTOF\LARS\2022\februar\Sigrid\FP18\mannifest\open.fp-manifest --workdir :\promec\TIMSTOF\LARS\2022\februar\Sigrid\FP182\` but it seems to silently fail with following message
```
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 0: :\promec\TIMSTOF\LARS\2022\februar\Sigrid\FP182\
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at com.dmtavt.fragpipe.Fragpipe.main0(Fragpipe.java:386)
        at com.dmtavt.fragpipe.FragPipeMain.main(FragPipeMain.java:40)
```
Any ideas what is the issue and how to overcome?

 
----------------------
## If you're submitting a bug report, please attach log file

The log file can be saved from FragPipe:

- by clicking the `Export Log` button on the `Run` tab.
- or just copy text from the output console on `Run` tab to a text file.

**Comment by fcyu** [comment]
Crystal-C does not support timsTOF data. You need to disable Crystal-C.

Best,

Fengchao
