### ISSUE TITLE
Spectral Library from DDA-data_easyPQP error

### ISSUE THREAD

**Issue by ludsinn** [Nesvilab/FragPipe#764]
Hi,
I am trying to generate spectral libraries from DDA data but get this error message:

Process 'SpecLibGen' finished, exit code: 1
Traceback (most recent call last):
  File "C:\fragpipe ver18_0\tools\speclib\gen_con_spec_lib.py", line 253, in <module>
    easypqp = get_bin_path('easypqp', 'easypqp')
  File "C:\fragpipe ver18_0\tools\speclib\gen_con_spec_lib.py", line 143, in get_bin_path_pip_CLI
    files = [location / e[2:] for e in a.search(stdout).group().splitlines()[1:]]
AttributeError: 'NoneType' object has no attribute 'group'

[log_2022-07-14_17-36-09.zip](https://github.com/Nesvilab/FragPipe/files/9113253/log_2022-07-14_17-36-09.zip)

Could you please point me at my mistake?
Thanks!

**Comment by guoci** [comment]
@ludsinn Did you install easyPQP?
In your Anaconda prompt, can you run the following and show me the output?
`C:\ProgramData\Anaconda3\python  -m pip show --files easypqp`

**Comment by ludsinn** [comment]
@guoci 

(base) C:\Users\QuantProt>C:\ProgramData\Anaconda3\python -m pip show --files easypqp                                 
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)                                   
WARNING: Ignoring invalid distribution -asypqp (c:\programdata\anaconda3\lib\site-packages)                             
Name: easypqp                                                                                                           
Version: 0.1.30                                                                                                         
Summary: EasyPQP: Simple library generation for OpenSWATH                                                               
Home-page: https://github.com/grosenberger/easypqp                                                                      
Author: George Rosenberger                                                                                              
Author-email: gr2578@cumc.columbia.edu                                                                                  
License: UNKNOWN                                                                                                        
Location: c:\users\quantprot\downloads\easypqp-master                                                                   
Requires: Click, numpy, scipy, scikit-learn, statsmodels, pandas, biopython, pyopenms, matplotlib, seaborn              
Required-by:                                                                                                            
Files:                                                                                                                  
Cannot locate RECORD or installed-files.txt                                                                                                                                                                                                     (base) C:\Users\QuantProt> 


I guess you should know that since the "Install/Upgrade Button EasyPQP" did not work (due to some Firewall issue), I tried to update "manually" from 0.1.27 to 0.1.30 via the Anaconda Prompt... I most likely did something wrong here.
