### ISSUE TITLE
.pin file not found in MSBooster step

### ISSUE THREAD

**Issue by Munchic** [Nesvilab/FragPipe#765]
Hello,

I have Thermo .raw runs grouped by experiments and want to run MSBooster on this data. However, MSBooster errors at the very beginning:
```
MSBooster [Work dir: /root/fragpipe/out]
java -Djava.awt.headless=true -Xmx223G -cp /fragpipe/tools/msbooster-1.1.4.jar:/fragpipe/tools/smile-core-2.6.0.jar:/fragpipe/tools/smile-math-2.6.0.jar:/fragpipe/tools/batmass-io-1.25.5.jar Features.MainClass --paramsList /root/fragpipe/out/msbooster_params.txt
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/cromwell_root/tmp.9ece03de
java.io.FileNotFoundException: /root/fragpipe/out/A_1/VB20220627_CC_WuBrain_LF1A_01.pin (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at java.base/java.io.FileReader.<init>(FileReader.java:60)
	at Features.pinReader.<init>(pinReader.java:28)
	at Features.peptideFileCreator.createPeptideFile(peptideFileCreator.java:58)
	at Features.MainClass.main(MainClass.java:478)
MSBooster v1.1.4
```

However, it looks like this file `/root/fragpipe/out/A_1/VB20220627_CC_WuBrain_LF1A_01.pin` should be present because it was used by Percolator in the previous step.

```
Percolator: Convert to pepxml [Work dir: /root/fragpipe/out/A_1]
java -cp /fragpipe/lib/* com.dmtavt.fragpipe.tools.percolator.PercolatorOutputToPepXML VB20220627_CC_WuBrain_LF1A_01.pin VB20220627_CC_WuBrain_LF1A_01 VB20220627_CC_WuBrain_LF1A_01_percolator_target_psms.tsv VB20220627_CC_WuBrain_LF1A_01_percolator_decoy_psms.tsv interact-VB20220627_CC_WuBrain_LF1A_01 DDA 0.5
```

This is the log file: [log.txt](https://github.com/Nesvilab/FragPipe/files/9122039/log.txt)

Thank you for your help!

**Comment by fcyu** [comment]
Your MSFragger output format is `pepXML`. You need to have `pepXML_pin` to generate the pin file. Please re-load the built-in workflow and do not make unnecessary charges.

Best,

Fengchao

**Comment by Munchic** [comment]
@fcyu thank you for your fast response. Will give it a try!
