### ISSUE TITLE
Cannot execute program. there was an error with PeptideProphet, please check your parameters and input files

### ISSUE THREAD

**Issue by animesh** [Nesvilab/FragPipe#779]
I am trying to run the open workflow 
[Open.workflow.txt](https://github.com/Nesvilab/FragPipe/files/9196781/Open.workflow.txt)
over timsTOF-pro data [manifest.fp-manifest.txt](https://github.com/Nesvilab/FragPipe/files/9196792/manifest.fp-manifest.txt)
 on a cluster using headless scheme

```
/cluster/projects/nn9036k/FP18/fragpipe/bin/fragpipe --headless --threads 40 --ram 128 --workflow /cluster/projects/nn9036k/Elise/Open.workflow --manifest /cluster/projects/nn9036k/Elise/manifest.fp-manifest --workdir /cluster/projects/nn9036k/Elise/FP182
```
and facing an error 
[out.slurm.txt](https://github.com/Nesvilab/FragPipe/files/9196752/out.slurm.txt)

```
...
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::ios_base::failure> >'
  what():  failed opening file: No such file or directory
time="00:21:29" level=error msg="Cannot execute program. there was an error with PeptideProphet, please check your parameters and input files"
panic: Cannot execute program. there was an error with PeptideProphet, please check your parameters and input files

goroutine 1 [running]:
philosopher/lib/msg.callLogrus({0xc000036150, 0x6c}, {0xb29f26, 0x1?})
	/workspace/philosopher/lib/msg/msg.go:319 +0x354
philosopher/lib/msg.ExecutingBinary({0xc74b40?, 0xc0002b2160?}, {0xb29f26, 0x5})
	/workspace/philosopher/lib/msg/msg.go:209 +0x6e
philosopher/lib/ext/peptideprophet.interactParser({{0xc000274300, 0x38}, {0xc000274340, 0x37}, {0xc000274380, 0x3e}, {0xc0002743c0, 0x3c}, {0xc000274400, 0x3b}, ...}, ...)
	/workspace/philosopher/lib/ext/peptideprophet/peptideprophet.go:235 +0xb6b
philosopher/lib/ext/peptideprophet.PeptideProphet.Execute({{0xc000274300, 0x38}, {0xc000274340, 0x37}, {0xc000274380, 0x3e}, {0xc0002743c0, 0x3c}, {0xc000274400, 0x3b}, ...}, ...)
	/workspace/philosopher/lib/ext/peptideprophet/peptideprophet.go:86 +0x105
philosopher/lib/ext/peptideprophet.Run({{0xc000214780, 0x24}, {0xc00029a460, 0x45}, {0xc0002147b0, 0x29}, {0xc0002023c0, 0x54}, {0xc00029a4b0, 0x4b}, ...}, ...)
	/workspace/philosopher/lib/ext/peptideprophet/peptideprophet.go:67 +0x3d3
philosopher/cmd.glob..func12(0x1cd6f00?, {0xc0002fc340, 0x1, 0xd})
	/workspace/philosopher/cmd/peproph.go:26 +0xb4
github.com/spf13/cobra.(*Command).execute(0x1cd6f00, {0xc0002fc270, 0xd, 0xd})
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x1cd7c20)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x37c
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
philosopher/cmd.Execute()
	/workspace/philosopher/cmd/root.go:35 +0x25
main.main()
	/workspace/philosopher/main.go:25 +0x90
Process 'PeptideProphet' finished, exit code: 2
Process returned non-zero exit code, stopping
...
```
I thought may be philosopher is non-executable but it seems to work just fine over call
```
(base) [ash022@login-1.SAGA ~/cluster]$ FP18/fragpipe/tools/philosopher_v4.4.0_linux_amd64/philosopher
Philosopher: A toolkit for Proteomics data analysis and post-processing filtering

Usage:
  philosopher [command]

Available Commands:
  abacus         Combined analysis of LC-MS/MS results
  bioquant       Protein report based on protein functional groups
  comet          Peptide spectrum matching with Comet
  database       Target-Decoy database formatting
  filter         Statistical filtering, validation and False Discovery Rates assessment
  freequant      Label-free Quantification
  help           Help about any command
  iprophet       MS/MS integrative analysis
  labelquant     Isobaric Labeling-Based Relative Quantification
  msfragger      Ultra fast and comprehensive peptide identification in mass spectrometry–based proteomics
  peptideprophet Peptide assignment validation
  pipeline       Automatic execution of consecutive analysis steps
  proteinprophet Protein identification validation
  ptmprophet     PTM site localization
  report         Multi-level reporting for both narrow-searches and open-searches
  slack          Push notifications to Slack
  tmtintegrator  integrates channel abundances from multiple TMT samples
  version        Philosopher version
  workspace      Manage the experiment workspace for the analysis

Flags:
  -h, --help   help for philosopher

Use "philosopher [command] --help" for more information about a command.

```

Any ideas how to proceed?

**Comment by prvst** [comment]
Hi @animesh. If you read the message carefully, you'll see in the very first line that PeptideProphet is telling you it cannot find or open the files. Try taking another look at your settings.

*failed opening file: No such file or directory*

**Comment by animesh** [comment]
yes i was wondering about it too but the files are there and maxquant can process them somehow, which settings are you talking about @prvst ?

**Comment by prvst** [comment]
I mean the file paths in your parameter files or graphical interface. Make sure they are OK or visible from where you are executing the program.

**Comment by animesh** [comment]
If you can check the log file i had shared earlier https://github.com/Nesvilab/FragPipe/files/9196752/out.slurm.txt, you might see that fragpipe seems to start or am i misunderstanding you?

**Comment by prvst** [comment]
That the GUI could run and execute Fragger is unrelated to the fact that PeptideProphet cannot see the output of the database search engine. Make sure that the output of Fragger is visible and accessible from the point where you execute the program

**Comment by animesh** [comment]
The output is from slurm job, not GUI. I don't think i have access to nodes which are running the program so probably that i won't be able to check. Sorry to waste your time, will close this issue.

**Comment by prvst** [comment]
Never a waste of time to help, get in touch again if necessary.

**Comment by ruizhao-cmu** [comment]
Hello. I also encountered the same issue. I wonder if the problem has been resolved? Also, I have a question: I am using AB Sciex mass spectrometry data, and I'm not sure if I can use MSfragger.
