### ISSUE TITLE
MS Fragger problem

### ISSUE THREAD

**Issue by Koddios** [Nesvilab/FragPipe#840]
Hello everyone, I'm a new FragPipe user. 
I was trying to analyze my MS data but I could not complete the analysis because of the following error message:
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.__unpackHeader(MZBINFile.java:395)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.__unpackBINHeader(MZBINFile.java:584)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.readMZBINStructure(MZBINFile.java:494)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.readMZBIN(MZBINFile.java:413)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.<init>(MZBINFile.java:67)
	at p.a(Unknown Source)
	at p.a(Unknown Source)
	at o.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 69 remaining tasks

Can you help me?
Thank you in advance
Best
Francesco
[log_2022-09-23_16-25-50.txt](https://github.com/Nesvilab/FragPipe/files/9634981/log_2022-09-23_16-25-50.txt)

**Comment by fcyu** [comment]
Can you send me your 06_Hct116_MA1_in.mzML file?

Thanks,

Fengchao

**Comment by Koddios** [comment]
Hello Fengchao, sorry for the late reply.
I've realized that my files have been acquired using IonTrap (MS2). I guess this is the reason why I cannot perform my analysis.
Thank you for your help
Best
Francesco

**Comment by fcyu** [comment]
I don't think it is the reason because we support ion trap MS2.

Best,

Fengchao

**Comment by Koddios** [comment]
OK, I can send you one of the files if you want! I tried to remove the file that gave the error but I had the same error with another sample, I have the impression that is the whole series that give me problems and since these are the only files acquired with IonTrap I thought it might have been the reason.
Best
Francesco

**Comment by fcyu** [comment]
Sure. Thanks.

Best,

Fengchao

**Comment by fcyu** [comment]
Hi Francesco @Koddios ,

I received your mzML file 01_Hct116_A12_in.mzML, but it is not the one having issues:

```
Operating on slice 1 of 1: 
	Fragment index slice generated in 3.77 s
	001. 01_Hct116_A12_in.mzBIN_calibrated 42.6 s
		[progress: 153486/153486 (100%) - 83 spectra/s] 1842.0s | ramaping alternative proteins and postprocessing 20.8 s
	002. 02_Hct116_KC9_in.mzBIN_calibrated 38.3 s
		[progress: 152666/152666 (100%) - 85 spectra/s] 1792.9s | ramaping alternative proteins and postprocessing 19.1 s
	003. 03_Hct116_MA1_in.mzBIN_calibrated 43.8 s
		[progress: 156861/156861 (100%) - 86 spectra/s] 1826.4s | ramaping alternative proteins and postprocessing 17.7 s
	004. 04_Hct116_A12_in.mzBIN_calibrated 35.4 s
		[progress: 153295/153295 (100%) - 85 spectra/s] 1806.0s | ramaping alternative proteins and postprocessing 17.0 s
	005. 05_Hct116_KC9_in.mzBIN_calibrated 39.9 s
		[progress: 149374/149374 (100%) - 87 spectra/s] 1712.4s | ramaping alternative proteins and postprocessing 15.8 s
	006. 06_Hct116_MA1_in.mzBIN_calibrated java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.__unpackHeader(MZBINFile.java:395)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.__unpackBINHeader(MZBINFile.java:584)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.readMZBINStructure(MZBINFile.java:494)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.readMZBIN(MZBINFile.java:413)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.<init>(MZBINFile.java:67)
	at p.a(Unknown Source)
	at p.a(Unknown Source)
	at o.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping
```

Could you please send me the 06_Hct116_MA1_in.mzML?

Thanks,

Fengchao

**Comment by fcyu** [comment]
Hi @Koddios ,

Thanks for your updated file. But I couldn't reproduce your error. Attached please find my log.

Please double check your system and files, and try again.

Best,

Fengchao

[log.txt](https://github.com/Nesvilab/FragPipe/files/9666641/log.txt)
