### ISSUE TITLE
Error in variable modifications table

### ISSUE THREAD

**Issue by EMRoxon** [Nesvilab/FragPipe#864]
- Describe the issue or question:
Hi, when I try to insert a 4th variable modification in the variable modifications table in MSFragger, the error below pops up as soon as I click on max occurrences. I can fill in Sites and Mass Delta. Do you know what is happening? Thank you!

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

13:27:04 ERROR: Something unexpected happened!

java.lang.IllegalArgumentException: illegal value

	at java.desktop/javax.swing.SpinnerNumberModel.setValue(Unknown Source)

	at java.desktop/javax.swing.JSpinner.setValue(Unknown Source)

	at com.github.chhh.utils.swing.renderers.TableCellIntSpinnerEditor.getTableCellEditorComponent(TableCellIntSpinnerEditor.java:76)

	at java.desktop/javax.swing.JTable.prepareEditor(Unknown Source)

	at java.desktop/javax.swing.JTable.editCellAt(Unknown Source)

	at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.adjustSelection(Unknown Source)

	at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.mousePressed(Unknown Source)

	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(Unknown Source)

	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)

	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)

	at java.desktop/java.awt.Component.processEvent(Unknown Source)

	at java.desktop/java.awt.Container.processEvent(Unknown Source)

	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)

	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)

	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)

	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)

	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)

	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)

	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)

	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)

	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)

	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)

	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)

	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)

	at java.base/java.security.AccessController.doPrivileged(Native Method)

	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)

	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)

	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)

**Comment by fcyu** [comment]
I couldn't reproduce this error. Please see the following screen recording.
![Animation](https://user-images.githubusercontent.com/6926299/196960607-a878e470-ac4e-4242-b6a7-b241ae19ce92.gif)

Best,

Fengchao

**Comment by EMRoxon** [comment]
Hi Fengchao, 

thank you for your quick response. After a fresh installation, the Variable modifications table behaves as shown in your video for the default workflows. However, for example for the isoTOP-ABPP workflow where there are empty rows in the Variable modifications table (please see below a screenshot), the error occurs when clicking on the empty row in Max occurrences column. We have checked this on two separate computers, can you reproduce this? Thank you!

![image](https://user-images.githubusercontent.com/87009680/196993629-d8a2d575-e909-4e1a-8150-bae1b7bfff93.png)

**Comment by fcyu** [comment]
Thank you very much for your detailed demonstration! I have found the bug and fixed it: https://github.com/Nesvilab/FragPipe/commit/8c68fefbe16861fdfc0f6f3a83f0b0dbf8063733

Best,

Fengchao
