### ISSUE TITLE
Error creating speclib with DDA file

### ISSUE THREAD

**Issue by ttessie2** [Nesvilab/FragPipe#883]
I'm just getting familiar with making DDA spectral libraries. I tested one file using the default workflow and I additionally checked off "generate spectral library from search results". Everything ran fine up until generating the speclib, so I've copied that part of the log file.

SpecLibGen [Work dir: D:\Adeno_miniTurbo_MassSpec\MSFragger_output\speclibtests]
C:\Users\Tanner\anaconda3\python.exe -u C:\Users\Tanner\fragpipe_v18\tools\speclib\gen_con_spec_lib.py D:\Adeno_miniTurbo_MassSpec\Databases\2022-11-10-decoys-HumanSwissProt_HAdVC5_contam_miniT.fasta.fas D:\Adeno_miniTurbo_MassSpec\MSFragger_output\speclibtests unused D:\Adeno_miniTurbo_MassSpec\MSFragger_output\speclibtests True unused use_easypqp ciRT;noIM 23 "--max_delta_unimod 0.02 --max_delta_ppm 15.0 --fragment_types [\'b\',\'y\',]" "--rt_lowess_fraction 0.0" delete_intermediate_files D:\Adeno_miniTurbo_MassSpec\MSFragger_output\speclibtests\filelist_speclibgen.txt
File list provided
Spectral library building
Commands to execute:
'C:\Users\Tanner\anaconda3\Scripts\easypqp.exe' convert --max_delta_unimod 0.02 --max_delta_ppm 15.0 --fragment_types '['"'"'b'"'"','"'"'y'"'"',]' --enable_unannotated --pepxml 'D:\Adeno_miniTurbo_MassSpec\MSFragger_output\speclibtests\interact-40020_2A_16_1_NBCC164_Mymryk_Tanner_90min_quarter_RJ.pep.xml' --spectra 'D:\Adeno_miniTurbo_MassSpec\NBCC_datafiles\NBCC00164_datafiles_2A\2A_DDA+DIA\40020_2A_16_1_NBCC164_Mymryk_Tanner_90min_quarter_RJ.mzML' --exclude-range -1.5,3.5 --psms 40020_2A_16_1_NBCC164_Mymryk_Tanner_90min_quarter_RJ.psmpkl --peaks 40020_2A_16_1_NBCC164_Mymryk_Tanner_90min_quarter_RJ.peakpkl
'C:\Users\Tanner\anaconda3\Scripts\easypqp.exe' library --psmtsv 'D:\Adeno_miniTurbo_MassSpec\MSFragger_output\speclibtests\psm.tsv' --peptidetsv 'D:\Adeno_miniTurbo_MassSpec\MSFragger_output\speclibtests\peptide.tsv' --rt_reference 'D:\Adeno_miniTurbo_MassSpec\MSFragger_output\speclibtests\irt.tsv' --out easypqp_lib_openswath.tsv --rt_lowess_fraction 0.0 'D:\Adeno_miniTurbo_MassSpec\MSFragger_output\speclibtests\filelist_easypqp_library.txt'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
easypqp, version 0.1.32
Executing ['C:\\Users\\Tanner\\anaconda3\\Scripts\\easypqp.exe', 'convert', '--max_delta_unimod', '0.02', '--max_delta_ppm', '15.0', '--fragment_types', "['b','y',]", '--enable_unannotated', '--pepxml', 'D:\\Adeno_miniTurbo_MassSpec\\MSFragger_output\\speclibtests\\interact-40020_2A_16_1_NBCC164_Mymryk_Tanner_90min_quarter_RJ.pep.xml', '--spectra', 'D:\\Adeno_miniTurbo_MassSpec\\NBCC_datafiles\\NBCC00164_datafiles_2A\\2A_DDA+DIA\\40020_2A_16_1_NBCC164_Mymryk_Tanner_90min_quarter_RJ.mzML', '--exclude-range', '-1.5,3.5', '--psms', '40020_2A_16_1_NBCC164_Mymryk_Tanner_90min_quarter_RJ.psmpkl', '--peaks', '40020_2A_16_1_NBCC164_Mymryk_Tanner_90min_quarter_RJ.peakpkl']
Traceback (most recent call last):
  File "C:\Users\Tanner\fragpipe_v18\tools\speclib\gen_con_spec_lib.py", line 975, in <module>
    main_easypqp()
  File "C:\Users\Tanner\fragpipe_v18\tools\speclib\gen_con_spec_lib.py", line 786, in main_easypqp
    assert all(p.returncode == 0 for p in procs)
AssertionError
EasyPQP convert error BEGIN
Info: Converting D:\Adeno_miniTurbo_MassSpec\MSFragger_output\speclibtests\interact-40020_2A_16_1_NBCC164_Mymryk_Tanner_90min_quarter_RJ.pep.xml.
Info: Parsing run 40020_2A_16_1_NBCC164_Mymryk_Tanner_90min_quarter_RJ.
Info: Parsing pepXML.
Info: Generate theoretical spectra.
Info: Processing spectra from file D:\Adeno_miniTurbo_MassSpec\NBCC_datafiles\NBCC00164_datafiles_2A\2A_DDA+DIA\40020_2A_16_1_NBCC164_Mymryk_Tanner_90min_quarter_RJ.mzML.
Progress of 'loading spectra list':

  4.84 %               
  12.40 %               
  22.49 %               
  34.09 %               
  44.34 %               
  53.53 %               
  63.36 %               
  72.77 %               
  81.85 %               
  90.34 %               
  96.93 %               
-- done [took 04:24 m (CPU), 11.22 s (Wall)] -- 
Progress of 'loading chromatogram list':

-- done [took 1.11 s (CPU), 0.04 s (Wall)] -- 
Traceback (most recent call last):
  File "C:\Users\Tanner\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Tanner\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Tanner\anaconda3\Scripts\easypqp.exe\__main__.py", line 7, in <module>
  File "C:\Users\Tanner\anaconda3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Tanner\anaconda3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\Tanner\anaconda3\lib\site-packages\click\core.py", line 1690, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Tanner\anaconda3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Tanner\anaconda3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Tanner\anaconda3\lib\site-packages\easypqp\main.py", line 76, in convert
    psms, peaks = conversion(pepxmlfile, spectralfile, unimodfile, exclude_range, max_delta_unimod, max_delta_ppm, enable_unannotated, enable_massdiff, fragment_types, fragment_charges, enable_specific_losses, enable_unspecific_losses, max_psm_pep)
  File "C:\Users\Tanner\anaconda3\lib\site-packages\easypqp\convert.py", line 631, in conversion
    peaks = read_mzml_or_mzxml_impl(spectralfile, psms[['scan_id', 'modified_peptide', 'precursor_charge']], theoretical, max_delta_ppm, 'mzml')
  File "C:\Users\Tanner\anaconda3\lib\site-packages\easypqp\convert.py", line 409, in read_mzml_or_mzxml_impl
    input_map = {get_scan(e.getNativeID()): e for e in input_map.getSpectra()}
  File "C:\Users\Tanner\anaconda3\lib\site-packages\easypqp\convert.py", line 409, in <dictcomp>
    input_map = {get_scan(e.getNativeID()): e for e in input_map.getSpectra()}
  File "C:\Users\Tanner\anaconda3\lib\site-packages\easypqp\convert.py", line 406, in get_scan
    scan_str, = re.compile('scan=([0-9]+)').findall(e)
ValueError: not enough values to unpack (expected 1, got 0)
exit status: 1
EasyPQP convert error END
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 2 remaining tasks

**Comment by fcyu** [comment]
Duplicated issue: https://github.com/Nesvilab/FragPipe/issues/880
