### ISSUE TITLE
non-specific search - Process 'MSBooster' finished, exit code: 1 Process returned non-zero exit code, stopping.

### ISSUE THREAD

**Issue by shahbazymoh** [Nesvilab/FragPipe#904]
Dear Nesvilab,

I am doing a non-specific search by the DDA database search by MSFragger+MSBooster to identify MHC-bound peptides using *raw Fusion Orbitrap files. The MSFragger can finish its search successfully, but the MSBooster showed the following error. 

When I untick MSBosster (and Percolator) and activate "PeptideProphet", it works properly. Is there any fixed MSBosster version? 

Thanks in advance for your help. The log file is attached. 

Kind regards,
Moh

[log_2022-12-02_10-46-08.txt](https://github.com/Nesvilab/FragPipe/files/10137038/log_2022-12-02_10-46-08.txt)

*error: 

MSBooster [Work dir: F:\Data\DC24_VACV_Fusion_DDA_MSFraggerDBsearch_29112022]
C:\FragPipe-jre-18.0\fragpipe\jre\bin\java.exe -Xmx16G -cp "C:\FragPipe-jre-18.0\fragpipe\tools\msbooster-1.1.4.jar;C:\FragPipe-jre-18.0\fragpipe\tools\smile-core-2.6.0.jar;C:\FragPipe-jre-18.0\fragpipe\tools\smile-math-2.6.0.jar;C:\FragPipe-jre-18.0\fragpipe\tools\batmass-io-1.25.5.jar" Features.MainClass --paramsList F:\Data\DC24_VACV_Fusion_DDA_MSFraggerDBsearch_29112022\msbooster_params.txt
java.io.UncheckedIOException: Z:\MS_data\Fusion
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:2152)
	at Features.PinMzmlMatcher.<init>(PinMzmlMatcher.java:44)
	at Features.MainClass.main(MainClass.java:470)
Caused by: java.nio.file.NoSuchFileException: Z:\MS_data\Fusion
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source)
	at java.base/java.nio.file.Files.readAttributes(Unknown Source)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(Unknown Source)
	at java.base/java.nio.file.FileTreeWalker.visit(Unknown Source)
	at java.base/java.nio.file.FileTreeWalker.walk(Unknown Source)
	at java.base/java.nio.file.FileTreeIterator.<init>(Unknown Source)
	at java.base/java.nio.file.Files.walk(Unknown Source)
	at org.apache.commons.io.file.PathUtils.walk(PathUtils.java:1049)
	at org.apache.commons.io.FileUtils.streamFiles(FileUtils.java:2970)
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:2150)
	... 2 more
Process 'MSBooster' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 123 remaining tasks
MSBooster v1.1.4
Using 32 threads

**Comment by fcyu** [comment]
This is because there is a space in your folder `Fusion data`. I believe FragPipe showed a dialog warning you this but I guess you ignored it.

Best,

Fengchao

**Comment by shahbazymoh** [comment]
@fcyu 
Thanks, it has been resolved. 
All the best,
Moh
