### ISSUE TITLE
FragPipe v19 on Windows 10 "Error delivering events through the bus"

### ISSUE THREAD

**Issue by awarsh** [Nesvilab/FragPipe#927]
- Describe the issue or question:

Trying to run FragPipe 19 results in the error listed below. FragPipe 17.1 and 18 both work properly on this PC. 

- Upload your log file

[log_2022-12-13_10-24-02.txt](https://github.com/Nesvilab/FragPipe/files/10219439/log_2022-12-13_10-24-02.txt)

**Comment by fcyu** [comment]
Hi @awarsh ,

Could you upgrade the Philosopher to the latest version, and try again?

Best,

Fengchao

**Comment by awarsh** [comment]
I updated Philosopher, IonQuant, and MSFragger and it worked. Thank you!

**Comment by witszymanski** [comment]
Hi! 

I have all the newest tools, but I still get the error. Any hints? 

![image](https://github.com/Nesvilab/FragPipe/assets/15866068/7274763f-1831-44ac-8068-16fc42dd2665)

``` 
14:00:54 ERROR: Error delivering events through the bus
java.util.NoSuchElementException: null
	at java.base/java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.base/java.util.HashMap$KeyIterator.next(Unknown Source)
	at com.dmtavt.fragpipe.cmd.CmdProteinProphet.configure(CmdProteinProphet.java:144)
	at com.dmtavt.fragpipe.FragpipeRun.lambda$configureTaskGraph$37(FragpipeRun.java:1318)
	at com.dmtavt.fragpipe.FragpipeRun.configureTaskGraph(FragpipeRun.java:1801)
	at com.dmtavt.fragpipe.FragpipeRun.run(FragpipeRun.java:294)
	at com.dmtavt.fragpipe.tabs.TabRun.on(TabRun.java:178)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:511)
	at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by fcyu** [comment]
Hi @witszymanski ,

Your error was due to a different reason. Can you send the whole log file?

Thanks,

Fengchao
