### ISSUE TITLE
SpecLibGen - Library not generated, not enough peptides could be found for alignment.

### ISSUE THREAD

**Issue by f-huber** [Nesvilab/FragPipe#932]
Dear Fragpipe team, 

It happened to us, from time to time, that fragpipe fails with spectral library generation, with the following error message:

```Not enough peptides could be found for alignment.
Using ciRT for alignment
Traceback (most recent call last):
  File "/usr/bin/anaconda/bin/easypqp", line 8, in <module>
    sys.exit(cli())
  File "/usr/bin/anaconda/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/bin/anaconda/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/bin/anaconda/lib/python3.9/site-packages/click/core.py", line 1690, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/bin/anaconda/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/bin/anaconda/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/bin/anaconda/lib/python3.9/site-packages/easypqp/main.py", line 117, in library
    generate(infiles, outfile, psmtsv, peptidetsv, perform_rt_calibration, rt_referencefile, rt_reference_run_path, rt_filter, perform_im_calibration, im_
  File "/usr/bin/anaconda/lib/python3.9/site-packages/easypqp/library.py", line 345, in generate
    pepid = process_psms(psms, psmtsv, peptidetsv, psm_fdr_threshold, peptide_fdr_threshold, protein_fdr_threshold, pi0_lambda, peptide_plot_path, protein
  File "/usr/bin/anaconda/lib/python3.9/site-packages/easypqp/library.py", line 132, in process_psms
    psmtsv_df["group_id"] = temp_df.iloc[:, 0] + "_" + pd.to_numeric(temp_df.iloc[:, -2]).astype(str) + \
  File "/usr/bin/anaconda/lib/python3.9/site-packages/pandas/core/indexing.py", line 925, in __getitem__
    return self._getitem_tuple(key)
  File "/usr/bin/anaconda/lib/python3.9/site-packages/pandas/core/indexing.py", line 1506, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/usr/bin/anaconda/lib/python3.9/site-packages/pandas/core/indexing.py", line 754, in _has_valid_tuple
    self._validate_key(k, i)
  File "/usr/bin/anaconda/lib/python3.9/site-packages/pandas/core/indexing.py", line 1409, in _validate_key
    self._validate_integer(key, axis)
  File "/usr/bin/anaconda/lib/python3.9/site-packages/pandas/core/indexing.py", line 1500, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
...
...
Process 'SpecLibGen' finished, exit code: 1
Library not generated, not enough peptides could be found for alignment.
Library not generated, not enough peptides could be found for alignment.
Please try using other options for alignment (e.g. ciRT if used other options)
Process returned non-zero exit code, stopping
```

We use it in HLA-DIA mode, headless version of fragpipe.

You will find the full log attached here.
[1JJ9-05.HLA-II.fragpipe.log.zip](https://github.com/Nesvilab/FragPipe/files/10244402/1JJ9-05.HLA-II.fragpipe.log.zip)

I noticed the following warning for some of the pep-xml:
`level=warning msg="No PSM was found in data set`
Maybe this may help.

As always, thanks a lot for your precious help.

Kind regards,

Florian

**Comment by fcyu** [comment]
Hi Florian,

Thank you very much for the bug report.

I located the bug and fixed it. To make sure that I did it correctly, could you send "20221207_CTE-BIO-063768-HLAIIp_R02.mzML" to me to test? I can send you a link to upload the file if you need one.

Thanks,

Fengchao

**Comment by f-huber** [comment]
Hi @fcyu ,
So efficient! Sure, I'll be happy to shere the file - can you please send an uploads link?

Best,

Florian

**Comment by fcyu** [comment]
Hi Florian,

Sounds good! Here is the link: https://www.dropbox.com/request/pTCBZQqKFI1wZfk9HVp3

Best,

Fengchao

**Comment by f-huber** [comment]
Awesome - It's uploaded!

**Comment by fcyu** [comment]
Hi @f-huber ,

When I tested your file, I got 2000+ peptides, which should not trigger the error you saw. Then, after looking carefully to your log file, I found something weird from the Philosopher log: there were 0 IDs passing the FDR filtering:
```
time="23:50:40" level=info msg="1+ Charge profile" decoy=2 target=7
time="23:50:40" level=info msg="2+ Charge profile" decoy=314 target=2500
time="23:50:40" level=info msg="3+ Charge profile" decoy=160 target=4632
time="23:50:40" level=info msg="4+ Charge profile" decoy=66 target=1279
time="23:50:40" level=info msg="5+ Charge profile" decoy=41 target=369
time="23:50:40" level=info msg="6+ Charge profile" decoy=0 target=0
time="23:50:40" level=info msg="Database search results" ions=3810 peptides=3469 psms=9370
time="23:50:40" level=info msg="Converged to 0.00 % FDR with 0 PSMs" decoy=0 threshold=10 total=0
time="23:50:40" level=info msg="Converged to 0.00 % FDR with 0 Peptides" decoy=0 threshold=10 total=0
time="23:50:40" level=info msg="Converged to 0.00 % FDR with 0 Ions" decoy=0 threshold=10 total=0
time="23:50:41" level=info msg="Protein inference results" decoy=451 target=1303
time="23:50:41" level=info msg="Converged to 40.81 % FDR with 1093 Proteins" decoy=446 threshold=0.6994 total=1539
time="23:50:41" level=info msg="Applying sequential FDR estimation" ions=0 peptides=0 psms=0
time="23:50:41" level=info msg="Converged to 0.00 % FDR with 0 PSMs" decoy=0 threshold=10 total=0
time="23:50:41" level=info msg="Converged to 0.00 % FDR with 0 Peptides" decoy=0 threshold=10 total=0
time="23:50:41" level=info msg="Converged to 0.00 % FDR with 0 Ions" decoy=0 threshold=10 total=0
time="23:50:41" level=info msg="Post processing identifications"
time="23:50:43" level=info msg="Assigning protein identifications to layers"
time="23:50:45" level=info msg="Processing protein inference"
time="23:51:04" level=info msg="Synchronizing PSMs and proteins"
time="23:51:04" level=info msg="Total report numbers after FDR filtering, and post-processing" ions=0 peptides=0 proteins=0 psms=0
time="23:51:04" level=info msg=Saving
time="23:51:04" level=info msg=Done
```

It explains why EasyPQP crashed, and it also reveals a potential bug in Philosopher.

I see that you were using an old version of Philosopher. Could you please re-run the whole workflow using the latest Philosopher (version 4.6.0) and see if the bug was still there? If so, we might want all of your 8 mzML files.

Thanks,

Fengchao

**Comment by f-huber** [comment]
Hi @fcyu ,
Correct, and I also realized this in the meantime and therefore decided to run it again with the last version of fragpipe (including the version of philosopher (4.6.1-RC2) and it worked great).  Sorry, but I have a container that contains this version of philosopher, following the issue #908. 
So I believe that this issue can be considered as solved. 
Thanks again for your help!
With best regards,
Florian

**Comment by fcyu** [comment]
No problem!

Best,

Fengchao
