### ISSUE TITLE
Annotating the database - panic: runtime error: index out of range [1] with length 0

### ISSUE THREAD

**Issue by tobiasko** [Nesvilab/FragPipe#933]
We are getting an error when trying to run a DB search incl. a spike-in fasta sequence. The error message is:

```
time="12:25:36" level=info msg="Annotating the database"
panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
philosopher/lib/dat.ProcessUniProtKB(0xc0001b4281, 0x39, 0xc00025ce00, 0x696, 0xc0001dce60, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
	/home/prvst/workspace/philosopher/lib/dat/db.go:259 +0xc96
philosopher/lib/dat.(*Base).ProcessDB(0xc000376000, 0xc000254280, 0x43, 0xc0001dce60, 0x4)
	/home/prvst/workspace/philosopher/lib/dat/dat.go:132 +0x82d
philosopher/lib/dat.Run(0xc0003581e0, 0x24, 0xc0003561e0, 0x4f, 0xc000358210, 0x29, 0xc000354180, 0x5e, 0xc0003541e0, 0x55, ...)
	/home/prvst/workspace/philosopher/lib/dat/dat.go:64 +0xb34
philosopher/lib/pip.AnnotateDatabase(0xc000358090, 0x24, 0xc0003560a0, 0x49, 0xc0003580c0, 0x29, 0xc0003540c0, 0x58, 0xc0003560f0, 0x4f, ...)
	/home/prvst/workspace/philosopher/lib/pip/pip.go:140 +0x26c
philosopher/cmd.glob..func13(0x894f1a0, 0xc000221ec0, 0x2, 0x4)
	/home/prvst/workspace/philosopher/cmd/pipeline.go:72 +0x41c
github.com/spf13/cobra.(*Command).execute(0x894f1a0, 0xc000221e80, 0x4, 0x4, 0x894f1a0, 0xc000221e80)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x894fc20, 0x0, 0x0, 0x0)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
philosopher/cmd.Execute()
	/home/prvst/workspace/philosopher/cmd/root.go:35 +0x2d
main.main()
	/home/prvst/workspace/philosopher/main.go:22 +0x6e
```
Once a specific spike-in is removed the search completes without any issues.

We tried running different FragPipe/Philosopher versions. All show the above error. The problematic FASTA entry is:

```
>sp|ADD001|StreptagII-CLIP1-ROS1 StreptagII-CLIP1-ROS1
YPYDVPDYAGTELGSTMASWSHPQFEKGGGSGGGSGGGSWSHPQFEKAAASMLKPSGLKAPTKILKPGSTALKTPTAVVAPVEKTISSEKASSTPSSETQEEFVDDFRVGERVWVNGNKPGFIQFLGETQFAPGQWAGIVLDEPIGKNDGSVAGVRYFQCEPLKGIFTRPSKLTRKVQAEDEANGLQTTPASRATSPLCTSTASMVSSSPSTPSNIPQKPSQPAAKEPSATPPISNLTKTASESISNLSEAGSIKKGERELKIGDRVLVGGTKAGVVRFLGETDFAKGEWCGVELDEPLGKNDGAVAGTRYFQCQPKYGLFAPVHKVTKIGFPSTTPAKAKANAVRRVMATTSASLKRSPSASSLSSMSSVASSVSSRPSRTGLLTETSSRYARKISGTTALQEALKEKQQHIEQLLAERDLERAEVAKATSHVGEIEQELALARDGHDQHVLELEAKMDQLRTMVEAADREKVELLNQLEEEKRKVEDLQFRVEEESITKGDLEQKSQISEDPENTQTKLEHARIKELEQSLLFEKTKADKLQRELEDTRVATVSEKSRIMELEKDLALRVQEVAELRRRLESNKPAGDVDMSLSLLQEISSLQEKLEVTRTDHQREITSLKEHFGAREETHQKEIKALYTATEKLSKENESLKSKLEHANKENSDVIALWKSKLETAIASHQQAMEELKVSFSKGLGTETAEFAELKTQIEKMRLDYQHEIENLQNQQDSERAAHAKEMEALRAKLMKVIKEKENSLEAIRSKLDKAEDQHLVEMEDTLNKLQEAEIKVKELEVLQAKCNEQTKVIDNFTSQLKATEEKLLDLDALRKASSEGKSEMKKLRQQLEAAEKQIKHLEIEKNAESSKASSITRELQGRELKLTNLQENLSEVSQVKETLEKELQILKEKFAEASEEAVSVQRSMQETVNKLHQKEEQFNMLSSDLEKLRENLADMEAKFREKDEREEQLIKAKEKLENDIAEIMKMSGDNSSQLTKMNDELRLKERDVEELQLKLTKANENASFLQKSIEDMTVKAEQSQQEAAKKHEEEKKELERKLSDLEKKMETSHNQCQELKARYERATSETKTKHEEILQNLQKTLLDTEDKLKGAREENSGLLQELEELRKQADKAKAAQTAEDAMQIMEQMTKEKTETLASLEDTKQTNAKLQNELDTLKENNLKNVEELNKSKELLTVENQKMEEFRKEIETLKQAAAQKSQQLSALQEENVKLAEELGRSRDEVTSHQKLEEERSVLNNQLLEMKKSTLPTQEEIENLPAFPREKLTLRLLLGSGAFGEVYEGTAVDILGVGSGEIKVAVKTLKKGSTDQEKIEFLKEAHLMSKFNHPNILKQLGVCLLNEPQYIILELMEGGDLLTYLRKARMATFYGPLLTLVDLVDLCVDISKGCVYLERMHFIHRDLAARNCLVSVKDYTSPRIVKIGDFGLARDIYKNDYYRKRGEGLLPVRWMAPESLMDGIFTTQSDVWSFGILIWEILTLGHQPYPAHSNLDVLNYVQTGGRLEPPRNCPDDLWNLMTQCWAQEPDQRPTFHRIQDQLQLFRNFFLNSIYKSRDEANNSGVINESFEGEDGDVICLNSDDIMPVALMETKNREGLNYMVLATECGQGEEKSEGPLGSQESESCGLRKEEKEPHADKDFCQEKQVAYCPSGKPEGLNYACLTHSGYGDGSD
```
The above fusion protein that does not exist in the human reference proteome.

**Comment by tobiasko** [comment]
I could provide the complete DB as zip archive (bigger than upload limit).

**Comment by antdit** [comment]
log and params files of the above issue are attached here:

[log_2022-12-16_12-05-39.zip](https://github.com/Nesvilab/FragPipe/files/10245480/log_2022-12-16_12-05-39.zip)

**Comment by fcyu** [comment]
Felipe @prvst any progress regarding this issue?

Thanks,

Fengchao

**Comment by prvst** [comment]
@tobiasko remove this `sp|`  from the header, and the program won't try to read it as an UniProt entry

**Comment by prvst** [comment]
I adjusted some parsing rules, and now your sequence should be fine as it is

Added to v5.0.0
