### ISSUE TITLE
Error running HLA search

### ISSUE THREAD

**Issue by Dmorgen** [Nesvilab/FragPipe#974]
Hi,

I'm trying to run 9 samples in HLA. 
I've uploaded the Non-Specific HLA workflow and noted that the export options in the validation step (i.e. export of protein and peptide level summaries) was grayed out. I've click the "Run Validation Tool" box off and on again, and then it appeared to be normal. however, trying to run the search yielded an immediate error:

java.lang.NullPointerException
	at com.dmtavt.fragpipe.cmd.CmdProteinProphet.createCmdStub(CmdProteinProphet.java:232)
	at com.dmtavt.fragpipe.cmd.CmdProteinProphet.configure(CmdProteinProphet.java:152)
	at com.dmtavt.fragpipe.FragpipeRun.lambda$configureTaskGraph$37(FragpipeRun.java:1186)
	at com.dmtavt.fragpipe.FragpipeRun.configureTaskGraph(FragpipeRun.java:1640)
	at com.dmtavt.fragpipe.FragpipeRun.run(FragpipeRun.java:286)
	at com.dmtavt.fragpipe.tabs.TabRun.on(TabRun.java:174)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:511)
	at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[log_2023-01-23_17-15-20.txt](https://github.com/Nesvilab/FragPipe/files/10481015/log_2023-01-23_17-15-20.txt)

Thanks!
David.

**Comment by fcyu** [comment]
Hi David,

Could you check if Philosopher has been configured in the "config" tab?

Thanks,

Fengchao

**Comment by Dmorgen** [comment]
No it doesn’t. thanks!
I’ll try again.

Thanks!
D.

**Comment by Dmorgen** [comment]
yeah, my bad. works now, thanks!

**Comment by fcyu** [comment]
No problem!

Best,

Fengchao
