### ISSUE TITLE
DIA-NN error: Failed to execute script dia-nn-plotter

### ISSUE THREAD

**Issue by jossmi** [Nesvilab/FragPipe#996]
I am running the standard DIA_SpecLib_Quant workflow on a yeast digest run with DIA on a Thermo Orbitrap Fusion Lumos. I've converted it to mzML with MSConvert, using the standard settings suggested on the FragPipe tutorial website (only filter was peak picking). Everything seems to run fine until I get to DIA-NN, at which point I get the following error:

Any ideas? I've attached my log. 

Thanks!
Josh

Process 'DIA-NN' finished, exit code: 0
DIA-NN [Work dir: D:\Data\2023\ColeR\JS\230206\Run2]
C:\FragPipe\FragPipe_v19.1\fragpipe\tools\diann\1.8.2_beta_8\win\dia-nn-plotter.exe diann-output\diann-output.stats.tsv diann-output\diann-output.tsv diann-output\diann-output.pdf
[3056] Failed to execute script dia-nn-plotter
Traceback (most recent call last):
  File "dia-nn-plotter.py", line 347, in <module>
  File "dia-nn-plotter.py", line 179, in report
  File "site-packages\pandas\core\indexes\base.py", line 1520, in droplevel
ValueError: Cannot remove 1 levels from an index with 1 levels: at least one level must be left.
Generating report. Stats, main report, output file: diann-output\diann-output.stats.tsv, diann-output\diann-output.tsv, diann-output\diann-output.pdf
Process 'DIA-NN' finished, exit code: -1
Process returned non-zero exit code, stopping

Cancelling 2 remaining tasks

[log_2023-02-06_18-57-31.txt](https://github.com/Nesvilab/FragPipe/files/10670171/log_2023-02-06_18-57-31.txt)

**Comment by jossmi** [comment]
I'm dumb, I just realized I forgot to change my database from human. Sorry, ignore this...
